from typing import Any

class MatrixGroupElement_gap(ElementLibGAP):
    def __init__(self: Any, parent: Any, M: Any, check: Any = ..., convert: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def list(self: Any) -> List[Any]:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def word_problem(self: Any, gens: Any = ...) -> Any:
        ...
