from typing import Any

def is_MatrixGroupElement(x: Any) -> Any:
    ...

class MatrixGroupElement_generic(MultiplicativeGroupElement):
    def __init__(self: Any, parent: Any, M: Any, check: Any = ..., convert: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def list(self: Any) -> List[Any]:
        ...
    def matrix(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
