from typing import Any

def unpickle_QuaternionAlgebraElement_generic_v0() -> Any:
    ...

def unpickle_QuaternionAlgebraElement_rational_field_v0() -> Any:
    ...

def unpickle_QuaternionAlgebraElement_number_field_v0() -> Any:
    ...

class QuaternionAlgebraElement_abstract(AlgebraElement):
    def __hash__(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def reduced_trace(self: Any) -> Any:
        ...
    def reduced_norm(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def reduced_characteristic_polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def matrix(self: Any, action: Any = ...) -> Any:
        ...
    def coefficient_tuple(self: Any) -> Any:
        ...
    def pair(self: Any, right: Any) -> Any:
        ...

class QuaternionAlgebraElement_generic(QuaternionAlgebraElement_abstract):
    def __init__(self: Any, parent: Any, v: Any, check: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class QuaternionAlgebraElement_rational_field(QuaternionAlgebraElement_abstract):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, v: Any, check: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def reduced_norm(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def reduced_trace(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def denominator_and_integer_coefficient_tuple(self: Any) -> Any:
        ...
    def integer_coefficient_tuple(self: Any) -> Any:
        ...
    def coefficient_tuple(self: Any) -> Any:
        ...

class QuaternionAlgebraElement_number_field(QuaternionAlgebraElement_abstract):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, v: Any, check: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
