from typing import Any

def unpickle_BooleanFunction(bool_list: Any) -> Any:
    ...

def random_boolean_function(n: Any) -> Any:
    ...

class BooleanFunction(SageObject):
    def __cinit__(self: Any, x: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __or__(self: Any, other: Any) -> Any:
        ...
    def algebraic_normal_form(self: Any) -> Any:
        ...
    def nvariables(self: Any) -> Any:
        ...
    def truth_table(self: Any, format: Any = ...) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def walsh_hadamard_transform(self: Any) -> Tuple[Any, ...]:
        ...
    def absolute_walsh_spectrum(self: Any) -> Any:
        ...
    def is_balanced(self: Any) -> Any:
        ...
    def is_symmetric(self: Any) -> Any:
        ...
    def nonlinearity(self: Any) -> Any:
        ...
    def is_bent(self: Any) -> Any:
        ...
    def correlation_immunity(self: Any) -> Any:
        ...
    def resiliency_order(self: Any) -> Any:
        ...
    def autocorrelation(self: Any) -> Any:
        ...
    def absolute_autocorrelation(self: Any) -> Any:
        ...
    def absolute_indicator(self: Any) -> Any:
        ...
    def sum_of_square_indicator(self: Any) -> Any:
        ...
    def annihilator(self: Any, d: Any, dim: Any = ...) -> Any:
        ...
    def algebraic_immunity(self: Any, annihilator: Any = ...) -> Any:
        ...
    def algebraic_degree(self: Any) -> Any:
        ...
    def is_plateaued(self: Any) -> Any:
        ...
    def is_linear_structure(self: Any, val: Any) -> Any:
        ...
    def linear_structures(self: Any) -> Any:
        ...
    def derivative(self: Any, u: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, y: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class BooleanFunctionIterator:
    def __init__(self: Any, f: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
