from typing import Any

def feistel_construction() -> Any:
    ...

def misty_construction() -> Any:
    ...

class SBox(SageObject):
    def __init__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __eq__(self: Any, rhs: Any) -> Any:
        ...
    def __ne__(self: Any, other: Any) -> Any:
        ...
    def to_bits(self: Any, x: Any, n: Any = ...) -> List[Any]:
        ...
    def from_bits(self: Any, x: Any, n: Any = ...) -> Any:
        ...
    def __call__(self: Any, X: Any) -> Any:
        ...
    def __getitem__(self: Any, X: Any) -> Any:
        ...
    def input_size(self: Any) -> Any:
        ...
    def output_size(self: Any) -> Any:
        ...
    def is_permutation(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def derivative(self: Any, u: Any) -> Any:
        ...
    def difference_distribution_table(self: Any) -> Any:
        ...
    def maximal_difference_probability_absolute(self: Any) -> Any:
        ...
    def maximal_difference_probability(self: Any) -> Any:
        ...
    def linear_approximation_table(self: Any, scale: Any = ...) -> Any:
        ...
    def maximal_linear_bias_absolute(self: Any) -> Any:
        ...
    def maximal_linear_bias_relative(self: Any) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def solutions(self: Any, X: Any = ..., Y: Any = ...) -> Any:
        ...
    def polynomials(self: Any, X: Any = ..., Y: Any = ..., degree: Any = ..., groebner: Any = ...) -> Any:
        ...
    def interpolation_polynomial(self: Any, k: Any = ...) -> Any:
        ...
    def cnf(self: Any, xi: Any = ..., yi: Any = ..., format: Any = ...) -> Any:
        ...
    def component_function(self: Any, b: Any) -> Any:
        ...
    def nonlinearity(self: Any) -> Any:
        ...
    def linearity(self: Any) -> Any:
        ...
    def is_apn(self: Any) -> Any:
        ...
    def differential_branch_number(self: Any) -> Any:
        ...
    def linear_branch_number(self: Any) -> Any:
        ...
    def autocorrelation_table(self: Any) -> Any:
        ...
    def boomerang_connectivity_table(self: Any) -> Any:
        ...
    def boomerang_uniformity(self: Any) -> Any:
        ...
    def linear_structures(self: Any) -> Any:
        ...
    def is_linear_structure(self: Any, a: Any, b: Any) -> Any:
        ...
    def max_degree(self: Any) -> Any:
        ...
    def min_degree(self: Any) -> Any:
        ...
    def is_balanced(self: Any) -> Any:
        ...
    def is_almost_bent(self: Any) -> Any:
        ...
    def fixed_points(self: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
    def is_monomial_function(self: Any) -> Any:
        ...
    def is_plateaued(self: Any) -> Any:
        ...
    def is_bent(self: Any) -> Any:
        ...
    def is_involution(self: Any) -> Any:
        ...
