from typing import Any

class Action(Functor):
    def __init__(self: Any, G: Any, S: Any, is_left: Any = ..., op: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def act(self: Any, g: Any, x: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def is_left(self: Any) -> Any:
        ...
    def actor(self: Any) -> Any:
        ...
    def codomain(self: Any) -> Any:
        ...
    def domain(self: Any) -> Any:
        ...
    def left_domain(self: Any) -> Any:
        ...
    def right_domain(self: Any) -> Any:
        ...
    def operation(self: Any) -> Any:
        ...

class InverseAction(Action):
    def __init__(self: Any, action: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def codomain(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...

class PrecomposedAction(Action):
    def __init__(self: Any, action: Any, left_precomposition: Any, right_precomposition: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def domain(self: Any) -> Any:
        ...
    def codomain(self: Any) -> Any:
        ...
    def left_precomposition(self: Any) -> Any:
        ...
    def right_precomposition(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...

class ActionEndomorphism(Morphism):
    def __init__(self: Any, action: Any, g: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
