from typing import Any

def is_Functor(x: Any) -> Any:
    ...

def IdentityFunctor(C: Any) -> Any:
    ...

def ForgetfulFunctor(domain: Any, codomain: Any) -> Any:
    ...

class Functor(SageObject):
    def __init__(self: Any, domain: Any, codomain: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def domain(self: Any) -> Any:
        ...
    def codomain(self: Any) -> Any:
        ...

class ForgetfulFunctor_generic(Functor):
    def __reduce__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __ne__(self: Any, other: Any) -> Any:
        ...

class IdentityFunctor_generic(ForgetfulFunctor_generic):
    def __init__(self: Any, C: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
