from typing import Any, Optional, Tuple, Dict
from sage.structure.element import Element

def unpickle_map(_class: type, parent: Any, _dict: Dict[str, Any], _slots: Dict[str, Any]) -> 'Map':
    ...

def is_Map(x: Any) -> bool:
    ...

class Map(Element):
    def __init__(self, parent: Any, codomain: Optional[Any] = None) -> None:
        ...
    def __copy__(self) -> 'Map':
        ...
    def parent(self) -> Any:
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def domains(self) -> list:
        ...
    def category_for(self) -> Any:
        ...
    def __call__(self, x: Any) -> Any:
        ...
    def __mul__(self, right: 'Map') -> 'Map':
        ...
    def pre_compose(self, right: 'Map') -> 'Map':
        ...
    def post_compose(self, left: 'Map') -> 'Map':
        ...
    def extend_domain(self, new_domain: Any) -> 'Map':
        ...
    def extend_codomain(self, new_codomain: Any) -> 'Map':
        ...
    def is_surjective(self) -> bool:
        ...
    def section(self) -> Optional['Map']:
        ...
    def __hash__(self) -> int:
        ...

class Section(Map):
    def __init__(self: Any, map: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...

class FormalCompositeMap(Map):
    def __init__(self: Any, parent: Any, first: Any, second: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def first(self: Any) -> Any:
        ...
    def then(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def domains(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
