from typing import Any

def unpickle_map(_class: Any, parent: Any, _dict: Any, _slots: Any) -> Any:
    ...

def is_Map(x: Any) -> Any:
    ...

class Map(Element):
    def __init__(self: Any, parent: Any, codomain: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def parent(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def domains(self: Any) -> Any:
        ...
    def category_for(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def __mul__(self: Any, right: Any) -> Any:
        ...
    def pre_compose(self: Any, right: Any) -> Any:
        ...
    def post_compose(self: Any, left: Any) -> Any:
        ...
    def extend_domain(self: Any, new_domain: Any) -> Any:
        ...
    def extend_codomain(self: Any, new_codomain: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class Section(Map):
    def __init__(self: Any, map: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...

class FormalCompositeMap(Map):
    def __init__(self: Any, parent: Any, first: Any, second: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def first(self: Any) -> Any:
        ...
    def then(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def domains(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
