from typing import Any

def is_Morphism(x: Any) -> Any:
    ...

class Morphism(Map):
    def category(self: Any) -> Any:
        ...
    def is_endomorphism(self: Any) -> Any:
        ...
    def is_identity(self: Any) -> Any:
        ...
    def pushforward(self: Any, I: Any) -> Any:
        ...
    def register_as_coercion(self: Any) -> Any:
        ...
    def register_as_conversion(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...

class FormalCoercionMorphism(Morphism):
    def __init__(self: Any, parent: Any) -> Any:
        ...

class CallMorphism(Morphism):
    ...

class IdentityMorphism(Morphism):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def is_identity(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...

class SetMorphism(Morphism):
    def __init__(self: Any, parent: Any, function: Any) -> Any:
        ...
    def __richcmp__(self: Any, right: Any, op: Any) -> Any:
        ...

class SetIsomorphism(SetMorphism):
    def __invert__(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
