from typing import Any

def hecke_images_gamma0_weight2(u: Any, v: Any, N: Any, indices: Any, R: Any) -> Any:
    ...

def hecke_images_nonquad_character_weight2(u: Any, v: Any, N: Any, indices: Any, chi: Any, R: Any) -> Any:
    ...

def hecke_images_quad_character_weight2(u: Any, v: Any, N: Any, indices: Any, chi: Any, R: Any) -> Any:
    ...

def hecke_images_gamma0_weight_k(u: Any, v: Any, i: Any, N: Any, k: Any, indices: Any, R: Any) -> Any:
    ...

class Heilbronn:
    def __dealloc__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def to_list(self: Any) -> Any:
        ...
    def apply(self: Any, u: Any, v: Any, N: Any) -> Any:
        ...

class HeilbronnCremona(Heilbronn):
    def __init__(self: Any, p: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class HeilbronnMerel(Heilbronn):
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
