from typing import Any

def is_ManinSymbol(x: Any) -> Any:
    ...

class ManinSymbol(Element):
    def __init__(self: Any, parent: Any, t: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def tuple(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __mul__(self: Any, matrix: Any) -> Any:
        ...
    def apply(self: Any, a: Any, b: Any, c: Any, d: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def lift_to_sl2z(self: Any, N: Any = ...) -> Any:
        ...
    def endpoints(self: Any, N: Any = ...) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def level(self: Any) -> Any:
        ...
    def modular_symbol_rep(self: Any) -> Any:
        ...
