from typing import Any

def p1_normalize_int(N: Any, u: Any, v: Any) -> Any:
    ...

def p1list_int(N: Any) -> Any:
    ...

def p1_normalize_llong(N: Any, u: Any, v: Any) -> Any:
    ...

def p1list_llong(N: Any) -> Any:
    ...

def p1list(N: Any) -> Any:
    ...

def p1_normalize(N: Any, u: Any, v: Any) -> Any:
    ...

def lift_to_sl2z_int(c: Any, d: Any, N: Any) -> Any:
    ...

def lift_to_sl2z_llong(c: Any, d: Any, N: Any) -> Any:
    ...

def lift_to_sl2z(c: Any, d: Any, N: Any) -> Any:
    ...

class P1List:
    def __init__(self: Any, N: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def lift_to_sl2z(self: Any, i: Any) -> Any:
        ...
    def apply_I(self: Any, i: Any) -> Any:
        ...
    def apply_S(self: Any, i: Any) -> Any:
        ...
    def apply_T(self: Any, i: Any) -> Any:
        ...
    def index(self: Any, u: Any, v: Any) -> Any:
        ...
    def index_of_normalized_pair(self: Any, u: Any, v: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def normalize(self: Any, u: Any, v: Any) -> Any:
        ...
    def normalize_with_scalar(self: Any, u: Any, v: Any) -> Any:
        ...
    def N(self: Any) -> Any:
        ...

class export:
    ...
