from typing import Any

def make_zz_pX(L: Any, context: Any) -> Any:
    ...

class ntl_zz_pX:
    def __init__(self: Any, ls: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, v: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, val: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, other: Any) -> Any:
        ...
    def __mod__(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, ignored: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def diff(self: Any) -> Any:
        ...
    def reverse(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def leading_coefficient(self: Any) -> Any:
        ...
    def constant_term(self: Any) -> Any:
        ...
    def square(self: Any) -> Any:
        ...
    def truncate(self: Any, m: Any) -> Any:
        ...
    def multiply_and_truncate(self: Any, other: Any, m: Any) -> Any:
        ...
    def square_and_truncate(self: Any, m: Any) -> Any:
        ...
    def invert_and_truncate(self: Any, m: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_monic(self: Any) -> Any:
        ...
    def set_x(self: Any) -> Any:
        ...
    def is_x(self: Any) -> Any:
        ...
    def clear(self: Any) -> Any:
        ...
    def preallocate_space(self: Any, n: Any) -> Any:
        ...
