from typing import Any

def make_zz_p(val: Any, context: Any) -> Any:
    ...

class ntl_zz_p:
    def __init__(self: Any, a: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, v: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, ignored: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def square(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def clear(self: Any) -> Any:
        ...
