from typing import Any

def ntl_GF2E_random(ctx: Any) -> Any:
    ...

class ntl_GF2E:
    def __init__(self: Any, x: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, x: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def modulus_context(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def IsZero(self: Any) -> Any:
        ...
    def IsOne(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def rep(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
