from typing import Any

def ntl_ZZ_pContext(v: Any) -> Any:
    ...

class ntl_ZZ_pContext_class:
    def __init__(self: Any, v: Any) -> Any:
        ...
    def __cinit__(self: Any, v: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def modulus(self: Any) -> Any:
        ...
    def restore(self: Any) -> Any:
        ...

class ntl_ZZ_pContext_factory:
    def __init__(self: Any) -> Any:
        ...
