from typing import Any

def ntl_GF2EContext(v: Any) -> Any:
    ...

class ntl_GF2EContext_class:
    def __init__(self: Any, v: Any) -> Any:
        ...
    def __cinit__(self: Any, v: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def modulus(self: Any) -> Any:
        ...
    def restore(self: Any) -> Any:
        ...
