from typing import Any

def unpickle_class_value(cls: Any, x: Any) -> Any:
    ...

def unpickle_class_args(cls: Any, x: Any) -> Any:
    ...

def ntl_setSeed(x: Any = ...) -> Any:
    ...

def randomBnd(q: Any) -> Any:
    ...

def randomBits(n: Any) -> Any:
    ...

class ntl_ZZ:
    def __init__(self: Any, v: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def get_as_int_doctest(self: Any) -> Any:
        ...
    def set_from_sage_int(self: Any, value: Any) -> Any:
        ...
    def set_from_int_doctest(self: Any, value: Any) -> Any:
        ...
    def valuation(self: Any, prime: Any) -> Any:
        ...
    def val_unit(self: Any, prime: Any) -> Any:
        ...
