from typing import Any

class ntl_mat_ZZ:
    def __init__(self: Any, nrows: Any = ..., ncols: Any = ..., v: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def nrows(self: Any) -> Any:
        ...
    def ncols(self: Any) -> Any:
        ...
    def __setitem__(self: Any, ij: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, ij: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def determinant(self: Any, deterministic: Any = ...) -> Any:
        ...
    def HNF(self: Any, D: Any = ...) -> Any:
        ...
    def charpoly(self: Any) -> Any:
        ...
    def BKZ_FP(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def BKZ_QP(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def BKZ_QP1(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def BKZ_XD(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def BKZ_RR(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_BKZ_FP(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_BKZ_QP(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_BKZ_QP1(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_BKZ_XD(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_BKZ_RR(self: Any, U: Any = ..., delta: Any = ..., BlockSize: Any = ..., prune: Any = ..., verbose: Any = ...) -> Any:
        ...
    def LLL(self: Any, a: Any = ..., b: Any = ..., return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def LLL_FP(self: Any, delta: Any = ..., return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def LLL_QP(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def LLL_XD(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def LLL_RR(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_LLL_FP(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_LLL_QP(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_LLL_XD(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
    def G_LLL_RR(self: Any, delta: Any, return_U: Any = ..., verbose: Any = ...) -> Any:
        ...
