from typing import Any

class ntl_GF2EX:
    def __init__(self: Any, modulus: Any = ..., x: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, modulus: Any = ..., x: Any = ...) -> Any:
        ...
    def modulus_context(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
