from typing import Any

def make_ZZ_pE(x: Any, c: Any) -> Any:
    ...

class ntl_ZZ_pE:
    def __init__(self: Any, v: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, v: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def get_modulus_context(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def get_as_ZZ_pX_doctest(self: Any) -> Any:
        ...
    def set_from_ZZ_pX_doctest(self: Any, value: Any) -> Any:
        ...
    def modulus(self: Any) -> Any:
        ...
