from typing import Any

def ntl_ZZ_pEContext(f: Any) -> Any:
    ...

class ntl_ZZ_pEContext_class:
    def __init__(self: Any, f: Any) -> Any:
        ...
    def __cinit__(self: Any, f: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def get_pc(self: Any) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...
    def restore(self: Any) -> Any:
        ...
    def ZZ_pE(self: Any, v: Any = ...) -> Any:
        ...
    def ZZ_pEX(self: Any, v: Any = ...) -> Any:
        ...
