from typing import Any

def ntl_ZZ_p_random_element(v: Any) -> Any:
    ...

class ntl_ZZ_p:
    def __init__(self: Any, v: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, v: Any = ..., modulus: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def modulus_context(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def modulus(self: Any) -> Any:
        ...
    def lift_centered(self: Any) -> Any:
        ...
