from typing import Any

def unpickle_class_value(cls: Any, x: Any) -> Any:
    ...

def unpickle_class_args(cls: Any, x: Any) -> Any:
    ...

class ntl_GF2:
    def __init__(self: Any, v: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
