from typing import Any

def GF2XHexOutput(have_hex: Any = ...) -> Any:
    ...

class ntl_GF2X:
    def __init__(self: Any, x: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, b: Any) -> Any:
        ...
    def DivRem(self: Any, b: Any) -> Any:
        ...
    def __floordiv__(self: Any, b: Any) -> Any:
        ...
    def __mod__(self: Any, b: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __lshift__(self: Any, i: Any) -> Any:
        ...
    def __rshift__(self: Any, offset: Any) -> Any:
        ...
    def GCD(self: Any, other: Any) -> Any:
        ...
    def XGCD(self: Any, other: Any) -> Any:
        ...
    def deg(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def bin(self: Any) -> Any:
        ...
    def hex(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def coeff(self: Any, i: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def LeadCoeff(self: Any) -> Any:
        ...
    def ConstTerm(self: Any) -> Any:
        ...
    def SetCoeff(self: Any, i: Any, a: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, a: Any) -> Any:
        ...
    def diff(self: Any) -> Any:
        ...
    def reverse(self: Any, hi: Any = ...) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def NumBits(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def NumBytes(self: Any) -> Any:
        ...
