from typing import Any

class ntl_ZZX:
    def __init__(self: Any, v: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, a: Any) -> Any:
        ...
    def setitem_from_int_doctest(self: Any, i: Any, value: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def getitem_as_int_doctest(self: Any, i: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, other: Any) -> Any:
        ...
    def __mod__(self: Any, other: Any) -> Any:
        ...
    def quo_rem(self: Any, other: Any) -> Any:
        ...
    def square(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, ignored: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_monic(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def left_shift(self: Any, n: Any) -> Any:
        ...
    def right_shift(self: Any, n: Any) -> Any:
        ...
    def content(self: Any) -> Any:
        ...
    def primitive_part(self: Any) -> Any:
        ...
    def pseudo_quo_rem(self: Any, other: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...
    def lcm(self: Any, other: Any) -> Any:
        ...
    def xgcd(self: Any, other: Any, proof: Any = ...) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def leading_coefficient(self: Any) -> Any:
        ...
    def constant_term(self: Any) -> Any:
        ...
    def set_x(self: Any) -> Any:
        ...
    def is_x(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def reverse(self: Any, hi: Any = ...) -> Any:
        ...
    def truncate(self: Any, m: Any) -> Any:
        ...
    def multiply_and_truncate(self: Any, other: Any, m: Any) -> Any:
        ...
    def square_and_truncate(self: Any, m: Any) -> Any:
        ...
    def invert_and_truncate(self: Any, m: Any) -> Any:
        ...
    def multiply_mod(self: Any, other: Any, modulus: Any) -> Any:
        ...
    def trace_mod(self: Any, modulus: Any) -> Any:
        ...
    def trace_list(self: Any) -> Any:
        ...
    def resultant(self: Any, other: Any, proof: Any = ...) -> Any:
        ...
    def norm_mod(self: Any, modulus: Any, proof: Any = ...) -> Any:
        ...
    def discriminant(self: Any, proof: Any = ...) -> Any:
        ...
    def charpoly_mod(self: Any, modulus: Any, proof: Any = ...) -> Any:
        ...
    def minpoly_mod_noproof(self: Any, modulus: Any) -> Any:
        ...
    def clear(self: Any) -> Any:
        ...
    def preallocate_space(self: Any, n: Any) -> Any:
        ...
    def squarefree_decomposition(self: Any) -> Any:
        ...
