from typing import Any

class ntl_mat_GF2:
    def __init__(self: Any, nrows: Any = ..., ncols: Any = ..., v: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, e: Any, ignored: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def NumRows(self: Any) -> Any:
        ...
    def NumCols(self: Any) -> Any:
        ...
    def __setitem__(self: Any, ij: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, ij: Any) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def gauss(self: Any, ncols: Any = ...) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def IsZero(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def IsIdent(self: Any, n: Any = ...) -> Any:
        ...
    def IsDiag(self: Any, n: Any, d: Any) -> Any:
        ...
    def image(self: Any) -> Any:
        ...
    def kernel(self: Any) -> Any:
        ...
