from typing import Any

def unpickle_Cache_givaro(parent: Any, p: Any, k: Any, modulus: Any, rep: Any, cache: Any) -> Any:
    ...

def unpickle_FiniteField_givaroElement(parent: Any, x: Any) -> Any:
    ...

class Cache_givaro(Cache_base):
    def __init__(self: Any, parent: Any, p: Any, k: Any, modulus: Any, repr: Any = ..., cache: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def random_element(self: Any) -> Any:
        ...
    def element_from_data(self: Any, e: Any) -> Any:
        ...
    def gen(self: Any) -> Any:
        ...
    def log_to_int(self: Any, n: Any) -> int:
        ...
    def int_to_log(self: Any, n: Any) -> int:
        ...
    def fetch_int(self: Any, number: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class FiniteField_givaro_iterator:
    def __init__(self: Any, cache: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...

class FiniteField_givaroElement(FinitePolyExtElement):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, other: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def log(self: Any, base: Any, order: Any = ..., check: Any = ...) -> Any:
        ...
    def polynomial(self: Any, name: Any = ...) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
