from typing import Any

def unpickle_FiniteFieldElement_pari_ffelt(parent: Any, elem: Any) -> Any:
    ...

class FiniteFieldElement_pari_ffelt(FinitePolyExtElement):
    def __init__(self: Any, parent: Any, x: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, other: Any) -> Any:
        ...
    def pth_power(self: Any, k: Any = ...) -> Any:
        ...
    def polynomial(self: Any, name: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def log(self: Any, base: Any, order: Any = ..., check: Any = ...) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __pari__(self: Any, var: Any = ...) -> Any:
        ...
