from typing import Any

def unpickleFiniteField_ntl_gf2eElement(parent: Any, elem: Any) -> Any:
    ...

class Cache_ntl_gf2e(Cache_base):
    def __cinit__(self: Any, parent: Any, k: Any, modulus: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, k: Any, modulus: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def import_data(self: Any, e: Any) -> Any:
        ...
    def fetch_int(self: Any, number: Any) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...

class FiniteField_ntl_gf2eElement(FinitePolyExtElement):
    def __init__(self: Any, parent: Any = ...) -> Any:
        ...
    def __cinit__(self: Any, parent: Any = ...) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def sqrt(self: Any, all: Any = ..., extend: Any = ...) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def polynomial(self: Any, name: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def log(self: Any, base: Any, order: Any = ..., check: Any = ...) -> Any:
        ...
