from typing import Any

def is_FiniteFieldElement(x: Any) -> Any:
    ...

class FiniteRingElement(CommutativeRingElement):
    def to_bytes(self: Any, byteorder: Any = ...) -> Any:
        ...
    def canonical_associate(self: Any) -> Any:
        ...

class FinitePolyExtElement(FiniteRingElement):
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minimal_polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def matrix(self: Any, reverse: Any = ...) -> Any:
        ...
    def __pari__(self: Any, var: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def norm(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def square_root(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def nth_root(self: Any, n: Any, extend: Any = ..., all: Any = ..., algorithm: Any = ..., cunningham: Any = ...) -> Any:
        ...
    def pth_power(self: Any, k: Any = ...) -> Any:
        ...
    def pth_root(self: Any, k: Any = ...) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def to_integer(self: Any, reverse: Any = ...) -> Any:
        ...
    def to_bytes(self: Any, byteorder: Any = ...) -> Any:
        ...

class Cache_base(SageObject):
    def fetch_int(self: Any, number: Any) -> Any:
        ...
