from typing import Any

def unpickle_FiniteField_ext(_type: Any, order: Any, variable_name: Any, modulus: Any, kwargs: Any) -> Any:
    ...

def unpickle_FiniteField_prm(_type: Any, order: Any, variable_name: Any, kwargs: Any) -> Any:
    ...

def is_FiniteField(R: Any) -> Any:
    ...

class FiniteField(Field):
    def __init__(self: Any, base: Any, names: Any, normalize: Any, category: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, m: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def from_integer(self: Any, n: Any, reverse: Any = ...) -> Any:
        ...
    def gen(self: Any) -> Any:
        ...
    def multiplicative_generator(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def factored_order(self: Any) -> Any:
        ...
    def factored_unit_order(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def is_prime_field(self: Any) -> Any:
        ...
    def modulus(self: Any) -> Any:
        ...
    def polynomial(self: Any, name: Any = ...) -> Any:
        ...
    def unit_group_exponent(self: Any) -> Any:
        ...
    def random_element(self: Any) -> Any:
        ...
    def some_elements(self: Any) -> Any:
        ...
    def polynomial_ring(self: Any, variable_name: Any = ...) -> Any:
        ...
    def free_module(self: Any, base: Any = ..., basis: Any = ..., map: Any = ...) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def make_family(gen: Any, poly: Any) -> Any:
        ...
    def subfield(self: Any, degree: Any, name: Any = ..., map: Any = ...) -> Any:
        ...
    def subfields(self: Any, degree: Any = ..., name: Any = ...) -> Any:
        ...
    def algebraic_closure(self: Any, name: Any = ...) -> Any:
        ...
    def is_conway(self: Any) -> Any:
        ...
    def an_embedding(self: Any, K: Any) -> Any:
        ...
    def embeddings(self: Any, K: Any) -> Any:
        ...
    def frobenius_endomorphism(self: Any, n: Any = ...) -> Any:
        ...
    def galois_group(self: Any) -> Any:
        ...
    def dual_basis(self: Any, basis: Any = ..., check: Any = ...) -> Any:
        ...
    def from_bytes(self: Any, input_bytes: Any, byteorder: Any = ...) -> Any:
        ...
