from typing import Any, List, Optional, Tuple, Iterator
from sage.rings.ring import Field
from sage.rings.integer import Integer

def unpickle_FiniteField_ext(_type: Any, order: Integer, variable_name: str, modulus: Any, kwargs: Any) -> "FiniteField":
    ...

def unpickle_FiniteField_prm(_type: Any, order: Integer, variable_name: str, kwargs: Any) -> "FiniteField":
    ...

def is_FiniteField(R: Any) -> bool:
    ...

class FiniteField(Field):
    def __init__(self, base: Any, names: Any, normalize: bool, category: Any = ...) -> None:
        ...
    def __hash__(self) -> int:
        ...
    def __richcmp__(self, other: Any, m: int) -> bool:
        ...
    def __iter__(self) -> Iterator[Any]:
        ...
    def from_integer(self, n: int, reverse: bool = ...) -> Any:
        ...
    def gen(self) -> Any:
        ...
    def multiplicative_generator(self) -> Any:
        ...
    def ngens(self) -> int:
        ...
    def order(self) -> Integer:
        ...
    def factored_order(self) -> Any:
        ...
    def factored_unit_order(self) -> Any:
        ...
    def cardinality(self) -> Integer:
        ...
    def is_prime_field(self) -> bool:
        ...
    def modulus(self) -> Any:
        ...
    def polynomial(self, name: Optional[str] = ...) -> Any:
        ...
    def unit_group_exponent(self) -> Integer:
        ...
    def random_element(self) -> Any:
        ...
    def some_elements(self) -> List[Any]:
        ...
    def polynomial_ring(self, variable_name: Optional[str] = ...) -> Any:
        ...
    def free_module(self, base: Any = ..., basis: Any = ..., map: bool = ...) -> Any:
        ...
    def construction(self) -> Optional[Tuple[Any, Any]]:
        ...
    def make_family(gen: Any, poly: Any) -> Any:
        ...
    def subfield(self, degree: int, name: Optional[str] = ..., map: bool = ...) -> "FiniteField":
        ...
    def subfields(self, degree: Optional[int] = ..., name: Optional[str] = ...) -> List["FiniteField"]:
        ...
    def algebraic_closure(self, name: Optional[str] = ...) -> Any:
        ...
    def is_conway(self) -> bool:
        ...
    def an_embedding(self, K: Any) -> Any:
        ...
    def embeddings(self, K: Any) -> List[Any]:
        ...
    def frobenius_endomorphism(self, n: int = ...) -> Any:
        ...
    def galois_group(self) -> Any:
        ...
    def dual_basis(self, basis: Any = ..., check: bool = ...) -> List[Any]:
        ...
    def from_bytes(self, input_bytes: bytes, byteorder: str = ...) -> Any:
        ...
