from typing import Any

class SectionFiniteFieldHomomorphism_generic(Section):
    ...

class FiniteFieldHomomorphism_generic(RingHomomorphism_im_gens):
    def __init__(self: Any, parent: Any, im_gens: Any = ..., base_map: Any = ..., check: Any = ..., section_class: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class FrobeniusEndomorphism_finite_field(FrobeniusEndomorphism_generic):
    def __init__(self: Any, domain: Any, n: Any = ...) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def power(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, modulus: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
    def fixed_field(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def is_identity(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
