from typing import Any, List, Optional, Union, Tuple
from sage.rings.finite_rings.finite_field_base import FiniteRingElement
from sage.categories.morphism import Morphism
from sage.categories.map import Map
from sage.rings.integer import Integer
from sage.rings.rational import Rational

def Mod(n: Any, m: Any, parent: Any = ...) -> "IntegerMod_abstract":
    ...

def IntegerMod(parent: Any, value: Any) -> "IntegerMod_abstract":
    ...

def is_IntegerMod(x: Any) -> bool:
    ...

def square_root_mod_prime_power(a: int, p: int, e: int) -> int:
    ...

def square_root_mod_prime(a: int, p: int = ...) -> int:
    ...

def lucas_q1(mm: int, P: int) -> int:
    ...

def lucas(k: int, P: int, Q: int = ..., n: int = ...) -> int:
    ...

class PariError(Exception):
    ...

class NativeIntStruct:
    def __cinit__(self) -> None:
        ...
    def __init__(self, m: int) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def precompute_table(self, parent: Any) -> None:
        ...

class IntegerMod_abstract(FiniteRingElement):
    def __init__(self, parent: Any, value: Any = ...) -> None:
        ...
    def __abs__(self) -> "IntegerMod_abstract":
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def __mod__(self, modulus: Any) -> "IntegerMod_abstract":
        ...
    def is_nilpotent(self) -> bool:
        ...
    def __pari__(self) -> Any:
        ...
    def log(self, b: Any = ..., order: Optional[int] = ..., check: bool = ...) -> Any:
        ...
    def generalised_log(self) -> List[int]:
        ...
    def modulus(self) -> Integer:
        ...
    def charpoly(self, var: str = ...) -> Any:
        ...
    def minpoly(self, var: str = ...) -> Any:
        ...
    def minimal_polynomial(self, var: str = ...) -> Any:
        ...
    def polynomial(self, var: str = ...) -> Any:
        ...
    def norm(self) -> Any:
        ...
    def trace(self) -> Any:
        ...
    def lift_centered(self) -> Integer:
        ...
    def divides(self, other: "IntegerMod_abstract") -> bool:
        ...
    def is_square(self) -> bool:
        ...
    def sqrt(self, extend: bool = ..., all: bool = ...) -> Union["IntegerMod_abstract", List["IntegerMod_abstract"]]:
        ...
    def nth_root(self, n: int, extend: bool = ..., all: bool = ..., algorithm: Optional[str] = ..., cunningham: bool = ...) -> Union["IntegerMod_abstract", List["IntegerMod_abstract"]]:
        ...
    def rational_reconstruction(self) -> Rational:
        ...
    def crt(self, other: "IntegerMod_abstract") -> "IntegerMod_abstract":
        ...
    def additive_order(self) -> Integer:
        ...
    def multiplicative_order(self) -> Integer:
        ...
    def valuation(self, p: int) -> int:
        ...

class IntegerMod_gmp(IntegerMod_abstract):
    def __cinit__(self) -> None:
        ...
    def __dealloc__(self) -> None:
        ...
    def __lshift__(self, k: int) -> "IntegerMod_gmp":
        ...
    def __rshift__(self, k: int) -> "IntegerMod_gmp":
        ...
    def __bool__(self) -> bool:
        ...
    def __copy__(self) -> "IntegerMod_gmp":
        ...
    def __deepcopy__(self, memo: Any) -> "IntegerMod_gmp":
        ...
    def __int__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __pow__(self, exp: Any, m: Any = None) -> "IntegerMod_gmp":
        ...
    def __invert__(self) -> "IntegerMod_gmp":
        ...
    def lift(self) -> Integer:
        ...
    def __float__(self) -> float:
        ...
    def __hash__(self) -> int:
        ...
    def gcd(self, other: "IntegerMod_abstract") -> "IntegerMod_gmp":
        ...

class IntegerMod_int(IntegerMod_abstract):
    def __bool__(self) -> bool:
        ...
    def __copy__(self) -> "IntegerMod_int":
        ...
    def __deepcopy__(self, memo: Any) -> "IntegerMod_int":
        ...
    def __int__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __lshift__(self, k: int) -> "IntegerMod_int":
        ...
    def __rshift__(self, k: int) -> "IntegerMod_int":
        ...
    def __pow__(self, exp: Any, m: Any = None) -> "IntegerMod_int":
        ...
    def __invert__(self) -> "IntegerMod_int":
        ...
    def lift(self) -> Integer:
        ...
    def __float__(self) -> float:
        ...
    def __hash__(self) -> int:
        ...
    def sqrt(self, extend: bool = ..., all: bool = ...) -> Union["IntegerMod_int", List["IntegerMod_int"]]:
        ...
    def gcd(self, other: "IntegerMod_abstract") -> "IntegerMod_int":
        ...

class IntegerMod_int64(IntegerMod_abstract):
    def __bool__(self) -> bool:
        ...
    def __copy__(self) -> "IntegerMod_int64":
        ...
    def __deepcopy__(self, memo: Any) -> "IntegerMod_int64":
        ...
    def __int__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __lshift__(self, k: int) -> "IntegerMod_int64":
        ...
    def __rshift__(self, k: int) -> "IntegerMod_int64":
        ...
    def __pow__(self, exp: Any, m: Any = None) -> "IntegerMod_int64":
        ...
    def __invert__(self) -> "IntegerMod_int64":
        ...
    def lift(self) -> Integer:
        ...
    def __float__(self) -> float:
        ...
    def __hash__(self) -> int:
        ...
    def gcd(self, other: "IntegerMod_abstract") -> "IntegerMod_int64":
        ...

class IntegerMod_hom(Morphism):
    def __init__(self, parent: Any) -> None:
        ...

class IntegerMod_to_IntegerMod(IntegerMod_hom):
    def __init__(self, R: Any, S: Any) -> None:
        ...
    def is_surjective(self) -> bool:
        ...
    def is_injective(self) -> bool:
        ...

class Integer_to_IntegerMod(IntegerMod_hom):
    def __init__(self, R: Any) -> None:
        ...
    def section(self) -> Any:
        ...
    def is_surjective(self) -> bool:
        ...
    def is_injective(self) -> bool:
        ...

class IntegerMod_to_Integer(Map):
    def __init__(self, R: Any) -> None:
        ...

class Int_to_IntegerMod(IntegerMod_hom):
    def __init__(self, R: Any) -> None:
        ...
