from typing import Any

def Mod(n: Any, m: Any, parent: Any = ...) -> Any:
    ...

def IntegerMod(parent: Any, value: Any) -> Any:
    ...

def is_IntegerMod(x: Any) -> Any:
    ...

def square_root_mod_prime_power(a: Any, p: Any, e: Any) -> Any:
    ...

def square_root_mod_prime(a: Any, p: Any = ...) -> Any:
    ...

def lucas_q1(mm: Any, P: Any) -> Any:
    ...

def lucas(k: Any, P: Any, Q: Any = ..., n: Any = ...) -> Any:
    ...

class PariError(Exception):
    ...

class NativeIntStruct:
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, m: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def precompute_table(self: Any, parent: Any) -> Any:
        ...

class IntegerMod_abstract(FiniteRingElement):
    def __init__(self: Any, parent: Any, value: Any = ...) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __mod__(self: Any, modulus: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def log(self: Any, b: Any = ..., order: Any = ..., check: Any = ...) -> Any:
        ...
    def generalised_log(self: Any) -> Any:
        ...
    def modulus(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def minimal_polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def norm(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def lift_centered(self: Any) -> Any:
        ...
    def divides(self: Any, other: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def nth_root(self: Any, n: Any, extend: Any = ..., all: Any = ..., algorithm: Any = ..., cunningham: Any = ...) -> Any:
        ...
    def rational_reconstruction(self: Any) -> Any:
        ...
    def crt(self: Any, other: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def valuation(self: Any, p: Any) -> Any:
        ...

class IntegerMod_gmp(IntegerMod_abstract):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, k: Any) -> Any:
        ...
    def __rshift__(self: Any, k: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, m: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...

class IntegerMod_int(IntegerMod_abstract):
    def __bool__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, k: Any) -> Any:
        ...
    def __rshift__(self: Any, k: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, m: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...

class IntegerMod_int64(IntegerMod_abstract):
    def __bool__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, k: Any) -> Any:
        ...
    def __rshift__(self: Any, k: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, m: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...

class IntegerMod_hom(Morphism):
    def __init__(self: Any, parent: Any) -> Any:
        ...

class IntegerMod_to_IntegerMod(IntegerMod_hom):
    def __init__(self: Any, R: Any, S: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...

class Integer_to_IntegerMod(IntegerMod_hom):
    def __init__(self: Any, R: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...

class IntegerMod_to_Integer(Map):
    def __init__(self: Any, R: Any) -> Any:
        ...

class Int_to_IntegerMod(IntegerMod_hom):
    def __init__(self: Any, R: Any) -> Any:
        ...
