from typing import Any

class ResidueFieldFactory(UniqueFactory):
    def create_key_and_extra_args(self: Any, p: Any, names: Any = ..., check: Any = ..., impl: Any = ...) -> Any:
        ...
    def create_object(self: Any, version: Any, key: Any) -> Any:
        ...

class ResidueField_generic(Field):
    def __init__(self: Any, p: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def ideal(self: Any) -> Any:
        ...
    def lift(self: Any, x: Any) -> Any:
        ...
    def reduction_map(self: Any) -> Any:
        ...
    def lift_map(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class ReductionMap(Map):
    def __init__(self: Any, K: Any, F: Any, to_vs: Any, to_order: Any, PB: Any, PBinv: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...

class ResidueFieldHomomorphism_global(RingHomomorphism):
    def __init__(self: Any, K: Any, F: Any, to_vs: Any, to_order: Any, PB: Any, PBinv: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def lift(self: Any, x: Any) -> Any:
        ...

class LiftingMap(Section):
    def __init__(self: Any, reduction: Any, to_order: Any, PB: Any) -> Any:
        ...

class ResidueFiniteField_prime_modn(ResidueField_generic, FiniteField_prime_modn):
    def __init__(self: Any, p: Any, name: Any, intp: Any, to_vs: Any, to_order: Any, PB: Any) -> Any:
        ...
