from typing import Any

def conjugatingbraid(braid1: Any, braid2: Any) -> Any:
    ...

def leftnormalform(braid: Any) -> Any:
    ...

def rightnormalform(braid: Any) -> Any:
    ...

def greatestcommondivisor(braid1: Any, braid2: Any) -> Any:
    ...

def leastcommonmultiple(braid1: Any, braid2: Any) -> Any:
    ...

def centralizer(braid: Any) -> Any:
    ...

def supersummitset(braid: Any) -> Any:
    ...

def ultrasummitset(braid: Any) -> Any:
    ...

def thurston_type(braid: Any) -> Any:
    ...

def rigidity(braid: Any) -> Any:
    ...

def sliding_circuits(braid: Any) -> Any:
    ...

def send_to_sss(braid: Any) -> Any:
    ...

def send_to_uss(braid: Any) -> Any:
    ...

def send_to_sc(braid: Any) -> Any:
    ...

def trajectory(braid: Any) -> Any:
    ...

def cyclic_slidings(braid: Any) -> Any:
    ...
