from typing import Any

def test_sigint_before_ecl_sig_on() -> Any:
    ...

def test_ecl_options() -> Any:
    ...

def init_ecl() -> Any:
    ...

def shutdown_ecl() -> Any:
    ...

def print_objects() -> Any:
    ...

def ecl_eval(s: Any) -> Any:
    ...

class EclObject:
    def __init__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def python(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def eval(self: Any) -> Any:
        ...
    def cons(self: Any, d: Any) -> Any:
        ...
    def rplaca(self: Any, d: Any) -> Any:
        ...
    def rplacd(self: Any, d: Any) -> Any:
        ...
    def car(self: Any) -> Any:
        ...
    def cdr(self: Any) -> Any:
        ...
    def caar(self: Any) -> Any:
        ...
    def cadr(self: Any) -> Any:
        ...
    def cdar(self: Any) -> Any:
        ...
    def cddr(self: Any) -> Any:
        ...
    def fixnump(self: Any) -> Any:
        ...
    def characterp(self: Any) -> Any:
        ...
    def nullp(self: Any) -> Any:
        ...
    def listp(self: Any) -> Any:
        ...
    def consp(self: Any) -> Any:
        ...
    def atomp(self: Any) -> Any:
        ...
    def symbolp(self: Any) -> Any:
        ...

class EclListIterator:
    def __init__(self: Any, o: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
