from typing import Any

def cocliques_HoffmannSingleton() -> Any:
    ...

def locally_GQ42_distance_transitive_graph() -> Any:
    ...

def ConwaySmith_for_3S7() -> Any:
    ...

def has_edge(u: Any, v: Any) -> Any:
    ...

def graph_3O73() -> Any:
    ...

def FosterGraph3S6() -> Any:
    ...

def J2Graph() -> Any:
    ...

def IvanovIvanovFaradjevGraph() -> Any:
    ...

def LargeWittGraph() -> Any:
    ...

def TruncatedWittGraph() -> Any:
    ...

def DoublyTruncatedWittGraph() -> Any:
    ...

def distance_3_doubly_truncated_Golay_code_graph() -> Any:
    ...

def shortened_00_11_binary_Golay_code_graph() -> Any:
    ...

def shortened_000_111_extended_binary_Golay_code_graph() -> Any:
    ...

def vanLintSchrijverGraph() -> Any:
    ...

def LeonardGraph() -> Any:
    ...

def UstimenkoGraph(m: Any, q: Any) -> Any:
    ...

def BilinearFormsGraph(d: Any, e: Any, q: Any) -> Any:
    ...

def AlternatingFormsGraph(n: Any, q: Any) -> Any:
    ...

def HermitianFormsGraph(n: Any, r: Any) -> Any:
    ...

def build_mat(v: Any, w: Any) -> Any:
    ...

def DoubleOddGraph(n: Any) -> Any:
    ...

def HalfCube(n: Any) -> Any:
    ...

def GrassmannGraph(q: Any, n: Any, input_e: Any) -> Any:
    ...

def DoubleGrassmannGraph(q: Any, e: Any) -> Any:
    ...

def is_from_GQ_spread(arr: Any) -> Any:
    ...

def graph_from_GQ_spread(s: Any, t: Any) -> Any:
    ...

def GeneralisedDodecagonGraph(s: Any, t: Any) -> Any:
    ...

def GeneralisedOctagonGraph(s: Any, t: Any) -> Any:
    ...

def GeneralisedHexagonGraph(s: Any, t: Any) -> Any:
    ...

def is_classical_parameters_graph(array: Any) -> Any:
    ...

def integral_log(x: Any, b: Any) -> Any:
    ...

def check_parameters(d: Any, b: Any, alpha: Any, beta: Any, arr: Any) -> Any:
    ...

def b_(i: Any) -> Any:
    ...

def c_(i: Any) -> Any:
    ...

def a_(i: Any) -> Any:
    ...

def graph_with_classical_parameters(d: Any, b: Any, alpha_in: Any, beta_in: Any, gamma: Any) -> Any:
    ...

def is_pseudo_partition_graph(arr: Any) -> Any:
    ...

def pseudo_partition_graph(m: Any, a: Any) -> Any:
    ...

def is_near_polygon(array: Any) -> Any:
    ...

def near_polygon_graph(family: Any, params: Any) -> Any:
    ...

def distance_regular_graph(arr: Any, existence: Any = ..., check: Any = ...) -> Any:
    ...

def result(G: Any) -> Any:
    ...

def is_iterable(obj: Any) -> Any:
    ...
