from typing import Any

def BalancedTree(r: Any, h: Any) -> Any:
    ...

def FibonacciTree(n: Any) -> Any:
    ...

def fib(level: Any, node: Any, y: Any) -> Any:
    ...

def RandomLobster(n: Any, p: Any, q: Any, seed: Any = ...) -> Any:
    ...

def RandomTree(n: Any, seed: Any = ...) -> Any:
    ...

def RandomTreePowerlaw(n: Any, gamma: Any = ..., tries: Any = ..., seed: Any = ...) -> Any:
    ...

def trees(n: Any) -> Any:
    ...

def nauty_gentreeg(options: Any = ..., debug: Any = ...) -> Any:
    ...

class TreeIterator:
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
