from typing import Any

def to_var(var: Any) -> Any:
    ...

def function_name(fn: Any) -> Any:
    ...

def get_builtin_functions() -> Dict[Any, Any]:
    ...

def generate_code(expr: Any, stream: Any) -> Any:
    ...

def op_list(args: Any, metadata: Any) -> Any:
    ...

class ExpressionTreeBuilder:
    def __init__(self: Any, vars: Any, domain: Any = ...) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def constant(self: Any, c: Any) -> Any:
        ...
    def var(self: Any, v: Any) -> Any:
        ...
    def call(self: Any, fn: Any) -> Any:
        ...
    def choice(self: Any, cond: Any, iftrue: Any, iffalse: Any) -> Any:
        ...

class Expression:
    def __init__(self: Any, etb: Any) -> Any:
        ...
    def __add__(s: Any, o: Any) -> Any:
        ...
    def __sub__(s: Any, o: Any) -> Any:
        ...
    def __mul__(s: Any, o: Any) -> Any:
        ...
    def __truediv__(s: Any, o: Any) -> Any:
        ...
    def __floordiv__(s: Any, o: Any) -> Any:
        ...
    def __pow__(s: Any, o: Any, dummy: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def abs(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...

class ExpressionConstant(Expression):
    def __init__(self: Any, etb: Any, c: Any) -> Any:
        ...
    def value(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class ExpressionVariable(Expression):
    def __init__(self: Any, etb: Any, n: Any) -> Any:
        ...
    def variable_index(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class ExpressionCall(Expression):
    def __init__(self: Any, etb: Any, fn: Any, args: Any) -> Any:
        ...
    def function(self: Any) -> Any:
        ...
    def arguments(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class ExpressionIPow(Expression):
    def __init__(self: Any, etb: Any, base: Any, exponent: Any) -> Any:
        ...
    def base(self: Any) -> Any:
        ...
    def exponent(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class ExpressionChoice(Expression):
    def __init__(self: Any, etb: Any, cond: Any, iftrue: Any, iffalse: Any) -> Any:
        ...
    def condition(self: Any) -> Any:
        ...
    def if_true(self: Any) -> Any:
        ...
    def if_false(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class IntegerPowerFunction:
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...

class InstructionStream:
    def __init__(self: Any, metadata: Any, n_args: Any, domain: Any = ...) -> Any:
        ...
    def load_const(self: Any, c: Any) -> Any:
        ...
    def load_arg(self: Any, n: Any) -> Any:
        ...
    def instr(self: Any, opname: Any) -> Any:
        ...
    def get_metadata(self: Any) -> Any:
        ...
    def current_op_list(self: Any) -> Any:
        ...
    def get_current(self: Any) -> Any:
        ...

class InterpreterMetadata:
    def __init__(self: Any, by_opname: Any, by_opcode: Any, ipow_range: Any) -> Any:
        ...

class CompilerInstrSpec:
    def __init__(self: Any, n_inputs: Any, n_outputs: Any, parameters: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class Wrapper:
    def __init__(self: Any, args: Any, metadata: Any) -> Any:
        ...
    def get_orig_args(self: Any) -> Any:
        ...
    def op_list(self: Any) -> Any:
        ...
    def python_calls(self: Any) -> Any:
        ...

class FastCallableFloatWrapper:
    def __init__(self: Any, ff: Any, imag_tol: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
