from typing import Any

def CrystalOfLetters(cartan_type: Any, element_print_style: Any = ..., dual: Any = ...) -> Any:
    ...

class ClassicalCrystalOfLetters(UniqueRepresentation, Parent):
    def __call__(self: Any, value: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def lt_elements(self: Any, x: Any, y: Any) -> Any:
        ...

class Letter(Element):
    def __init__(self: Any, parent: Any, value: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class EmptyLetter(Element):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Crystal_of_letters_type_A_element(Letter):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Crystal_of_letters_type_B_element(Letter):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Crystal_of_letters_type_C_element(Letter):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Crystal_of_letters_type_D_element(Letter):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Crystal_of_letters_type_G_element(Letter):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class LetterTuple(Element):
    def __init__(self: Any, parent: Any, value: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class Crystal_of_letters_type_E6_element(LetterTuple):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Crystal_of_letters_type_E6_element_dual(LetterTuple):
    def lift(self: Any) -> Any:
        ...
    def retract(self: Any, p: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...

class Crystal_of_letters_type_E7_element(LetterTuple):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class BKKLetter(Letter):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...

class CrystalOfBKKLetters(ClassicalCrystalOfLetters):
    def __classcall_private__(cls: Any, ct: Any, dual: Any = ...) -> Any:
        ...
    def __init__(self: Any, ct: Any, dual: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...

class CrystalOfQueerLetters(ClassicalCrystalOfLetters):
    def __classcall_private__(cls: Any, ct: Any) -> Any:
        ...
    def __init__(self: Any, ct: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def index_set(self: Any) -> Any:
        ...

class QueerLetter_element(Letter):
    def weight(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class LetterWrapped(Element):
    def __init__(self: Any, parent: Any, value: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class ClassicalCrystalOfLettersWrapped(ClassicalCrystalOfLetters):
    def __init__(self: Any, cartan_type: Any) -> Any:
        ...
    def __call__(self: Any, value: Any) -> Any:
        ...
