from typing import Any

def compute_new_lusztig_datum(enhanced_braid_chain: Any, initial_lusztig_datum: Any) -> Tuple[Any, ...]:
    ...

def tropical_plucker_relation(a: Any, lusztig_datum: Any) -> Tuple[Any, ...]:
    ...

def enhance_braid_move_chain(braid_move_chain: Any, cartan_type: Any) -> List[Any]:
    ...

class PBWDatum:
    def __init__(self: Any, parent: Any, long_word: Any, lusztig_datum: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other_PBWDatum: Any) -> Any:
        ...
    def is_equivalent_to(self: Any, other_pbw_datum: Any) -> Any:
        ...
    def convert_to_long_word_with_first_letter(self: Any, i: Any) -> Any:
        ...
    def convert_to_new_long_word(self: Any, new_long_word: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def star(self: Any) -> Any:
        ...

class PBWData:
    def __init__(self: Any, cartan_type: Any) -> Any:
        ...
    def convert_to_new_long_word(self: Any, pbw_datum: Any, new_long_word: Any) -> Any:
        ...
