from typing import Any

def CrystalOfSpins(ct: Any) -> Any:
    ...

def CrystalOfSpinsPlus(ct: Any) -> Any:
    ...

def CrystalOfSpinsMinus(ct: Any) -> Any:
    ...

class GenericCrystalOfSpins(UniqueRepresentation, Parent):
    def __init__(self: Any, ct: Any, element_class: Any, case: Any) -> Any:
        ...
    def lt_elements(self: Any, x: Any, y: Any) -> Any:
        ...

class Spin(Element):
    def __init__(self: Any, parent: Any, val: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def value(self: Any) -> Any:
        ...
    def signature(self: Any) -> Any:
        ...
    def pp(self: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...

class Spin_crystal_type_B_element(Spin):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class Spin_crystal_type_D_element(Spin):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
