from typing import Any

class ImmutableListWithParent(ClonableArray):
    def __init__(self: Any, parent: Any, list: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...

class TensorProductOfCrystalsElement(ImmutableListWithParent):
    def pp(self: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def epsilon(self: Any, i: Any) -> Any:
        ...
    def phi(self: Any, i: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class TensorProductOfRegularCrystalsElement(TensorProductOfCrystalsElement):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
    def phi(self: Any, i: Any) -> Any:
        ...
    def epsilon(self: Any, i: Any) -> Any:
        ...
    def position_of_last_unmatched_minus(self: Any, i: Any) -> Any:
        ...
    def position_of_first_unmatched_plus(self: Any, i: Any) -> Any:
        ...
    def positions_of_unmatched_minus(self: Any, i: Any, dual: Any = ..., reverse: Any = ...) -> Any:
        ...
    def positions_of_unmatched_plus(self: Any, i: Any) -> Any:
        ...

class CrystalOfTableauxElement(TensorProductOfRegularCrystalsElement):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def pp(self: Any) -> Any:
        ...
    def to_tableau(self: Any) -> Any:
        ...
    def shape(self: Any) -> Any:
        ...
    def promotion(self: Any) -> Any:
        ...
    def promotion_inverse(self: Any) -> Any:
        ...

class InfinityCrystalOfTableauxElement(CrystalOfTableauxElement):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class InfinityCrystalOfTableauxElementTypeD(InfinityCrystalOfTableauxElement):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...

class TensorProductOfSuperCrystalsElement(TensorProductOfRegularCrystalsElement):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
    def epsilon(self: Any, i: Any) -> Any:
        ...
    def phi(self: Any, i: Any) -> Any:
        ...

class CrystalOfBKKTableauxElement(TensorProductOfSuperCrystalsElement):
    def pp(self: Any) -> Any:
        ...
    def to_tableau(self: Any) -> Any:
        ...

class TensorProductOfQueerSuperCrystalsElement(TensorProductOfRegularCrystalsElement):
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
    def epsilon(self: Any, i: Any) -> Any:
        ...
    def phi(self: Any, i: Any) -> Any:
        ...

class InfinityQueerCrystalOfTableauxElement(TensorProductOfQueerSuperCrystalsElement):
    def __init__(self: Any, parent: Any, list: Any, row_lengths: Any = ...) -> Any:
        ...
    def rows(self: Any) -> Any:
        ...
    def e(self: Any, i: Any) -> Any:
        ...
    def f(self: Any, i: Any) -> Any:
        ...
    def epsilon(self: Any, i: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def fwt(i: Any) -> Any:
        ...
