from typing import Any

def is_PointCollection(x: Any) -> Any:
    ...

def read_palp_point_collection(f: Any, lattice: Any = ..., permutation: Any = ...) -> Any:
    ...

class PointCollection(SageObject):
    def __init__(self: Any, points: Any, module: Any = ...) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, right: Any, op: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __list__(self: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __tuple__(self: Any) -> Any:
        ...
    def basis(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def cartesian_product(self: Any, other: Any, module: Any = ...) -> Any:
        ...
    def column_matrix(self: Any) -> Any:
        ...
    def dimension(self: Any) -> Any:
        ...
    def dual_module(self: Any) -> Any:
        ...
    def index(self: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def module(self: Any) -> Any:
        ...
    def output_format(format: Any = ...) -> Any:
        ...
    def set(self: Any) -> Any:
        ...
    def write_for_palp(self: Any, f: Any) -> Any:
        ...
