from typing import Any, Iterator, List, Tuple, Optional, Union
from sage.structure.sage_object import SageObject

def is_PointCollection(x: Any) -> bool:
    ...

def read_palp_point_collection(f: Any, lattice: Any = ..., permutation: Any = ...) -> "PointCollection":
    ...

class PointCollection(SageObject):
    def __init__(self, points: Any, module: Any = ...) -> None:
        ...
    def __add__(left: "PointCollection", right: "PointCollection") -> "PointCollection":
        ...
    def __call__(self) -> "PointCollection":
        ...
    def __richcmp__(self, right: "PointCollection", op: int) -> bool:
        ...
    def __getitem__(self, n: int) -> Any:
        ...
    def __hash__(self) -> int:
        ...
    def __iter__(self) -> Iterator[Any]:
        ...
    def __len__(self) -> int:
        ...
    def __list__(self) -> List[Any]:
        ...
    def __mul__(left: "PointCollection", right: Any) -> "PointCollection":
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def __tuple__(self) -> Tuple[Any, ...]:
        ...
    def basis(self) -> Any:
        ...
    def cardinality(self) -> int:
        ...
    def cartesian_product(self, other: "PointCollection", module: Any = ...) -> "PointCollection":
        ...
    def column_matrix(self) -> Any:
        ...
    def dimension(self) -> int:
        ...
    def dual_module(self) -> Any:
        ...
    def index(self) -> int:
        ...
    def matrix(self) -> Any:
        ...
    def module(self) -> Any:
        ...
    def output_format(format: Optional[str] = ...) -> Any:
        ...
    def set(self) -> set:
        ...
    def write_for_palp(self, f: Any) -> None:
        ...
