from typing import Any

def is_ToricLatticeElement(x: Any) -> Any:
    ...

def unpickle_v1(parent: Any, entries: Any, degree: Any, is_mutable: Any) -> Any:
    ...

class ToricLatticeElement(Vector_integer_dense):
    def __richcmp__(self: Any, right: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...
