from typing import Any

class FiniteZZsubmodule_iterator:
    def __init__(self: Any, basis: Any, order: Any = ..., coset_rep: Any = ..., immutable: Any = ...) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...

class FiniteFieldsubspace_iterator(FiniteZZsubmodule_iterator):
    def __init__(self: Any, basis: Any, coset_rep: Any = ..., immutable: Any = ...) -> Any:
        ...

class FiniteFieldsubspace_projPoint_iterator:
    def __init__(self: Any, basis: Any, normalize: Any = ..., immutable: Any = ...) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
