from typing import Any

def is_FreeModuleElement(x: Any) -> Any:
    ...

def vector(arg0: Any, arg1: Any = ..., arg2: Any = ..., sparse: Any = ..., immutable: Any = ...) -> Any:
    ...

def prepare(v: Any, R: Any, degree: Any = ...) -> Any:
    ...

def zero_vector(arg0: Any, arg1: Any = ...) -> Any:
    ...

def random_vector(ring: Any, degree: Any = ...) -> Any:
    ...

def make_FreeModuleElement_generic_dense(parent: Any, entries: Any, degree: Any) -> Any:
    ...

def make_FreeModuleElement_generic_dense_v1(parent: Any, entries: Any, degree: Any, is_mutable: Any) -> Any:
    ...

def make_FreeModuleElement_generic_sparse(parent: Any, entries: Any, degree: Any) -> Any:
    ...

def make_FreeModuleElement_generic_sparse_v1(parent: Any, entries: Any, degree: Any, is_mutable: Any) -> Any:
    ...

class FreeModuleElement(Vector):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def numpy(self: Any, dtype: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def numerical_approx(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def row(self: Any) -> Any:
        ...
    def column(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def subs(self: Any, in_dict: Any = ...) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def coordinate_ring(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def norm(self: Any, p: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def get(self: Any, i: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, value: Any) -> Any:
        ...
    def set(self: Any, i: Any, value: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __mod__(self: Any, p: Any) -> Any:
        ...
    def Mod(self: Any, p: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> Any:
        ...
    def list_from_positions(self: Any, positions: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def lift_centered(self: Any) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, dummy: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def dict(self: Any, copy: Any = ...) -> Any:
        ...
    def plot(self: Any, plot_type: Any = ..., start: Any = ...) -> Any:
        ...
    def dot_product(self: Any, right: Any) -> Any:
        ...
    def cross_product(self: Any, right: Any) -> Any:
        ...
    def cross_product_matrix(self: Any) -> Any:
        ...
    def pairwise_product(self: Any, right: Any) -> Any:
        ...
    def div(self: Any, variables: Any = ...) -> Any:
        ...
    def curl(self: Any, variables: Any = ...) -> Any:
        ...
    def element(self: Any) -> Any:
        ...
    def monic(self: Any) -> Any:
        ...
    def normalized(self: Any, p: Any = ...) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def inner_product(self: Any, right: Any) -> Any:
        ...
    def outer_product(self: Any, right: Any) -> Any:
        ...
    def hermitian_inner_product(self: Any, right: Any) -> Any:
        ...
    def nonzero_positions(self: Any) -> Any:
        ...
    def support(self: Any) -> Any:
        ...
    def dense_vector(self: Any) -> Any:
        ...
    def sparse_vector(self: Any) -> Any:
        ...
    def apply_map(self: Any, phi: Any, R: Any = ..., sparse: Any = ...) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def integral(self: Any) -> Any:
        ...
    def nintegral(self: Any) -> Any:
        ...
    def concatenate(self: Any, other: Any, ring: Any = ...) -> Any:
        ...
    def compositional_inverse(self: Any, allow_multivalued_inverse: Any = ...) -> Any:
        ...

class FreeModuleElement_generic_dense(FreeModuleElement):
    def __copy__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any, coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def function(self: Any) -> Any:
        ...

class FreeModuleElement_generic_sparse(FreeModuleElement):
    def __copy__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def dict(self: Any, copy: Any = ...) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> Any:
        ...
    def nonzero_positions(self: Any) -> Any:
        ...
    def numerical_approx(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...
