from typing import Any

def is_Module(x: Any) -> Any:
    ...

def is_VectorSpace(x: Any) -> Any:
    ...

class Module(Parent):
    def __init__(self: Any, base: Any, category: Any = ..., names: Any = ...) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def base_extend(self: Any, R: Any) -> Any:
        ...
    def endomorphism_ring(self: Any) -> Any:
        ...
