from typing import Any

class Vector_numpy_dense(FreeModuleElement):
    def __cinit__(self: Any, parent: Any, entries: Any, coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def __create_vector__(self: Any) -> Any:
        ...
    def __copy__(self: Any, copy: Any = ...) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any, coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def numpy(self: Any, dtype: Any = ...) -> Any:
        ...
