from typing import Any

def unpickle_v0(parent: Any, entries: Any, degree: Any) -> Any:
    ...

def unpickle_v1(parent: Any, entries: Any, degree: Any, is_mutable: Any) -> Any:
    ...

class Vector_integer_dense(free_module_element.FreeModuleElement):
    def __copy__(self: Any) -> Any:
        ...
    def __cinit__(self: Any, parent: Any = ..., x: Any = ..., coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any, coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
