from typing import Any

class Vector_double_dense(Vector_numpy_dense):
    def inv_fft(self: Any, algorithm: Any = ..., inplace: Any = ...) -> Any:
        ...
    def fft(self: Any, direction: Any = ..., algorithm: Any = ..., inplace: Any = ...) -> Any:
        ...
    def complex_vector(self: Any) -> Any:
        ...
    def zero_at(self: Any, eps: Any) -> Any:
        ...
    def norm(self: Any, p: Any = ...) -> Any:
        ...
    def mean(self: Any) -> Any:
        ...
    def variance(self: Any, population: Any = ...) -> Any:
        ...
    def standard_deviation(self: Any, population: Any = ...) -> Any:
        ...
    def stats_kurtosis(self: Any) -> Any:
        ...
    def prod(self: Any) -> Any:
        ...
    def sum(self: Any) -> Any:
        ...
