from typing import Any

def unpickle_v0(parent: Any, entries: Any, degree: Any) -> Any:
    ...

def unpickle_v1(parent: Any, entries: Any, degree: Any, is_mutable: Any = ...) -> Any:
    ...

class Vector_real_double_dense(Vector_double_dense):
    def __cinit__(self: Any, parent: Any, entries: Any, coerce: Any = ..., copy: Any = ...) -> Any:
        ...
    def stats_skew(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
