from typing import Any

class SemimonomialTransformation(MultiplicativeGroupElement):
    def __init__(self: Any, parent: Any, v: Any, perm: Any, alpha: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def get_v(self: Any) -> Any:
        ...
    def get_v_inverse(self: Any) -> Any:
        ...
    def get_perm(self: Any) -> Any:
        ...
    def get_autom(self: Any) -> Any:
        ...
    def invert_v(self: Any) -> Any:
        ...
