from typing import Any

def get_var_mapping(ring: Any, other: Any) -> Any:
    ...

def add_up_polynomials(v: Any, init: Any) -> Any:
    ...

def nf3(s: Any, p: Any, m: Any) -> Any:
    ...

def red_tail(s: Any, p: Any) -> Any:
    ...

def map_every_x_to_x_plus_one(p: Any) -> Any:
    ...

def zeros(pol: Any, s: Any) -> Any:
    ...

def interpolate(zero: Any, one: Any) -> Any:
    ...

def interpolate_smallest_lex(zero: Any, one: Any) -> Any:
    ...

def contained_vars(m: Any) -> Any:
    ...

def mod_var_set(a: Any, v: Any) -> Any:
    ...

def mult_fact_sim_C(v: Any, ring: Any) -> Any:
    ...

def recursively_insert(n: Any, ind: Any, m: Any) -> Any:
    ...

def ll_red_nf_redsb(p: Any, reductors: Any) -> Any:
    ...

def ll_red_nf_noredsb(p: Any, reductors: Any) -> Any:
    ...

def ll_red_nf_noredsb_single_recursive_call(p: Any, reductors: Any) -> Any:
    ...

def mod_mon_set(a_s: Any, v_s: Any) -> Any:
    ...

def if_then_else(root: Any, a: Any, b: Any) -> Any:
    ...

def top_index(s: Any) -> Any:
    ...

def gauss_on_polys(inp: Any) -> Any:
    ...

def substitute_variables(parent: Any, vec: Any, poly: Any) -> Any:
    ...

def set_random_seed(seed: Any) -> Any:
    ...

def random_set(variables: Any, length: Any) -> Any:
    ...

def easy_linear_factors(p: Any) -> Any:
    ...

def unpickle_BooleanPolynomial(ring: Any, string: Any) -> Any:
    ...

def unpickle_BooleanPolynomial0(ring: Any, l: Any) -> Any:
    ...

def unpickle_BooleanPolynomialRing(n: Any, names: Any, order: Any) -> Any:
    ...

def TermOrder_from_pb_order(n: Any, order: Any, blocks: Any) -> Any:
    ...

class BooleanPolynomialRing(BooleanPolynomialRing_base):
    def __init__(self: Any, n: Any = ..., names: Any = ..., order: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...
    def change_ring(self: Any, base_ring: Any = ..., names: Any = ..., order: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def remove_var(self: Any, order: Any = ...) -> Any:
        ...
    def ideal(self: Any) -> Any:
        ...
    def random_element(self: Any, degree: Any = ..., terms: Any = ..., choose_degree: Any = ..., vars_set: Any = ...) -> Any:
        ...
    def cover_ring(self: Any) -> Any:
        ...
    def defining_ideal(self: Any) -> Any:
        ...
    def interpolation_polynomial(self: Any, zeros: Any, ones: Any) -> Any:
        ...
    def id(self: Any) -> Any:
        ...
    def variable(self: Any, i: Any = ...) -> Any:
        ...
    def get_order_code(self: Any) -> Any:
        ...
    def get_base_order_code(self: Any) -> Any:
        ...
    def has_degree_order(self: Any) -> Any:
        ...
    def one(self: Any) -> Any:
        ...
    def zero(self: Any) -> Any:
        ...
    def clone(self: Any, ordering: Any = ..., names: Any = ..., blocks: Any = ...) -> Any:
        ...
    def n_variables(self: Any) -> Any:
        ...

class BooleanMonomialMonoid(UniqueRepresentation, Monoid_class):
    def __init__(self: Any, polring: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...

class BooleanMonomial(MonoidElement):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def stable_hash(self: Any) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def index(self: Any) -> Any:
        ...
    def deg(self: Any) -> Any:
        ...
    def degree(self: Any, x: Any = ...) -> Any:
        ...
    def divisors(self: Any) -> Any:
        ...
    def multiples(self: Any, rhs: Any) -> Any:
        ...
    def reducible_by(self: Any, rhs: Any) -> Any:
        ...
    def set(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def iterindex(self: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __floordiv__(left: Any, right: Any) -> Any:
        ...
    def navigation(self: Any) -> Any:
        ...
    def gcd(self: Any, rhs: Any) -> Any:
        ...

class BooleanMonomialVariableIterator:
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class BooleanMonomialIterator:
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class BooleanPolynomial(MPolynomial):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def is_equal(self: Any, right: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, ignored: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def total_degree(self: Any) -> Any:
        ...
    def degree(self: Any, x: Any = ...) -> Any:
        ...
    def lm(self: Any) -> Any:
        ...
    def lt(self: Any) -> Any:
        ...
    def is_singleton(self: Any) -> Any:
        ...
    def is_singleton_or_pair(self: Any) -> Any:
        ...
    def is_pair(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def lead_deg(self: Any) -> Any:
        ...
    def vars_as_monomial(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def nvariables(self: Any) -> Any:
        ...
    def is_univariate(self: Any) -> Any:
        ...
    def univariate_polynomial(self: Any, R: Any = ...) -> Any:
        ...
    def monomials(self: Any) -> Any:
        ...
    def variable(self: Any, i: Any = ...) -> Any:
        ...
    def terms(self: Any) -> Any:
        ...
    def monomial_coefficient(self: Any, mon: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def subs(self: Any, in_dict: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def is_homogeneous(self: Any) -> Any:
        ...
    def set(self: Any) -> Any:
        ...
    def deg(self: Any) -> Any:
        ...
    def elength(self: Any) -> Any:
        ...
    def lead(self: Any) -> Any:
        ...
    def lex_lead(self: Any) -> Any:
        ...
    def lex_lead_deg(self: Any) -> Any:
        ...
    def constant(self: Any) -> Any:
        ...
    def navigation(self: Any) -> Any:
        ...
    def map_every_x_to_x_plus_one(self: Any) -> Any:
        ...
    def lead_divisors(self: Any) -> Any:
        ...
    def first_term(self: Any) -> Any:
        ...
    def reducible_by(self: Any, rhs: Any) -> Any:
        ...
    def n_nodes(self: Any) -> Any:
        ...
    def n_vars(self: Any) -> Any:
        ...
    def graded_part(self: Any, deg: Any) -> Any:
        ...
    def has_constant_part(self: Any) -> Any:
        ...
    def zeros_in(self: Any, s: Any) -> Any:
        ...
    def spoly(self: Any, rhs: Any) -> Any:
        ...
    def stable_hash(self: Any) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def reduce(self: Any, I: Any) -> Any:
        ...

class PolynomialConstruct:
    def lead(self: Any, x: Any) -> Any:
        ...
    def __call__(self: Any, x: Any, ring: Any = ...) -> Any:
        ...

class MonomialConstruct:
    def __call__(self: Any, x: Any) -> Any:
        ...

class VariableConstruct:
    def __call__(self: Any, arg: Any, ring: Any = ...) -> Any:
        ...

class BooleanPolynomialIterator:
    def __dealloc__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class BooleanPolynomialIdeal(MPolynomialIdeal):
    def __init__(self: Any, ring: Any, gens: Any = ..., coerce: Any = ...) -> Any:
        ...
    def dimension(self: Any) -> Any:
        ...
    def groebner_basis(self: Any, algorithm: Any = ...) -> Any:
        ...
    def variety(self: Any) -> Any:
        ...
    def reduce(self: Any, f: Any) -> Any:
        ...
    def interreduced_basis(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __ne__(self: Any, other: Any) -> Any:
        ...

class BooleSet:
    def __init__(self: Any, param: Any = ..., ring: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def set(self: Any) -> Any:
        ...
    def empty(self: Any) -> Any:
        ...
    def navigation(self: Any) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def cartesian_product(self: Any, rhs: Any) -> Any:
        ...
    def diff(self: Any, rhs: Any) -> Any:
        ...
    def union(self: Any, rhs: Any) -> Any:
        ...
    def change(self: Any, ind: Any) -> Any:
        ...
    def vars(self: Any) -> Any:
        ...
    def n_nodes(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __mod__(self: Any, vs: Any) -> Any:
        ...
    def __contains__(self: Any, m: Any) -> Any:
        ...
    def stable_hash(self: Any) -> Any:
        ...
    def divide(self: Any, rhs: Any) -> Any:
        ...
    def subset0(self: Any, i: Any) -> Any:
        ...
    def subset1(self: Any, i: Any) -> Any:
        ...
    def include_divisors(self: Any) -> Any:
        ...
    def minimal_elements(self: Any) -> Any:
        ...
    def intersect(self: Any, other: Any) -> Any:
        ...
    def divisors_of(self: Any, m: Any) -> Any:
        ...
    def multiples_of(self: Any, m: Any) -> Any:
        ...
    def size_double(self: Any) -> Any:
        ...

class BooleSetIterator:
    def __dealloc__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class CCuddNavigator:
    def __call__(self: Any) -> Any:
        ...
    def value(self: Any) -> Any:
        ...
    def else_branch(self: Any) -> Any:
        ...
    def then_branch(self: Any) -> Any:
        ...
    def constant(self: Any) -> Any:
        ...
    def terminal_one(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class BooleanPolynomialVector:
    def __init__(self: Any, I: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, p: Any) -> Any:
        ...
    def append(self: Any, el: Any) -> Any:
        ...

class BooleanPolynomialVectorIterator:
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class ReductionStrategy:
    def __init__(self: Any, ring: Any) -> Any:
        ...
    def add_generator(self: Any, p: Any) -> Any:
        ...
    def nf(self: Any, p: Any) -> Any:
        ...
    def reduced_normal_form(self: Any, p: Any) -> Any:
        ...
    def head_normal_form(self: Any, p: Any) -> Any:
        ...
    def can_rewrite(self: Any, p: Any) -> Any:
        ...
    def cheap_reductions(self: Any, p: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def __setattr__(self: Any, name: Any, val: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...

class BooleanPolynomialEntry:
    def __init__(self: Any, p: Any) -> Any:
        ...

class FGLMStrategy:
    def __init__(self: Any, from_ring: Any, to_ring: Any, vec: Any) -> Any:
        ...
    def main(self: Any) -> Any:
        ...

class GroebnerStrategy:
    def __init__(self: Any, param: Any) -> Any:
        ...
    def add_generator_delayed(self: Any, p: Any) -> Any:
        ...
    def add_generator(self: Any, p: Any) -> Any:
        ...
    def add_as_you_wish(self: Any, p: Any) -> Any:
        ...
    def implications(self: Any, i: Any) -> Any:
        ...
    def clean_top_by_chain_criterion(self: Any) -> Any:
        ...
    def symmGB_F2(self: Any) -> Any:
        ...
    def contains_one(self: Any) -> Any:
        ...
    def faugere_step_dense(self: Any, v: Any) -> Any:
        ...
    def minimalize(self: Any) -> Any:
        ...
    def minimalize_and_tail_reduce(self: Any) -> Any:
        ...
    def npairs(self: Any) -> Any:
        ...
    def top_sugar(self: Any) -> Any:
        ...
    def some_spolys_in_next_degree(self: Any, n: Any) -> Any:
        ...
    def all_spolys_in_next_degree(self: Any) -> Any:
        ...
    def small_spolys_in_next_degree(self: Any, f: Any, n: Any) -> Any:
        ...
    def ll_reduce_all(self: Any) -> Any:
        ...
    def next_spoly(self: Any) -> Any:
        ...
    def all_generators(self: Any) -> Any:
        ...
    def suggest_plugin_variable(self: Any) -> Any:
        ...
    def variable_has_value(self: Any, v: Any) -> Any:
        ...
    def nf(self: Any, p: Any) -> Any:
        ...
    def select(self: Any, m: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def __setattr__(self: Any, name: Any, val: Any) -> Any:
        ...

class BooleanMulAction(Action):
    ...

class VariableBlock:
    def __dealloc__(self: Any) -> Any:
        ...
    def __call__(self: Any, i: Any) -> Any:
        ...

class BooleConstant:
    def __init__(self: Any, value: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def deg(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def has_constant_part(self: Any) -> Any:
        ...

class VariableFactory:
    def __init__(self: Any, ring: Any = ...) -> Any:
        ...
    def __call__(self: Any, arg: Any = ..., ring: Any = ...) -> Any:
        ...

class MonomialFactory:
    def __init__(self: Any, ring: Any = ...) -> Any:
        ...
    def __call__(self: Any, arg: Any = ...) -> Any:
        ...

class PolynomialFactory:
    def __init__(self: Any, ring: Any = ...) -> Any:
        ...
    def lead(self: Any, x: Any) -> Any:
        ...
    def __call__(self: Any, arg: Any, ring: Any = ...) -> Any:
        ...
