from typing import Any

class Point(SageObject):
    def __init__(self: Any, point_configuration: Any, i: Any, projective: Any, affine: Any, reduced: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def point_configuration(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def index(self: Any) -> Any:
        ...
    def projective(self: Any) -> Any:
        ...
    def affine(self: Any) -> Any:
        ...
    def reduced_affine(self: Any) -> Any:
        ...
    def reduced_projective(self: Any) -> Any:
        ...
    def reduced_affine_vector(self: Any) -> Any:
        ...
    def reduced_projective_vector(self: Any) -> Any:
        ...

class PointConfiguration_base(Parent):
    def __init__(self: Any, points: Any, defined_affine: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def reduced_affine_vector_space(self: Any) -> Any:
        ...
    def reduced_projective_vector_space(self: Any) -> Any:
        ...
    def ambient_dim(self: Any) -> Any:
        ...
    def dim(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def n_points(self: Any) -> Any:
        ...
    def points(self: Any) -> Any:
        ...
    def point(self: Any, i: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def simplex_to_int(self: Any, simplex: Any) -> Any:
        ...
    def int_to_simplex(self: Any, s: Any) -> Any:
        ...

class ConnectedTriangulationsIterator(SageObject):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, point_configuration: Any, seed: Any = ..., star: Any = ..., fine: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
