from typing import Any

def test_valuation(a: int, p: int) -> int: ...

def test_padic_square(a: int, p: int) -> bool: ...

def test_qpls(a: int, b: int, c: int, d: int, e: int, p: int) -> int: ...

def test_els(a: int, b: int, c: int, d: int, e: int) -> int: ...

def two_descent_by_two_isogeny(E: Any, **kwds: Any) -> tuple[int, list[Any], dict[Any, Any]]: ...

def two_descent_by_two_isogeny_work(c: int, d: int, **kwds: Any) -> tuple[int, list[Any], dict[Any, Any]]: ...
