from typing import Any

class _CuspsForModularSymbolNumerical:
    def __init__(self: Any, r: Any, N: Any) -> Any:
        ...

class ModularSymbolNumerical:
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, E: Any, sign: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def elliptic_curve(self: Any) -> Any:
        ...
    def __call__(self: Any, r: Any, sign: Any = ..., use_twist: Any = ...) -> Any:
        ...
    def approximative_value(self: Any, r: Any, sign: Any = ..., prec: Any = ..., use_twist: Any = ...) -> Any:
        ...
    def clear_cache(self: Any) -> Any:
        ...
    def transportable_symbol(self: Any, r: Any, rr: Any, sign: Any = ...) -> Any:
        ...
    def manin_symbol(self: Any, u: Any, v: Any, sign: Any = ...) -> Any:
        ...
    def all_values_for_one_denominator(self: Any, m: Any, sign: Any = ...) -> Any:
        ...
