from typing import Any

class PeriodicRegion:
    def __init__(self: Any, w1: Any, w2: Any, data: Any, full: Any = ...) -> Any:
        ...
    def is_empty(self: Any) -> Any:
        ...
    def ds(self: Any) -> Any:
        ...
    def verify(self: Any, condition: Any) -> Any:
        ...
    def refine(self: Any, condition: Any = ..., times: Any = ...) -> Any:
        ...
    def expand(self: Any, corners: Any = ...) -> Any:
        ...
    def contract(self: Any, corners: Any = ...) -> Any:
        ...
    def __contains__(self: Any, z: Any) -> Any:
        ...
    def __truediv__(self: Any, n: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __and__(left: Any, right: Any) -> Any:
        ...
    def __xor__(left: Any, right: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def border(self: Any, raw: Any = ...) -> Any:
        ...
    def innermost_point(self: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...
