[build-system]
build-backend = 'mesonpy'
requires = [
    'meson-python',
    'cython >=3.0, != 3.0.3',
    'numpy >=1.19',
    'cypari2 >=2.1.1',
    'cysignals >=1.10.2',
    'gmpy2 >=2.1.0',
    'memory-allocator'
]

[project]
name = 'sagemath'
dynamic = ["version"]
description = "Sage: Open Source Mathematics Software"
dependencies = [
    'six >=1.15.0',
    'conway-polynomials >=0.8',
    'cypari2 >=2.1.1',
    'cysignals >=1.10.2',
    'cython >=3.0, != 3.0.3',
    'gmpy2 >=2.1.0',
    'importlib_metadata >=4.13',
    'importlib_resources >= 5.7',
    'jupyter_core >=4.6.3',
    'lrcalc ~=2.1',
    'memory-allocator',
    'numpy >=1.19',
    'pplpy >=0.8.6',
    'primecountpy',
    'requests >=2.13.0',
    'typing_extensions >= 4.4.0',
    'ipython >=7.13.0',
    'pexpect >=4.8.0',
    'networkx >=2.4, <3.3',
    'scipy >=1.5, <1.12',
    'sympy >=1.6, <2.0',
    'matplotlib >=3.5.1',
    'pillow >=7.2.0',
    'mpmath >=1.1.0',
    'ipykernel >=5.2.1',
    'jupyter-client',
    'ipywidgets >=7.5.1',
    'fpylll >=0.5.9',
    'ptyprocess > 0.5'
]

[tool.meson-python.args]
install = ['--skip-subprojects']
