from typing import Any

def edge_connectivity(g: Any) -> Any:
    ...

def clustering_coeff(g: Any, vertices: Any = ...) -> Any:
    ...

def dominator_tree(g: Any, root: Any, return_dict: Any = ..., reverse: Any = ...) -> Any:
    ...

def bandwidth_heuristics(g: Any, algorithm: Any = ...) -> Any:
    ...

def blocks_and_cut_vertices(g: Any) -> Any:
    ...

def shortest_paths(g: Any, start: Any, weight_function: Any = ..., algorithm: Any = ...) -> Any:
    ...

def johnson_shortest_paths(g: Any, weight_function: Any = ..., distances: Any = ..., predecessors: Any = ...) -> Any:
    ...

def floyd_warshall_shortest_paths(g: Any, weight_function: Any = ..., distances: Any = ..., predecessors: Any = ...) -> Any:
    ...

def johnson_closeness_centrality(g: Any, weight_function: Any = ...) -> Any:
    ...

def min_cycle_basis(g_sage: Any, weight_function: Any = ..., by_weight: Any = ...) -> Any:
    ...

def eccentricity_DHV(g: Any, vertex_list: Any = ..., weight_function: Any = ..., check_weight: Any = ...) -> Any:
    ...

def radius_DHV(g: Any, weight_function: Any = ..., check_weight: Any = ...) -> Any:
    ...

def diameter_DHV(g: Any, weight_function: Any = ..., check_weight: Any = ...) -> Any:
    ...

def wiener_index(g: Any, algorithm: Any = ..., weight_function: Any = ..., check_weight: Any = ...) -> Any:
    ...
