from typing import Any, List, Iterator, Optional, Union, Tuple
from sage.graphs.base.graph_backends import GenericGraphBackend

class CGraph:
    def has_vertex(self, n: Any) -> bool:
        ...
    def check_vertex(self, n: Any) -> None:
        ...
    def add_vertex(self, k: Any = ...) -> int:
        ...
    def add_vertices(self, verts: List[Any]) -> None:
        ...
    def del_vertex(self, v: Any) -> None:
        ...
    def verts(self) -> List[Any]:
        ...
    def realloc(self, total: int) -> None:
        ...
    def add_arc(self, u: Any, v: Any) -> int:
        ...
    def has_arc(self, u: Any, v: Any) -> bool:
        ...
    def del_all_arcs(self, u: Any, v: Any) -> None:
        ...
    def all_arcs(self, u: Any, v: Any) -> List[Any]:
        ...
    def del_arc_label(self, u: Any, v: Any, l: Any) -> None:
        ...
    def out_neighbors(self, u: Any) -> List[Any]:
        ...
    def in_neighbors(self, v: Any) -> List[Any]:
        ...

class CGraphBackend(GenericGraphBackend):
    def c_graph(self) -> CGraph:
        ...
    def loops(self, new: Optional[bool] = ...) -> bool:
        ...
    def num_edges(self, directed: bool) -> int:
        ...
    def num_verts(self) -> int:
        ...
    def has_vertex(self, v: Any) -> bool:
        ...
    def add_vertex(self, name: Any) -> None:
        ...
    def add_vertices(self, vertices: List[Any]) -> None:
        ...
    def del_vertex(self, v: Any) -> None:
        ...
    def del_vertices(self, vertices: List[Any]) -> None:
        ...
    def iterator_verts(self, verts: Optional[List[Any]] = ...) -> Iterator[Any]:
        ...
    def relabel(self, perm: Any, directed: bool) -> None:
        ...
    def degree(self, v: Any, directed: bool) -> int:
        ...
    def out_degree(self, v: Any) -> int:
        ...
    def in_degree(self, v: Any) -> int:
        ...
    def iterator_nbrs(self, v: Any) -> Iterator[Any]:
        ...
    def iterator_in_nbrs(self, v: Any) -> Iterator[Any]:
        ...
    def iterator_out_nbrs(self, v: Any) -> Iterator[Any]:
        ...
    def add_edges(self, edges: List[Any], directed: bool, remove_loops: bool = ...) -> None:
        ...
    def add_edge(self, u: Any, v: Any, l: Any, directed: bool) -> None:
        ...
    def del_edges(self, edges: List[Any], directed: bool) -> None:
        ...
    def del_edge(self, u: Any, v: Any, l: Any, directed: bool) -> None:
        ...
    def iterator_edges(self, vertices: Optional[List[Any]], labels: bool) -> Iterator[Any]:
        ...
    def iterator_unsorted_edges(self, vertices: Optional[List[Any]], labels: bool) -> Iterator[Any]:
        ...
    def iterator_out_edges(self, vertices: Optional[List[Any]], labels: bool) -> Iterator[Any]:
        ...
    def iterator_in_edges(self, vertices: Optional[List[Any]], labels: bool) -> Iterator[Any]:
        ...
    def is_subgraph(self, other: "CGraphBackend", vertices: List[Any], ignore_labels: bool = ...) -> bool:
        ...
    def subgraph_given_vertices(self, other: "CGraphBackend", vertices: List[Any]) -> None:
        ...
    def shortest_path_special(self, x: Any, y: Any, exclude_vertices: Optional[List[Any]] = ..., exclude_edges: Optional[List[Any]] = ..., distance_flag: bool = ...) -> Union[List[Any], Tuple[List[Any], int]]:
        ...
    def shortest_path(self, x: Any, y: Any, distance_flag: bool = ...) -> Union[List[Any], Tuple[List[Any], int]]:
        ...
    def weight_function(e: Any) -> Any:
        ...
    def weight_function(e: Any) -> Any:
        ...
    def is_connected(self, forbidden_vertices: Optional[List[Any]] = ...) -> bool:
        ...
    def is_strongly_connected(self) -> bool:
        ...
    def strongly_connected_component_containing_vertex(self, v: Any) -> List[Any]:
        ...
    def is_directed_acyclic(self, certificate: bool = ...) -> Union[bool, Tuple[bool, List[Any]]]:
        ...

class Search_iterator:
    def __dealloc__(self) -> None:
        ...
    def __iter__(self) -> "Search_iterator":
        ...
    def __next__(self) -> Any:
        ...
