from typing import Any

class CGraph:
    def has_vertex(self: Any, n: Any) -> bool:
        ...
    def check_vertex(self: Any, n: Any) -> Any:
        ...
    def add_vertex(self: Any, k: Any = ...) -> Any:
        ...
    def add_vertices(self: Any, verts: Any) -> Any:
        ...
    def del_vertex(self: Any, v: Any) -> Any:
        ...
    def verts(self: Any) -> List[Any]:
        ...
    def realloc(self: Any, total: Any) -> Any:
        ...
    def add_arc(self: Any, u: Any, v: Any) -> Any:
        ...
    def has_arc(self: Any, u: Any, v: Any) -> bool:
        ...
    def del_all_arcs(self: Any, u: Any, v: Any) -> Any:
        ...
    def all_arcs(self: Any, u: Any, v: Any) -> List[Any]:
        ...
    def del_arc_label(self: Any, u: Any, v: Any, l: Any) -> Any:
        ...
    def out_neighbors(self: Any, u: Any) -> List[Any]:
        ...
    def in_neighbors(self: Any, v: Any) -> List[Any]:
        ...

class CGraphBackend(GenericGraphBackend):
    def c_graph(self: Any) -> Any:
        ...
    def loops(self: Any, new: Any = ...) -> Any:
        ...
    def num_edges(self: Any, directed: Any) -> Any:
        ...
    def num_verts(self: Any) -> Any:
        ...
    def has_vertex(self: Any, v: Any) -> Any:
        ...
    def add_vertex(self: Any, name: Any) -> Any:
        ...
    def add_vertices(self: Any, vertices: Any) -> Any:
        ...
    def del_vertex(self: Any, v: Any) -> Any:
        ...
    def del_vertices(self: Any, vertices: Any) -> Any:
        ...
    def iterator_verts(self: Any, verts: Any = ...) -> Any:
        ...
    def relabel(self: Any, perm: Any, directed: Any) -> Any:
        ...
    def degree(self: Any, v: Any, directed: Any) -> Any:
        ...
    def out_degree(self: Any, v: Any) -> Any:
        ...
    def in_degree(self: Any, v: Any) -> Any:
        ...
    def iterator_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_in_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_out_nbrs(self: Any, v: Any) -> Any:
        ...
    def add_edges(self: Any, edges: Any, directed: Any, remove_loops: Any = ...) -> Any:
        ...
    def add_edge(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def del_edges(self: Any, edges: Any, directed: Any) -> Any:
        ...
    def del_edge(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def iterator_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_unsorted_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_out_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_in_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def is_subgraph(self: Any, other: Any, vertices: Any, ignore_labels: Any = ...) -> Any:
        ...
    def subgraph_given_vertices(self: Any, other: Any, vertices: Any) -> Any:
        ...
    def shortest_path_special(self: Any, x: Any, y: Any, exclude_vertices: Any = ..., exclude_edges: Any = ..., distance_flag: Any = ...) -> Any:
        ...
    def shortest_path(self: Any, x: Any, y: Any, distance_flag: Any = ...) -> Any:
        ...
    def weight_function(e: Any) -> Any:
        ...
    def weight_function(e: Any) -> Any:
        ...
    def is_connected(self: Any, forbidden_vertices: Any = ...) -> Any:
        ...
    def is_strongly_connected(self: Any) -> Any:
        ...
    def strongly_connected_component_containing_vertex(self: Any, v: Any) -> Any:
        ...
    def is_directed_acyclic(self: Any, certificate: Any = ...) -> Any:
        ...

class Search_iterator:
    def __dealloc__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
