from typing import Any

class DenseGraph(CGraph):
    def __cinit__(self: Any, nverts: Any, extra_vertices: Any = ..., verts: Any = ..., arcs: Any = ..., directed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def realloc(self: Any, total_verts: Any) -> Any:
        ...
    def complement(self: Any) -> Any:
        ...

class DenseGraphBackend(CGraphBackend):
    def __init__(self: Any, n: Any, directed: Any = ...) -> Any:
        ...
    def add_edges(self: Any, edges: Any, directed: Any, remove_loops: Any = ...) -> Any:
        ...
    def get_edge_label(self: Any, u: Any, v: Any) -> Any:
        ...
    def has_edge(self: Any, u: Any, v: Any, l: Any) -> Any:
        ...
    def multiple_edges(self: Any, new: Any) -> Any:
        ...
    def set_edge_label(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
