from typing import Any

def unpickle_graph_backend(directed: Any, vertices: Any, edges: Any, kwds: Any) -> Any:
    ...

class GenericGraphBackend(SageObject):
    def add_edge(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def add_edges(self: Any, edges: Any, directed: Any) -> Any:
        ...
    def add_vertex(self: Any, name: Any) -> Any:
        ...
    def add_vertices(self: Any, vertices: Any) -> Any:
        ...
    def degree(self: Any, v: Any, directed: Any) -> Any:
        ...
    def in_degree(self: Any, v: Any) -> Any:
        ...
    def out_degree(self: Any, v: Any) -> Any:
        ...
    def del_edge(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def del_vertex(self: Any, v: Any) -> Any:
        ...
    def del_vertices(self: Any, vertices: Any) -> Any:
        ...
    def get_edge_label(self: Any, u: Any, v: Any) -> Any:
        ...
    def has_edge(self: Any, u: Any, v: Any, l: Any) -> Any:
        ...
    def has_vertex(self: Any, v: Any) -> Any:
        ...
    def iterator_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_in_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_out_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_in_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_out_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_verts(self: Any, verts: Any) -> Any:
        ...
    def loops(self: Any, new: Any = ...) -> Any:
        ...
    def multiple_edges(self: Any, new: Any = ...) -> Any:
        ...
    def name(self: Any, new: Any = ...) -> Any:
        ...
    def num_edges(self: Any, directed: Any) -> Any:
        ...
    def num_verts(self: Any) -> Any:
        ...
    def relabel(self: Any, perm: Any, directed: Any) -> Any:
        ...
    def set_edge_label(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
