from typing import Any

class SparseGraph(CGraph):
    def __dealloc__(self: Any) -> Any:
        ...
    def realloc(self: Any, total: Any) -> Any:
        ...
    def add_arc_label(self: Any, u: Any, v: Any, l: Any = ...) -> Any:
        ...

class SparseGraphBackend(CGraphBackend):
    def __init__(self: Any, n: Any, directed: Any = ...) -> Any:
        ...
    def get_edge_label(self: Any, u: Any, v: Any) -> Any:
        ...
    def has_edge(self: Any, u: Any, v: Any, l: Any) -> Any:
        ...
    def multiple_edges(self: Any, new: Any) -> Any:
        ...
    def set_edge_label(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
