from typing import Any

class StaticSparseCGraph(CGraph):
    def __cinit__(self: Any, G: Any, vertex_list: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def has_vertex(self: Any, v: Any) -> bool:
        ...
    def add_vertex(self: Any, k: Any) -> Any:
        ...
    def del_vertex(self: Any, k: Any) -> Any:
        ...
    def verts(self: Any) -> List[Any]:
        ...
    def has_arc(self: Any, u: Any, v: Any) -> bool:
        ...
    def out_neighbors(self: Any, u: Any) -> List[Any]:
        ...
    def in_neighbors(self: Any, u: Any) -> List[Any]:
        ...
    def out_degree(self: Any, u: Any) -> int:
        ...
    def in_degree(self: Any, u: Any) -> int:
        ...

class StaticSparseBackend(CGraphBackend):
    def __init__(self: Any, G: Any, loops: Any = ..., multiedges: Any = ..., sort: Any = ...) -> Any:
        ...
    def has_vertex(self: Any, v: Any) -> Any:
        ...
    def add_vertex(self: Any, v: Any) -> Any:
        ...
    def add_edge(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def add_edges(self: Any, edges: Any, directed: Any, remove_loops: Any = ...) -> Any:
        ...
    def add_vertices(self: Any, vertices: Any) -> Any:
        ...
    def del_vertex(self: Any, v: Any) -> Any:
        ...
    def del_vertices(self: Any, vertices: Any) -> Any:
        ...
    def del_edge(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def del_edges(self: Any, edges: Any, directed: Any) -> Any:
        ...
    def set_edge_label(self: Any, u: Any, v: Any, l: Any, directed: Any) -> Any:
        ...
    def relabel(self: Any, perm: Any, directed: Any) -> Any:
        ...
    def get_edge_label(self: Any, u: Any, v: Any) -> Any:
        ...
    def has_edge(self: Any, u: Any, v: Any, l: Any) -> Any:
        ...
    def iterator_in_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_out_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def iterator_verts(self: Any, vertices: Any) -> Any:
        ...
    def num_verts(self: Any) -> Any:
        ...
    def allows_loops(self: Any, value: Any = ...) -> Any:
        ...
    def multiple_edges(self: Any, value: Any = ...) -> Any:
        ...
    def num_edges(self: Any, directed: Any) -> Any:
        ...
    def iterator_edges(self: Any, vertices: Any, labels: Any) -> Any:
        ...
    def degree(self: Any, v: Any, directed: Any) -> Any:
        ...
    def in_degree(self: Any, v: Any) -> Any:
        ...
    def out_degree(self: Any, v: Any) -> Any:
        ...
    def iterator_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_out_nbrs(self: Any, v: Any) -> Any:
        ...
    def iterator_in_nbrs(self: Any, v: Any) -> Any:
        ...
    def same_function_on_static_version() -> Any:
        ...
