from typing import Any

class ModularSymbols:
    def __init__(self: Any, level: Any, sign: Any = ..., cuspidal: Any = ..., verbose: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def level(self: Any) -> Any:
        ...
    def dimension(self: Any) -> Any:
        ...
    def number_of_cusps(self: Any) -> Any:
        ...
    def sign(self: Any) -> Any:
        ...
    def is_cuspidal(self: Any) -> Any:
        ...
    def hecke_matrix(self: Any, p: Any, dual: Any = ..., verbose: Any = ...) -> Any:
        ...
    def sparse_hecke_matrix(self: Any, p: Any, dual: Any = ..., verbose: Any = ..., base_ring: Any = ...) -> Any:
        ...
