from typing import Any

class Matrix:
    def __repr__(self: Any) -> Any:
        ...
    def str(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, ij: Any) -> Any:
        ...
    def nrows(self: Any) -> Any:
        ...
    def ncols(self: Any) -> Any:
        ...
    def add_scalar(self: Any, s: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def sage_matrix_over_ZZ(self: Any, sparse: Any = ...) -> Any:
        ...

class MatrixFactory:
    ...
