from typing import Any

def get_precision() -> Any:
    ...

def set_precision(n: Any) -> Any:
    ...

def initprimes(filename: Any, verb: Any = ...) -> Any:
    ...

def parse_point_list(s: Any) -> Any:
    ...

class _bigint:
    def __init__(self: Any, x: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class _Curvedata:
    def __init__(self: Any, a1: Any, a2: Any, a3: Any, a4: Any, a6: Any, min_on_init: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def silverman_bound(self: Any) -> Any:
        ...
    def cps_bound(self: Any) -> Any:
        ...
    def height_constant(self: Any) -> Any:
        ...
    def discriminant(self: Any) -> Any:
        ...
    def conductor(self: Any) -> Any:
        ...
    def isogeny_class(self: Any, verbose: Any = ...) -> Any:
        ...

class _mw:
    def __init__(self: Any, curve: Any, verb: Any = ..., pp: Any = ..., maxr: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def process(self: Any, point: Any, saturation_bound: Any = ...) -> Any:
        ...
    def getbasis(self: Any) -> Any:
        ...
    def regulator(self: Any) -> Any:
        ...
    def rank(self: Any) -> Any:
        ...
    def saturate(self: Any, sat_bd: Any = ..., sat_low_bd: Any = ...) -> Any:
        ...
    def search(self: Any, h_lim: Any, moduli_option: Any = ..., verb: Any = ...) -> Any:
        ...

class _two_descent:
    def __init__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def getrank(self: Any) -> Any:
        ...
    def getrankbound(self: Any) -> Any:
        ...
    def getselmer(self: Any) -> Any:
        ...
    def ok(self: Any) -> Any:
        ...
    def getcertain(self: Any) -> Any:
        ...
    def saturate(self: Any, saturation_bound: Any = ..., lower: Any = ...) -> Any:
        ...
    def getbasis(self: Any) -> Any:
        ...
    def regulator(self: Any) -> Any:
        ...
