from typing import Any

class ECModularSymbol:
    def __init__(self: Any, E: Any, sign: Any = ..., nap: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __call__(self: Any, r: Any, sign: Any = ..., base_at_infinity: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
