from typing import Any

def is_connected(G: Any, forbidden_vertices: Any = ...) -> Any:
    ...

def connected_components(G: Any, sort: Any = ..., key: Any = ..., forbidden_vertices: Any = ...) -> Any:
    ...

def connected_components_number(G: Any, forbidden_vertices: Any = ...) -> Any:
    ...

def connected_components_subgraphs(G: Any, forbidden_vertices: Any = ...) -> Any:
    ...

def connected_components_sizes(G: Any, forbidden_vertices: Any = ...) -> Any:
    ...

def blocks_and_cut_vertices(G: Any, algorithm: Any = ..., sort: Any = ..., key: Any = ...) -> Any:
    ...

def blocks_and_cuts_tree(G: Any) -> Any:
    ...

def biconnected_components_subgraphs(G: Any) -> Any:
    ...

def is_edge_cut(G: Any, edges: Any) -> Any:
    ...

def is_cut_edge(G: Any, u: Any, v: Any = ..., label: Any = ...) -> Any:
    ...

def is_vertex_cut(G: Any, cut: Any, weak: Any = ...) -> Any:
    ...

def is_cut_vertex(G: Any, u: Any, weak: Any = ...) -> Any:
    ...

def minimal_separators(G: Any, forbidden_vertices: Any = ...) -> Any:
    ...

def weight(x: Any) -> Any:
    ...

def weight(x: Any) -> Any:
    ...

def is_strongly_connected(G: Any) -> Any:
    ...

def strongly_connected_components_digraph(G: Any, keep_labels: Any = ...) -> Any:
    ...

def strongly_connected_components_subgraphs(G: Any) -> Any:
    ...

def strongly_connected_component_containing_vertex(G: Any, v: Any) -> Any:
    ...

def strong_articulation_points(G: Any) -> Any:
    ...

def bridges(G: Any, labels: Any = ...) -> Any:
    ...

def spqr_tree_to_graph(T: Any) -> Any:
    ...

def is_triconnected(G: Any) -> Any:
    ...

class _Component:
    def __init__(self: Any, edge_list: Any, type_c: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...

class TriconnectivitySPQR:
    def __init__(self: Any, G: Any, check: Any = ...) -> Any:
        ...
    def print_triconnected_components(self: Any) -> Any:
        ...
    def get_triconnected_components(self: Any) -> Any:
        ...
    def get_spqr_tree(self: Any) -> Any:
        ...
