from typing import Any

def geodetic_closure(G: Any, S: Any) -> Any:
    ...

def is_geodetic(G: Any) -> Any:
    ...

class ConvexityProperties:
    def __init__(self: Any, G: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def hull(self: Any, vertices: Any) -> Any:
        ...
    def hull_number(self: Any, value_only: Any = ..., verbose: Any = ...) -> Any:
        ...
