from typing import Any

def shortest_path_all_pairs(G: Any) -> Any:
    ...

def distances_all_pairs(G: Any) -> Any:
    ...

def is_distance_regular(G: Any, parameters: Any = ...) -> Any:
    ...

def distances_and_predecessors_all_pairs(G: Any) -> Any:
    ...

def eccentricity(G: Any, algorithm: Any = ..., vertex_list: Any = ...) -> Any:
    ...

def diameter(G: Any, algorithm: Any = ..., source: Any = ...) -> Any:
    ...

def radius_DHV(G: Any) -> Any:
    ...

def wiener_index(G: Any) -> Any:
    ...

def szeged_index(G: Any, algorithm: Any = ...) -> Any:
    ...

def distances_distribution(G: Any) -> Any:
    ...

def antipodal_graph(G: Any) -> Any:
    ...

def floyd_warshall(gg: Any, paths: Any = ..., distances: Any = ...) -> Any:
    ...
