from typing import Any

def layout_split(layout_function: Any, G: Any) -> Any:
    ...

def int_to_binary_string(n: Any) -> Any:
    ...

def binary_string_to_graph6(x: Any) -> Any:
    ...

def small_integer_to_graph6(n: Any) -> Any:
    ...

def length_and_string_from_graph6(s: Any) -> Any:
    ...

def binary_string_from_graph6(s: Any, n: Any) -> Any:
    ...

def binary_string_from_dig6(s: Any, n: Any) -> Any:
    ...

def transitive_reduction_acyclic(G: Any, immutable: Any = ...) -> Any:
    ...

class GenericGraph_pyx(SageObject):
    ...

class SubgraphSearch:
    def __init__(self: Any, G: Any, H: Any, induced: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __cinit__(self: Any, G: Any, H: Any, induced: Any = ...) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
