from typing import Any

def simple_connected_graph_genus(G: Any, set_embedding: Any = ..., check: Any = ..., minimal: Any = ...) -> Any:
    ...

class simple_connected_genus_backtracker:
    def __init__(self: Any, G: Any) -> Any:
        ...
    def get_embedding(self: Any) -> Any:
        ...
    def genus(self: Any, style: Any = ..., cutoff: Any = ..., record_embedding: Any = ...) -> Any:
        ...
