from typing import Any

def format_coloring(data: Any, value_only: Any = ..., hex_colors: Any = ..., vertex_color_dict: Any = ...) -> Any:
    ...

def first_coloring(G: Any, n: Any = ..., hex_colors: Any = ...) -> Any:
    ...

def number_of_n_colorings(G: Any, n: Any) -> Any:
    ...

def numbers_of_colorings(G: Any) -> Any:
    ...

def chromatic_number(G: Any) -> Any:
    ...

def fractional_chromatic_index(G: Any, solver: Any = ..., verbose_constraints: Any = ..., verbose: Any = ...) -> Any:
    ...

def extend_color_classes(classes: Any, coloring: Any) -> Any:
    ...

def colors_of(v: Any) -> Any:
    ...

def maximal_fan(edge: Any) -> Any:
    ...

def rotate_fan(fan_center: Any, fan: Any) -> Any:
    ...

def find_path(v: Any, a: Any, b: Any) -> Any:
    ...

def invert_path(v: Any, a: Any, b: Any) -> Any:
    ...

def find_free_color(v: Any) -> Any:
    ...

def round_robin(n: Any) -> Any:
    ...

def my_mod(x: Any, y: Any) -> Any:
    ...

def add(uv: Any, i: Any) -> Any:
    ...

def add(uv: Any, i: Any) -> Any:
    ...

def E(x: Any, y: Any) -> Any:
    ...

def add(uv: Any, i: Any) -> Any:
    ...

def add(uv: Any, i: Any) -> Any:
    ...

class Test:
    def random(self: Any, tests: Any = ...) -> Any:
        ...
    def random_all_graph_colorings(self: Any, tests: Any = ...) -> Any:
        ...
