from typing import Any

class IndependentSets:
    def __init__(self: Any, G: Any, maximal: Any = ..., complement: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __contains__(self: Any, S: Any) -> Any:
        ...
