from typing import Any

def all_paths(G: Any, start: Any, end: Any, use_multiedges: Any = ..., report_edges: Any = ..., labels: Any = ...) -> Any:
    ...

def length_func(path: Any) -> Any:
    ...

def length_func(path: Any) -> Any:
    ...

def relabeled_weight_function(e: Any, wf: Any = ...) -> Any:
    ...

def reverse_weight_function(e: Any) -> Any:
    ...

def tree_path(v: Any) -> Any:
    ...

def ancestor_idx_func(v: Any, t: Any, target_idx: Any) -> Any:
    ...

def shortest_path_to_green(dev: Any, exclude_vertices: Any, target_idx: Any) -> Any:
    ...
