from typing import Any

def kruskal(G: Any, by_weight: Any = ..., weight_function: Any = ..., check_weight: Any = ..., check: Any = ...) -> Any:
    ...

def kruskal_iterator(G: Any, by_weight: Any = ..., weight_function: Any = ..., check_weight: Any = ..., check: Any = ...) -> Any:
    ...

def boruvka(G: Any, by_weight: Any = ..., weight_function: Any = ..., check_weight: Any = ..., check: Any = ...) -> Any:
    ...

def random_spanning_tree(G: Any, output_as_graph: Any = ..., by_weight: Any = ..., weight_function: Any = ..., check_weight: Any = ...) -> Any:
    ...

def next_neighbor(s: Any) -> Any:
    ...

def next_neighbor(s: Any) -> Any:
    ...

def spanning_trees(g: Any, labels: Any = ...) -> Any:
    ...

def edge_disjoint_spanning_trees(G: Any, k: Any, by_weight: Any = ..., weight_function: Any = ..., check_weight: Any = ...) -> Any:
    ...
