from typing import Any

def is_paley(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_mathon_PC_srg(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_muzychuk_S6(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_orthogonal_array_block_graph(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_johnson(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_steiner(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_affine_polar(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_orthogonal_polar(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_goethals_seidel(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_NOodd(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_NOperp_F5(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_NO_F2(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_NO_F3(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_NU(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_haemers(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_cossidente_penttila(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_complete_multipartite(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def CompleteMultipartiteSRG(nparts: Any, partsize: Any) -> Any:
    ...

def is_polhill(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def additive_cayley(vertices: Any) -> Any:
    ...

def is_RSHCD(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def SRG_from_RSHCD(v: Any, k: Any, l: Any, mu: Any, existence: Any = ..., check: Any = ...) -> Any:
    ...

def sgn(x: Any) -> Any:
    ...

def is_unitary_polar(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_unitary_dual_polar(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_GQqmqp(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_twograph_descendant_of_srg(v: Any, k0: Any, l: Any, mu: Any) -> Any:
    ...

def la() -> Any:
    ...

def is_taylor_twograph_srg(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_switch_skewhad(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def is_switch_OA_srg(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def switch_OA_srg(c: Any, n: Any) -> Any:
    ...

def is_nowhere0_twoweight(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def eigenmatrix(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def latin_squares_graph_parameters(v: Any, k: Any, l: Any, mu: Any) -> Any:
    ...

def SRG_100_44_18_20() -> Any:
    ...

def SRG_100_45_20_20() -> Any:
    ...

def SRG_105_32_4_12() -> Any:
    ...

def SRG_120_77_52_44() -> Any:
    ...

def SRG_144_39_6_12() -> Any:
    ...

def SRG_176_49_12_14() -> Any:
    ...

def SRG_176_105_68_54() -> Any:
    ...

def SRG_210_99_48_45() -> Any:
    ...

def ekg(g0: Any) -> Any:
    ...

def SRG_243_110_37_60() -> Any:
    ...

def SRG_253_140_87_65() -> Any:
    ...

def SRG_196_91_42_42() -> Any:
    ...

def SRG_220_84_38_28() -> Any:
    ...

def SRG_276_140_58_84() -> Any:
    ...

def SRG_280_135_70_60() -> Any:
    ...

def SRG_280_117_44_52() -> Any:
    ...

def strongly_regular_from_two_weight_code(L: Any) -> Any:
    ...

def SRG_416_100_36_20() -> Any:
    ...

def SRG_560_208_72_80() -> Any:
    ...

def strongly_regular_from_two_intersection_set(M: Any) -> Any:
    ...

def SRG_120_63_30_36() -> Any:
    ...

def SRG_126_25_8_4() -> Any:
    ...

def SRG_175_72_20_36() -> Any:
    ...

def SRG_176_90_38_54() -> Any:
    ...

def SRG_630_85_20_10() -> Any:
    ...

def SRG_126_50_13_24() -> Any:
    ...

def SRG_1288_792_476_504() -> Any:
    ...

def strongly_regular_graph(v: Any, k: Any, l: Any, mu: Any = ..., existence: Any = ..., check: Any = ...) -> Any:
    ...

def strongly_regular_graph_lazy(v: Any, k: Any, l: Any, mu: Any = ..., existence: Any = ...) -> Any:
    ...

def apparently_feasible_parameters(n: Any) -> Any:
    ...
