from typing import Any

def lex_BFS(G: Any, reverse: Any = ..., tree: Any = ..., initial_vertex: Any = ..., algorithm: Any = ...) -> Any:
    ...

def lex_UP(G: Any, reverse: Any = ..., tree: Any = ..., initial_vertex: Any = ...) -> Any:
    ...

def lex_DFS(G: Any, reverse: Any = ..., tree: Any = ..., initial_vertex: Any = ...) -> Any:
    ...

def lex_DOWN(G: Any, reverse: Any = ..., tree: Any = ..., initial_vertex: Any = ...) -> Any:
    ...

def lex_M(self: Any, triangulation: Any = ..., labels: Any = ..., initial_vertex: Any = ..., algorithm: Any = ...) -> Any:
    ...

def lex_M_slow(G: Any, triangulation: Any = ..., labels: Any = ..., initial_vertex: Any = ...) -> Any:
    ...

def lex_M_fast(G: Any, triangulation: Any = ..., initial_vertex: Any = ...) -> Any:
    ...

def is_valid_lex_M_order(G: Any, alpha: Any, F: Any) -> Any:
    ...

def maximum_cardinality_search(G: Any, reverse: Any = ..., tree: Any = ..., initial_vertex: Any = ...) -> Any:
    ...

def maximum_cardinality_search_M(G: Any, initial_vertex: Any = ...) -> Any:
    ...
