from typing import Any

class EdgesView:
    def __len__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __eq__(self: Any, right: Any) -> Any:
        ...
    def __contains__(self: Any, e: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
