from typing import Any

def test_bitset(py_a: Any, py_b: Any, n: Any) -> Any:
    ...

def test_bitset_set_first_n(py_a: Any, n: Any) -> Any:
    ...

def test_bitset_remove(py_a: Any, n: Any) -> Any:
    ...

def test_bitset_pop(py_a: Any) -> Any:
    ...

def test_bitset_unpickle(data: Any) -> Any:
    ...

def test_bitset_copy_flex(py_a: Any) -> Any:
    ...

class FrozenBitset:
    def __cinit__(self: Any, iter: Any = ..., capacity: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, iter: Any = ..., capacity: Any = ...) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __reversed__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def issubset(self: Any, other: Any) -> bool:
        ...
    def issuperset(self: Any, other: Any) -> bool:
        ...
    def isdisjoint(self: Any, other: Any) -> bool:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __bytes__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def union(self: Any, other: Any) -> Any:
        ...
    def __or__(self: Any, other: Any) -> Any:
        ...
    def intersection(self: Any, other: Any) -> Any:
        ...
    def __and__(self: Any, other: Any) -> Any:
        ...
    def difference(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def symmetric_difference(self: Any, other: Any) -> Any:
        ...
    def __xor__(self: Any, other: Any) -> Any:
        ...
    def complement(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...

class Bitset(FrozenBitset):
    def __copy__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def update(self: Any, other: Any) -> Any:
        ...
    def __ior__(self: Any, other: Any) -> Any:
        ...
    def intersection_update(self: Any, other: Any) -> Any:
        ...
    def __iand__(self: Any, other: Any) -> Any:
        ...
    def difference_update(self: Any, other: Any) -> Any:
        ...
    def __isub__(self: Any, other: Any) -> Any:
        ...
    def symmetric_difference_update(self: Any, other: Any) -> Any:
        ...
    def __ixor__(self: Any, other: Any) -> Any:
        ...
    def add(self: Any, n: Any) -> Any:
        ...
    def remove(self: Any, n: Any) -> Any:
        ...
    def discard(self: Any, n: Any) -> Any:
        ...
    def pop(self: Any) -> Any:
        ...
    def clear(self: Any) -> Any:
        ...
