from typing import Any

def iaxpy(a: Any, X: Any, Y: Any, remove_zeros: Any = ..., factor_on_left: Any = ...) -> int:
    ...

def axpy(a: Any, X: Any, Y: Any, factor_on_left: Any = ...) -> Dict[Any, Any]:
    ...

def negate(D: Any) -> Dict[Any, Any]:
    ...

def scal(a: Any, D: Any, factor_on_left: Any = ...) -> Dict[Any, Any]:
    ...

def add(D: Any, D2: Any) -> Dict[Any, Any]:
    ...

def sum(dict_iter: Any) -> Dict[Any, Any]:
    ...

def linear_combination(dict_factor_iter: Any, factor_on_left: Any = ...) -> Dict[Any, Any]:
    ...

def sum_of_monomials(monomials: Any, scalar: Any) -> Dict[Any, Any]:
    ...

def sum_of_terms(index_coeff_pairs: Any) -> Dict[Any, Any]:
    ...

def convert_remove_zeroes(D: Any, R: Any) -> Dict[Any, Any]:
    ...
