from typing import Any

def NewBISEQ(bitset_data: Any, itembitsize: Any, length: Any) -> Any:
    ...

class BoundedIntegerSequence:
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, bound: Any, data: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def bound(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, index: Any) -> Any:
        ...
    def __contains__(self: Any, other: Any) -> Any:
        ...
    def list(self: Any) -> List[Any]:
        ...
    def index(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def maximal_overlap(self: Any, other: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
