from typing import Any

class PairingHeap_class:
    def __repr__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def top(self: Any) -> Tuple[Any, ...]:
        ...
    def top_value(self: Any) -> Any:
        ...

class PairingHeap_of_n_integers(PairingHeap_class):
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def push(self: Any, item: Any, value: Any) -> None:
        ...
    def top(self: Any) -> Tuple[Any, ...]:
        ...
    def top_item(self: Any) -> int:
        ...
    def decrease(self: Any, item: Any, new_value: Any) -> None:
        ...
    def __contains__(self: Any, item: Any) -> Any:
        ...
    def value(self: Any, item: Any) -> Any:
        ...

class PairingHeap_of_n_hashables(PairingHeap_class):
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def push(self: Any, item: Any, value: Any) -> None:
        ...
    def top(self: Any) -> Tuple[Any, ...]:
        ...
    def top_item(self: Any) -> Any:
        ...
    def decrease(self: Any, item: Any, new_value: Any) -> None:
        ...
    def __contains__(self: Any, item: Any) -> Any:
        ...
    def value(self: Any, item: Any) -> Any:
        ...
