from typing import Any

def flatten_list(L: Any) -> Any:
    ...

def min3(v: Any) -> Any:
    ...

def max3(v: Any) -> Any:
    ...

def point_list_bounding_box(v: Any) -> Any:
    ...

def optimal_aspect_ratios(ratios: Any) -> Any:
    ...

def optimal_extra_kwds(v: Any) -> Any:
    ...

class Graphics3d(SageObject):
    def __cinit__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def aspect_ratio(self: Any, v: Any = ...) -> Any:
        ...
    def frame_aspect_ratio(self: Any, v: Any = ...) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def transform(self: Any) -> Any:
        ...
    def translate(self: Any) -> Any:
        ...
    def scale(self: Any) -> Any:
        ...
    def rotate(self: Any, v: Any, theta: Any) -> Any:
        ...
    def rotateX(self: Any, theta: Any) -> Any:
        ...
    def rotateY(self: Any, theta: Any) -> Any:
        ...
    def rotateZ(self: Any, theta: Any) -> Any:
        ...
    def viewpoint(self: Any) -> Any:
        ...
    def default_render_params(self: Any) -> Any:
        ...
    def testing_render_params(self: Any) -> Any:
        ...
    def x3d(self: Any) -> Any:
        ...
    def obj(self: Any) -> Any:
        ...
    def json_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def texture_set(self: Any) -> Any:
        ...
    def mtl_str(self: Any) -> Any:
        ...
    def flatten(self: Any) -> Any:
        ...
    def show(self: Any) -> Any:
        ...
    def save_image(self: Any, filename: Any) -> Any:
        ...
    def save(self: Any, filename: Any) -> Any:
        ...
    def stl_binary(self: Any) -> Any:
        ...
    def stl_ascii_string(self: Any, name: Any = ...) -> Any:
        ...
    def chopped_faces_iter() -> Any:
        ...
    def ply_ascii_string(self: Any, name: Any = ...) -> Any:
        ...
    def amf_ascii_string(self: Any, name: Any = ...) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...

class Graphics3dGroup(Graphics3d):
    def __init__(self: Any, all: Any = ..., rot: Any = ..., trans: Any = ..., scale: Any = ..., T: Any = ...) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def transform(self: Any) -> Any:
        ...
    def set_texture(self: Any) -> Any:
        ...
    def json_repr(self: Any, render_params: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def x3d_str(self: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def stl_binary_repr(self: Any, render_params: Any) -> Any:
        ...
    def texture_set(self: Any) -> Any:
        ...
    def flatten(self: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...

class TransformGroup(Graphics3dGroup):
    def __init__(self: Any, all: Any = ..., rot: Any = ..., trans: Any = ..., scale: Any = ..., T: Any = ...) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def x3d_str(self: Any) -> Any:
        ...
    def json_repr(self: Any, render_params: Any) -> Any:
        ...
    def stl_binary_repr(self: Any, render_params: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def get_transformation(self: Any) -> Any:
        ...
    def flatten(self: Any) -> Any:
        ...
    def transform(self: Any) -> Any:
        ...

class KeyframeAnimationGroup(Graphics3dGroup):
    def __init__(self: Any, all: Any = ...) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...

class Viewpoint(Graphics3d):
    def __init__(self: Any) -> Any:
        ...
    def x3d_str(self: Any) -> Any:
        ...

class PrimitiveObject(Graphics3d):
    def __init__(self: Any) -> Any:
        ...
    def set_texture(self: Any, texture: Any = ...) -> Any:
        ...
    def get_texture(self: Any) -> Any:
        ...
    def texture_set(self: Any) -> Any:
        ...
    def x3d_str(self: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...

class BoundingSphere(SageObject):
    def __init__(self: Any, cen: Any, r: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def transform(self: Any, T: Any) -> Any:
        ...

class RenderParams(SageObject):
    def __init__(self: Any) -> Any:
        ...
    def push_transform(self: Any, T: Any) -> Any:
        ...
    def pop_transform(self: Any) -> Any:
        ...
    def unique_name(self: Any, desc: Any = ...) -> Any:
        ...
