from typing import Any

def render_implicit(f: Any, xrange: Any, yrange: Any, zrange: Any, plot_points: Any, cube_marchers: Any) -> Any:
    ...

class VertexInfo:
    def __repr__(self: Any) -> Any:
        ...

class MarchingCubes:
    def finish(self: Any) -> Any:
        ...

class MarchingCubesTriangles(MarchingCubes):
    def __init__(self: Any) -> Any:
        ...
    def process_slice(self: Any, x: Any, slice: Any) -> Any:
        ...
    def process_cubes(self: Any, _left: Any, _right: Any) -> Any:
        ...
    def add_triangle(self: Any, v1: Any, v2: Any, v3: Any) -> Any:
        ...

class ImplicitSurface(IndexFaceSet):
    def bounding_box(self: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def json_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def triangulate(self: Any, force: Any = ...) -> Any:
        ...
