from typing import Any

def midpoint(pointa: Any, pointb: Any, w: Any) -> Any:
    ...

def cut_edge_by_bisection(pointa: Any, pointb: Any, condition: Any, eps: Any = ..., N: Any = ...) -> Any:
    ...

def sticker(face: Any, width: Any, hover: Any) -> Any:
    ...

class IndexFaceSet(PrimitiveObject):
    def __dealloc__(self: Any) -> Any:
        ...
    def is_enclosed(self: Any) -> Any:
        ...
    def index_faces(self: Any) -> Any:
        ...
    def index_faces_with_colors(self: Any) -> Any:
        ...
    def faces(self: Any) -> Any:
        ...
    def face_list(self: Any, render_params: Any = ...) -> Any:
        ...
    def edges(self: Any) -> Any:
        ...
    def edge_list(self: Any) -> Any:
        ...
    def vertices(self: Any) -> Any:
        ...
    def vertex_list(self: Any) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def partition(self: Any, f: Any) -> Any:
        ...
    def add_condition(self: Any, condition: Any, N: Any = ..., eps: Any = ...) -> Any:
        ...
    def condi(x: Any, y: Any, z: Any) -> Any:
        ...
    def condi(x: Any, y: Any, z: Any) -> Any:
        ...
    def cut(a: Any, b: Any, c: Any) -> Any:
        ...
    def cut(x: Any, y: Any, z: Any) -> Any:
        ...
    def iter_split_faces() -> Any:
        ...
    def iter_split_faces() -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def json_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def stl_binary_repr(self: Any, render_params: Any) -> Any:
        ...
    def chopped_faces_iter() -> Any:
        ...
    def dual(self: Any) -> Any:
        ...
    def stickers(self: Any, colors: Any, width: Any, hover: Any) -> Any:
        ...
    def sticker(self: Any, face_list: Any, width: Any, hover: Any) -> Any:
        ...

class FaceIter:
    def __init__(self: Any, face_set: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class EdgeIter:
    def __init__(self: Any, face_set: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class VertexIter:
    def __init__(self: Any, face_set: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
