from typing import Any

def f(x: Any, y: Any) -> Any:
    ...

def f(x: Any, y: Any) -> Any:
    ...

def f(x: Any, y: Any) -> Any:
    ...

def c(x: Any, y: Any) -> Any:
    ...

def g(x: Any, y: Any) -> Any:
    ...

def c(x: Any, y: Any) -> Any:
    ...

class ParametricSurface(IndexFaceSet):
    def f(x: Any, y: Any) -> Any:
        ...
    def f(u: Any, v: Any) -> Any:
        ...
    def g(x: Any, y: Any) -> Any:
        ...
    def c(x: Any, y: Any) -> Any:
        ...
    def __init__(self: Any, f: Any = ..., domain: Any = ...) -> Any:
        ...
    def default_render_params(self: Any) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def json_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def is_enclosed(self: Any) -> Any:
        ...
    def dual(self: Any) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def triangulate(self: Any, render_params: Any = ...) -> Any:
        ...
    def get_grid(self: Any, ds: Any) -> Any:
        ...
    def eval(self: Any, u: Any, v: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...

class MoebiusStrip(ParametricSurface):
    def __init__(self: Any, r: Any, width: Any, twists: Any = ...) -> Any:
        ...
    def get_grid(self: Any, ds: Any) -> Any:
        ...
    def eval(self: Any, u: Any, v: Any) -> Any:
        ...
