from typing import Any

def validate_frame_size(size: Any) -> Any:
    ...

def ColorCube(size: Any, colors: Any, opacity: Any = ...) -> Any:
    ...

def LineSegment(start: Any, end: Any, thickness: Any = ..., radius: Any = ...) -> Any:
    ...

def arrow3d(start: Any, end: Any, width: Any = ..., radius: Any = ..., head_radius: Any = ..., head_len: Any = ...) -> Any:
    ...

class Box(IndexFaceSet):
    def __init__(self: Any) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...

class Cone(ParametricSurface):
    def __init__(self: Any, radius: Any, height: Any, closed: Any = ...) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...
    def get_grid(self: Any, ds: Any) -> Any:
        ...

class Cylinder(ParametricSurface):
    def __init__(self: Any, radius: Any, height: Any, closed: Any = ...) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def get_endpoints(self: Any, transform: Any = ...) -> Any:
        ...
    def get_radius(self: Any, transform: Any = ...) -> Any:
        ...
    def get_grid(self: Any, ds: Any) -> Any:
        ...

class Sphere(ParametricSurface):
    def __init__(self: Any, radius: Any) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def get_grid(self: Any, ds: Any) -> Any:
        ...

class Torus(ParametricSurface):
    def __init__(self: Any, R: Any = ..., r: Any = ...) -> Any:
        ...
    def get_grid(self: Any, ds: Any) -> Any:
        ...

class Text(PrimitiveObject):
    def __init__(self: Any, string: Any) -> Any:
        ...
    def x3d_geometry(self: Any) -> Any:
        ...
    def obj_repr(self: Any, render_params: Any) -> Any:
        ...
    def tachyon_repr(self: Any, render_params: Any) -> Any:
        ...
    def jmol_repr(self: Any, render_params: Any) -> Any:
        ...
    def threejs_repr(self: Any, render_params: Any) -> Any:
        ...
    def bounding_box(self: Any) -> Any:
        ...
