from typing import Any

def rotate_arbitrary(v: Any, theta: Any) -> Any:
    ...

class Transformation:
    def get_matrix(self: Any) -> Any:
        ...
    def is_skew(self: Any, eps: Any = ...) -> Any:
        ...
    def is_uniform(self: Any, eps: Any = ...) -> Any:
        ...
    def is_uniform_on(self: Any, basis: Any, eps: Any = ...) -> Any:
        ...
    def transform_point(self: Any, x: Any) -> Any:
        ...
    def transform_vector(self: Any, v: Any) -> Any:
        ...
    def transform_bounding_box(self: Any, box: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __call__(self: Any, p: Any) -> Any:
        ...
    def max_scale(self: Any) -> Any:
        ...
    def avg_scale(self: Any) -> Any:
        ...
