from typing import Any

class LinearCodeAutGroupCanLabel:
    def __init__(self: Any, C: Any, P: Any = ..., algorithm_type: Any = ...) -> Any:
        ...
    def get_canonical_form(self: Any) -> Any:
        ...
    def get_transporter(self: Any) -> Any:
        ...
    def get_autom_gens(self: Any) -> Any:
        ...
    def get_autom_order(self: Any) -> Any:
        ...
    def get_PGammaL_gens(self: Any) -> Any:
        ...
    def get_PGammaL_order(self: Any) -> Any:
        ...
