from typing import Any

class InnerGroup:
    def __cinit__(self: Any, k: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def column_blocks(self: Any, mat: Any) -> Any:
        ...

class PartitionRefinementLinearCode(PartitionRefinement_generic):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, n: Any, generator_matrix: Any, P: Any = ..., algorithm_type: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def get_canonical_form(self: Any) -> Any:
        ...
    def get_transporter(self: Any) -> Any:
        ...
    def get_autom_gens(self: Any) -> Any:
        ...
    def get_autom_order_inner_stabilizer(self: Any) -> Any:
        ...
