from typing import Any

def unpickle_gaussian_hmm_v0(A: Any, B: Any, pi: Any, name: Any) -> Any:
    ...

def unpickle_gaussian_hmm_v1(A: Any, B: Any, pi: Any, prob: Any, n_out: Any) -> Any:
    ...

def unpickle_gaussian_mixture_hmm_v1(A: Any, B: Any, pi: Any, mixture: Any) -> Any:
    ...

class GaussianHiddenMarkovModel(HiddenMarkovModel):
    def __init__(self: Any, A: Any, B: Any, pi: Any, normalize: Any = ...) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def emission_parameters(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def generate_sequence(self: Any, length: Any, starting_state: Any = ...) -> Any:
        ...
    def log_likelihood(self: Any, obs: Any) -> Any:
        ...
    def viterbi(self: Any, obs: Any) -> Any:
        ...

class GaussianMixtureHiddenMarkovModel(GaussianHiddenMarkovModel):
    def __init__(self: Any, A: Any, B: Any, pi: Any = ..., normalize: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def emission_parameters(self: Any) -> Any:
        ...
