from typing import Any

class Distribution:
    def sample(self: Any, n: Any = ...) -> Any:
        ...
    def prob(self: Any, x: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...

class GaussianMixtureDistribution(Distribution):
    def __init__(self: Any, B: Any, eps: Any = ..., normalize: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def is_fixed(self: Any, i: Any = ...) -> Any:
        ...
    def fix(self: Any, i: Any = ...) -> Any:
        ...
    def unfix(self: Any, i: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def sample(self: Any, n: Any = ...) -> Any:
        ...
