from typing import Any

def unpickle_discrete_hmm_v0(A: Any, B: Any, pi: Any, emission_symbols: Any, name: Any) -> Any:
    ...

def unpickle_discrete_hmm_v1(A: Any, B: Any, pi: Any, n_out: Any, emission_symbols: Any, emission_symbols_dict: Any) -> Any:
    ...

class HiddenMarkovModel:
    def initial_probabilities(self: Any) -> Any:
        ...
    def transition_matrix(self: Any) -> Any:
        ...
    def graph(self: Any, eps: Any = ...) -> Any:
        ...
    def sample(self: Any, length: Any, number: Any = ..., starting_state: Any = ...) -> Any:
        ...

class DiscreteHiddenMarkovModel(HiddenMarkovModel):
    def __init__(self: Any, A: Any, B: Any, pi: Any, emission_symbols: Any = ..., normalize: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def emission_matrix(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def log_likelihood(self: Any, obs: Any, scale: Any = ...) -> Any:
        ...
    def generate_sequence(self: Any, length: Any, starting_state: Any = ...) -> Any:
        ...
    def viterbi(self: Any, obs: Any, log_scale: Any = ...) -> Any:
        ...
    def baum_welch(self: Any, obs: Any, max_iter: Any = ..., log_likelihood_cutoff: Any = ..., fix_emissions: Any = ...) -> Any:
        ...
