from typing import Any

def unpickle_intlist_v1(v: Any, n: Any) -> Any:
    ...

class IntList:
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, values: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, x: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def min(self: Any, index: Any = ...) -> Any:
        ...
    def max(self: Any, index: Any = ...) -> Any:
        ...
    def time_series(self: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...
    def plot_histogram(self: Any) -> Any:
        ...
