from typing import Any

def unpickle_time_series_v1(v: Any, n: Any) -> Any:
    ...

def autoregressive_fit(acvs: Any) -> Any:
    ...

class TimeSeries:
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, values: Any, initialize: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def vector(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, x: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def autoregressive_fit(self: Any, M: Any) -> Any:
        ...
    def autoregressive_forecast(self: Any, filter: Any) -> Any:
        ...
    def reversed(self: Any) -> Any:
        ...
    def extend(self: Any, right: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def log(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def abs(self: Any) -> Any:
        ...
    def diffs(self: Any, k: Any = ...) -> Any:
        ...
    def scale_time(self: Any, k: Any) -> Any:
        ...
    def rescale(self: Any, s: Any) -> Any:
        ...
    def scale(self: Any, s: Any) -> Any:
        ...
    def add_scalar(self: Any, s: Any) -> Any:
        ...
    def add_entries(self: Any, t: Any) -> Any:
        ...
    def show(self: Any) -> Any:
        ...
    def plot(self: Any, plot_points: Any = ..., points: Any = ...) -> Any:
        ...
    def simple_moving_average(self: Any, k: Any) -> Any:
        ...
    def exponential_moving_average(self: Any, alpha: Any) -> Any:
        ...
    def sums(self: Any, s: Any = ...) -> Any:
        ...
    def prod(self: Any) -> Any:
        ...
    def mean(self: Any) -> Any:
        ...
    def pow(self: Any, k: Any) -> Any:
        ...
    def moment(self: Any, k: Any) -> Any:
        ...
    def central_moment(self: Any, k: Any) -> Any:
        ...
    def covariance(self: Any, other: Any) -> Any:
        ...
    def autocovariance(self: Any, k: Any = ...) -> Any:
        ...
    def correlation(self: Any, other: Any) -> Any:
        ...
    def autocorrelation(self: Any, k: Any = ...) -> Any:
        ...
    def variance(self: Any, bias: Any = ...) -> Any:
        ...
    def standard_deviation(self: Any, bias: Any = ...) -> Any:
        ...
    def range_statistic(self: Any, b: Any = ...) -> Any:
        ...
    def hurst_exponent(self: Any) -> Any:
        ...
    def min(self: Any, index: Any = ...) -> Any:
        ...
    def max(self: Any, index: Any = ...) -> Any:
        ...
    def clip_remove(self: Any, min: Any = ..., max: Any = ...) -> Any:
        ...
    def histogram(self: Any, bins: Any = ..., normalize: Any = ...) -> Any:
        ...
    def plot_histogram(self: Any, bins: Any = ..., normalize: Any = ...) -> Any:
        ...
    def plot_candlestick(self: Any, bins: Any = ...) -> Any:
        ...
    def numpy(self: Any, copy: Any = ...) -> Any:
        ...
    def randomize(self: Any, distribution: Any = ..., loc: Any = ..., scale: Any = ...) -> Any:
        ...
    def fft(self: Any, overwrite: Any = ...) -> Any:
        ...
    def ifft(self: Any, overwrite: Any = ...) -> Any:
        ...
