from typing import Any

def legendre_phi(x: Any, a: Any) -> Integer:
    ...

class PrimePi(BuiltinFunction):
    def __init__(self: Any) -> Any:
        ...
    def __call__(self: Any, coerce: Any = ..., hold: Any = ...) -> Any:
        ...
    def plot(self: Any, xmin: Any = ..., xmax: Any = ..., vertical_lines: Any = ...) -> Any:
        ...
