from typing import Any

def debruijn_sequence(k: Any, n: Any) -> Any:
    ...

def is_debruijn_sequence(seq: Any, k: Any, n: Any) -> Any:
    ...

class DeBruijnSequences(UniqueRepresentation, Parent):
    def __init__(self: Any, k: Any, n: Any) -> Any:
        ...
    def __contains__(self: Any, seq: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
