from typing import Any

class DegreeSequences:
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __contains__(self: Any, seq: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __dealloc__() -> Any:
        ...
