from typing import Any

def ZS1_iterator(n: Any) -> Any:
    ...

def ZS1_next(P: Any) -> Any:
    ...

def ZS1_iterator_nk(n: Any, k: Any) -> Any:
    ...

def ZS2_iterator(n: Any) -> Any:
    ...

def ZS2_next(P: Any) -> Any:
    ...

def AccelDesc_iterator(n: Any) -> Any:
    ...

def AccelDesc_next(P: Any) -> Any:
    ...

def AccelAsc_iterator(n: Any) -> Any:
    ...

def AccelAsc_next(P: Any) -> Any:
    ...
