from typing import Any, Iterator, List

def ZS1_iterator(n: int) -> Iterator[List[int]]:
    ...

def ZS1_next(P: List[int]) -> List[int]:
    ...

def ZS1_iterator_nk(n: int, k: int) -> Iterator[List[int]]:
    ...

def ZS2_iterator(n: int) -> Iterator[List[int]]:
    ...

def ZS2_next(P: List[int]) -> List[int]:
    ...

def AccelDesc_iterator(n: int) -> Iterator[List[int]]:
    ...

def AccelDesc_next(P: List[int]) -> List[int]:
    ...

def AccelAsc_iterator(n: int) -> Iterator[List[int]]:
    ...

def AccelAsc_next(P: List[int]) -> List[int]:
    ...
