from typing import Any

class CombinatorialPolyhedron(SageObject):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, data: Any, Vrep: Any = ..., facets: Any = ..., unbounded: Any = ..., far_face: Any = ...) -> Any:
        ...
    def f(v: Any) -> Any:
        ...
    def f(v: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def Vrepresentation(self: Any) -> Any:
        ...
    def Hrepresentation(self: Any) -> Any:
        ...
    def dimension(self: Any) -> Any:
        ...
    def n_vertices(self: Any) -> Any:
        ...
    def vertices(self: Any, names: Any = ...) -> Any:
        ...
    def n_facets(self: Any) -> Any:
        ...
    def facets(self: Any, names: Any = ...) -> Any:
        ...
    def incidence_matrix(self: Any) -> Any:
        ...
    def edges(self: Any, names: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def f(i: Any) -> Any:
        ...
    def f(i: Any) -> Any:
        ...
    def vertex_graph(self: Any, names: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def vertex_adjacency_matrix(self: Any, algorithm: Any = ...) -> Any:
        ...
    def ridges(self: Any, add_equations: Any = ..., names: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def f(i: Any) -> Any:
        ...
    def f(i: Any) -> Any:
        ...
    def facet_adjacency_matrix(self: Any, algorithm: Any = ...) -> Any:
        ...
    def facet_graph(self: Any, names: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def vertex_facet_graph(self: Any, names: Any = ...) -> Any:
        ...
    def f_vector(self: Any, num_threads: Any = ..., parallelization_depth: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def flag_f_vector(self: Any) -> Any:
        ...
    def neighborliness(self: Any) -> Any:
        ...
    def simpliciality(self: Any) -> Any:
        ...
    def is_simple(self: Any) -> Any:
        ...
    def simplicity(self: Any) -> Any:
        ...
    def is_lawrence_polytope(self: Any) -> Any:
        ...
    def is_pyramid(self: Any, certificate: Any = ...) -> Any:
        ...
    def is_bipyramid(self: Any, certificate: Any = ...) -> Any:
        ...
    def is_prism(self: Any, certificate: Any = ...) -> Any:
        ...
    def join_of_Vrep(self: Any) -> Any:
        ...
    def meet_of_Hrep(self: Any) -> Any:
        ...
    def face_generator(self: Any, dimension: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def face_lattice(self: Any) -> Any:
        ...
    def hasse_diagram(self: Any) -> Any:
        ...
    def face_by_face_lattice_index(self: Any, index: Any) -> Any:
        ...
    def a_maximal_chain(self: Any, Vindex: Any = ..., Hindex: Any = ...) -> Any:
        ...
    def test_a_chain(b: Any) -> Any:
        ...
    def is_compact(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def dual(self: Any) -> Any:
        ...
    def pyramid(self: Any, new_vertex: Any = ..., new_facet: Any = ...) -> Any:
        ...
    def choose_algorithm_to_compute_edges_or_ridges(self: Any, edges_or_ridges: Any) -> Any:
        ...
