from typing import Any

class CombinatorialFace(SageObject):
    def __cinit__(self: Any, data: Any, dimension: Any = ..., index: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __lt__(self: Any, other: Any) -> Any:
        ...
    def is_subface(self: Any, other: Any) -> Any:
        ...
    def dimension(self: Any) -> Any:
        ...
    def ambient_dimension(self: Any) -> Any:
        ...
    def ambient_Vrepresentation(self: Any) -> Any:
        ...
    def ambient_V_indices(self: Any) -> Any:
        ...
    def n_ambient_Vrepresentation(self: Any) -> Any:
        ...
    def ambient_Hrepresentation(self: Any) -> Any:
        ...
    def ambient_H_indices(self: Any, add_equations: Any = ...) -> Any:
        ...
    def n_ambient_Hrepresentation(self: Any, add_equations: Any = ...) -> Any:
        ...
    def as_combinatorial_polyhedron(self: Any, quotient: Any = ...) -> Any:
        ...
