from typing import Any

class FaceIterator_base(SageObject):
    def __cinit__(self: Any, P: Any, dual: Any = ..., output_dimension: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def reset(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def current(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def ignore_subfaces(self: Any) -> Any:
        ...
    def ignore_supfaces(self: Any) -> Any:
        ...
    def meet_of_Hrep(self: Any) -> Any:
        ...
    def join_of_Vrep(self: Any) -> Any:
        ...
    def only_subfaces(self: Any) -> Any:
        ...
    def only_supfaces(self: Any) -> Any:
        ...

class FaceIterator(FaceIterator_base):
    def face_iterator(faces: Any, visited_all: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class FaceIterator_geom(FaceIterator_base):
    def __init__(self: Any, P: Any, dual: Any = ..., output_dimension: Any = ...) -> Any:
        ...
    def reset(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def current(self: Any) -> Any:
        ...
