from typing import Any

class ListOfFaces:
    def __cinit__(self: Any, n_faces: Any, n_atoms: Any, n_coatoms: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def compute_dimension(self: Any) -> int:
        ...
    def pyramid(self: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
