from typing import Any

class PolyhedronFaceLattice:
    def __cinit__(self: Any, C: Any) -> Any:
        ...
    def __init__(self: Any, C: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def get_face(self: Any, dimension: Any, index: Any) -> Any:
        ...
