from typing import Any

def pari_to_cdf(g: Any) -> Any:
    ...

def new_gen_from_complex_double_element(self: Any) -> Any:
    ...

def complex_double_element_eta(self: Any, flag: Any) -> Any:
    ...

def complex_double_element_agm(self: Any, right: Any) -> Any:
    ...

def complex_double_element_dilog(self: Any) -> Any:
    ...

def complex_double_element_gamma(self: Any) -> Any:
    ...

def complex_double_element_gamma_inc(self: Any, t: Any) -> Any:
    ...

def complex_double_element_zeta(self: Any) -> Any:
    ...
