from typing import Any

def gen_to_sage(z: Any, locals: Any = ...) -> Any:
    ...

def set_integer_from_gen(self: Any, x: Any) -> Any:
    ...

def new_gen_from_integer(self: Any) -> Any:
    ...

def set_rational_from_gen(self: Any, x: Any) -> Any:
    ...

def new_gen_from_rational(self: Any) -> Any:
    ...

def pari_divisors_small(self: Any) -> List[Any]:
    ...

def pari_is_prime(p: Any) -> Any:
    ...

def pari_is_prime_power(q: Any, get_data: Any) -> Any:
    ...

def pari_prime_range(c_start: Any, c_stop: Any, py_ints: Any = ...) -> List[Any]:
    ...
