from typing import Any

def path_algebra_element_unpickle(P: Any, data: Any) -> Any:
    ...

class PathAlgebraElement(RingElement):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, S: Any, data: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any) -> Dict[Any, Any]:
        ...
    def coefficients(self: Any) -> List[Any]:
        ...
    def monomials(self: Any) -> List[Any]:
        ...
    def terms(self: Any) -> List[Any]:
        ...
    def support(self: Any) -> List[Any]:
        ...
    def support_of_term(self: Any) -> Any:
        ...
    def coefficient(self: Any, P: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, k: Any) -> Any:
        ...
    def sort_by_vertices(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __truediv__(self: Any, x: Any) -> Any:
        ...
