from typing import Any

def NewQuiverPath(Q: Any, start: Any, end: Any, biseq_data: Any) -> Any:
    ...

class QuiverPath(MonoidElement):
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, start: Any, end: Any, path: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, index: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def gcd(self: Any, P: Any) -> Any:
        ...
    def complement(self: Any, subpath: Any) -> Tuple[Any, ...]:
        ...
    def has_subpath(self: Any, subpath: Any) -> bool:
        ...
    def has_prefix(self: Any, subpath: Any) -> bool:
        ...
    def initial_vertex(self: Any) -> Any:
        ...
    def terminal_vertex(self: Any) -> Any:
        ...
    def reversal(self: Any) -> Any:
        ...
