from typing import Any

def WaveletTransform(n: Any, wavelet_type: Any, wavelet_k: Any) -> Any:
    ...

def is2pow(n: Any) -> Any:
    ...

class DiscreteWaveletTransform(GSLDoubleArray):
    def __cinit__(self: Any, n: Any, stride: Any, wavelet_type: Any, wavelet_k: Any) -> Any:
        ...
    def __init__(self: Any, n: Any, stride: Any, wavelet_type: Any, wavelet_k: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def forward_transform(self: Any) -> Any:
        ...
    def backward_transform(self: Any) -> Any:
        ...
    def plot(self: Any, xmin: Any = ..., xmax: Any = ...) -> Any:
        ...
