from typing import Any

def FastFourierTransform(size: Any, base_ring: Any = ...) -> Any:
    ...

class FastFourierTransform_base:
    ...

class FastFourierTransform_complex(FastFourierTransform_base):
    def __init__(self: Any, n: Any, stride: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, xy: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def plot(self: Any, style: Any = ..., xmin: Any = ..., xmax: Any = ...) -> Any:
        ...
    def forward_transform(self: Any) -> Any:
        ...
    def inverse_transform(self: Any) -> Any:
        ...
    def backward_transform(self: Any) -> Any:
        ...

class FourierTransform_complex:
    ...

class FourierTransform_real:
    ...
