from typing import Any

def bell_number(n: Any) -> Any:
    ...

def bernoulli_number(n: Any) -> Any:
    ...

def euler_number(n: Any) -> Any:
    ...

def stirling_number_1(n: Any, k: Any) -> Any:
    ...

def stirling_number_2(n: Any, k: Any) -> Any:
    ...

def number_of_partitions(n: Any) -> Any:
    ...

def dedekind_sum(p: Any, q: Any) -> Any:
    ...

def harmonic_number(n: Any) -> Any:
    ...
