from typing import Any

class Fmpz_poly(SageObject):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, v: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, value: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, dummy: Any) -> Any:
        ...
    def pow_truncate(self: Any, exp: Any, n: Any) -> Any:
        ...
    def __floordiv__(left: Any, right: Any) -> Any:
        ...
    def div_rem(self: Any, other: Any) -> Any:
        ...
    def left_shift(self: Any, n: Any) -> Any:
        ...
    def right_shift(self: Any, n: Any) -> Any:
        ...
    def pseudo_div(self: Any, other: Any) -> Any:
        ...
    def pseudo_div_rem(self: Any, other: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
