from typing import Any

class IdealMonoid_nc(IdealMonoid_c):
    def __init__(self: Any, R: Any) -> Any:
        ...

class Ideal_nc(Ideal_generic):
    def __init__(self: Any, ring: Any, gens: Any, coerce: Any = ..., side: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __eq__(self: Any, right: Any) -> Any:
        ...
    def __ne__(self: Any, right: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def side(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
