from typing import Any, List, Optional, Union, Iterator, Dict, Tuple
from sage.structure.element import AlgebraElement

# Type aliases for better specificity
SageInteger = Union['sage.rings.integer.Integer', int]
SageNumber = Union['sage.rings.rational.Rational', SageInteger, 'sage.structure.element.RingElement']
PowerSeriesRing = Any  # Will be refined when power_series_ring.pyi is created
Variable = Any
Polynomial = Any

def is_PowerSeries(x: Any) -> bool:
    ...

class PowerSeries(AlgebraElement):
    """Base class for power series over any ring."""
    
    def __init__(self, parent: Any, prec: int = ..., check: bool = True) -> None:
        ...
    
    def _repr_(self, name: Optional[str] = None) -> str:
        ...
    
    def _latex_(self, name: Optional[str] = None) -> str:
        ...
    
    def list(self) -> List[Any]:
        ...
    
    def dict(self) -> dict:
        ...
    
    def prec(self) -> int:
        ...
    
    def precision_absolute(self) -> int:
        ...
    
    def precision_relative(self) -> int:
        ...
    
    def valuation(self) -> int:
        ...
    
    def variable(self) -> Any:
        ...
    
    def variables(self) -> tuple:
        ...
    
    def degree(self) -> int:
        ...
    
    def polynomial(self) -> Any:
        ...
    
    def truncate(self, n: int) -> 'PowerSeries':
        ...
    
    def truncate_powerseries(self, prec: int) -> 'PowerSeries':
        ...
    
    def add_bigoh(self, prec: int) -> 'PowerSeries':
        ...
    
    def O(self, prec: int) -> 'PowerSeries':
        ...
    
    def padded_list(self, n: Optional[int] = None) -> List[Any]:
        ...
    
    def __getitem__(self, n: int) -> Any:
        ...
    
    def coefficients(self) -> Iterator[Any]:
        ...
    
    def exponents(self) -> Iterator[int]:
        ...
    
    def __iter__(self) -> Iterator[Any]:
        ...
    
    def __call__(self, *args: Any, **kwds: Any) -> Any:
        ...
    
    def _compute_polylog(self, n: int, algorithm: str) -> 'PowerSeries':
        ...
    
    def derivative(self, *args: Any) -> 'PowerSeries':
        ...
    
    def integral(self) -> 'PowerSeries':
        ...
    
    def solve_linear_de(self, prec: int = ..., b: Optional[Any] = None, f0: Optional[Any] = None, start_solution: Optional[Any] = None) -> 'PowerSeries':
        ...
    
    def exp(self, prec: Optional[int] = None) -> 'PowerSeries':
        ...
    
    def log(self, prec: Optional[int] = None) -> 'PowerSeries':
        ...
    
    def sqrt(self, prec: Optional[int] = None, extend: bool = True, all: bool = False) -> Any:
        ...
    
    def square_root(self) -> 'PowerSeries':
        ...
    
    def nth_root(self, n: int, prec: Optional[int] = None) -> 'PowerSeries':
        ...
    
    def reverse(self, precision: Optional[int] = None) -> 'PowerSeries':
        ...
    
    def reversion(self, precision: Optional[int] = None) -> 'PowerSeries':
        ...
    
    def pade(self, m: int, n: int) -> tuple:
        ...
    
    def ogf_to_egf(self) -> 'PowerSeries':
        ...
    
    def egf_to_ogf(self) -> 'PowerSeries':
        ...
    
    def _add_(self, right: 'PowerSeries') -> 'PowerSeries':
        ...
    
    def _sub_(self, right: 'PowerSeries') -> 'PowerSeries':
        ...
    
    def _mul_(self, right: 'PowerSeries') -> 'PowerSeries':
        ...
    
    def _rmul_(self, left: Any) -> 'PowerSeries':
        ...
    
    def _lmul_(self, right: Any) -> 'PowerSeries':
        ...
    
    def _div_(self, right: 'PowerSeries') -> 'PowerSeries':
        ...
    
    def __pow__(self, right: Any, modulus: Optional[Any] = None) -> 'PowerSeries':
        ...
    
    def __neg__(self) -> 'PowerSeries':
        ...
    
    def __pos__(self) -> 'PowerSeries':
        ...
    
    def shift(self, n: int) -> 'PowerSeries':
        ...
    
    def __lshift__(self, n: int) -> 'PowerSeries':
        ...
    
    def __rshift__(self, n: int) -> 'PowerSeries':
        ...
    
    def is_zero(self) -> bool:
        ...
    
    def is_unit(self) -> bool:
        ...
    
    def is_nilpotent(self) -> bool:
        ...
    
    def is_square(self) -> bool:
        ...
    
    def common_prec(self, f: 'PowerSeries') -> int:
        ...
    
    def prec_degree(self) -> int:
        ...

def _solve_linear_de(R: Any, N: int, L: List[Any], a: Any, b: Any, f0: Any) -> Any:
    ...

def make_powerseries_poly_v0(parent: Any, f: Any, prec: int, is_gen: bool) -> PowerSeries:
    ...

def make_element_from_parent_v0(parent: Any, *args: Any) -> PowerSeries:
    ...