from typing import Any

def make_powerseries_poly_v0(parent: Any, f: Any, prec: Any, is_gen: Any) -> Any:
    ...

class PowerSeries_poly(PowerSeries):
    def __init__(self: Any, parent: Any, f: Any = ..., prec: Any = ..., check: Any = ..., is_gen: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def truncate(self: Any, prec: Any = ...) -> Any:
        ...
    def truncate_powerseries(self: Any, prec: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Any:
        ...
    def integral(self: Any, var: Any = ...) -> Any:
        ...
    def reverse(self: Any, precision: Any = ...) -> Any:
        ...
    def pade(self: Any, m: Any, n: Any) -> Any:
        ...

class BaseRingFloorDivAction(Action):
    ...
