from typing import Any

class PowerSeries_pari(PowerSeries):
    def __init__(self: Any, parent: Any, f: Any = ..., prec: Any = ..., check: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, m: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def padded_list(self: Any, n: Any = ...) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Any:
        ...
    def integral(self: Any, var: Any = ...) -> Any:
        ...
    def reverse(self: Any, precision: Any = ...) -> Any:
        ...
