from typing import Any

def make_powerseries_mpoly_v0(parent: Any, f: Any, prec: Any, is_gen: Any) -> Any:
    ...

class PowerSeries_mpoly(PowerSeries):
    def __init__(self: Any, parent: Any, f: Any = ..., prec: Any = ..., check: Any = ..., is_gen: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def do_truncation(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
