from typing import Any

def is_PowerSeries(x: Any) -> Any:
    ...

def make_powerseries_poly_v0(parent: Any, f: Any, prec: Any, is_gen: Any) -> Any:
    ...

def make_element_from_parent_v0(parent: Any) -> Any:
    ...

class PowerSeries(AlgebraElement):
    def __init__(self: Any, parent: Any, prec: Any, is_gen: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def is_sparse(self: Any) -> Any:
        ...
    def is_dense(self: Any) -> Any:
        ...
    def is_gen(self: Any) -> Any:
        ...
    def base_extend(self: Any, R: Any) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...
    def lift_to_precision(self: Any, absprec: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def padded_list(self: Any, n: Any = ...) -> Any:
        ...
    def prec(self: Any) -> Any:
        ...
    def precision_absolute(self: Any) -> Any:
        ...
    def precision_relative(self: Any) -> Any:
        ...
    def truncate(self: Any, prec: Any = ...) -> Any:
        ...
    def add_bigoh(self: Any, prec: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def common_prec(self: Any, f: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
    def valuation_zero_part(self: Any) -> Any:
        ...
    def __mod__(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, r: Any, dummy: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def map_coefficients(self: Any, f: Any, new_base_ring: Any = ...) -> Any:
        ...
    def jacobi_continued_fraction(self: Any) -> Any:
        ...
    def super_delta_fraction(self: Any, delta: Any) -> Any:
        ...
    def stieltjes_continued_fraction(self: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def sqrt(self: Any, prec: Any = ..., extend: Any = ..., all: Any = ..., name: Any = ...) -> Any:
        ...
    def square_root(self: Any) -> Any:
        ...
    def nth_root(self: Any, n: Any, prec: Any = ...) -> Any:
        ...
    def cos(self: Any, prec: Any = ...) -> Any:
        ...
    def sin(self: Any, prec: Any = ...) -> Any:
        ...
    def tan(self: Any, prec: Any = ...) -> Any:
        ...
    def sinh(self: Any, prec: Any = ...) -> Any:
        ...
    def cosh(self: Any, prec: Any = ...) -> Any:
        ...
    def tanh(self: Any, prec: Any = ...) -> Any:
        ...
    def O(self: Any, prec: Any) -> Any:
        ...
    def solve_linear_de(self: Any, prec: Any = ..., b: Any = ..., f0: Any = ...) -> Any:
        ...
    def exp(self: Any, prec: Any = ...) -> Any:
        ...
    def log(self: Any, prec: Any = ...) -> Any:
        ...
    def V(self: Any, n: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def variable(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def __setitem__(self: Any, n: Any, value: Any) -> Any:
        ...
    def laurent_series(self: Any) -> Any:
        ...
    def egf_to_ogf(self: Any) -> Any:
        ...
    def ogf_to_egf(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
