from typing import Any

class PuiseuxSeries(AlgebraElement):
    def __init__(self: Any, parent: Any, f: Any, e: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def __pow__(_self: Any, r: Any, dummy: Any) -> Any:
        ...
    def __lshift__(self: Any, r: Any) -> Any:
        ...
    def __rshift__(self: Any, r: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, r: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def laurent_part(self: Any) -> Any:
        ...
    def ramification_index(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def add_bigoh(self: Any, prec: Any) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def __setitem__(self: Any, n: Any, value: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def shift(self: Any, r: Any) -> Any:
        ...
    def truncate(self: Any, r: Any) -> Any:
        ...
    def prec(self: Any) -> Any:
        ...
    def precision_relative(self: Any) -> Any:
        ...
    def common_prec(self: Any, p: Any) -> Any:
        ...
    def variable(self: Any) -> Any:
        ...
    def laurent_series(self: Any) -> Any:
        ...
    def power_series(self: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
