from typing import Any, List, Optional, Tuple, Union
from sage.structure.element import FieldElement

def is_Rational(x: Any) -> bool:
    ...

class Rational(FieldElement):
    def __cinit__(self) -> None:
        ...
    
    def __init__(self, x: Any = None, base: int = 0) -> None:
        ...
    
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    
    def __index__(self) -> int:
        ...
    
    def list(self) -> List[int]:
        ...
    
    def continued_fraction_list(self, type: str = 'std') -> List[int]:
        ...
    
    def continued_fraction(self) -> Any:
        ...
    
    def __copy__(self) -> 'Rational':
        ...
    
    def __deepcopy__(self, memo: Any) -> 'Rational':
        ...
    
    def __dealloc__(self) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def _latex_(self) -> str:
        ...
    
    def _symbolic_(self, sring: Any) -> Any:
        ...
    
    def _sympy_(self) -> Any:
        ...
    
    def __mpz__(self) -> Any:
        ...
    
    def __mpq__(self) -> Any:
        ...
    
    def _magma_init_(self, magma: Any) -> str:
        ...
    
    def _regina_(self, regina: Any) -> Any:
        ...
    
    def __array_interface__(self) -> dict:
        ...
    
    def _mathml_(self) -> str:
        ...
    
    def _im_gens_(self, codomain: Any, im_gens: Any, base_map: Optional[Any] = None) -> Any:
        ...
    
    def content(self, other: Any) -> 'Rational':
        ...
    
    def valuation(self, p: Any) -> Any:
        ...
    
    def local_height(self, p: Any, prec: Optional[int] = None) -> Any:
        ...
    
    def local_height_arch(self, prec: Optional[int] = None) -> Any:
        ...
    
    def global_height_non_arch(self, prec: Optional[int] = None) -> Any:
        ...
    
    def global_height_arch(self, prec: Optional[int] = None) -> Any:
        ...
    
    def global_height(self, prec: Optional[int] = None) -> Any:
        ...
    
    def is_square(self) -> bool:
        ...
    
    def is_norm(self, L: Any, element: bool = False, proof: bool = True) -> Union[bool, Tuple[bool, Any]]:
        ...
    
    def _bnfisnorm(self, L: Any, proof: bool = True) -> Tuple[bool, Any]:
        ...
    
    def is_perfect_power(self, expected_n: Optional[int] = None) -> Union[bool, Tuple['Rational', int]]:
        ...
    
    def squarefree_part(self) -> 'Rational':
        ...
    
    def is_padic_square(self, p: Any, check_validity: bool = True) -> bool:
        ...
    
    def val_unit(self, p: Any) -> Tuple[int, 'Rational']:
        ...
    
    def prime_to_S_part(self, S: Any) -> 'Rational':
        ...
    
    def sqrt(self, prec: Optional[int] = None, extend: bool = True, all: bool = False) -> Any:
        ...
    
    def period(self) -> List[int]:
        ...
    
    def nth_root(self, n: int, truncate_mode: int = 0) -> Union['Rational', Any]:
        ...
    
    def is_nth_power(self, n: int) -> bool:
        ...
    
    def str(self, base: int = 10) -> str:
        ...
    
    def __float__(self) -> float:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __getitem__(self, n: int) -> int:
        ...
    
    def __add__(self, other: Any) -> Any:
        ...
    
    def __sub__(self, other: Any) -> Any:
        ...
    
    def __mul__(self, other: Any) -> Any:
        ...
    
    def __truediv__(self, other: Any) -> Any:
        ...
    
    def __invert__(self) -> 'Rational':
        ...
    
    def __pos__(self) -> 'Rational':
        ...
    
    def __neg__(self) -> 'Rational':
        ...
    
    def __abs__(self) -> 'Rational':
        ...
    
    def __int__(self) -> int:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __pow__(self, n: Any, modulus: Optional[Any] = None) -> Any:
        ...
    
    def _pari_(self) -> Any:
        ...
    
    def _interface_init_(self, I: Optional[Any] = None) -> str:
        ...
    
    def additive_order(self) -> Any:
        ...
    
    def multiplicative_order(self) -> Any:
        ...
    
    def sign(self) -> int:
        ...
    
    def ceil(self) -> Any:
        ...
    
    def floor(self) -> Any:
        ...
    
    def trunc(self) -> Any:
        ...
    
    def round(self, mode: str = "away") -> Any:
        ...
    
    def frac(self) -> 'Rational':
        ...
    
    def numerator(self) -> Any:
        ...
    
    def denominator(self) -> Any:
        ...
    
    def factor(self) -> Any:
        ...
    
    def support(self) -> List[Any]:
        ...
    
    def lcm(self, other: Any) -> 'Rational':
        ...
    
    def gcd(self, other: Any) -> 'Rational':
        ...
    
    def rational_reconstruction(self, m: Any) -> 'Rational':
        ...
    
    def mod(self, other: Any) -> 'Rational':
        ...
    
    def _lcm(self, other: Any) -> 'Rational':
        ...
    
    def _gcd(self, other: Any) -> 'Rational':
        ...
    
    def real(self) -> 'Rational':
        ...
    
    def imag(self) -> 'Rational':
        ...
    
    def conjugate(self) -> 'Rational':
        ...

# Additional module-level functions
def rational_power_parts(a: 'Rational', b: 'Rational', factor_limit: int = 100000) -> Tuple[Any, bool]:
    ...