from typing import Any

def integer_rational_power(a: Any, b: Any) -> Integer:
    ...

def rational_power_parts(a: Any, b: Any, factor_limit: Any = ...) -> Any:
    ...

def is_Rational(x: Any) -> Any:
    ...

def make_rational(s: Any) -> Any:
    ...

class Rational(sage.structure.element.FieldElement):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, x: Any = ..., base: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def continued_fraction_list(self: Any, type: Any = ...) -> Any:
        ...
    def continued_fraction(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __mpz__(self: Any) -> Any:
        ...
    def __mpq__(self: Any) -> Any:
        ...
    def __array_interface__(self: Any) -> Any:
        ...
    def content(self: Any, other: Any) -> Any:
        ...
    def valuation(self: Any, p: Any) -> Any:
        ...
    def local_height(self: Any, p: Any, prec: Any = ...) -> Any:
        ...
    def local_height_arch(self: Any, prec: Any = ...) -> Any:
        ...
    def global_height_non_arch(self: Any, prec: Any = ...) -> Any:
        ...
    def global_height_arch(self: Any, prec: Any = ...) -> Any:
        ...
    def global_height(self: Any, prec: Any = ...) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def is_norm(self: Any, L: Any, element: Any = ..., proof: Any = ...) -> Any:
        ...
    def is_perfect_power(self: Any, expected_value: Any = ...) -> Any:
        ...
    def squarefree_part(self: Any) -> Any:
        ...
    def is_padic_square(self: Any, p: Any, check: Any = ...) -> Any:
        ...
    def val_unit(self: Any, p: Any) -> Any:
        ...
    def prime_to_S_part(self: Any, S: Any = ...) -> Any:
        ...
    def sqrt(self: Any, prec: Any = ..., extend: Any = ..., all: Any = ...) -> Any:
        ...
    def period(self: Any) -> Any:
        ...
    def nth_root(self: Any, n: Any) -> Any:
        ...
    def is_nth_power(self: Any, n: Any) -> Any:
        ...
    def str(self: Any, base: Any = ...) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def sign(self: Any) -> Any:
        ...
    def mod_ui(self: Any, n: Any) -> Any:
        ...
    def __mod__(x: Any, y: Any) -> Any:
        ...
    def norm(self: Any) -> Any:
        ...
    def relative_norm(self: Any) -> Any:
        ...
    def absolute_norm(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def as_integer_ratio(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def support(self: Any) -> Any:
        ...
    def log(self: Any, m: Any = ..., prec: Any = ...) -> Any:
        ...
    def gamma(self: Any, prec: Any = ...) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def trunc(self: Any) -> Any:
        ...
    def round(self: Any, mode: Any = ...) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def height(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_integral(self: Any) -> Any:
        ...
    def is_rational(self: Any) -> Any:
        ...
    def is_S_integral(self: Any, S: Any = ...) -> Any:
        ...
    def is_S_unit(self: Any, S: Any = ...) -> Any:
        ...
    def __lshift__(x: Any, y: Any) -> Any:
        ...
    def __rshift__(x: Any, y: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...

class Z_to_Q(Morphism):
    def __init__(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...

class Q_to_Z(Map):
    def section(self: Any) -> Any:
        ...

class int_to_Q(Morphism):
    def __init__(self: Any) -> Any:
        ...
