from typing import Any, Optional, Tuple, List, Union
from sage.rings.integer import Integer
from sage.structure.element import FieldElement
from sage.categories.morphism import Morphism
from sage.categories.map import Map

def integer_rational_power(a: Any, b: Any) -> Integer:
    ...

def rational_power_parts(a: Any, b: Any, factor_limit: int = 1000000) -> Any:
    ...

def is_Rational(x: Any) -> bool:
    ...

def make_rational(s: str) -> 'Rational':
    ...

class Rational(FieldElement):
    def __cinit__(self) -> None:
        ...
    def __init__(self, x: Any = 0, base: int = 10) -> None:
        ...
    def __reduce__(self) -> tuple:
        ...
    def __index__(self) -> int:
        ...
    def list(self) -> List['Rational']:
        ...
    def continued_fraction_list(self, type: str = 'std') -> List[Integer]:
        ...
    def continued_fraction(self) -> Any:
        ...
    def __copy__(self) -> 'Rational':
        ...
    def __deepcopy__(self, memo: dict) -> 'Rational':
        ...
    def __dealloc__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __mpz__(self) -> Any:
        ...
    def __mpq__(self) -> Any:
        ...
    def __array_interface__(self) -> dict:
        ...
    def content(self, other: 'Rational') -> 'Rational':
        ...
    def valuation(self, p: Any) -> Any:
        ...
    def local_height(self, p: Any, prec: int = 53) -> Any:
        ...
    def local_height_arch(self, prec: int = 53) -> Any:
        ...
    def global_height_non_arch(self, prec: int = 53) -> Any:
        ...
    def global_height_arch(self, prec: int = 53) -> Any:
        ...
    def global_height(self, prec: int = 53) -> Any:
        ...
    def is_square(self) -> bool:
        ...
    def is_norm(self, L: Any, element: bool = False, proof: bool = True) -> Union[bool, Tuple[bool, Any]]:
        ...
    def is_perfect_power(self, expected_value: bool = False) -> Union[bool, Tuple[Integer, int]]:
        ...
    def squarefree_part(self) -> 'Rational':
        ...
    def is_padic_square(self, p: Any, check: bool = True) -> bool:
        ...
    def val_unit(self, p: Any) -> Tuple[int, 'Rational']:
        ...
    def prime_to_S_part(self, S: List[Any] = []) -> 'Rational':
        ...
    def sqrt(self, prec: int = 53, extend: bool = True, all: bool = False) -> Any:
        ...
    def period(self) -> Integer:
        ...
    def nth_root(self, n: int) -> Any:
        ...
    def is_nth_power(self, n: int) -> bool:
        ...
    def str(self, base: int = 10) -> str:
        ...
    def __float__(self) -> float:
        ...
    def __hash__(self) -> int:
        ...
    def __getitem__(self, n: int) -> Integer:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self) -> 'Rational':
        ...
    def __pos__(self) -> 'Rational':
        ...
    def __neg__(self) -> 'Rational':
        ...
    def __bool__(self) -> bool:
        ...
    def __abs__(self) -> 'Rational':
        ...
    def sign(self) -> int:
        ...
    def mod_ui(self, n: int) -> int:
        ...
    def __mod__(x: Any, y: Any) -> Any:
        ...
    def norm(self) -> 'Rational':
        ...
    def relative_norm(self) -> 'Rational':
        ...
    def absolute_norm(self) -> 'Rational':
        ...
    def trace(self) -> 'Rational':
        ...
    def charpoly(self, var: str = 'x') -> Any:
        ...
    def minpoly(self, var: str = 'x') -> Any:
        ...
    def numerator(self) -> Integer:
        ...
    def __int__(self) -> int:
        ...
    def denominator(self) -> Integer:
        ...
    def as_integer_ratio(self) -> Tuple[int, int]:
        ...
    def factor(self) -> Any:
        ...
    def support(self) -> List[Integer]:
        ...
    def log(self, m: Optional[Any] = None, prec: Optional[int] = None) -> Any:
        ...
    def gamma(self, prec: int = 53) -> Any:
        ...
    def floor(self) -> Integer:
        ...
    def ceil(self) -> Integer:
        ...
    def trunc(self) -> Integer:
        ...
    def round(self, mode: str = 'half-even') -> Integer:
        ...
    def real(self) -> 'Rational':
        ...
    def imag(self) -> 'Rational':
        ...
    def height(self) -> Integer:
        ...
    def additive_order(self) -> Any:
        ...
    def multiplicative_order(self) -> Any:
        ...
    def is_one(self) -> bool:
        ...
    def is_integral(self) -> bool:
        ...
    def is_rational(self) -> bool:
        ...
    def is_S_integral(self, S: List[Any] = []) -> bool:
        ...
    def is_S_unit(self, S: List[Any] = []) -> bool:
        ...
    def __lshift__(x: Any, y: Any) -> Any:
        ...
    def __rshift__(x: Any, y: Any) -> Any:
        ...
    def conjugate(self) -> 'Rational':
        ...
    def __pari__(self) -> Any:
        ...

class Z_to_Q(Morphism):
    def __init__(self) -> None:
        ...
    def section(self) -> Any:
        ...
    def is_surjective(self) -> bool:
        ...

class Q_to_Z(Map):
    def section(self) -> Any:
        ...

class int_to_Q(Morphism):
    def __init__(self) -> None:
        ...
