from typing import Any

class RealDoubleElement_gsl(RealDoubleElement):
    def nth_root(self: Any, n: Any) -> Any:
        ...
    def log(self: Any, base: Any = ...) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def log10(self: Any) -> Any:
        ...
    def logpi(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def exp2(self: Any) -> Any:
        ...
    def exp10(self: Any) -> Any:
        ...
    def cos(self: Any) -> Any:
        ...
    def sin(self: Any) -> Any:
        ...
    def dilog(self: Any) -> Any:
        ...
    def restrict_angle(self: Any) -> Any:
        ...
    def tan(self: Any) -> Any:
        ...
    def sincos(self: Any) -> Any:
        ...
    def hypot(self: Any, other: Any) -> Any:
        ...
    def arccos(self: Any) -> Any:
        ...
    def arcsin(self: Any) -> Any:
        ...
    def arctan(self: Any) -> Any:
        ...
    def cosh(self: Any) -> Any:
        ...
    def sinh(self: Any) -> Any:
        ...
    def tanh(self: Any) -> Any:
        ...
    def acosh(self: Any) -> Any:
        ...
    def arcsinh(self: Any) -> Any:
        ...
    def arctanh(self: Any) -> Any:
        ...
    def sech(self: Any) -> Any:
        ...
    def csch(self: Any) -> Any:
        ...
    def coth(self: Any) -> Any:
        ...
    def erf(self: Any) -> Any:
        ...
    def gamma(self: Any) -> Any:
        ...
    def zeta(self: Any) -> Any:
        ...
