from typing import Any

def create_RealBall(parent: Any, serialized: Any) -> Any:
    ...

class RealBallField(UniqueRepresentation, sage.rings.abc.RealBallField):
    def __classcall__(cls: Any, precision: Any = ...) -> Any:
        ...
    def __init__(self: Any, precision: Any = ...) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def complex_field(self: Any) -> Any:
        ...
    def precision(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def some_elements(self: Any) -> Any:
        ...
    def pi(self: Any) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def euler_constant(self: Any) -> Any:
        ...
    def catalan_constant(self: Any) -> Any:
        ...
    def sinpi(self: Any, x: Any) -> Any:
        ...
    def cospi(self: Any, x: Any) -> Any:
        ...
    def gamma(self: Any, x: Any) -> Any:
        ...
    def zeta(self: Any, s: Any) -> Any:
        ...
    def bernoulli(self: Any, n: Any) -> Any:
        ...
    def fibonacci(self: Any, n: Any) -> Any:
        ...
    def bell_number(self: Any, n: Any) -> Any:
        ...
    def double_factorial(self: Any, n: Any) -> Any:
        ...
    def maximal_accuracy(self: Any) -> Any:
        ...

class RealBall(RingElement):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, mid: Any = ..., rad: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def mid(self: Any) -> Any:
        ...
    def rad(self: Any) -> Any:
        ...
    def diameter(self: Any) -> Any:
        ...
    def squash(self: Any) -> Any:
        ...
    def rad_as_ball(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def below_abs(self: Any, test_zero: Any = ...) -> Any:
        ...
    def above_abs(self: Any) -> Any:
        ...
    def upper(self: Any, rnd: Any = ...) -> Any:
        ...
    def lower(self: Any, rnd: Any = ...) -> Any:
        ...
    def endpoints(self: Any, rnd: Any = ...) -> Any:
        ...
    def union(self: Any, other: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def nbits(self: Any) -> Any:
        ...
    def round(self: Any) -> Any:
        ...
    def accuracy(self: Any) -> Any:
        ...
    def trim(self: Any) -> Any:
        ...
    def add_error(self: Any, ampl: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def is_nonzero(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> Any:
        ...
    def min(self: Any) -> Any:
        ...
    def max(self: Any) -> Any:
        ...
    def is_finite(self: Any) -> Any:
        ...
    def identical(self: Any, other: Any) -> Any:
        ...
    def overlaps(self: Any, other: Any) -> Any:
        ...
    def contains_exact(self: Any, other: Any) -> Any:
        ...
    def __contains__(self: Any, other: Any) -> Any:
        ...
    def contains_zero(self: Any) -> Any:
        ...
    def contains_integer(self: Any) -> Any:
        ...
    def is_negative_infinity(self: Any) -> Any:
        ...
    def is_positive_infinity(self: Any) -> Any:
        ...
    def is_infinity(self: Any) -> Any:
        ...
    def is_NaN(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __pow__(base: Any, expo: Any, _: Any) -> Any:
        ...
    def sqrt(self: Any) -> Any:
        ...
    def sqrtpos(self: Any) -> Any:
        ...
    def rsqrt(self: Any) -> Any:
        ...
    def sqrt1pm1(self: Any) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def __lshift__(val: Any, shift: Any) -> Any:
        ...
    def __rshift__(val: Any, shift: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def log(self: Any, base: Any = ...) -> Any:
        ...
    def log1p(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def expm1(self: Any) -> Any:
        ...
    def sin(self: Any) -> Any:
        ...
    def cos(self: Any) -> Any:
        ...
    def tan(self: Any) -> Any:
        ...
    def cot(self: Any) -> Any:
        ...
    def sec(self: Any) -> Any:
        ...
    def csc(self: Any) -> Any:
        ...
    def arcsin(self: Any) -> Any:
        ...
    def arccos(self: Any) -> Any:
        ...
    def arctan(self: Any) -> Any:
        ...
    def sinh(self: Any) -> Any:
        ...
    def cosh(self: Any) -> Any:
        ...
    def tanh(self: Any) -> Any:
        ...
    def coth(self: Any) -> Any:
        ...
    def sech(self: Any) -> Any:
        ...
    def csch(self: Any) -> Any:
        ...
    def arcsinh(self: Any) -> Any:
        ...
    def arccosh(self: Any) -> Any:
        ...
    def arctanh(self: Any) -> Any:
        ...
    def erf(self: Any) -> Any:
        ...
    def erfi(self: Any) -> Any:
        ...
    def Ei(self: Any) -> Any:
        ...
    def Si(self: Any) -> Any:
        ...
    def Ci(self: Any) -> Any:
        ...
    def Shi(self: Any) -> Any:
        ...
    def Chi(self: Any) -> Any:
        ...
    def li(self: Any) -> Any:
        ...
    def Li(self: Any) -> Any:
        ...
    def beta(self: Any, a: Any, z: Any = ...) -> Any:
        ...
    def gamma(self: Any, a: Any = ...) -> Any:
        ...
    def gamma_inc_lower(self: Any, a: Any) -> Any:
        ...
    def log_gamma(self: Any) -> Any:
        ...
    def rgamma(self: Any) -> Any:
        ...
    def rising_factorial(self: Any, n: Any) -> Any:
        ...
    def psi(self: Any) -> Any:
        ...
    def zeta(self: Any, a: Any = ...) -> Any:
        ...
    def zetaderiv(self: Any, k: Any) -> Any:
        ...
    def lambert_w(self: Any) -> Any:
        ...
    def polylog(self: Any, s: Any) -> Any:
        ...
    def chebyshev_T(self: Any, n: Any) -> Any:
        ...
    def chebyshev_U(self: Any, n: Any) -> Any:
        ...
    def agm(self: Any, other: Any) -> Any:
        ...
