from typing import Any

def RealDoubleField() -> Any:
    ...

def is_RealDoubleElement(x: Any) -> Any:
    ...

class RealDoubleField_class(sage.rings.abc.RealDoubleField):
    def __init__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> bool:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, x: Any, op: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def complex_field(self: Any) -> Any:
        ...
    def algebraic_closure(self: Any) -> Any:
        ...
    def precision(self: Any) -> Any:
        ...
    def to_prec(self: Any, prec: Any) -> Any:
        ...
    def gen(self: Any, n: Any = ...) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def random_element(self: Any, min: Any = ..., max: Any = ...) -> Any:
        ...
    def name(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def pi(self: Any) -> Any:
        ...
    def euler_constant(self: Any) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def factorial(self: Any, n: Any) -> Any:
        ...
    def zeta(self: Any, n: Any = ...) -> Any:
        ...
    def NaN(self: Any) -> Any:
        ...

class RealDoubleElement(FieldElement):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, x: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def prec(self: Any) -> Any:
        ...
    def ulp(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def __mpfr__(self: Any) -> Any:
        ...
    def __format__(self: Any, format_spec: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def str(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def integer_part(self: Any) -> Any:
        ...
    def sign_mantissa_exponent(self: Any) -> Any:
        ...
    def as_integer_ratio(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def abs(self: Any) -> Any:
        ...
    def __lshift__(x: Any, y: Any) -> Any:
        ...
    def __rshift__(x: Any, y: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def sign(self: Any) -> Any:
        ...
    def round(self: Any) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def trunc(self: Any) -> Any:
        ...
    def frac(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def is_NaN(self: Any) -> Any:
        ...
    def is_positive_infinity(self: Any) -> Any:
        ...
    def is_negative_infinity(self: Any) -> Any:
        ...
    def is_infinity(self: Any) -> Any:
        ...
    def NaN(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def is_integer(self: Any) -> Any:
        ...
    def cube_root(self: Any) -> Any:
        ...
    def agm(self: Any, other: Any) -> Any:
        ...
    def algebraic_dependency(self: Any, n: Any) -> Any:
        ...

class ToRDF(Morphism):
    def __init__(self: Any, R: Any) -> Any:
        ...
