from typing import Any

def RealLazyField() -> Any:
    ...

def ComplexLazyField() -> Any:
    ...

def make_element(parent: Any) -> Any:
    ...

class LazyField(Field):
    def __init__(self: Any, base: Any = ..., names: Any = ..., normalize: Any = ..., category: Any = ...) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def algebraic_closure(self: Any) -> Any:
        ...
    def interval_field(self: Any, prec: Any = ...) -> Any:
        ...

class RealLazyField_class(LazyField):
    def interval_field(self: Any, prec: Any = ...) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class ComplexLazyField_class(LazyField):
    def __init__(self: Any) -> Any:
        ...
    def interval_field(self: Any, prec: Any = ...) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class LazyFieldElement(FieldElement):
    def __pow__(left: Any, right: Any, dummy: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def approx(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __getattribute__(self: Any, name: Any) -> Any:
        ...
    def continued_fraction(self: Any) -> Any:
        ...

class LazyWrapper(LazyFieldElement):
    def __init__(self: Any, parent: Any, value: Any, check: Any = ...) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def continued_fraction(self: Any) -> Any:
        ...

class LazyBinop(LazyFieldElement):
    def __init__(self: Any, parent: Any, left: Any, right: Any, op: Any) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class LazyUnop(LazyFieldElement):
    def __init__(self: Any, parent: Any, arg: Any, op: Any) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class LazyNamedUnop(LazyUnop):
    def __init__(self: Any, parent: Any, arg: Any, op: Any, extra_args: Any = ...) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def approx(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class LazyConstant(LazyFieldElement):
    def __init__(self: Any, parent: Any, name: Any, extra_args: Any = ...) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class LazyAlgebraic(LazyFieldElement):
    def __init__(self: Any, parent: Any, poly: Any, approx: Any, prec: Any = ...) -> Any:
        ...
    def eval(self: Any, R: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class LazyWrapperMorphism(Morphism):
    def __init__(self: Any, domain: Any, codomain: Any) -> Any:
        ...
