from typing import Any

def RealIntervalField(prec: Any = ..., sci_not: Any = ...) -> Any:
    ...

def RealInterval(s: Any, upper: Any = ..., base: Any = ..., pad: Any = ..., min_prec: Any = ...) -> Any:
    ...

def is_RealIntervalField(x: Any) -> Any:
    ...

def is_RealIntervalFieldElement(x: Any) -> Any:
    ...

def __create__RealIntervalField_version0(prec: Any, sci_not: Any) -> Any:
    ...

def __create__RealIntervalFieldElement_version0(parent: Any, x: Any, base: Any = ...) -> Any:
    ...

def __create__RealIntervalFieldElement_version1(parent: Any, lower: Any, upper: Any) -> Any:
    ...

class RealIntervalField_class(sage.rings.abc.RealIntervalField):
    def __init__(self: Any, prec: Any = ..., sci_not: Any = ...) -> Any:
        ...
    def lower_field(self: Any) -> Any:
        ...
    def middle_field(self: Any) -> Any:
        ...
    def upper_field(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> bool:
        ...
    def __call__(self: Any, x: Any = ..., y: Any = ...) -> Any:
        ...
    def algebraic_closure(self: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def random_element(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...
    def complex_field(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def name(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def precision(self: Any) -> Any:
        ...
    def to_prec(self: Any, prec: Any) -> Any:
        ...
    def pi(self: Any) -> Any:
        ...
    def euler_constant(self: Any) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def scientific_notation(self: Any, status: Any = ...) -> Any:
        ...
    def zeta(self: Any, n: Any = ...) -> Any:
        ...

class RealIntervalFieldElement(RingElement):
    def __cinit__(self: Any, parent: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any, base: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def str(self: Any, base: Any = ..., style: Any = ..., no_sci: Any = ..., e: Any = ..., error_digits: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def lower(self: Any, rnd: Any = ...) -> Any:
        ...
    def upper(self: Any, rnd: Any = ...) -> Any:
        ...
    def endpoints(self: Any, rnd: Any = ...) -> Any:
        ...
    def edges(self: Any) -> Any:
        ...
    def absolute_diameter(self: Any) -> Any:
        ...
    def relative_diameter(self: Any) -> Any:
        ...
    def diameter(self: Any) -> Any:
        ...
    def fp_rank_diameter(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> Any:
        ...
    def magnitude(self: Any) -> Any:
        ...
    def mignitude(self: Any) -> Any:
        ...
    def center(self: Any) -> Any:
        ...
    def bisection(self: Any) -> Any:
        ...
    def alea(self: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def square(self: Any) -> Any:
        ...
    def __lshift__(x: Any, y: Any) -> Any:
        ...
    def __rshift__(x: Any, y: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def precision(self: Any) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def round(self: Any) -> Any:
        ...
    def trunc(self: Any) -> Any:
        ...
    def frac(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def unique_sign(self: Any) -> Any:
        ...
    def argument(self: Any) -> Any:
        ...
    def unique_floor(self: Any) -> Any:
        ...
    def unique_ceil(self: Any) -> Any:
        ...
    def unique_round(self: Any) -> Any:
        ...
    def unique_trunc(self: Any) -> Any:
        ...
    def unique_integer(self: Any) -> Any:
        ...
    def simplest_rational(self: Any, low_open: Any = ..., high_open: Any = ...) -> Any:
        ...
    def is_NaN(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def lexico_cmp(left: Any, right: Any) -> Any:
        ...
    def __contains__(self: Any, other: Any) -> Any:
        ...
    def contains_zero(self: Any) -> Any:
        ...
    def overlaps(self: Any, other: Any) -> Any:
        ...
    def intersection(self: Any, other: Any) -> Any:
        ...
    def union(self: Any, other: Any) -> Any:
        ...
    def min(self: Any) -> Any:
        ...
    def max(self: Any) -> Any:
        ...
    def sqrt(self: Any) -> Any:
        ...
    def square_root(self: Any) -> Any:
        ...
    def __pow__(self: Any, exponent: Any, modulus: Any) -> Any:
        ...
    def log(self: Any, base: Any = ...) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def log10(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def exp2(self: Any) -> Any:
        ...
    def is_int(self: Any) -> Any:
        ...
    def cos(self: Any) -> Any:
        ...
    def sin(self: Any) -> Any:
        ...
    def tan(self: Any) -> Any:
        ...
    def arccos(self: Any) -> Any:
        ...
    def arcsin(self: Any) -> Any:
        ...
    def arctan(self: Any) -> Any:
        ...
    def cosh(self: Any) -> Any:
        ...
    def sinh(self: Any) -> Any:
        ...
    def tanh(self: Any) -> Any:
        ...
    def arccosh(self: Any) -> Any:
        ...
    def arcsinh(self: Any) -> Any:
        ...
    def arctanh(self: Any) -> Any:
        ...
    def sec(self: Any) -> Any:
        ...
    def csc(self: Any) -> Any:
        ...
    def cot(self: Any) -> Any:
        ...
    def sech(self: Any) -> Any:
        ...
    def csch(self: Any) -> Any:
        ...
    def coth(self: Any) -> Any:
        ...
    def arcsech(self: Any) -> Any:
        ...
    def arccsch(self: Any) -> Any:
        ...
    def arccoth(self: Any) -> Any:
        ...
    def algebraic_dependency(self: Any, n: Any) -> Any:
        ...
    def factorial(self: Any) -> Any:
        ...
    def gamma(self: Any) -> Any:
        ...
    def psi(self: Any) -> Any:
        ...
    def zeta(self: Any, a: Any = ...) -> Any:
        ...
