from typing import Any

def mpfr_prec_min() -> Any:
    ...

def mpfr_prec_max() -> Any:
    ...

def mpfr_get_exp_min() -> Any:
    ...

def mpfr_get_exp_max() -> Any:
    ...

def mpfr_set_exp_min(e: Any) -> Any:
    ...

def mpfr_set_exp_max(e: Any) -> Any:
    ...

def mpfr_get_exp_min_min() -> Any:
    ...

def mpfr_get_exp_max_max() -> Any:
    ...

def RealField(prec: Any = ..., sci_not: Any = ..., rnd: Any = ...) -> Any:
    ...

def create_RealNumber(s: Any, base: Any = ..., pad: Any = ..., rnd: Any = ..., min_prec: Any = ...) -> Any:
    ...

def is_RealNumber(x: Any) -> Any:
    ...

def __create__RealField_version0(prec: Any, sci_not: Any, rnd: Any) -> Any:
    ...

def __create__RealNumber_version0(parent: Any, x: Any, base: Any = ...) -> Any:
    ...

class RealField_class(sage.rings.abc.RealField):
    def __init__(self: Any, prec: Any = ..., sci_not: Any = ..., rnd: Any = ...) -> Any:
        ...
    def is_exact(self: Any) -> bool:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...
    def complex_field(self: Any) -> Any:
        ...
    def algebraic_closure(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def name(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def precision(self: Any) -> Any:
        ...
    def to_prec(self: Any, prec: Any) -> Any:
        ...
    def pi(self: Any) -> Any:
        ...
    def euler_constant(self: Any) -> Any:
        ...
    def catalan_constant(self: Any) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def random_element(self: Any, min: Any = ..., max: Any = ..., distribution: Any = ...) -> Any:
        ...
    def factorial(self: Any, n: Any) -> Any:
        ...
    def rounding_mode(self: Any) -> Any:
        ...
    def scientific_notation(self: Any, status: Any = ...) -> Any:
        ...
    def zeta(self: Any, n: Any = ...) -> Any:
        ...

class RealNumber(sage.structure.element.RingElement):
    def __cinit__(self: Any, parent: Any, x: Any = ..., base: Any = ...) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any = ..., base: Any = ...) -> Any:
        ...
    def __array_interface__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __format__(self: Any, format_spec: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def hex(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def integer_part(self: Any) -> Any:
        ...
    def fp_rank(self: Any) -> Any:
        ...
    def fp_rank_delta(self: Any, other: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def __lshift__(x: Any, y: Any) -> Any:
        ...
    def __rshift__(x: Any, y: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def sign(self: Any) -> Any:
        ...
    def precision(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def ulp(self: Any, field: Any = ...) -> Any:
        ...
    def epsilon(self: Any, field: Any = ...) -> Any:
        ...
    def round(self: Any) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def trunc(self: Any) -> Any:
        ...
    def frac(self: Any) -> Any:
        ...
    def nexttoward(self: Any, other: Any) -> Any:
        ...
    def nextabove(self: Any) -> Any:
        ...
    def nextbelow(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def sign_mantissa_exponent(self: Any) -> Any:
        ...
    def exact_rational(self: Any) -> Any:
        ...
    def as_integer_ratio(self: Any) -> Any:
        ...
    def simplest_rational(self: Any) -> Any:
        ...
    def nearby_rational(self: Any, max_error: Any = ..., max_denominator: Any = ...) -> Any:
        ...
    def __mpfr__(self: Any) -> Any:
        ...
    def is_NaN(self: Any) -> Any:
        ...
    def is_positive_infinity(self: Any) -> Any:
        ...
    def is_negative_infinity(self: Any) -> Any:
        ...
    def is_infinity(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_real(self: Any) -> Any:
        ...
    def is_integer(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ...) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def cube_root(self: Any) -> Any:
        ...
    def __pow__(self: Any, exponent: Any, modulus: Any) -> Any:
        ...
    def log(self: Any, base: Any = ...) -> Any:
        ...
    def log2(self: Any) -> Any:
        ...
    def log10(self: Any) -> Any:
        ...
    def log1p(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def exp2(self: Any) -> Any:
        ...
    def exp10(self: Any) -> Any:
        ...
    def expm1(self: Any) -> Any:
        ...
    def eint(self: Any) -> Any:
        ...
    def cos(self: Any) -> Any:
        ...
    def sin(self: Any) -> Any:
        ...
    def tan(self: Any) -> Any:
        ...
    def sincos(self: Any) -> Any:
        ...
    def arccos(self: Any) -> Any:
        ...
    def arcsin(self: Any) -> Any:
        ...
    def arctan(self: Any) -> Any:
        ...
    def cosh(self: Any) -> Any:
        ...
    def sinh(self: Any) -> Any:
        ...
    def tanh(self: Any) -> Any:
        ...
    def coth(self: Any) -> Any:
        ...
    def arccoth(self: Any) -> Any:
        ...
    def cot(self: Any) -> Any:
        ...
    def csch(self: Any) -> Any:
        ...
    def arccsch(self: Any) -> Any:
        ...
    def csc(self: Any) -> Any:
        ...
    def sech(self: Any) -> Any:
        ...
    def arcsech(self: Any) -> Any:
        ...
    def sec(self: Any) -> Any:
        ...
    def arccosh(self: Any) -> Any:
        ...
    def arcsinh(self: Any) -> Any:
        ...
    def arctanh(self: Any) -> Any:
        ...
    def agm(self: Any, other: Any) -> Any:
        ...
    def erf(self: Any) -> Any:
        ...
    def erfc(self: Any) -> Any:
        ...
    def j0(self: Any) -> Any:
        ...
    def j1(self: Any) -> Any:
        ...
    def jn(self: Any, n: Any) -> Any:
        ...
    def y0(self: Any) -> Any:
        ...
    def y1(self: Any) -> Any:
        ...
    def yn(self: Any, n: Any) -> Any:
        ...
    def gamma(self: Any) -> Any:
        ...
    def log_gamma(self: Any) -> Any:
        ...
    def zeta(self: Any) -> Any:
        ...
    def algebraic_dependency(self: Any, n: Any) -> Any:
        ...
    def nth_root(self: Any, n: Any, algorithm: Any = ...) -> Any:
        ...

class RealLiteral(RealNumber):
    def __init__(self: Any, parent: Any, x: Any, base: Any = ...) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def numerical_approx(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...

class RRtoRR(Map):
    def section(self: Any) -> Any:
        ...

class ZZtoRR(Map):
    ...

class QQtoRR(Map):
    ...

class double_toRR(Map):
    ...

class int_toRR(Map):
    ...
