from typing import Any

def shift_floor(x: Any, shift: Any) -> Any:
    ...

def shift_ceil(x: Any, shift: Any) -> Any:
    ...

class Factory(UniqueFactory):
    def create_key(self: Any, prec: Any) -> Any:
        ...
    def create_object(self: Any, version: Any, prec: Any) -> Any:
        ...

class RealIntervalAbsoluteField_class(Field):
    def __init__(self: Any, absprec: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def absprec(self: Any) -> Any:
        ...

class RealIntervalAbsoluteElement(FieldElement):
    def __init__(self: Any, parent: Any, value: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def lower(self: Any) -> Any:
        ...
    def midpoint(self: Any) -> Any:
        ...
    def upper(self: Any) -> Any:
        ...
    def absolute_diameter(self: Any) -> Any:
        ...
    def endpoints(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def abs(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def __pow__(self: Any, exponent: Any, dummy: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def sqrt(self: Any) -> Any:
        ...

class MpfrOp:
    def __init__(self: Any, value: Any, name: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
