from typing import Any, Optional, Union, List, Tuple
from sage.structure.element import RingElement
from sage.rings.abc import RealField as AbstractRealField

# Module-level functions
def mpfr_prec_min() -> int:
    ...

def mpfr_prec_max() -> int:
    ...

def mpfr_get_exp_min() -> int:
    ...

def mpfr_get_exp_max() -> int:
    ...

def mpfr_set_exp_min(e: int) -> None:
    ...

def mpfr_set_exp_max(e: int) -> None:
    ...

def mpfr_get_exp_min_min() -> int:
    ...

def mpfr_get_exp_max_max() -> int:
    ...

class RealField_class(AbstractRealField):
    """Arbitrary precision real number field using MPFR."""
    
    def __init__(self, prec: int = 53, sci_not: int = 0, rnd: int = 0) -> None:
        ...
    
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __cmp__(self, other: Any) -> int:
        ...
    
    def __call__(self, x: Any = 0, base: int = 10) -> 'RealNumber':
        ...
    
    def __repr__(self) -> str:
        ...
    
    def _latex_(self) -> str:
        ...
    
    def prec(self) -> int:
        ...
    
    def precision(self) -> int:
        ...
    
    def rounding_mode(self) -> str:
        ...
    
    def is_exact(self) -> bool:
        ...
    
    def is_finite(self) -> bool:
        ...
    
    def characteristic(self) -> int:
        ...
    
    def gen(self, n: int = 0) -> 'RealNumber':
        ...
    
    def ngens(self) -> int:
        ...
    
    def pi(self) -> 'RealNumber':
        ...
    
    def euler_constant(self) -> 'RealNumber':
        ...
    
    def log2(self) -> 'RealNumber':
        ...
    
    def catalan_constant(self) -> 'RealNumber':
        ...
    
    def khinchin_constant(self) -> 'RealNumber':
        ...
    
    def glaisher_constant(self) -> 'RealNumber':
        ...
    
    def zeta(self, n: int = 3) -> 'RealNumber':
        ...

class RealNumber(RingElement):
    """An arbitrary precision real number using MPFR."""
    
    def __cinit__(self, parent: Any, x: Any = None, base: Optional[int] = None) -> None:
        ...
    
    def __init__(self, parent: Any, x: Any = 0, base: int = 10) -> None:
        ...
    
    def _magma_init_(self, magma: Any) -> str:
        ...
    
    def __array_interface__(self) -> dict:
        ...
    
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    
    def __dealloc__(self) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __format__(self, format_spec: str) -> str:
        ...
    
    def _latex_(self) -> str:
        ...
    
    def _interface_init_(self, I: Optional[Any] = None) -> str:
        ...
    
    def _mathematica_init_(self) -> str:
        ...
    
    def _sage_input_(self, sib: Any, coerced: bool) -> Any:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def _im_gens_(self, codomain: Any, im_gens: Any, base_map: Optional[Any] = None) -> Any:
        ...
    
    def real(self) -> 'RealNumber':
        ...
    
    def imag(self) -> 'RealNumber':
        ...
    
    def str(self, base: int = 10, digits: int = 0, no_sci: Optional[bool] = None, 
           e: Optional[str] = None, truncate: bool = True, skip_zeroes: bool = False) -> str:
        ...
    
    def hex(self) -> str:
        ...
    
    def exact_rational(self) -> Any:
        ...
    
    def simplest_rational(self) -> Any:
        ...
    
    def nearby_rational(self, max_error: Optional[Any] = None, max_denominator: Optional[int] = None) -> Any:
        ...
    
    def fp_rank(self) -> int:
        ...
    
    def ulp(self) -> 'RealNumber':
        ...
    
    def epsilon(self, field: Optional[Any] = None) -> 'RealNumber':
        ...
    
    def algebraic_degree(self) -> int:
        ...
    
    def prec(self) -> int:
        ...
    
    def precision(self) -> int:
        ...
    
    def parent(self) -> RealField_class:
        ...
    
    def nexttoward(self, other: 'RealNumber') -> 'RealNumber':
        ...
    
    def nextabove(self) -> 'RealNumber':
        ...
    
    def nextbelow(self) -> 'RealNumber':
        ...
    
    def is_zero(self) -> bool:
        ...
    
    def is_one(self) -> bool:
        ...
    
    def is_negative(self) -> bool:
        ...
    
    def is_positive(self) -> bool:
        ...
    
    def is_infinity(self) -> bool:
        ...
    
    def is_NaN(self) -> bool:
        ...
    
    def is_finite(self) -> bool:
        ...
    
    def is_real(self) -> bool:
        ...
    
    def is_square(self) -> bool:
        ...
    
    def is_integer(self) -> bool:
        ...
    
    def sign(self) -> int:
        ...
    
    def round(self) -> Any:
        ...
    
    def floor(self) -> Any:
        ...
    
    def ceil(self) -> Any:
        ...
    
    def ceiling(self) -> Any:
        ...
    
    def trunc(self) -> Any:
        ...
    
    def frac(self) -> 'RealNumber':
        ...
    
    def __int__(self) -> int:
        ...
    
    def __float__(self) -> float:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __add__(self, other: Any) -> Any:
        ...
    
    def __sub__(self, other: Any) -> Any:
        ...
    
    def __mul__(self, other: Any) -> Any:
        ...
    
    def __truediv__(self, other: Any) -> Any:
        ...
    
    def __pow__(self, other: Any) -> Any:
        ...
    
    def __neg__(self) -> 'RealNumber':
        ...
    
    def __pos__(self) -> 'RealNumber':
        ...
    
    def __abs__(self) -> 'RealNumber':
        ...
    
    def sqrt(self) -> 'RealNumber':
        ...
    
    def nth_root(self, n: int) -> 'RealNumber':
        ...
    
    def is_nth_power(self, n: int) -> bool:
        ...
    
    def log(self, base: Optional[Any] = None) -> 'RealNumber':
        ...
    
    def log2(self) -> 'RealNumber':
        ...
    
    def log10(self) -> 'RealNumber':
        ...
    
    def log1p(self) -> 'RealNumber':
        ...
    
    def exp(self) -> 'RealNumber':
        ...
    
    def exp2(self) -> 'RealNumber':
        ...
    
    def exp10(self) -> 'RealNumber':
        ...
    
    def expm1(self) -> 'RealNumber':
        ...
    
    def sin(self) -> 'RealNumber':
        ...
    
    def cos(self) -> 'RealNumber':
        ...
    
    def tan(self) -> 'RealNumber':
        ...
    
    def sec(self) -> 'RealNumber':
        ...
    
    def csc(self) -> 'RealNumber':
        ...
    
    def cot(self) -> 'RealNumber':
        ...
    
    def arcsin(self) -> 'RealNumber':
        ...
    
    def arccos(self) -> 'RealNumber':
        ...
    
    def arctan(self) -> 'RealNumber':
        ...
    
    def arctan2(self, x: 'RealNumber') -> 'RealNumber':
        ...
    
    def sinh(self) -> 'RealNumber':
        ...
    
    def cosh(self) -> 'RealNumber':
        ...
    
    def tanh(self) -> 'RealNumber':
        ...
    
    def sech(self) -> 'RealNumber':
        ...
    
    def csch(self) -> 'RealNumber':
        ...
    
    def coth(self) -> 'RealNumber':
        ...
    
    def arcsinh(self) -> 'RealNumber':
        ...
    
    def arccosh(self) -> 'RealNumber':
        ...
    
    def arctanh(self) -> 'RealNumber':
        ...
    
    def gamma(self) -> 'RealNumber':
        ...
    
    def log_gamma(self) -> 'RealNumber':
        ...
    
    def factorial(self) -> 'RealNumber':
        ...
    
    def zeta(self) -> 'RealNumber':
        ...
    
    def erf(self) -> 'RealNumber':
        ...
    
    def erfc(self) -> 'RealNumber':
        ...
    
    def j0(self) -> 'RealNumber':
        ...
    
    def j1(self) -> 'RealNumber':
        ...
    
    def jn(self, n: int) -> 'RealNumber':
        ...
    
    def y0(self) -> 'RealNumber':
        ...
    
    def y1(self) -> 'RealNumber':
        ...
    
    def yn(self, n: int) -> 'RealNumber':
        ...
    
    def agm(self, other: 'RealNumber') -> 'RealNumber':
        ...
    
    def min(self, other: 'RealNumber') -> 'RealNumber':
        ...
    
    def max(self, other: 'RealNumber') -> 'RealNumber':
        ...

class RealLiteral(RealNumber):
    """A real number literal with automatic parent determination."""
    pass

# Type aliases
RealField = RealField_class