from typing import Any

class RingExtensionHomomorphism(RingMap):
    def __init__(self: Any, parent: Any, defn: Any, base_map: Any = ..., check: Any = ...) -> Any:
        ...
    def base_map(self: Any) -> Any:
        ...
    def is_identity(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...

class RingExtensionBackendIsomorphism(RingExtensionHomomorphism):
    def __init__(self: Any, parent: Any) -> Any:
        ...

class RingExtensionBackendReverseIsomorphism(RingExtensionHomomorphism):
    def __init__(self: Any, parent: Any) -> Any:
        ...

class MapFreeModuleToRelativeRing(Map):
    def __init__(self: Any, E: Any, K: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...

class MapRelativeRingToFreeModule(Map):
    def __init__(self: Any, E: Any, K: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
