from typing import Any

class RingExtensionElement(CommutativeAlgebraElement):
    def __init__(self: Any, parent: Any, x: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def wrapper() -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def backend(self: Any, force: Any = ...) -> Any:
        ...
    def in_base(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def is_prime(self: Any) -> Any:
        ...
    def is_square(self: Any, root: Any = ...) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ..., name: Any = ...) -> Any:
        ...

class RingExtensionFractionFieldElement(RingExtensionElement):
    def __hash__(self: Any) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...

class RingExtensionWithBasisElement(RingExtensionElement):
    def __hash__(self: Any) -> Any:
        ...
    def vector(self: Any, base: Any = ...) -> Any:
        ...
    def polynomial(self: Any, base: Any = ..., var: Any = ...) -> Any:
        ...
    def matrix(self: Any, base: Any = ...) -> Any:
        ...
    def trace(self: Any, base: Any = ...) -> Any:
        ...
    def norm(self: Any, base: Any = ...) -> Any:
        ...
    def charpoly(self: Any, base: Any = ..., var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, base: Any = ..., var: Any = ...) -> Any:
        ...
