from typing import Any

def tower_bases(ring: Any, degree: Any) -> Any:
    ...

def common_base(K: Any, L: Any, degree: Any) -> Any:
    ...

def generators(ring: Any, base: Any) -> Any:
    ...

def variable_names(ring: Any, base: Any) -> Any:
    ...

class RingExtensionFactory(UniqueFactory):
    def create_key_and_extra_args(self: Any, ring: Any, defining_morphism: Any = ..., gens: Any = ..., names: Any = ..., constructors: Any = ...) -> Any:
        ...
    def create_object(self: Any, version: Any, key: Any) -> Any:
        ...

class RingExtension_generic(Parent):
    def __init__(self: Any, defining_morphism: Any, print_options: Any = ..., import_methods: Any = ..., is_backend_exposed: Any = ..., category: Any = ...) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def wrapper() -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def backend(self: Any, force: Any = ...) -> Any:
        ...
    def from_base_ring(self: Any, r: Any) -> Any:
        ...
    def print_options(self: Any) -> Any:
        ...
    def base(self: Any) -> Any:
        ...
    def bases(self: Any) -> Any:
        ...
    def absolute_base(self: Any) -> Any:
        ...
    def is_defined_over(self: Any, base: Any) -> Any:
        ...
    def defining_morphism(self: Any, base: Any = ...) -> Any:
        ...
    def ngens(self: Any, base: Any = ...) -> Any:
        ...
    def gen(self: Any) -> Any:
        ...
    def random_element(self: Any) -> Any:
        ...
    def degree_over(self: Any, base: Any = ...) -> Any:
        ...
    def degree(self: Any, base: Any) -> Any:
        ...
    def relative_degree(self: Any) -> Any:
        ...
    def absolute_degree(self: Any) -> Any:
        ...
    def is_finite_over(self: Any, base: Any = ...) -> Any:
        ...
    def is_free_over(self: Any, base: Any = ...) -> Any:
        ...
    def is_field(self: Any, proof: Any = ...) -> Any:
        ...
    def fraction_field(self: Any, extend_base: Any = ...) -> Any:
        ...
    def hom(self: Any, im_gens: Any, codomain: Any = ..., base_map: Any = ..., category: Any = ..., check: Any = ...) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...

class RingExtensionFractionField(RingExtension_generic):
    def __init__(self: Any, defining_morphism: Any, ring: Any = ...) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...

class RingExtensionWithBasis(RingExtension_generic):
    def __init__(self: Any, defining_morphism: Any, basis: Any, names: Any = ..., check: Any = ...) -> Any:
        ...
    def basis_over(self: Any, base: Any = ...) -> Any:
        ...
    def free_module(self: Any, base: Any = ..., map: Any = ...) -> Any:
        ...
    def fraction_field(self: Any, extend_base: Any = ...) -> Any:
        ...

class RingExtensionWithGen(RingExtensionWithBasis):
    def __init__(self: Any, defining_morphism: Any, gen: Any, names: Any, check: Any = ...) -> Any:
        ...
    def modulus(self: Any, var: Any = ...) -> Any:
        ...
    def fraction_field(self: Any, extend_base: Any = ...) -> Any:
        ...
