from typing import Any

def is_Ring(x: Any) -> Any:
    ...

class Ring(ParentWithGens):
    def __init__(self: Any, base: Any, names: Any = ..., normalize: Any = ..., category: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __xor__(self: Any, n: Any) -> Any:
        ...
    def base_extend(self: Any, R: Any) -> Any:
        ...
    def category(self: Any) -> Any:
        ...
    def __mul__(self: Any, x: Any) -> Any:
        ...
    def zero(self: Any) -> Any:
        ...
    def one(self: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...

class CommutativeRing(Ring):
    def __init__(self: Any, base_ring: Any, names: Any = ..., normalize: Any = ..., category: Any = ...) -> Any:
        ...
    def fraction_field(self: Any) -> Any:
        ...
    def extension(self: Any, poly: Any, name: Any = ..., names: Any = ...) -> Any:
        ...

class IntegralDomain(CommutativeRing):
    def __init__(self: Any) -> Any:
        ...

class NoetherianRing(CommutativeRing):
    def __init__(self: Any) -> Any:
        ...

class DedekindDomain(CommutativeRing):
    def __init__(self: Any) -> Any:
        ...

class PrincipalIdealDomain(CommutativeRing):
    def __init__(self: Any) -> Any:
        ...

class Field(CommutativeRing):
    ...

class Algebra(Ring):
    def __init__(self: Any, base_ring: Any) -> Any:
        ...

class CommutativeAlgebra(CommutativeRing):
    def __init__(self: Any, base_ring: Any) -> Any:
        ...
