from typing import Any

def backend_parent(R: Any) -> Any:
    ...

def from_backend_parent(R: Any, E: Any) -> Any:
    ...

def backend_element(x: Any) -> Any:
    ...

def from_backend_element(x: Any, E: Any) -> Any:
    ...

def backend_morphism(f: Any, forget: Any = ...) -> Any:
    ...

def from_backend_morphism(f: Any, E: Any) -> Any:
    ...

def to_backend(arg: Any) -> Any:
    ...

def from_backend(arg: Any, E: Any) -> Any:
    ...
