from typing import Any

def groebner_basis_buchberger(I: Any, prec: Any, py_integral: Any) -> Any:
    ...

def print_pair(p: Any, verbose: Any) -> Any:
    ...

def groebner_basis_pote(I: Any, prec: Any, verbose: Any = ...) -> Any:
    ...

def groebner_basis_vapote(I: Any, prec: Any, verbose: Any = ..., interrupt_red_with_val: Any = ..., interrupt_interred_with_val: Any = ...) -> Any:
    ...

class TateAlgebraIdeal(Ideal_generic):
    def groebner_basis(self: Any, prec: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def is_saturated(self: Any) -> Any:
        ...
    def saturate(self: Any) -> Any:
        ...
