from typing import Any

class TateAlgebraTerm(MonoidElement):
    def __init__(self: Any, parent: Any, coeff: Any, exponent: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def coefficient(self: Any) -> Any:
        ...
    def exponent(self: Any) -> Any:
        ...
    def monomial(self: Any) -> Any:
        ...
    def monic(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def is_coprime_with(self: Any, other: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...
    def lcm(self: Any, other: Any) -> Any:
        ...
    def is_divisible_by(self: Any, other: Any, integral: Any = ...) -> Any:
        ...
    def divides(self: Any, other: Any, integral: Any = ...) -> Any:
        ...

class TateAlgebraElement(CommutativeAlgebraElement):
    def __init__(self: Any, parent: Any, x: Any, prec: Any = ..., reduce: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def inverse_of_unit(self: Any, prec: Any = ...) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def __pow__(self: Any, exponent: Any, modulus: Any) -> Any:
        ...
    def square_root(self: Any, prec: Any = ...) -> Any:
        ...
    def sqrt(self: Any, prec: Any = ...) -> Any:
        ...
    def nth_root(self: Any, n: Any = ..., prec: Any = ...) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_zero(self: Any, prec: Any = ...) -> Any:
        ...
    def restriction(self: Any, log_radii: Any) -> Any:
        ...
    def terms(self: Any) -> Any:
        ...
    def monomials(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any) -> Any:
        ...
    def coefficient(self: Any, exponent: Any) -> Any:
        ...
    def __getitem__(self: Any, exponent: Any) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def add_bigoh(self: Any, n: Any) -> Any:
        ...
    def lift_to_precision(self: Any, prec: Any = ...) -> Any:
        ...
    def lift_without_error(elt: Any) -> Any:
        ...
    def precision_absolute(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def precision_relative(self: Any) -> Any:
        ...
    def log(self: Any, prec: Any = ...) -> Any:
        ...
    def exp(self: Any, prec: Any = ...) -> Any:
        ...
    def leading_term(self: Any, secure: Any = ...) -> Any:
        ...
    def leading_coefficient(self: Any, secure: Any = ...) -> Any:
        ...
    def leading_monomial(self: Any, secure: Any = ...) -> Any:
        ...
    def monic(self: Any) -> Any:
        ...
    def is_monic(self: Any) -> Any:
        ...
    def weierstrass_degree(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def weierstrass_degrees(self: Any) -> Any:
        ...
    def degrees(self: Any) -> Any:
        ...
    def residue(self: Any, n: Any = ...) -> Any:
        ...
    def quo_rem(self: Any, divisors: Any) -> Any:
        ...
    def __mod__(self: Any, divisors: Any) -> Any:
        ...
    def __floordiv__(self: Any, divisors: Any) -> Any:
        ...
    def reduce(self: Any, I: Any) -> Any:
        ...
    def Spoly(self: Any, other: Any) -> Any:
        ...
