from typing import Any

def is_FreeAbelianMonoidElement(x: Any) -> Any:
    ...

class FreeAbelianMonoidElement(MonoidElement):
    def __cinit__(self: Any, parent: Any = ..., x: Any = ...) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __mul__(self: Any, y: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, modulus: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
