from typing import Any

def DisjointSet(arg: Any) -> Any:
    ...

class DisjointSet_class(SageObject):
    def __iter__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def number_of_subsets(self: Any) -> Any:
        ...

class DisjointSet_of_integers(DisjointSet_class):
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, l: Any) -> Any:
        ...
    def find(self: Any, i: Any) -> int:
        ...
    def union(self: Any, i: Any, j: Any) -> None:
        ...
    def make_set(self: Any) -> Any:
        ...
    def root_to_elements_dict(self: Any) -> Any:
        ...
    def element_to_root_dict(self: Any) -> Any:
        ...
    def to_digraph(self: Any) -> Any:
        ...

class DisjointSet_of_hashables(DisjointSet_class):
    def __init__(self: Any, iterable: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, l: Any) -> Any:
        ...
    def find(self: Any, e: Any) -> Any:
        ...
    def union(self: Any, e: Any, f: Any) -> None:
        ...
    def make_set(self: Any, new_elt: Any = ...) -> Any:
        ...
    def root_to_elements_dict(self: Any) -> Any:
        ...
    def element_to_root_dict(self: Any) -> Any:
        ...
    def to_digraph(self: Any) -> Any:
        ...
