from typing import Any

def Family(indices: Any, function: Any = ..., hidden_keys: Any = ..., hidden_function: Any = ..., lazy: Any = ..., name: Any = ...) -> Any:
    ...

class AbstractFamily(Parent):
    def hidden_keys(self: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def values(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def zip(self: Any, f: Any, other: Any, name: Any = ...) -> Any:
        ...
    def map(self: Any, f: Any, name: Any = ...) -> Any:
        ...
    def inverse_family(self: Any) -> Any:
        ...

class FiniteFamily(AbstractFamily):
    def __init__(self: Any, dictionary: Any, keys: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def values(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...

class FiniteFamilyWithHiddenKeys(FiniteFamily):
    def __init__(self: Any, dictionary: Any, hidden_keys: Any, hidden_function: Any, keys: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def hidden_keys(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, d: Any) -> Any:
        ...

class LazyFamily(AbstractFamily):
    def __init__(self: Any, set: Any, function: Any, name: Any = ...) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, d: Any) -> Any:
        ...

class TrivialFamily(AbstractFamily):
    def __init__(self: Any, enumeration: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def map(self: Any, f: Any, name: Any = ...) -> Any:
        ...

class EnumeratedFamily(LazyFamily):
    def __init__(self: Any, enumset: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
