from typing import Any

def fibers(f: Any, domain: Any) -> Any:
    ...

def fibers_args(f: Any, domain: Any) -> Any:
    ...

def FiniteSetMap_Set_from_list(t: Any, parent: Any, lst: Any) -> Any:
    ...

def FiniteSetMap_Set_from_dict(t: Any, parent: Any, d: Any) -> Any:
    ...

class FiniteSetMap_MN(ClonableIntArray):
    def __call__(self: Any, i: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def domain(self: Any) -> Any:
        ...
    def codomain(self: Any) -> Any:
        ...
    def setimage(self: Any, i: Any, j: Any) -> Any:
        ...
    def getimage(self: Any, i: Any) -> Any:
        ...
    def image_set(self: Any) -> Any:
        ...
    def fibers(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def check(self: Any) -> Any:
        ...

class FiniteSetMap_Set(FiniteSetMap_MN):
    def __init__(self: Any, parent: Any, fun: Any, check: Any = ...) -> Any:
        ...
    def __call__(self: Any, i: Any) -> Any:
        ...
    def image_set(self: Any) -> Any:
        ...
    def setimage(self: Any, i: Any, j: Any) -> Any:
        ...
    def getimage(self: Any, i: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...

class FiniteSetEndoMap_N(FiniteSetMap_MN):
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, dummy: Any) -> Any:
        ...

class FiniteSetEndoMap_Set(FiniteSetMap_Set):
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, dummy: Any) -> Any:
        ...
