from typing import Any

def Set_PythonType(typ: Any) -> Any:
    ...

class Set_PythonType_class(Set_generic):
    def __init__(self: Any, typ: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def object(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
