from typing import Any

def search_forest_iterator(roots: Any, children: Any, algorithm: Any = ...) -> Any:
    ...

class RecursivelyEnumeratedSet_generic(Parent):
    def __reduce__(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, l: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __contains__(self: Any, elt: Any) -> Any:
        ...
    def seeds(self: Any) -> Any:
        ...
    def graded_component_iterator(self: Any) -> Any:
        ...
    def graded_component(self: Any, depth: Any) -> Any:
        ...
    def elements_of_depth_iterator(self: Any, depth: Any) -> Any:
        ...
    def breadth_first_search_iterator(self: Any, max_depth: Any = ...) -> Any:
        ...
    def naive_search_iterator(self: Any) -> Any:
        ...
    def depth_first_search_iterator(self: Any) -> Any:
        ...
    def to_digraph(self: Any, max_depth: Any = ..., loops: Any = ..., multiedges: Any = ...) -> Any:
        ...

class RecursivelyEnumeratedSet_symmetric(RecursivelyEnumeratedSet_generic):
    def breadth_first_search_iterator(self: Any, max_depth: Any = ...) -> Any:
        ...
    def graded_component_iterator(self: Any) -> Any:
        ...
    def graded_component(self: Any, depth: Any) -> Any:
        ...

class RecursivelyEnumeratedSet_graded(RecursivelyEnumeratedSet_generic):
    def breadth_first_search_iterator(self: Any, max_depth: Any = ...) -> Any:
        ...
    def graded_component_iterator(self: Any) -> Any:
        ...
    def graded_component(self: Any, depth: Any) -> Any:
        ...

class RecursivelyEnumeratedSet_forest(Parent):
    def roots(self: Any) -> Any:
        ...
    def children(self: Any, x: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def depth_first_search_iterator(self: Any) -> Any:
        ...
    def breadth_first_search_iterator(self: Any) -> Any:
        ...
    def elements_of_depth_iterator(self: Any, depth: Any = ...) -> Any:
        ...
    def __contains__(self: Any, elt: Any) -> Any:
        ...
