from typing import Any

class LocalGenericElement(CommutativeRingElement):
    def inverse_of_unit(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def slice(self: Any, i: Any, j: Any, k: Any = ..., lift_mode: Any = ...) -> Any:
        ...
    def add_bigoh(self: Any, absprec: Any) -> Any:
        ...
    def is_integral(self: Any) -> Any:
        ...
    def is_padic_unit(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def sqrt(self: Any, extend: Any = ..., all: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def normalized_valuation(self: Any) -> Any:
        ...
    def euclidean_degree(self: Any) -> Any:
        ...
    def quo_rem(self: Any, other: Any, integral: Any = ...) -> Any:
        ...
