from typing import Any

class FrobeniusEndomorphism_padics(RingHomomorphism):
    def __init__(self: Any, domain: Any, n: Any = ...) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def power(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, modulus: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
