from typing import Any

def make_pAdicFixedModElement(parent: Any, value: Any) -> Any:
    ...

class PowComputer_(PowComputer_base):
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any) -> Any:
        ...

class pAdicFixedModElement(FMElement):
    def lift(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def residue(self: Any, absprec: Any = ..., field: Any = ..., check_prec: Any = ...) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
