from typing import Any

def make_ZZpXCAElement(parent: Any, value: Any, absprec: Any, version: Any) -> Any:
    ...

class pAdicZZpXCAElement(pAdicZZpXElement):
    def __init__(self: Any, parent: Any, x: Any, absprec: Any = ..., relprec: Any = ..., empty: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def to_fraction_field(self: Any) -> Any:
        ...
    def __lshift__(self: Any, shift: Any) -> Any:
        ...
    def __rshift__(self: Any, shift: Any) -> Any:
        ...
    def __pow__(self: Any, _right: Any, m: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def is_zero(self: Any, absprec: Any = ...) -> Any:
        ...
    def polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def is_equal_to(self: Any, right: Any, absprec: Any = ...) -> Any:
        ...
    def lift_to_precision(self: Any, absprec: Any = ...) -> Any:
        ...
    def expansion(self: Any, n: Any = ..., lift_mode: Any = ...) -> Any:
        ...
    def matrix_mod_pn(self: Any) -> Any:
        ...
    def teichmuller_expansion(self: Any, n: Any = ...) -> Any:
        ...
    def precision_absolute(self: Any) -> Any:
        ...
    def precision_relative(self: Any) -> Any:
        ...
    def unit_part(self: Any) -> Any:
        ...
