from typing import Any

def pAdicPrinter(ring: Any, options: Any = ...) -> Any:
    ...

class pAdicPrinterDefaults(SageObject):
    def __init__(self: Any, mode: Any = ..., pos: Any = ..., max_ram_terms: Any = ..., max_unram_terms: Any = ..., max_terse_terms: Any = ..., sep: Any = ..., alphabet: Any = ...) -> Any:
        ...
    def mode(self: Any, mode: Any = ...) -> Any:
        ...
    def allow_negatives(self: Any, neg: Any = ...) -> Any:
        ...
    def max_series_terms(self: Any, max: Any = ...) -> Any:
        ...
    def max_unram_terms(self: Any, max: Any = ...) -> Any:
        ...
    def max_poly_terms(self: Any, max: Any = ...) -> Any:
        ...
    def sep(self: Any, sep: Any = ...) -> Any:
        ...
    def alphabet(self: Any, alphabet: Any = ...) -> Any:
        ...

class pAdicPrinter_class(SageObject):
    def __init__(self: Any, ring: Any, mode: Any, pos: Any, ram_name: Any, unram_name: Any, var_name: Any, max_ram_terms: Any, max_unram_terms: Any, max_terse_terms: Any, sep: Any, alphabet: Any, show_prec: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def dict(self: Any) -> Any:
        ...
    def __exit__(self: Any, type: Any, value: Any, traceback: Any) -> Any:
        ...
    def repr_gen(self: Any, elt: Any, do_latex: Any, pos: Any = ..., mode: Any = ..., ram_name: Any = ...) -> Any:
        ...
