from typing import Any

def dwork_mahler_coeffs(R: Any, bd: Any = ...) -> Any:
    ...

def evaluate_dwork_mahler(v: Any, x: Any, p: Any, bd: Any, a: Any) -> Any:
    ...

def gauss_table(p: Any, f: Any, prec: Any, use_longs: Any) -> Any:
    ...

class pAdicGenericElement(LocalGenericElement):
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def str(self: Any, mode: Any = ...) -> Any:
        ...
    def additive_order(self: Any, prec: Any = ...) -> Any:
        ...
    def artin_hasse_exp(self: Any, prec: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minimal_polynomial(self: Any, name: Any = ..., base: Any = ...) -> Any:
        ...
    def norm(self: Any, base: Any = ...) -> Any:
        ...
    def trace(self: Any, base: Any = ...) -> Any:
        ...
    def algebraic_dependency(self: Any, n: Any) -> Any:
        ...
    def dwork_expansion(self: Any, bd: Any = ..., a: Any = ...) -> Any:
        ...
    def gamma(self: Any, algorithm: Any = ...) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...
    def xgcd(self: Any, other: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def is_squarefree(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any, prec: Any = ...) -> Any:
        ...
    def valuation(self: Any, p: Any = ...) -> Any:
        ...
    def val_unit(self: Any) -> Any:
        ...
    def ordp(self: Any, p: Any = ...) -> Any:
        ...
    def is_prime(self: Any) -> Any:
        ...
    def rational_reconstruction(self: Any) -> Any:
        ...
    def log(self: Any, p_branch: Any = ..., pi_branch: Any = ..., aprec: Any = ..., change_frac: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def exp(self: Any, aprec: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def square_root(self: Any, extend: Any = ..., all: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def nth_root(self: Any, n: Any, all: Any = ...) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def abs(self: Any, prec: Any = ...) -> Any:
        ...
    def bound(m: Any) -> Any:
        ...
    def polylog(self: Any, n: Any, p_branch: Any = ...) -> Any:
        ...
