from typing import Any

def PowComputer_relative_maker(prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any, prec_type: Any) -> Any:
    ...

class PowComputer_relative(PowComputer_class):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any) -> Any:
        ...
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def polynomial(self: Any, n: Any = ..., var: Any = ...) -> Any:
        ...

class PowComputer_relative_eis(PowComputer_relative):
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any) -> Any:
        ...
    def invert(self: Any, a: Any, prec: Any) -> Any:
        ...
    def px_pow(self: Any, r: Any) -> Any:
        ...
    def pxe_pow(self: Any, r: Any) -> Any:
        ...
    def uniformizer_pow(self: Any, r: Any) -> Any:
        ...
