from typing import Any

def PowComputer_flint_maker(prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, prec_type: Any) -> Any:
    ...

class PowComputer_flint(PowComputer_class):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ..., shift_seed: Any = ...) -> Any:
        ...
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ..., shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def polynomial(self: Any, n: Any = ..., var: Any = ...) -> Any:
        ...

class PowComputer_flint_1step(PowComputer_flint):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, _poly: Any) -> Any:
        ...
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, _poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def polynomial(self: Any, _n: Any = ..., var: Any = ...) -> Any:
        ...

class PowComputer_flint_unram(PowComputer_flint_1step):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, _poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ...) -> Any:
        ...

class PowComputer_flint_eis(PowComputer_flint_1step):
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ...) -> Any:
        ...
