from typing import Any

def ZZ_pX_eis_shift_test(_shifter: Any, _a: Any, _n: Any, _finalprec: Any) -> Any:
    ...

def PowComputer_ext_maker(prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, prec_type: Any = ..., ext_type: Any = ..., shift_seed: Any = ...) -> Any:
    ...

class PowComputer_ext(PowComputer_class):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class PowComputer_ZZ_pX(PowComputer_ext):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def polynomial(self: Any) -> Any:
        ...
    def speed_test(self: Any, n: Any, runs: Any) -> Any:
        ...

class PowComputer_ZZ_pX_FM(PowComputer_ZZ_pX):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...

class PowComputer_ZZ_pX_FM_Eis(PowComputer_ZZ_pX_FM):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class PowComputer_ZZ_pX_small(PowComputer_ZZ_pX):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class PowComputer_ZZ_pX_small_Eis(PowComputer_ZZ_pX_small):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class PowComputer_ZZ_pX_big(PowComputer_ZZ_pX):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def reset_dictionaries(self: Any) -> Any:
        ...

class PowComputer_ZZ_pX_big_Eis(PowComputer_ZZ_pX_big):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any, shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
