from typing import Any

def PowComputer(m: Any, cache_limit: Any, prec_cap: Any, in_field: Any = ..., prec_type: Any = ...) -> Any:
    ...

class PowComputer_class(SageObject):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ..., shift_seed: Any = ...) -> Any:
        ...
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ..., shift_seed: Any = ...) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def pow_Integer_Integer(self: Any, n: Any) -> Any:
        ...
    def __call__(self: Any, n: Any) -> Any:
        ...

class PowComputer_base(PowComputer_class):
    def __cinit__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ..., shift_seed: Any = ...) -> Any:
        ...
    def __init__(self: Any, prime: Any, cache_limit: Any, prec_cap: Any, ram_prec_cap: Any, in_field: Any, poly: Any = ..., shift_seed: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
