from typing import Any

class MultiModularBasis_base:
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, val: Any, l_bound: Any = ..., u_bound: Any = ...) -> Any:
        ...
    def extend_with_primes(self: Any, plist: Any, partial_products: Any = ..., check: Any = ...) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def crt(self: Any, b: Any) -> Any:
        ...
    def precomputation_list(self: Any) -> Any:
        ...
    def partial_product(self: Any, n: Any) -> Any:
        ...
    def prod(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, ix: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class MultiModularBasis(MultiModularBasis_base):
    ...

class MutableMultiModularBasis(MultiModularBasis):
    def next_prime(self: Any) -> Any:
        ...
    def replace_prime(self: Any, ix: Any) -> Any:
        ...
