from typing import Any

class BasisMatroid(BasisExchangeMatroid):
    def __init__(self: Any, M: Any = ..., groundset: Any = ..., bases: Any = ..., nonbases: Any = ..., rank: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def dual(self: Any) -> Any:
        ...
    def truncation(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
    def bases_count(self: Any) -> Any:
        ...
    def bases(self: Any) -> Any:
        ...
    def nonbases(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
