from typing import Any

class BasisExchangeMatroid(Matroid):
    def __init__(self: Any, groundset: Any, basis: Any = ..., rank: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def groundset(self: Any) -> Any:
        ...
    def groundset_list(self: Any) -> List[Any]:
        ...
    def __len__(self: Any) -> Any:
        ...
    def full_rank(self: Any) -> Any:
        ...
    def full_corank(self: Any) -> Any:
        ...
    def basis(self: Any) -> Any:
        ...
    def components(self: Any) -> Any:
        ...
    def whitney_numbers2(self: Any) -> List[Any]:
        ...
    def flats(self: Any, k: Any) -> Any:
        ...
    def coflats(self: Any, k: Any) -> Any:
        ...
    def bases_count(self: Any) -> Any:
        ...
    def independent_sets(self: Any, k: Any = ...) -> Any:
        ...
    def dependent_sets(self: Any, k: Any) -> Any:
        ...
    def nonspanning_circuits(self: Any) -> Any:
        ...
    def noncospanning_cocircuits(self: Any) -> Any:
        ...
    def cocircuits(self: Any) -> Any:
        ...
    def circuits(self: Any, k: Any = ...) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
