from typing import Any

class CircuitsMatroid(Matroid):
    def __init__(self: Any, M: Any = ..., groundset: Any = ..., circuits: Any = ..., nsc_defined: Any = ...) -> Any:
        ...
    def groundset(self: Any) -> Any:
        ...
    def full_rank(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
    def bases_iterator(self: Any) -> Any:
        ...
    def independent_sets(self: Any, k: Any = ...) -> Any:
        ...
    def dependent_sets(self: Any, k: Any) -> Any:
        ...
    def circuits(self: Any, k: Any = ...) -> Any:
        ...
    def circuits_iterator(self: Any, k: Any = ...) -> Any:
        ...
    def nonspanning_circuits(self: Any) -> Any:
        ...
    def nonspanning_circuits_iterator(self: Any) -> Any:
        ...
    def no_broken_circuits_facets(self: Any, ordering: Any = ..., reduced: Any = ...) -> Any:
        ...
    def no_broken_circuits_sets(self: Any, ordering: Any = ..., reduced: Any = ...) -> Any:
        ...
    def broken_circuit_complex(self: Any, ordering: Any = ..., reduced: Any = ...) -> Any:
        ...
    def girth(self: Any) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
