from typing import Any

class CircuitClosuresMatroid(Matroid):
    def __init__(self: Any, M: Any = ..., groundset: Any = ..., circuit_closures: Any = ...) -> Any:
        ...
    def groundset(self: Any) -> Any:
        ...
    def full_rank(self: Any) -> Any:
        ...
    def circuit_closures(self: Any) -> Dict[Any, Any]:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
