from typing import Any

class CutNode:
    def __cinit__(self: Any, MC: Any, N: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class LinearSubclassesIter:
    def __init__(self: Any, MC: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class LinearSubclasses:
    def __init__(self: Any, M: Any, line_length: Any = ..., subsets: Any = ..., splice: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, node: Any) -> Any:
        ...

class MatroidExtensions(LinearSubclasses):
    def __init__(self: Any, M: Any, e: Any, line_length: Any = ..., subsets: Any = ..., splice: Any = ..., orderly: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, node: Any) -> Any:
        ...
