from typing import Any

class FlatsMatroid(Matroid):
    def __init__(self: Any, M: Any = ..., groundset: Any = ..., flats: Any = ...) -> Any:
        ...
    def groundset(self: Any) -> Any:
        ...
    def full_rank(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
    def flats(self: Any, k: Any) -> Any:
        ...
    def flats_iterator(self: Any, k: Any) -> Any:
        ...
    def lattice_of_flats(self: Any) -> Any:
        ...
    def whitney_numbers(self: Any) -> List[Any]:
        ...
    def whitney_numbers2(self: Any) -> List[Any]:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
