from typing import Any

class GraphicMatroid(Matroid):
    def __init__(self: Any, G: Any, groundset: Any = ...) -> Any:
        ...
    def groundset(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __ne__(self: Any, other: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def graph(self: Any) -> Any:
        ...
    def vertex_map(self: Any) -> Any:
        ...
    def groundset_to_edges(self: Any, X: Any) -> List[Any]:
        ...
    def subgraph_from_set(self: Any, X: Any) -> Any:
        ...
    def graphic_extension(self: Any, u: Any, v: Any = ..., element: Any = ...) -> Any:
        ...
    def graphic_extensions(self: Any, element: Any = ..., vertices: Any = ..., simple: Any = ...) -> Any:
        ...
    def graphic_coextension(self: Any, u: Any, v: Any = ..., X: Any = ..., element: Any = ...) -> Any:
        ...
    def graphic_coextensions(self: Any, vertices: Any = ..., v: Any = ..., element: Any = ..., cosimple: Any = ...) -> Any:
        ...
    def twist(self: Any, X: Any) -> Any:
        ...
    def one_sum(self: Any, X: Any, u: Any, v: Any) -> Any:
        ...
    def regular_matroid(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
