from typing import Any

def generic_identity(n: Any, ring: Any) -> Any:
    ...

class LeanMatrix:
    def __init__(self: Any, m: Any, n: Any, M: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def ncols(self: Any) -> int:
        ...
    def nrows(self: Any) -> int:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class GenericMatrix(LeanMatrix):
    def __init__(self: Any, nrows: Any, ncols: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class BinaryMatrix(LeanMatrix):
    def __cinit__(self: Any, m: Any, n: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __init__(self: Any, m: Any, n: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class TernaryMatrix(LeanMatrix):
    def __cinit__(self: Any, m: Any, n: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __init__(self: Any, m: Any, n: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class QuaternaryMatrix(LeanMatrix):
    def __cinit__(self: Any, m: Any, n: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __init__(self: Any, m: Any, n: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class PlusMinusOneMatrix(LeanMatrix):
    def __cinit__(self: Any, nrows: Any, ncols: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __init__(self: Any, nrows: Any, ncols: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class RationalMatrix(LeanMatrix):
    def __cinit__(self: Any, nrows: Any, ncols: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __init__(self: Any, nrows: Any, ncols: Any, M: Any = ..., ring: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
