from typing import Any

class LinearMatroid(BasisExchangeMatroid):
    def __init__(self: Any, matrix: Any = ..., groundset: Any = ..., reduced_matrix: Any = ..., ring: Any = ..., keep_initial_representation: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def representation(self: Any, B: Any = ..., reduced: Any = ..., labels: Any = ..., order: Any = ..., lift_map: Any = ...) -> Any:
        ...
    def representation_vectors(self: Any) -> Any:
        ...
    def is_field_equivalent(self: Any, other: Any) -> Any:
        ...
    def is_field_isomorphism(self: Any, other: Any, morphism: Any) -> Any:
        ...
    def is_field_isomorphic(self: Any, other: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def dual(self: Any) -> Any:
        ...
    def has_line_minor(self: Any, k: Any, hyperlines: Any = ..., certificate: Any = ...) -> Any:
        ...
    def has_field_minor(self: Any, N: Any) -> Any:
        ...
    def fundamental_cycle(self: Any, B: Any, e: Any) -> Any:
        ...
    def fundamental_cocycle(self: Any, B: Any, e: Any) -> Any:
        ...
    def cross_ratios(self: Any, hyperlines: Any = ...) -> Any:
        ...
    def cross_ratio(self: Any, F: Any, a: Any, b: Any, c: Any, d: Any) -> Any:
        ...
    def linear_extension(self: Any, element: Any, chain: Any = ..., col: Any = ...) -> Any:
        ...
    def linear_coextension(self: Any, element: Any, cochain: Any = ..., row: Any = ...) -> Any:
        ...
    def linear_extension_chains(self: Any, F: Any = ..., simple: Any = ..., fundamentals: Any = ...) -> Any:
        ...
    def linear_coextension_cochains(self: Any, F: Any = ..., cosimple: Any = ..., fundamentals: Any = ...) -> Any:
        ...
    def linear_extensions(self: Any, element: Any = ..., F: Any = ..., simple: Any = ..., fundamentals: Any = ...) -> Any:
        ...
    def linear_coextensions(self: Any, element: Any = ..., F: Any = ..., cosimple: Any = ..., fundamentals: Any = ...) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def orlik_terao_algebra(self: Any, R: Any = ..., ordering: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...

class BinaryMatroid(LinearMatroid):
    def __init__(self: Any, matrix: Any = ..., groundset: Any = ..., reduced_matrix: Any = ..., ring: Any = ..., keep_initial_representation: Any = ..., basis: Any = ...) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def bicycle_dimension(self: Any) -> Any:
        ...
    def brown_invariant(self: Any) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def binary_matroid(self: Any, randomized_tests: Any = ..., verify: Any = ...) -> Any:
        ...
    def is_binary(self: Any, randomized_tests: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...

class TernaryMatroid(LinearMatroid):
    def __init__(self: Any, matrix: Any = ..., groundset: Any = ..., reduced_matrix: Any = ..., ring: Any = ..., keep_initial_representation: Any = ..., basis: Any = ...) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def bicycle_dimension(self: Any) -> Any:
        ...
    def character(self: Any) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def ternary_matroid(self: Any, randomized_tests: Any = ..., verify: Any = ...) -> Any:
        ...
    def is_ternary(self: Any, randomized_tests: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...

class QuaternaryMatroid(LinearMatroid):
    def __init__(self: Any, matrix: Any = ..., groundset: Any = ..., reduced_matrix: Any = ..., ring: Any = ..., keep_initial_representation: Any = ..., basis: Any = ...) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def bicycle_dimension(self: Any) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...

class RegularMatroid(LinearMatroid):
    def __init__(self: Any, matrix: Any = ..., groundset: Any = ..., reduced_matrix: Any = ..., ring: Any = ..., keep_initial_representation: Any = ...) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def bases_count(self: Any) -> Any:
        ...
    def has_line_minor(self: Any, k: Any, hyperlines: Any = ..., certificate: Any = ...) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def binary_matroid(self: Any, randomized_tests: Any = ..., verify: Any = ...) -> Any:
        ...
    def is_binary(self: Any, randomized_tests: Any = ...) -> Any:
        ...
    def ternary_matroid(self: Any, randomized_tests: Any = ..., verify: Any = ...) -> Any:
        ...
    def is_ternary(self: Any, randomized_tests: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
