from typing import Any

class Matroid(SageObject):
    def groundset(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def size(self: Any) -> Any:
        ...
    def rank(self: Any, X: Any = ...) -> Any:
        ...
    def full_rank(self: Any) -> Any:
        ...
    def basis(self: Any) -> Any:
        ...
    def max_independent(self: Any, X: Any) -> Any:
        ...
    def circuit(self: Any, X: Any = ...) -> Any:
        ...
    def fundamental_circuit(self: Any, B: Any, e: Any) -> Any:
        ...
    def closure(self: Any, X: Any) -> Any:
        ...
    def k_closure(self: Any, X: Any, k: Any) -> Any:
        ...
    def augment(self: Any, X: Any, Y: Any = ...) -> Any:
        ...
    def corank(self: Any, X: Any = ...) -> Any:
        ...
    def full_corank(self: Any) -> Any:
        ...
    def cobasis(self: Any) -> Any:
        ...
    def max_coindependent(self: Any, X: Any) -> Any:
        ...
    def coclosure(self: Any, X: Any) -> Any:
        ...
    def cocircuit(self: Any, X: Any = ...) -> Any:
        ...
    def fundamental_cocircuit(self: Any, B: Any, e: Any) -> Any:
        ...
    def loops(self: Any) -> Any:
        ...
    def is_independent(self: Any, X: Any) -> Any:
        ...
    def is_dependent(self: Any, X: Any) -> Any:
        ...
    def is_basis(self: Any, X: Any) -> Any:
        ...
    def is_closed(self: Any, X: Any) -> Any:
        ...
    def is_subset_k_closed(self: Any, X: Any, k: Any) -> Any:
        ...
    def is_circuit(self: Any, X: Any) -> Any:
        ...
    def coloops(self: Any) -> Any:
        ...
    def is_coindependent(self: Any, X: Any) -> Any:
        ...
    def is_codependent(self: Any, X: Any) -> Any:
        ...
    def is_cobasis(self: Any, X: Any) -> Any:
        ...
    def is_cocircuit(self: Any, X: Any) -> Any:
        ...
    def is_coclosed(self: Any, X: Any) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
    def circuits(self: Any, k: Any = ...) -> Any:
        ...
    def circuits_iterator(self: Any, k: Any = ...) -> Any:
        ...
    def nonspanning_circuits(self: Any) -> Any:
        ...
    def nonspanning_circuits_iterator(self: Any) -> Any:
        ...
    def cocircuits(self: Any) -> Any:
        ...
    def cocircuits_iterator(self: Any) -> Any:
        ...
    def noncospanning_cocircuits(self: Any) -> Any:
        ...
    def circuit_closures(self: Any) -> Dict[Any, Any]:
        ...
    def nonspanning_circuit_closures(self: Any) -> Dict[Any, Any]:
        ...
    def nonbases(self: Any) -> Any:
        ...
    def nonbases_iterator(self: Any) -> Any:
        ...
    def dependent_sets(self: Any, k: Any) -> Any:
        ...
    def dependent_sets_iterator(self: Any, k: Any) -> Any:
        ...
    def bases(self: Any) -> Any:
        ...
    def bases_iterator(self: Any) -> Any:
        ...
    def independent_sets(self: Any, k: Any = ...) -> Any:
        ...
    def independent_sets_iterator(self: Any, k: Any = ...) -> Any:
        ...
    def flats(self: Any, k: Any) -> Any:
        ...
    def coflats(self: Any, k: Any) -> Any:
        ...
    def lattice_of_flats(self: Any) -> Any:
        ...
    def hyperplanes(self: Any) -> Any:
        ...
    def f_vector(self: Any) -> List[Any]:
        ...
    def whitney_numbers(self: Any) -> List[Any]:
        ...
    def whitney_numbers2(self: Any) -> List[Any]:
        ...
    def broken_circuits(self: Any, ordering: Any = ...) -> Any:
        ...
    def no_broken_circuits_sets(self: Any, ordering: Any = ...) -> Any:
        ...
    def no_broken_circuits_sets_iterator(self: Any, ordering: Any = ...) -> Any:
        ...
    def orlik_solomon_algebra(self: Any, R: Any, ordering: Any = ...) -> Any:
        ...
    def matroid_polytope(self: Any) -> Any:
        ...
    def independence_matroid_polytope(self: Any) -> Any:
        ...
    def is_isomorphic(self: Any, other: Any, certificate: Any = ...) -> Any:
        ...
    def isomorphism(self: Any, other: Any) -> Any:
        ...
    def equals(self: Any, other: Any) -> Any:
        ...
    def is_isomorphism(self: Any, other: Any, morphism: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def minor(self: Any, contractions: Any = ..., deletions: Any = ...) -> Any:
        ...
    def contract(self: Any, X: Any) -> Any:
        ...
    def __truediv__(self: Any, X: Any) -> Any:
        ...
    def delete(self: Any, X: Any) -> Any:
        ...
    def dual(self: Any) -> Any:
        ...
    def truncation(self: Any) -> Any:
        ...
    def has_minor(self: Any, N: Any, certificate: Any = ...) -> Any:
        ...
    def has_line_minor(self: Any, k: Any, hyperlines: Any = ..., certificate: Any = ...) -> Any:
        ...
    def extension(self: Any, element: Any = ..., subsets: Any = ...) -> Any:
        ...
    def coextension(self: Any, element: Any = ..., subsets: Any = ...) -> Any:
        ...
    def modular_cut(self: Any, subsets: Any) -> Any:
        ...
    def linear_subclasses(self: Any, line_length: Any = ..., subsets: Any = ...) -> Any:
        ...
    def extensions(self: Any, element: Any = ..., line_length: Any = ..., subsets: Any = ...) -> Any:
        ...
    def coextensions(self: Any, element: Any = ..., coline_length: Any = ..., subsets: Any = ...) -> Any:
        ...
    def simplify(self: Any) -> Any:
        ...
    def cosimplify(self: Any) -> Any:
        ...
    def is_simple(self: Any) -> Any:
        ...
    def is_cosimple(self: Any) -> Any:
        ...
    def components(self: Any) -> Any:
        ...
    def is_connected(self: Any, certificate: Any = ...) -> Any:
        ...
    def connectivity(self: Any, S: Any, T: Any = ...) -> Any:
        ...
    def link(self: Any, S: Any, T: Any) -> Any:
        ...
    def is_kconnected(self: Any, k: Any, certificate: Any = ...) -> Any:
        ...
    def is_3connected(self: Any, certificate: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def is_4connected(self: Any, certificate: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def girth(self: Any) -> Any:
        ...
    def binary_matroid(self: Any, randomized_tests: Any = ..., verify: Any = ...) -> Any:
        ...
    def is_binary(self: Any, randomized_tests: Any = ...) -> Any:
        ...
    def ternary_matroid(self: Any, randomized_tests: Any = ..., verify: Any = ...) -> Any:
        ...
    def is_ternary(self: Any, randomized_tests: Any = ...) -> Any:
        ...
    def is_k_closed(self: Any, k: Any) -> Any:
        ...
    def is_circuit_chordal(self: Any, C: Any, certificate: Any = ...) -> Any:
        ...
    def is_chordal(self: Any, k1: Any = ..., k2: Any = ..., certificate: Any = ...) -> Any:
        ...
    def chordality(self: Any) -> Any:
        ...
    def max_weight_independent(self: Any, X: Any = ..., weights: Any = ...) -> Any:
        ...
    def max_weight_coindependent(self: Any, X: Any = ..., weights: Any = ...) -> Any:
        ...
    def is_max_weight_independent_generic(self: Any, X: Any = ..., weights: Any = ...) -> Any:
        ...
    def is_max_weight_coindependent_generic(self: Any, X: Any = ..., weights: Any = ...) -> Any:
        ...
    def intersection(self: Any, other: Any, weights: Any = ...) -> Any:
        ...
    def intersection_unweighted(self: Any, other: Any) -> Any:
        ...
    def partition(self: Any) -> Any:
        ...
    def tutte_polynomial(self: Any, x: Any = ..., y: Any = ...) -> Any:
        ...
    def characteristic_polynomial(self: Any, la: Any = ...) -> Any:
        ...
    def flat_cover(self: Any, solver: Any = ..., verbose: Any = ..., integrality_tolerance: Any = ...) -> Any:
        ...
    def chow_ring(self: Any, R: Any, augmented: Any = ..., presentation: Any = ...) -> Any:
        ...
    def plot(self: Any, B: Any = ..., lineorders: Any = ..., pos_method: Any = ..., pos_dict: Any = ..., save_pos: Any = ...) -> Any:
        ...
    def show(self: Any, B: Any = ..., lineorders: Any = ..., pos_method: Any = ..., pos_dict: Any = ..., save_pos: Any = ..., lims: Any = ...) -> Any:
        ...
    def broken_circuit_complex(self: Any, ordering: Any = ...) -> Any:
        ...
    def automorphism_group(self: Any) -> Any:
        ...
    def bergman_complex(self: Any) -> Any:
        ...
    def augmented_bergman_complex(self: Any) -> Any:
        ...
    def union(self: Any, matroids: Any) -> Any:
        ...
    def direct_sum(self: Any, matroids: Any) -> Any:
        ...
    def relabel(self: Any, mapping: Any) -> Any:
        ...
    def f_relabel(X: Any) -> Any:
        ...
