from typing import Any

class SetSystem:
    def __cinit__(self: Any, groundset: Any, subsets: Any = ..., capacity: Any = ...) -> Any:
        ...
    def __init__(self: Any, groundset: Any, subsets: Any = ..., capacity: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, k: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def is_connected(self: Any) -> Any:
        ...

class SetSystemIterator:
    def __init__(self: Any, H: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
