from typing import Any

class TransversalMatroid(BasisExchangeMatroid):
    def __init__(self: Any, sets: Any, groundset: Any = ..., set_labels: Any = ..., matching: Any = ...) -> Any:
        ...
    def sets(self: Any) -> List[Any]:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def graph(self: Any) -> Any:
        ...
    def set_labels(self: Any) -> Any:
        ...
    def reduce_presentation(self: Any) -> Any:
        ...
    def transversal_extension(self: Any, element: Any = ..., newset: Any = ..., sets: Any = ...) -> Any:
        ...
    def transversal_extensions(self: Any, element: Any = ..., sets: Any = ...) -> Any:
        ...
    def is_valid(self: Any, certificate: Any = ...) -> Any:
        ...
