from typing import Any

def unpickle_basis_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_circuits_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_circuit_closures_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_flats_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_dual_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_gammoid(version: Any, data: Any) -> Any:
    ...

def unpickle_generic_matrix(version: Any, data: Any) -> Any:
    ...

def unpickle_binary_matrix(version: Any, data: Any) -> Any:
    ...

def unpickle_ternary_matrix(version: Any, data: Any) -> Any:
    ...

def unpickle_quaternary_matrix(version: Any, data: Any) -> Any:
    ...

def unpickle_plus_minus_one_matrix(version: Any, data: Any) -> Any:
    ...

def unpickle_rational_matrix(version: Any, data: Any) -> Any:
    ...

def unpickle_linear_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_binary_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_ternary_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_quaternary_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_regular_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_minor_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_graphic_matroid(version: Any, data: Any) -> Any:
    ...

def unpickle_transversal_matroid(version: Any, data: Any) -> Any:
    ...
