from typing import Any

class KhuriMakdisi_base:
    def negate(self: Any, wd: Any) -> Matrix:
        ...
    def add(self: Any, wd1: Any, wd2: Any) -> Matrix:
        ...
    def subtract(self: Any, wd1: Any, wd2: Any) -> Matrix:
        ...
    def multiple(self: Any, wd: Any, n: Any) -> Matrix:
        ...
    def zero_divisor(self: Any) -> Matrix:
        ...

class KhuriMakdisi_large(KhuriMakdisi_base):
    def __init__(self: Any, V: Any, mu: Any, w0: Any, d0: Any, g: Any) -> Any:
        ...
    def equal(self: Any, wd: Any, we: Any) -> Any:
        ...
    def addflip(self: Any, wd1: Any, wd2: Any) -> Matrix:
        ...
    def add_divisor(self: Any, wd1: Any, wd2: Any, d1: Any, d2: Any) -> Matrix:
        ...

class KhuriMakdisi_medium(KhuriMakdisi_base):
    def __init__(self: Any, V: Any, mu: Any, w0: Any, d0: Any, g: Any) -> Any:
        ...
    def equal(self: Any, wd: Any, we: Any) -> Any:
        ...
    def addflip(self: Any, wd1: Any, wd2: Any) -> Matrix:
        ...
    def add_divisor(self: Any, wd1: Any, wd2: Any, d1: Any, d2: Any) -> Matrix:
        ...

class KhuriMakdisi_small(KhuriMakdisi_base):
    def __init__(self: Any, V: Any, mu: Any, w0: Any, d0: Any, g: Any) -> Any:
        ...
    def equal(self: Any, wd: Any, we: Any) -> Any:
        ...
    def addflip(self: Any, wd1: Any, wd2: Any) -> Matrix:
        ...
    def negate(self: Any, wd: Any) -> Matrix:
        ...
    def add_divisor(self: Any, wd1: Any, wd2: Any, d1: Any, d2: Any) -> Matrix:
        ...
