from typing import Any

class LieAlgebraElement(IndexedFreeModuleElement):
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def base_map(x: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...

class LieAlgebraElementWrapper(ElementWrapper):
    def __bool__(self: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(self: Any, x: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...

class LieAlgebraMatrixWrapper(LieAlgebraElementWrapper):
    def __init__(self: Any, parent: Any, value: Any) -> Any:
        ...

class LieSubalgebraElementWrapper(LieAlgebraElementWrapper):
    def __init__(self: Any, parent: Any, value: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Dict[Any, Any]:
        ...

class StructureCoefficientsElement(LieAlgebraMatrixWrapper):
    def bracket(self: Any, right: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def to_vector(self: Any, sparse: Any = ..., order: Any = ...) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Dict[Any, Any]:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...

class UntwistedAffineLieAlgebraElement(Element):
    def __init__(self: Any, parent: Any, t_dict: Any, c_coeff: Any, d_coeff: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def t_dict(self: Any) -> Dict[Any, Any]:
        ...
    def c_coefficient(self: Any) -> Any:
        ...
    def d_coefficient(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Any:
        ...
    def bracket(self: Any, right: Any) -> Any:
        ...
    def canonical_derivation(self: Any) -> Any:
        ...

class FreeLieAlgebraElement(LieAlgebraElement):
    def lift(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def k(x: Any) -> Any:
        ...

class LieObject(SageObject):
    def to_word(self: Any) -> Tuple[Any, ...]:
        ...

class LieGenerator(LieObject):
    def __init__(self: Any, name: Any, index: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, rhs: Any, op: Any) -> Any:
        ...
    def to_word(self: Any) -> Tuple[Any, ...]:
        ...
    def lift(self: Any, UEA_gens_dict: Any) -> Any:
        ...

class LieBracket(LieObject):
    def __init__(self: Any, l: Any, r: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __richcmp__(self: Any, rhs: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def lift(self: Any, UEA_gens_dict: Any) -> Any:
        ...
    def to_word(self: Any) -> Tuple[Any, ...]:
        ...

class GradedLieBracket(LieBracket):
    def __init__(self: Any, l: Any, r: Any, grade: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, rhs: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class LyndonBracket(GradedLieBracket):
    def __richcmp__(self: Any, rhs: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
