from typing import Any

class GapElement(RingElement):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def deepcopy(self: Any, mut: Any) -> GapElement:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __contains__(self: Any, other: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def is_function(self: Any) -> Any:
        ...
    def is_list(self: Any) -> Any:
        ...
    def is_record(self: Any) -> Any:
        ...
    def is_bool(self: Any) -> Any:
        ...
    def is_string(self: Any) -> Any:
        ...
    def is_permutation(self: Any) -> Any:
        ...
    def sage(self: Any) -> Any:
        ...

class GapElement_Integer(GapElement):
    def is_C_int(self: Any) -> Any:
        ...
    def sage(self: Any, ring: Any = ...) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...

class GapElement_Float(GapElement):
    def sage(self: Any, ring: Any = ...) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...

class GapElement_IntegerMod(GapElement):
    def lift(self: Any) -> Any:
        ...
    def sage(self: Any, ring: Any = ...) -> Any:
        ...

class GapElement_FiniteField(GapElement):
    def lift(self: Any) -> Any:
        ...
    def sage(self: Any, ring: Any = ..., var: Any = ...) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...

class GapElement_Cyclotomic(GapElement):
    def sage(self: Any, ring: Any = ...) -> Any:
        ...

class GapElement_Rational(GapElement):
    def sage(self: Any, ring: Any = ...) -> Any:
        ...

class GapElement_Ring(GapElement):
    def ring_integer(self: Any) -> Any:
        ...
    def ring_rational(self: Any) -> Any:
        ...
    def ring_integer_mod(self: Any) -> Any:
        ...
    def ring_finite_field(self: Any, var: Any = ...) -> Any:
        ...
    def ring_cyclotomic(self: Any) -> Any:
        ...
    def ring_polynomial(self: Any) -> Any:
        ...
    def sage(self: Any) -> Any:
        ...

class GapElement_Boolean(GapElement):
    def sage(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...

class GapElement_String(GapElement):
    def __str__(self: Any) -> Any:
        ...

class GapElement_Function(GapElement):
    def __repr__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...

class GapElement_MethodProxy(GapElement_Function):
    def __call__(self: Any) -> Any:
        ...

class GapElement_List(GapElement):
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, elt: Any) -> Any:
        ...
    def sage(self: Any) -> Any:
        ...
    def matrix(self: Any, ring: Any = ...) -> Any:
        ...
    def vector(self: Any, ring: Any = ...) -> Any:
        ...

class GapElement_Permutation(GapElement):
    def sage(self: Any, parent: Any = ...) -> Any:
        ...

class GapElement_Record(GapElement):
    def __len__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, name: Any) -> Any:
        ...
    def sage(self: Any) -> Any:
        ...

class GapElement_RecordIterator:
    def __cinit__(self: Any, rec: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
