from typing import Any

def crash_and_burn() -> None:
    ...

class Gap(Parent):
    def eval(self: Any, gap_command: Any) -> Any:
        ...
    def load_package(self: Any, pkg: Any) -> Any:
        ...
    def function_factory(self: Any, function_name: Any) -> Any:
        ...
    def set_global(self: Any, variable: Any, value: Any) -> Any:
        ...
    def unset_global(self: Any, variable: Any) -> Any:
        ...
    def get_global(self: Any, variable: Any) -> Any:
        ...
    def global_context(self: Any, variable: Any, value: Any) -> Any:
        ...
    def set_seed(self: Any, seed: Any = ...) -> Any:
        ...
    def zero(self: Any) -> Any:
        ...
    def one(self: Any) -> Any:
        ...
    def __init__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def show(self: Any) -> Any:
        ...
    def count_GAP_objects(self: Any) -> Any:
        ...
    def collect(self: Any) -> Any:
        ...
