from typing import Any

class RiggedPartition(SageObject):
    def __init__(self: Any, shape: Any = ..., rigging_list: Any = ..., vacancy_nums: Any = ...) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def get_num_cells_to_column(self: Any, end_column: Any, t: Any = ...) -> Any:
        ...
    def insert_cell(self: Any, max_width: Any) -> Any:
        ...
    def remove_cell(self: Any, row: Any, num_cells: Any = ...) -> Any:
        ...

class RiggedPartitionTypeB(RiggedPartition):
    def __init__(self: Any, arg0: Any, arg1: Any = ..., arg2: Any = ...) -> Any:
        ...
