from typing import Any

def make_permgroup_element(G: Any, x: Any) -> Any:
    ...

def make_permgroup_element_v2(G: Any, x: Any, domain: Any) -> Any:
    ...

def is_PermutationGroupElement(x: Any) -> Any:
    ...

class PermutationGroupElement(MultiplicativeGroupElement):
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, g: Any, parent: Any, check: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __call__(self: Any, i: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def domain(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def tuple(self: Any) -> Any:
        ...
    def dict(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
    def sign(self: Any) -> Any:
        ...
    def orbit(self: Any, n: Any, sorted: Any = ...) -> Any:
        ...
    def cycles(self: Any) -> Any:
        ...
    def cycle_tuples(self: Any, singletons: Any = ...) -> Any:
        ...
    def cycle_string(self: Any, singletons: Any = ...) -> Any:
        ...
    def cycle_type(self: Any, singletons: Any = ..., as_list: Any = ...) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def word_problem(self: Any, words: Any, display: Any = ..., as_list: Any = ...) -> Any:
        ...
    def convert_back(string: Any) -> Any:
        ...

class SymmetricGroupElement(PermutationGroupElement):
    def absolute_length(self: Any) -> Any:
        ...
