from typing import Any, Optional, Tuple, Dict, List, Union
from sage.structure.element import MultiplicativeGroupElement

def make_permgroup_element(G: Any, x: Any) -> 'PermutationGroupElement':
    ...

def make_permgroup_element_v2(G: Any, x: Any, domain: Any) -> 'PermutationGroupElement':
    ...

def is_PermutationGroupElement(x: Any) -> bool:
    ...

class PermutationGroupElement(MultiplicativeGroupElement):
    def __dealloc__(self) -> None:
        ...
    def __init__(self, g: Any, parent: Any, check: bool = True) -> None:
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def __getitem__(self, i: int) -> int:
        ...
    def __call__(self, i: int) -> int:
        ...
    def __mul__(left: 'PermutationGroupElement', right: 'PermutationGroupElement') -> 'PermutationGroupElement':
        ...
    def __invert__(self) -> 'PermutationGroupElement':
        ...
    def domain(self) -> List[int]:
        ...
    def __hash__(self) -> int:
        ...
    def tuple(self) -> Tuple[int, ...]:
        ...
    def dict(self) -> Dict[int, int]:
        ...
    def multiplicative_order(self) -> int:
        ...
    def inverse(self) -> 'PermutationGroupElement':
        ...
    def sign(self) -> int:
        ...
    def orbit(self, n: int, sorted: bool = True) -> List[int]:
        ...
    def cycles(self) -> List[Tuple[int, ...]]:
        ...
    def cycle_tuples(self, singletons: bool = True) -> List[Tuple[int, ...]]:
        ...
    def cycle_string(self, singletons: bool = True) -> str:
        ...
    def cycle_type(self, singletons: bool = True, as_list: bool = False) -> Union[List[int], Tuple[int, ...]]:
        ...
    def matrix(self: Any) -> Any:
        ...
    def word_problem(self: Any, words: Any, display: Any = ..., as_list: Any = ...) -> Any:
        ...
    def convert_back(string: Any) -> Any:
        ...

class SymmetricGroupElement(PermutationGroupElement):
    def absolute_length(self: Any) -> Any:
        ...
