from typing import Any, List, Tuple, Union

class Spline:
    def __init__(self, v: List[Tuple[float, float]] = ...) -> None:
        ...
    def __dealloc__(self) -> None:
        ...
    def __setitem__(self, i: int, xy: Tuple[float, float]) -> None:
        ...
    def __getitem__(self, i: int) -> Tuple[float, float]:
        ...
    def __delitem__(self, i: int) -> None:
        ...
    def append(self, xy: Tuple[float, float]) -> None:
        ...
    def list(self) -> List[Tuple[float, float]]:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __call__(self, x: float) -> float:
        ...
    def derivative(self, x: float, order: int = ...) -> float:
        ...
    def definite_integral(self, a: float, b: float) -> float:
        ...
