from typing import Any

class Spline:
    def __init__(self: Any, v: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, xy: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __delitem__(self: Any, i: Any) -> Any:
        ...
    def append(self: Any, xy: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def derivative(self: Any, x: Any, order: Any = ...) -> Any:
        ...
    def definite_integral(self: Any, a: Any, b: Any) -> Any:
        ...
