from typing import Any

def polygon_spline(pts: Any) -> Any:
    ...

def complex_cubic_spline(pts: Any) -> Any:
    ...

class PSpline:
    def __init__(self: Any, pts: Any) -> Any:
        ...
    def value(self: Any, t: Any) -> Any:
        ...
    def derivative(self: Any, t: Any) -> Any:
        ...

class CCSpline:
    def __init__(self: Any, pts: Any) -> Any:
        ...
    def value(self: Any, t: Any) -> Any:
        ...
    def derivative(self: Any, t: Any) -> Any:
        ...
