from typing import Any

def __setattr__(self: Any, name: Any, value: Any) -> Any:
    ...

def interpolate_solution(self: Any, i: Any = ...) -> Any:
    ...

def plot_solution(self: Any, i: Any = ..., filename: Any = ..., interpolate: Any = ...) -> Any:
    ...

def ode_solve(self: Any, t_span: Any = ..., y_0: Any = ..., num_points: Any = ..., params: Any = ...) -> Any:
    ...

class PyFunctionWrapper:
    ...

class ode_system:
    ...

class ode_solver:
    ...

class van_der_pol(sage.calculus.ode.ode_system):
    ...
