from typing import Any

def complex_to_rgb(ndim: Any = ...) -> Any:
    ...

def analytic_boundary(t: Any, n: Any, epsilon: Any) -> Any:
    ...

def cauchy_kernel(t: Any, args: Any) -> Any:
    ...

def analytic_interior(z: Any, n: Any, epsilon: Any) -> Any:
    ...

class Riemann_Map:
    def get_szego(self: Any, boundary: Any = ..., absolute_value: Any = ...) -> Any:
        ...
    def get_theta_points(self: Any, boundary: Any = ...) -> Any:
        ...
    def riemann_map(self: Any, pt: Any) -> Any:
        ...
    def inverse_riemann_map(self: Any, pt: Any) -> Any:
        ...
    def plot_boundaries(self: Any, plotjoined: Any = ..., rgbcolor: Any = ..., thickness: Any = ...) -> Any:
        ...
    def compute_on_grid(self: Any, plot_range: Any, x_points: Any) -> Any:
        ...
    def plot_colored(self: Any, plot_range: Any = ..., plot_points: Any = ...) -> Any:
        ...
