from typing import Any

class Context:
    def __cinit__(ctx: Any) -> Any:
        ...
    def default(ctx: Any) -> Any:
        ...
    def make_mpf(ctx: Any, v: Any) -> Any:
        ...
    def make_mpc(ctx: Any, v: Any) -> Any:
        ...
    def convert(ctx: Any, x: Any, strings: Any = ...) -> Any:
        ...
    def isnan(ctx: Any, x: Any) -> Any:
        ...
    def isinf(ctx: Any, x: Any) -> Any:
        ...
    def isnormal(ctx: Any, x: Any) -> Any:
        ...
    def isint(ctx: Any, x: Any, gaussian: Any = ...) -> Any:
        ...
    def fsum(ctx: Any, terms: Any, absolute: Any = ..., squared: Any = ...) -> Any:
        ...
    def fdot(ctx: Any, A: Any, B: Any = ..., conjugate: Any = ...) -> Any:
        ...
    def mag(ctx: Any, x: Any) -> Any:
        ...

class wrapped_libmp_function:
    def __init__(self: Any, mpf_f: Any, mpc_f: Any = ..., mpi_f: Any = ..., doc: Any = ...) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...

class wrapped_specfun:
    def __init__(self: Any, name: Any, f: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...

class mpnumber:
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __truediv__(self: Any, other: Any) -> Any:
        ...
    def __mod__(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, other: Any, mod: Any) -> Any:
        ...
    def ae(s: Any, t: Any, rel_eps: Any = ..., abs_eps: Any = ...) -> Any:
        ...

class mpf_base(mpnumber):
    def __hash__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def man(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def bc(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def to_fixed(self: Any, prec: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, val: Any) -> Any:
        ...

class mpf(mpf_base):
    def __init__(self: Any, x: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def man(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def bc(self: Any) -> Any:
        ...
    def to_fixed(self: Any, prec: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, val: Any) -> Any:
        ...
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __neg__(s: Any) -> Any:
        ...
    def __pos__(s: Any) -> Any:
        ...
    def __abs__(s: Any) -> Any:
        ...
    def sqrt(s: Any) -> Any:
        ...
    def __round__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...

class constant(mpf_base):
    def __init__(self: Any, func: Any, name: Any, docname: Any = ...) -> Any:
        ...
    def __call__(self: Any, prec: Any = ..., dps: Any = ..., rounding: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def sqrt(self: Any) -> Any:
        ...
    def to_fixed(self: Any, prec: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, val: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...

class mpc(mpnumber):
    def __init__(self: Any, real: Any = ..., imag: Any = ...) -> Any:
        ...
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, val: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(s: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __neg__(s: Any) -> Any:
        ...
    def conjugate(s: Any) -> Any:
        ...
    def __pos__(s: Any) -> Any:
        ...
    def __abs__(s: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
