from typing import Any

def mpf_add(x: Any, y: Any, prec: Any = ..., rnd: Any = ...) -> Any:
    ...

def mpf_sub(x: Any, y: Any, prec: Any = ..., rnd: Any = ...) -> Any:
    ...

def mpf_mul(x: Any, y: Any, prec: Any = ..., rnd: Any = ...) -> Any:
    ...

def mpf_div(x: Any, y: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpf_sqrt(x: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpf_log(x: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpf_exp(x: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpf_cos(x: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpf_sin(x: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpc_sqrt(z: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpc_exp(z: Any, prec: Any, rnd: Any = ...) -> Any:
    ...

def mpf_pow(x: Any, y: Any, prec: Any, rnd: Any = ...) -> Any:
    ...
