from typing import Any

def iterator_tracking_words(W: Any) -> Any:
    ...

def parabolic_iteration_application(W: Any, f: Any) -> Any:
    ...

def reduced_word_c(W: Any, w: Any) -> List[Any]:
    ...

class Iterator:
    def __iter__(self: Any) -> Any:
        ...
    def iter_depth(self: Any) -> Any:
        ...
    def iter_words_depth(self: Any) -> Any:
        ...
    def iter_breadth(self: Any) -> Any:
        ...
    def iter_words_breadth(self: Any) -> Any:
        ...
    def iter_parabolic(self: Any) -> Any:
        ...
