from typing import Any

class ComplexReflectionGroupElement(PermutationGroupElement):
    def __hash__(self: Any) -> Any:
        ...
    def reduced_word(self: Any) -> Any:
        ...
    def reduced_word_in_reflections(self: Any) -> Any:
        ...
    def length(self: Any) -> Any:
        ...
    def to_matrix(self: Any, on_space: Any = ...) -> Any:
        ...
    def canonical_matrix(self: Any) -> Any:
        ...
    def action(self: Any, vec: Any, on_space: Any = ...) -> Any:
        ...
    def action_on_root_indices(self: Any, i: Any) -> Any:
        ...
    def action_on_root(self: Any, root: Any) -> Any:
        ...
    def to_permutation_of_roots(self: Any) -> Any:
        ...
    def fix_space(self: Any) -> Any:
        ...
    def reflection_eigenvalues(self: Any, is_class_representative: Any = ...) -> Any:
        ...
    def galois_conjugates(self: Any) -> Any:
        ...

class RealReflectionGroupElement(ComplexReflectionGroupElement):
    def reduced_word_in_reflections(self: Any) -> Any:
        ...
    def length(self: Any) -> Any:
        ...
    def coset_representative(self: Any, index_set: Any, side: Any = ...) -> Any:
        ...
    def to_matrix(self: Any, side: Any = ..., on_space: Any = ...) -> Any:
        ...
    def action(self: Any, vec: Any, side: Any = ..., on_space: Any = ...) -> Any:
        ...
    def action_on_root_indices(self: Any, i: Any, side: Any = ...) -> Any:
        ...
    def action_on_root(self: Any, root: Any, side: Any = ...) -> Any:
        ...
    def inversion_set(self: Any, side: Any = ...) -> Any:
        ...
