from typing import Any

class IntegerListsBackend:
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...

class Envelope:
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def limit_start(self: Any) -> Any:
        ...
    def limit(self: Any) -> Any:
        ...
    def __call__(self: Any, k: Any) -> Any:
        ...
    def adapt(self: Any, m: Any, j: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
