from typing import Any

def unpickle_FiniteDimensionalAlgebraElement(A: Any, vec: Any, mat: Any) -> Any:
    ...

class FiniteDimensionalAlgebraElement(AlgebraElement):
    def __init__(self: Any, A: Any, elt: Any = ..., check: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def vector(self: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Dict[Any, Any]:
        ...
    def left_matrix(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, m: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, m: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def is_invertible(self: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
    def is_zerodivisor(self: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def minimal_polynomial(self: Any) -> Any:
        ...
    def characteristic_polynomial(self: Any) -> Any:
        ...
