from typing import Any, Dict, Tuple
from sage.algebras.algebra_element import AlgebraElement

def unpickle_FiniteDimensionalAlgebraElement(A: Any, vec: Any, mat: Any) -> "FiniteDimensionalAlgebraElement":
    ...

class FiniteDimensionalAlgebraElement(AlgebraElement):
    def __init__(self, A: Any, elt: Any = ..., check: bool = ...) -> None:
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def __setstate__(self, state: Any) -> None:
        ...
    def vector(self) -> Any:
        ...
    def matrix(self) -> Any:
        ...
    def monomial_coefficients(self, copy: bool = ...) -> Dict[Any, Any]:
        ...
    def left_matrix(self) -> Any:
        ...
    def __hash__(self) -> int:
        ...
    def __getitem__(self, m: Any) -> Any:
        ...
    def __len__(self) -> int:
        ...
    def __pow__(self, n: int, m: Any = None) -> "FiniteDimensionalAlgebraElement":
        ...
    def __invert__(self) -> "FiniteDimensionalAlgebraElement":
        ...
    def is_invertible(self) -> bool:
        ...
    def inverse(self) -> "FiniteDimensionalAlgebraElement":
        ...
    def is_zerodivisor(self) -> bool:
        ...
    def is_nilpotent(self) -> bool:
        ...
    def minimal_polynomial(self) -> Any:
        ...
    def characteristic_polynomial(self) -> Any:
        ...
