from typing import Any

class IndexedFreeModuleElement(ModuleElement):
    def __init__(self: Any, M: Any, x: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Dict[Any, Any]:
        ...
    def __getitem__(self: Any, m: Any) -> Any:
        ...
    def __truediv__(left: Any, x: Any) -> Any:
        ...
