from typing import Any

class _BestValStore:
    def __cinit__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class LabelledBranching:
    def __cinit__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def add_gen(self: Any, gen: Any) -> Any:
        ...
    def small_generating_set(self: Any) -> Any:
        ...
    def get_order(self: Any) -> Any:
        ...

class PartitionRefinement_generic:
    def __cinit__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def get_canonical_form(self: Any) -> Any:
        ...
    def get_transporter(self: Any) -> Any:
        ...
    def get_autom_gens(self: Any) -> Any:
        ...
    def get_autom_order_permutation(self: Any) -> Any:
        ...
