from typing import Any

class ProbabilityDistribution:
    def __init__(self: Any) -> Any:
        ...
    def get_random_element(self: Any) -> Any:
        ...
    def generate_histogram_data(self: Any, num_samples: Any = ..., bins: Any = ...) -> Any:
        ...
    def generate_histogram_plot(self: Any, name: Any, num_samples: Any = ..., bins: Any = ...) -> Any:
        ...

class SphericalDistribution(ProbabilityDistribution):
    def __init__(self: Any, dimension: Any = ..., rng: Any = ..., seed: Any = ...) -> Any:
        ...
    def set_seed(self: Any, seed: Any) -> Any:
        ...
    def set_random_number_generator(self: Any, rng: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def get_random_element(self: Any) -> Any:
        ...
    def reset_distribution(self: Any) -> Any:
        ...

class RealDistribution(ProbabilityDistribution):
    def set_seed(self: Any, seed: Any) -> Any:
        ...
    def set_random_number_generator(self: Any, rng: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def get_random_element(self: Any) -> Any:
        ...
    def set_distribution(self: Any, name: Any = ..., parameters: Any = ...) -> Any:
        ...
    def reset_distribution(self: Any) -> Any:
        ...
    def distribution_function(self: Any, x: Any) -> Any:
        ...
    def cum_distribution_function(self: Any, x: Any) -> Any:
        ...
    def cum_distribution_function_inv(self: Any, x: Any) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...

class GeneralDiscreteDistribution(ProbabilityDistribution):
    def __init__(self: Any, P: Any, rng: Any = ..., seed: Any = ...) -> Any:
        ...
    def set_seed(self: Any, seed: Any) -> Any:
        ...
    def set_random_number_generator(self: Any, rng: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def get_random_element(self: Any) -> Any:
        ...
    def reset_distribution(self: Any) -> Any:
        ...
