from typing import Any

class CVXOPTSDPBackend(MatrixSDPBackend):
    def __init__(self: Any, maximization: Any = ..., base_ring: Any = ...) -> Any:
        ...
    def solve(self: Any) -> int:
        ...
    def get_objective_value(self: Any) -> Any:
        ...
    def get_variable_value(self: Any, variable: Any) -> Any:
        ...
    def dual_variable(self: Any, i: Any, sparse: Any = ...) -> Any:
        ...
    def slack(self: Any, i: Any, sparse: Any = ...) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
