from typing import Any

class CVXOPTBackend(GenericBackend):
    def __cinit__(self: Any, maximization: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def add_variable(self: Any, lower_bound: Any = ..., upper_bound: Any = ..., binary: Any = ..., continuous: Any = ..., integer: Any = ..., obj: Any = ..., name: Any = ...) -> int:
        ...
    def set_variable_type(self: Any, variable: Any, vtype: Any) -> Any:
        ...
    def set_sense(self: Any, sense: Any) -> Any:
        ...
    def objective_coefficient(self: Any, variable: Any, coeff: Any = ...) -> Any:
        ...
    def set_objective(self: Any, coeff: Any, d: Any = ...) -> Any:
        ...
    def set_verbosity(self: Any, level: Any) -> Any:
        ...
    def add_col(self: Any, indices: Any, coeffs: Any) -> Any:
        ...
    def add_linear_constraint(self: Any, coefficients: Any, lower_bound: Any, upper_bound: Any, name: Any = ...) -> Any:
        ...
    def solve(self: Any) -> int:
        ...
    def get_objective_value(self: Any) -> Any:
        ...
    def get_variable_value(self: Any, variable: Any) -> Any:
        ...
    def problem_name(self: Any, name: Any = ...) -> Any:
        ...
    def row(self: Any, i: Any) -> Any:
        ...
    def row_bounds(self: Any, index: Any) -> Any:
        ...
    def col_bounds(self: Any, index: Any) -> Any:
        ...
    def row_name(self: Any, index: Any) -> Any:
        ...
    def col_name(self: Any, index: Any) -> Any:
        ...
    def variable_upper_bound(self: Any, index: Any, value: Any = ...) -> Any:
        ...
    def variable_lower_bound(self: Any, index: Any, value: Any = ...) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
