from typing import Any

def default_sdp_solver(solver: Any = ...) -> Any:
    ...

def get_solver(solver: Any = ..., base_ring: Any = ...) -> Any:
    ...

class GenericSDPBackend:
    def base_ring(self: Any) -> Any:
        ...
    def zero(self: Any) -> Any:
        ...
    def add_variable(self: Any, obj: Any = ..., name: Any = ...) -> int:
        ...
    def add_variables(self: Any, n: Any, names: Any = ...) -> int:
        ...
    def set_sense(self: Any, sense: Any) -> Any:
        ...
    def objective_coefficient(self: Any, variable: Any, coeff: Any = ...) -> Any:
        ...
    def set_objective(self: Any, coeff: Any, d: Any = ...) -> Any:
        ...
    def add_linear_constraint(self: Any, coefficients: Any, name: Any = ...) -> Any:
        ...
    def add_linear_constraints(self: Any, number: Any, names: Any = ...) -> Any:
        ...
    def solve(self: Any) -> int:
        ...
    def get_objective_value(self: Any) -> Any:
        ...
    def get_variable_value(self: Any, variable: Any) -> Any:
        ...
    def problem_name(self: Any, name: Any = ...) -> Any:
        ...
    def row(self: Any, i: Any) -> Any:
        ...
    def row_name(self: Any, index: Any) -> Any:
        ...
    def col_name(self: Any, index: Any) -> Any:
        ...
    def dual_variable(self: Any, i: Any, sparse: Any = ...) -> Any:
        ...
    def slack(self: Any, i: Any, sparse: Any = ...) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
