from typing import Any

def default_mip_solver(solver: Any = ...) -> Any:
    ...

def get_solver(constraint_generation: Any = ..., solver: Any = ..., base_ring: Any = ...) -> Any:
    ...

class GenericBackend:
    def base_ring(self: Any) -> Any:
        ...
    def zero(self: Any) -> Any:
        ...
    def add_variables(self: Any, n: Any, lower_bound: Any = ..., upper_bound: Any = ..., binary: Any = ..., continuous: Any = ..., integer: Any = ..., obj: Any = ..., names: Any = ...) -> int:
        ...
    def set_variable_type(self: Any, variable: Any, vtype: Any) -> Any:
        ...
    def set_sense(self: Any, sense: Any) -> Any:
        ...
    def objective_coefficient(self: Any, variable: Any, coeff: Any = ...) -> Any:
        ...
    def objective_constant_term(self: Any, d: Any = ...) -> Any:
        ...
    def set_objective(self: Any, coeff: Any, d: Any = ...) -> Any:
        ...
    def set_verbosity(self: Any, level: Any) -> Any:
        ...
    def remove_constraint(self: Any, i: Any) -> Any:
        ...
    def remove_constraints(self: Any, constraints: Any) -> Any:
        ...
    def add_linear_constraint(self: Any, coefficients: Any, lower_bound: Any, upper_bound: Any, name: Any = ...) -> Any:
        ...
    def add_linear_constraint_vector(self: Any, degree: Any, coefficients: Any, lower_bound: Any, upper_bound: Any, name: Any = ...) -> Any:
        ...
    def add_col(self: Any, indices: Any, coeffs: Any) -> Any:
        ...
    def add_linear_constraints(self: Any, number: Any, lower_bound: Any, upper_bound: Any, names: Any = ...) -> Any:
        ...
    def solve(self: Any) -> int:
        ...
    def get_objective_value(self: Any) -> Any:
        ...
    def best_known_objective_bound(self: Any) -> Any:
        ...
    def get_relative_objective_gap(self: Any) -> Any:
        ...
    def get_variable_value(self: Any, variable: Any) -> Any:
        ...
    def problem_name(self: Any, name: Any = ...) -> Any:
        ...
    def write_lp(self: Any, name: Any) -> Any:
        ...
    def write_mps(self: Any, name: Any, modern: Any) -> Any:
        ...
    def copy(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def row(self: Any, i: Any) -> Any:
        ...
    def row_bounds(self: Any, index: Any) -> Any:
        ...
    def col_bounds(self: Any, index: Any) -> Any:
        ...
    def row_name(self: Any, index: Any) -> Any:
        ...
    def col_name(self: Any, index: Any) -> Any:
        ...
    def assert_equal_problem_data(method: Any) -> Any:
        ...
    def assert_equal_col_data(method: Any) -> Any:
        ...
    def assert_equal_row_data(method: Any) -> Any:
        ...
    def variable_upper_bound(self: Any, index: Any, value: Any = ...) -> Any:
        ...
    def variable_lower_bound(self: Any, index: Any, value: Any = ...) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
