from typing import Any

class GLPKExactBackend(GLPKBackend):
    def __cinit__(self: Any, maximization: Any = ...) -> Any:
        ...
    def add_variable(self: Any, lower_bound: Any = ..., upper_bound: Any = ..., binary: Any = ..., continuous: Any = ..., integer: Any = ..., obj: Any = ..., name: Any = ...) -> int:
        ...
    def add_variables(self: Any, number: Any, lower_bound: Any = ..., upper_bound: Any = ..., binary: Any = ..., continuous: Any = ..., integer: Any = ..., obj: Any = ..., names: Any = ...) -> int:
        ...
    def set_variable_type(self: Any, variable: Any, vtype: Any) -> Any:
        ...
