from typing import Any

class GLPKBackend(GenericBackend):
    def __cinit__(self: Any, maximization: Any = ...) -> Any:
        ...
    def add_variable(self: Any, lower_bound: Any = ..., upper_bound: Any = ..., binary: Any = ..., continuous: Any = ..., integer: Any = ..., obj: Any = ..., name: Any = ...) -> int:
        ...
    def add_variables(self: Any, number: Any, lower_bound: Any = ..., upper_bound: Any = ..., binary: Any = ..., continuous: Any = ..., integer: Any = ..., obj: Any = ..., names: Any = ...) -> int:
        ...
    def set_variable_type(self: Any, variable: Any, vtype: Any) -> Any:
        ...
    def set_sense(self: Any, sense: Any) -> Any:
        ...
    def objective_coefficient(self: Any, variable: Any, coeff: Any = ...) -> Any:
        ...
    def problem_name(self: Any, name: Any = ...) -> Any:
        ...
    def set_objective(self: Any, coeff: Any, d: Any = ...) -> Any:
        ...
    def set_verbosity(self: Any, level: Any) -> Any:
        ...
    def remove_constraint(self: Any, i: Any) -> Any:
        ...
    def remove_constraints(self: Any, constraints: Any) -> Any:
        ...
    def add_linear_constraint(self: Any, coefficients: Any, lower_bound: Any, upper_bound: Any, name: Any = ...) -> Any:
        ...
    def add_linear_constraints(self: Any, number: Any, lower_bound: Any, upper_bound: Any, names: Any = ...) -> Any:
        ...
    def row(self: Any, index: Any) -> Any:
        ...
    def row_bounds(self: Any, index: Any) -> Any:
        ...
    def col_bounds(self: Any, index: Any) -> Any:
        ...
    def add_col(self: Any, indices: Any, coeffs: Any) -> Any:
        ...
    def solve(self: Any) -> int:
        ...
    def get_objective_value(self: Any) -> Any:
        ...
    def best_known_objective_bound(self: Any) -> Any:
        ...
    def get_relative_objective_gap(self: Any) -> Any:
        ...
    def get_variable_value(self: Any, variable: Any) -> Any:
        ...
    def get_row_prim(self: Any, i: Any) -> Any:
        ...
    def col_name(self: Any, index: Any) -> Any:
        ...
    def row_name(self: Any, index: Any) -> Any:
        ...
    def variable_upper_bound(self: Any, index: Any, value: Any = ...) -> Any:
        ...
    def variable_lower_bound(self: Any, index: Any, value: Any = ...) -> Any:
        ...
    def write_lp(self: Any, filename: Any) -> Any:
        ...
    def write_mps(self: Any, filename: Any, modern: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
    def print_ranges(self: Any, filename: Any = ...) -> int:
        ...
    def set_row_stat(self: Any, i: Any, stat: Any) -> Any:
        ...
    def set_col_stat(self: Any, j: Any, stat: Any) -> Any:
        ...
    def eval_tab_row(self: Any, k: Any) -> Any:
        ...
    def eval_tab_col(self: Any, k: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
