from typing import Any

class GLPKGraphBackend:
    def __cinit__(self: Any, data: Any = ..., format: Any = ...) -> Any:
        ...
    def add_vertex(self: Any, name: Any = ...) -> Any:
        ...
    def __add_vertices_sage(self: Any, g: Any) -> Any:
        ...
    def add_vertices(self: Any, vertices: Any) -> List[Any]:
        ...
    def set_vertex_demand(self: Any, vertex: Any, demand: Any) -> Any:
        ...
    def set_vertices_demand(self: Any, pairs: Any) -> Any:
        ...
    def get_vertex(self: Any, vertex: Any) -> Dict[Any, Any]:
        ...
    def get_vertices(self: Any, verts: Any) -> Dict[Any, Any]:
        ...
    def vertices(self: Any) -> List[Any]:
        ...
    def add_edge(self: Any, u: Any, v: Any, params: Any = ...) -> Any:
        ...
    def add_edges(self: Any, edges: Any) -> List[Any]:
        ...
    def __add_edges_sage(self: Any, g: Any) -> Any:
        ...
    def get_edge(self: Any, u: Any, v: Any) -> Tuple[Any, ...]:
        ...
    def edges(self: Any) -> List[Any]:
        ...
    def delete_vertex(self: Any, vert: Any) -> Any:
        ...
    def delete_vertices(self: Any, verts: Any) -> Any:
        ...
    def delete_edge(self: Any, u: Any, v: Any, params: Any = ...) -> Any:
        ...
    def delete_edges(self: Any, edges: Any) -> Any:
        ...
    def mincost_okalg(self: Any) -> float:
        ...
    def write_maxflow(self: Any, fname: Any) -> int:
        ...
    def maxflow_ffalg(self: Any, u: Any = ..., v: Any = ...) -> float:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
