from typing import Any

class LinearTensor(ModuleElement):
    def __init__(self: Any, parent: Any, f: Any) -> Any:
        ...
    def __getitem__(self: Any, indices: Any) -> Any:
        ...
    def dict(self: Any) -> Any:
        ...
    def coefficient(self: Any, x: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
