from typing import Any

def is_LinearFunction(x: Any) -> Any:
    ...

def is_LinearConstraint(x: Any) -> Any:
    ...

def LinearFunctionsParent(base_ring: Any) -> Any:
    ...

def LinearConstraintsParent(linear_functions_parent: Any) -> Any:
    ...

class LinearFunctionOrConstraint(ModuleElement):
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class LinearFunctionsParent_class(Parent):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, base_ring: Any) -> Any:
        ...
    def set_multiplication_symbol(self: Any, symbol: Any = ...) -> Any:
        ...
    def tensor(self: Any, free_module: Any) -> Any:
        ...
    def gen(self: Any, i: Any) -> Any:
        ...

class LinearFunction(LinearFunctionOrConstraint):
    def __init__(self: Any, parent: Any, f: Any) -> Any:
        ...
    def iteritems(self: Any) -> Any:
        ...
    def dict(self: Any) -> Any:
        ...
    def coefficient(self: Any, x: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def equals(left: Any, right: Any) -> Any:
        ...

class LinearConstraintsParent_class(Parent):
    def __cinit__(self: Any, linear_functions_parent: Any) -> Any:
        ...
    def __init__(self: Any, linear_functions_parent: Any) -> Any:
        ...
    def linear_functions_parent(self: Any) -> Any:
        ...

class LinearConstraint(LinearFunctionOrConstraint):
    def __init__(self: Any, parent: Any, terms: Any, equality: Any = ...) -> Any:
        ...
    def equals(left: Any, right: Any) -> Any:
        ...
    def is_equation(self: Any) -> Any:
        ...
    def is_less_or_equal(self: Any) -> Any:
        ...
    def is_trivial(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def equations(self: Any) -> Any:
        ...
    def inequalities(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
