from typing import Any

class MixedIntegerLinearProgram(SageObject):
    def linear_functions_parent(self: Any) -> Any:
        ...
    def linear_constraints_parent(self: Any) -> Any:
        ...
    def plural(num: Any, noun: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def copying_solver() -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, v: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def set_problem_name(self: Any, name: Any) -> Any:
        ...
    def default_variable(self: Any) -> Any:
        ...
    def constraints(self: Any, indices: Any = ...) -> Any:
        ...
    def polyhedron(self: Any) -> Any:
        ...
    def show(self: Any) -> Any:
        ...
    def write_mps(self: Any, filename: Any, modern: Any = ...) -> Any:
        ...
    def write_lp(self: Any, filename: Any) -> Any:
        ...
    def get_values(self: Any, convert: Any = ..., tolerance: Any = ...) -> Any:
        ...
    def set_objective(self: Any, obj: Any) -> Any:
        ...
    def remove_constraint(self: Any, i: Any) -> Any:
        ...
    def remove_constraints(self: Any, constraints: Any) -> Any:
        ...
    def set_binary(self: Any, ee: Any) -> Any:
        ...
    def is_binary(self: Any, e: Any) -> Any:
        ...
    def set_integer(self: Any, ee: Any) -> Any:
        ...
    def is_integer(self: Any, e: Any) -> Any:
        ...
    def set_real(self: Any, ee: Any) -> Any:
        ...
    def is_real(self: Any, e: Any) -> Any:
        ...
    def solve(self: Any, log: Any = ..., objective_only: Any = ...) -> Any:
        ...
    def set_min(self: Any, v: Any, min: Any) -> Any:
        ...
    def set_max(self: Any, v: Any, max: Any) -> Any:
        ...
    def get_min(self: Any, v: Any) -> Any:
        ...
    def get_max(self: Any, v: Any) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
    def sum(self: Any, L: Any) -> Any:
        ...
    def get_backend(self: Any) -> Any:
        ...
    def get_objective_value(self: Any) -> Any:
        ...
    def best_known_objective_bound(self: Any) -> Any:
        ...
    def get_relative_objective_gap(self: Any) -> Any:
        ...
    def interactive_lp_problem(self: Any, form: Any = ...) -> Any:
        ...
    def get_obj_coef(i: Any) -> Any:
        ...
    def format(name: Any, prefix: Any, index: Any) -> Any:
        ...

class MIPSolverException(RuntimeError):
    ...

class MIPVariable(FiniteFamily):
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def copy_for_mip(self: Any, mip: Any) -> Any:
        ...
    def set_min(self: Any, min: Any) -> Any:
        ...
    def set_max(self: Any, max: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def values(self: Any) -> Any:
        ...
    def mip(self: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
