from typing import Any

class SemidefiniteProgram(SageObject):
    def linear_functions_parent(self: Any) -> Any:
        ...
    def linear_constraints_parent(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, v: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def set_problem_name(self: Any, name: Any) -> Any:
        ...
    def new_variable(self: Any, name: Any = ...) -> Any:
        ...
    def gen(self: Any, i: Any) -> Any:
        ...
    def show(self: Any) -> Any:
        ...
    def get_values(self: Any) -> Any:
        ...
    def set_objective(self: Any, obj: Any) -> Any:
        ...
    def add_constraint(self: Any, linear_function: Any, name: Any = ...) -> Any:
        ...
    def solve(self: Any, objective_only: Any = ...) -> Any:
        ...
    def dual_variable(self: Any, i: Any, sparse: Any = ...) -> Any:
        ...
    def slack(self: Any, i: Any, sparse: Any = ...) -> Any:
        ...
    def solver_parameter(self: Any, name: Any, value: Any = ...) -> Any:
        ...
    def sum(self: Any, L: Any) -> Any:
        ...
    def get_backend(self: Any) -> Any:
        ...

class SDPSolverException(RuntimeError):
    ...

class SDPVariable(Element):
    def __init__(self: Any, parent: Any, sdp: Any, name: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def values(self: Any) -> Any:
        ...

class SDPVariableParent(Parent):
    ...
