from typing import Any, Union, Optional
from sage.structure.parent import Parent
from sage.rings.integer import Integer
from sage.rings.infinity import PlusInfinity

def is_Group(x: Any) -> bool:
    ...

class Group(Parent):
    def __init__(self, base: Any = None, category: Any = None) -> None:
        ...
    def is_abelian(self) -> bool:
        ...
    def is_commutative(self) -> bool:
        ...
    def order(self) -> Union[Integer, PlusInfinity]:
        ...
    def cardinality(self) -> Union[Integer, PlusInfinity]:
        ...

class AbelianGroup(Group):
    def is_abelian(self) -> bool:
        ...

class FiniteGroup(Group):
    def order(self) -> Integer:
        ...
    def cardinality(self) -> Integer:
        ...
