from typing import Any

class ParentLibGAP(SageObject):
    def __init__(self: Any, libgap_parent: Any, ambient: Any = ...) -> Any:
        ...
    def ambient(self: Any) -> Any:
        ...
    def is_subgroup(self: Any) -> Any:
        ...
    def subgroup(self: Any, generators: Any) -> Any:
        ...
    def gap(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def minimal_normal_subgroups(self: Any) -> Any:
        ...
    def maximal_normal_subgroups(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any) -> Any:
        ...
    def one(self: Any) -> Any:
        ...

class ElementLibGAP(MultiplicativeGroupElement):
    def __init__(self: Any, parent: Any, libgap_element: Any) -> Any:
        ...
    def gap(self: Any) -> GapElement:
        ...
    def is_one(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, dummy: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def is_conjugate(self: Any, other: Any) -> Any:
        ...
    def normalizer(self: Any) -> Any:
        ...
    def nth_roots(self: Any, n: Any) -> Any:
        ...
