from typing import Any

def is_covering_array(array: Any, strength: Any = ..., levels: Any = ..., verbose: Any = ..., parameters: Any = ...) -> Any:
    ...

def is_orthogonal_array(OA: Any, k: Any, n: Any, t: Any = ..., verbose: Any = ..., terminology: Any = ...) -> Any:
    ...

def is_group_divisible_design(groups: Any, blocks: Any, v: Any, G: Any = ..., K: Any = ..., lambd: Any = ..., verbose: Any = ...) -> Any:
    ...

def is_pairwise_balanced_design(blocks: Any, v: Any, K: Any = ..., lambd: Any = ..., verbose: Any = ...) -> Any:
    ...

def is_projective_plane(blocks: Any, verbose: Any = ...) -> Any:
    ...

def is_difference_matrix(M: Any, G: Any, k: Any, lmbda: Any = ..., verbose: Any = ...) -> Any:
    ...

def is_quasi_difference_matrix(M: Any, G: Any, k: Any, lmbda: Any, mu: Any, u: Any, verbose: Any = ...) -> Any:
    ...
