from typing import Any

class EvenlyDistributedSetsBacktracker:
    def __init__(self: Any, K: Any, k: Any, up_to_isomorphism: Any = ..., check: Any = ...) -> Any:
        ...
    def to_difference_family(self: Any, B: Any, check: Any = ...) -> Any:
        ...
    def an_element(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def cardinality(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
