from typing import Any

def find_recursive_construction(k: Any, n: Any) -> Any:
    ...

def find_product_decomposition(k: Any, n: Any) -> Any:
    ...

def find_wilson_decomposition_with_one_truncated_group(k: Any, n: Any) -> Any:
    ...

def find_wilson_decomposition_with_two_truncated_groups(k: Any, n: Any) -> Any:
    ...

def find_construction_3_3(k: Any, n: Any) -> Any:
    ...

def find_construction_3_4(k: Any, n: Any) -> Any:
    ...

def find_construction_3_5(k: Any, n: Any) -> Any:
    ...

def find_construction_3_6(k: Any, n: Any) -> Any:
    ...

def find_q_x(k: Any, n: Any) -> Any:
    ...

def find_thwart_lemma_3_5(k: Any, N: Any) -> Any:
    ...

def find_thwart_lemma_4_1(k: Any, n: Any) -> Any:
    ...

def find_three_factor_product(k: Any, n: Any) -> Any:
    ...

def find_brouwer_separable_design(k: Any, n: Any) -> Any:
    ...

def int_as_sum(value: Any, S: Any, k_max: Any) -> Any:
    ...

def find_brouwer_van_rees_with_one_truncated_column(k: Any, n: Any) -> Any:
    ...
