from typing import Any

class SubHypergraphSearch:
    def __cinit__(self: Any, H1: Any, H2: Any, induced: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def relabel_heuristic(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
