from typing import Any, Union

def _fast_possible_periods(self: Any, return_points: bool = False) -> Union[list[int], list[tuple[Any, int]]]: ...

def _enum_points(prime: int, dimension: int) -> Any: ...

def _hash(Point: list[int], prime: int) -> int: ...

def _get_point_from_hash(value: int, prime: int, dimension: int) -> list[int]: ...

def _normalize_coordinates(point: list[int], prime: int, len_points: int) -> None: ...

def _all_periodic_points(self: Any) -> list[Any]: ...
