from typing import Any

class LaurentPolynomial_mpair(LaurentPolynomial):
    def __init__(self: Any, parent: Any, x: Any, mon: Any = ..., reduce: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def number_of_terms(self: Any) -> int:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, mod: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def iterator_exp_coeff(self: Any) -> Any:
        ...
    def monomials(self: Any) -> Any:
        ...
    def monomial_coefficient(self: Any, mon: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def coefficient(self: Any, mon: Any) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def variables(self: Any, sort: Any = ...) -> Any:
        ...
    def monomial_coefficients(self: Any) -> Dict[Any, Any]:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def degree(self: Any, x: Any = ...) -> Any:
        ...
    def valuation(self: Any, x: Any = ...) -> Any:
        ...
    def has_inverse_of(self: Any, i: Any) -> Any:
        ...
    def has_any_inverse(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def subs(self: Any, in_dict: Any = ...) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def is_univariate(self: Any) -> Any:
        ...
    def univariate_polynomial(self: Any, R: Any = ...) -> Any:
        ...
    def monomial_reduction(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def is_square(self: Any, root: Any = ...) -> Any:
        ...
    def rescale_vars(self: Any, d: Any, h: Any = ..., new_ring: Any = ...) -> Any:
        ...
    def toric_coordinate_change(self: Any, M: Any, h: Any = ..., new_ring: Any = ...) -> Any:
        ...
    def toric_substitute(self: Any, v: Any, v1: Any, a: Any, h: Any = ..., new_ring: Any = ...) -> Any:
        ...
    def divides(self: Any, other: Any) -> Any:
        ...
