from typing import Any

class LaurentPolynomial(CommutativeAlgebraElement):
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def number_of_terms(self: Any) -> int:
        ...
    def hamming_weight(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any) -> Dict[Any, Any]:
        ...
    def map_coefficients(self: Any, f: Any, new_base_ring: Any = ...) -> Any:
        ...

class LaurentPolynomial_univariate(LaurentPolynomial):
    def __init__(self: Any, parent: Any, f: Any, n: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def number_of_terms(self: Any) -> int:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def monomial_coefficients(self: Any) -> Dict[Any, Any]:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def __setitem__(self: Any, n: Any, value: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def __pow__(_self: Any, r: Any, mod: Any) -> Any:
        ...
    def shift(self: Any, k: Any) -> Any:
        ...
    def __lshift__(self: Any, k: Any) -> Any:
        ...
    def __rshift__(self: Any, k: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def inverse_of_unit(self: Any) -> Any:
        ...
    def xgcd(self: Any, other: Any) -> Any:
        ...
    def inverse_mod(a: Any, m: Any) -> Any:
        ...
    def gcd(self: Any, right: Any) -> Any:
        ...
    def euclidean_degree(self: Any) -> Any:
        ...
    def quo_rem(self: Any, other: Any) -> Any:
        ...
    def valuation(self: Any, p: Any = ...) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def variable_name(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def polynomial_construction(self: Any) -> Any:
        ...
    def monomial_reduction(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def is_square(self: Any, root: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def integral(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def residue(self: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def divides(self: Any, other: Any) -> Any:
        ...
