from typing import Any

def is_MPolynomialRing(x: Any) -> Any:
    ...

def unpickle_MPolynomialRing_generic_v1(base_ring: Any, n: Any, names: Any, order: Any) -> Any:
    ...

def unpickle_MPolynomialRing_generic(base_ring: Any, n: Any, names: Any, order: Any) -> Any:
    ...

class MPolynomialRing_base(CommutativeRing):
    def __init__(self: Any, base_ring: Any, n: Any, names: Any, order: Any) -> Any:
        ...
    def is_integral_domain(self: Any, proof: Any = ...) -> Any:
        ...
    def is_noetherian(self: Any) -> Any:
        ...
    def flattening_morphism(self: Any) -> Any:
        ...
    def construction(self: Any) -> Any:
        ...
    def irrelevant_ideal(self: Any) -> Any:
        ...
    def completion(self: Any, names: Any = ..., prec: Any = ..., extras: Any = ...) -> Any:
        ...
    def remove_var(self: Any, order: Any = ...) -> Any:
        ...
    def univariate_ring(self: Any, x: Any) -> Any:
        ...
    def interpolation(self: Any, bound: Any) -> Any:
        ...
    def sample_points(num_samples: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def repr_long(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> bool:
        ...
    def is_field(self: Any, proof: Any = ...) -> Any:
        ...
    def term_order(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def gen(self: Any, n: Any = ...) -> Any:
        ...
    def variable_names_recursive(self: Any, depth: Any = ...) -> Any:
        ...
    def krull_dimension(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def some_elements(self: Any) -> Any:
        ...
    def change_ring(self: Any, base_ring: Any = ..., names: Any = ..., order: Any = ...) -> Any:
        ...
    def monomial(self: Any) -> Any:
        ...
    def monomials_of_degree(self: Any, degree: Any) -> Any:
        ...
    def macaulay_resultant(self: Any) -> Any:
        ...
    def weyl_algebra(self: Any) -> Any:
        ...

class BooleanPolynomialRing_base(MPolynomialRing_base):
    ...
