from typing import Any, List, Dict, Tuple, Optional, Union
from sage.rings.polynomial.commutative_polynomial import CommutativePolynomial

def is_MPolynomial(x: Any) -> bool:
    ...

class MPolynomial(CommutativePolynomial):
    """Base class for multivariate polynomials."""
    
    def _scalar_conversion(self, R: Any) -> Any:
        ...
    
    def args(self) -> Tuple[Any, ...]:
        ...
    
    def variables(self) -> Tuple[Any, ...]:
        ...
    
    def variable(self, i: int) -> Any:
        ...
    
    def nvariables(self) -> int:
        ...
    
    def parent(self) -> Any:
        ...
    
    def is_univariate(self) -> bool:
        ...
    
    def is_multivariate(self) -> bool:
        ...
    
    def is_constant(self) -> bool:
        ...
    
    def is_monomial(self) -> bool:
        ...
    
    def is_term(self) -> bool:
        ...
    
    def is_homogeneous(self) -> bool:
        ...
    
    def total_degree(self) -> int:
        ...
    
    def degree(self, x: Optional[Any] = None) -> Union[int, Dict[Any, int]]:
        ...
    
    def degrees(self) -> Tuple[int, ...]:
        ...
    
    def monomial_coefficient(self, mon: Any) -> Any:
        ...
    
    def coefficient(self, degrees: Any) -> Any:
        ...
    
    def coefficients(self) -> List[Any]:
        ...
    
    def monomials(self) -> List['MPolynomial']:
        ...
    
    def exponents(self) -> List[Tuple[int, ...]]:
        ...
    
    def terms(self) -> List['MPolynomial']:
        ...
    
    def iterator_exp_coeff(self, as_ETuples: bool = True) -> Any:
        ...
    
    def dict(self) -> Dict[Tuple[int, ...], Any]:
        ...
    
    def leading_monomial(self, order: Optional[str] = None) -> 'MPolynomial':
        ...
    
    def leading_coefficient(self, order: Optional[str] = None) -> Any:
        ...
    
    def leading_term(self, order: Optional[str] = None) -> 'MPolynomial':
        ...
    
    def lm(self) -> 'MPolynomial':
        ...
    
    def lc(self) -> Any:
        ...
    
    def lt(self) -> 'MPolynomial':
        ...
    
    def derivative(self, *args: Any) -> 'MPolynomial':
        ...
    
    def integral(self, var: Any) -> 'MPolynomial':
        ...
    
    def subs(self, fixed: Optional[Dict[Any, Any]] = None, **kwds: Any) -> 'MPolynomial':
        ...
    
    def substitute(self, *args: Any, **kwds: Any) -> 'MPolynomial':
        ...
    
    def __call__(self, *args: Any, **kwds: Any) -> Any:
        ...
    
    def reduce(self, I: Any) -> 'MPolynomial':
        ...
    
    def lift(self, I: Any) -> List['MPolynomial']:
        ...
    
    def gcd(self, other: 'MPolynomial') -> 'MPolynomial':
        ...
    
    def lcm(self, other: 'MPolynomial') -> 'MPolynomial':
        ...
    
    def quo_rem(self, other: 'MPolynomial') -> Tuple['MPolynomial', 'MPolynomial']:
        ...
    
    def resultant(self, other: 'MPolynomial', variable: Any) -> 'MPolynomial':
        ...
    
    def sylvester_matrix(self, other: 'MPolynomial', variable: Any) -> Any:
        ...
    
    def factor(self, proof: Optional[bool] = None) -> Any:
        ...
    
    def content(self) -> Any:
        ...
    
    def primitive_part(self) -> 'MPolynomial':
        ...
    
    def is_squarefree(self) -> bool:
        ...
    
    def squarefree_decomposition(self) -> Any:
        ...
    
    def newton_polytope(self) -> Any:
        ...

class MPolynomial_libsingular(MPolynomial):
    """Multivariate polynomial implemented via libSINGULAR."""
    pass

def _is_M_convex_(points: List[Tuple[int, ...]]) -> bool:
    ...