from typing import Any

def is_MPolynomial(x: Any) -> Any:
    ...

class MPolynomial(CommutativePolynomial):
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def leading_support(self: Any) -> Any:
        ...
    def trailing_support(self: Any) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def truncate(self: Any, var: Any, n: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def polynomial(self: Any, var: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def args(self: Any) -> Any:
        ...
    def homogenize(self: Any, var: Any = ...) -> Any:
        ...
    def is_homogeneous(self: Any) -> Any:
        ...
    def homogeneous_components(self: Any) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def is_symmetric(self: Any, group: Any = ...) -> Any:
        ...
    def gradient(self: Any) -> Any:
        ...
    def jacobian_ideal(self: Any) -> Any:
        ...
    def newton_polytope(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def iterator_exp_coeff(self: Any, as_ETuples: Any = ...) -> Any:
        ...
    def content(self: Any) -> Any:
        ...
    def content_ideal(self: Any) -> Any:
        ...
    def is_gen(self: Any) -> Any:
        ...
    def map_coefficients(self: Any, f: Any, new_base_ring: Any = ...) -> Any:
        ...
    def sylvester_matrix(self: Any, right: Any, variable: Any = ...) -> Any:
        ...
    def discriminant(self: Any, variable: Any) -> Any:
        ...
    def subresultants(self: Any, other: Any, variable: Any = ...) -> Any:
        ...
    def macaulay_resultant(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def lift(self: Any, I: Any) -> Any:
        ...
    def inverse_mod(self: Any, I: Any) -> Any:
        ...
    def weighted_degree(self: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...
    def nth_root(self: Any, n: Any) -> Any:
        ...
    def is_square(self: Any, root: Any = ...) -> Any:
        ...
    def specialization(self: Any, D: Any = ..., phi: Any = ...) -> Any:
        ...
    def reduced_form(self: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def is_lorentzian(self: Any, explain: Any = ...) -> Any:
        ...
    def result(val: Any, explanation: Any = ...) -> Any:
        ...
    def crt(self: Any, y: Any, m: Any, n: Any) -> Any:
        ...
    def canonical_associate(self: Any) -> Any:
        ...

class MPolynomial_libsingular(MPolynomial):
    ...
