from typing import Any

def unpickle_MPolynomialRing_libsingular(base_ring: Any, names: Any, term_order: Any) -> Any:
    ...

def unpickle_MPolynomial_libsingular(R: Any, d: Any) -> Any:
    ...

class MPolynomialRing_libsingular(MPolynomialRing_base):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, base_ring: Any, n: Any, names: Any, order: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def gen(self: Any, n: Any = ...) -> Any:
        ...
    def ideal(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def cmp_key(x: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def monomial_quotient(self: Any, f: Any, g: Any, coeff: Any = ...) -> Any:
        ...
    def monomial_divides(self: Any, a: Any, b: Any) -> Any:
        ...
    def monomial_lcm(self: Any, f: Any, g: Any) -> Any:
        ...
    def monomial_reduce(self: Any, f: Any, G: Any) -> Any:
        ...
    def monomial_pairwise_prime(self: Any, g: Any, h: Any) -> Any:
        ...
    def monomial_all_divisors(self: Any, t: Any) -> Any:
        ...

class MPolynomial_libsingular(MPolynomial_libsingular_base):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, mod: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def degree(self: Any, x: Any = ..., std_grading: Any = ...) -> Any:
        ...
    def total_degree(self: Any, std_grading: Any = ...) -> Any:
        ...
    def degrees(self: Any) -> Any:
        ...
    def coefficient(self: Any, degrees: Any) -> Any:
        ...
    def monomial_coefficient(self: Any, mon: Any) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Any:
        ...
    def iterator_exp_coeff(self: Any, as_ETuples: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, x: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def exponents(self: Any, as_ETuples: Any = ...) -> Any:
        ...
    def inverse_of_unit(self: Any) -> Any:
        ...
    def is_homogeneous(self: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def is_term(self: Any) -> Any:
        ...
    def subs(self: Any, fixed: Any = ...) -> Any:
        ...
    def monomials(self: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def univariate_polynomial(self: Any, R: Any = ...) -> Any:
        ...
    def is_univariate(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def variable(self: Any, i: Any = ...) -> Any:
        ...
    def nvariables(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def lm(self: Any) -> Any:
        ...
    def lc(self: Any) -> Any:
        ...
    def lt(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def factor(self: Any, proof: Any = ...) -> Any:
        ...
    def lift(self: Any, I: Any) -> Any:
        ...
    def reduce(self: Any, I: Any) -> Any:
        ...
    def divides(self: Any, other: Any) -> Any:
        ...
    def gcd(self: Any, right: Any, algorithm: Any = ...) -> Any:
        ...
    def lcm(self: Any, g: Any) -> Any:
        ...
    def is_squarefree(self: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def sub_m_mul_q(self: Any, m: Any, q: Any) -> Any:
        ...
    def add_m_mul_q(self: Any, m: Any, q: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def integral(self: Any, var: Any) -> Any:
        ...
    def resultant(self: Any, other: Any, variable: Any = ...) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def global_height(self: Any, prec: Any = ...) -> Any:
        ...
    def local_height(self: Any, v: Any, prec: Any = ...) -> Any:
        ...
    def local_height_arch(self: Any, i: Any, prec: Any = ...) -> Any:
        ...
    def gradient(self: Any) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def in_subalgebra(self: Any, J: Any, algorithm: Any = ..., certificate: Any = ...) -> Any:
        ...
