from typing import Any

class OrePolynomial(AlgebraElement):
    def __init__(self: Any, parent: Any, construct: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Integer:
        ...
    def __setitem__(self: Any, n: Any, value: Any) -> Any:
        ...
    def square(self: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def leading_coefficient(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def is_monic(self: Any) -> Any:
        ...
    def left_monic(self: Any) -> Any:
        ...
    def right_monic(self: Any) -> Any:
        ...
    def is_left_divisible_by(self: Any, other: Any) -> Any:
        ...
    def is_right_divisible_by(self: Any, other: Any) -> Any:
        ...
    def left_divides(self: Any, other: Any) -> Any:
        ...
    def right_divides(self: Any, other: Any) -> Any:
        ...
    def left_xgcd(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def left_quo_rem(self: Any, other: Any) -> Any:
        ...
    def right_quo_rem(self: Any, other: Any) -> Any:
        ...
    def right_xgcd(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def right_gcd(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def left_gcd(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def left_xlcm(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def right_xlcm(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def left_lcm(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def right_lcm(self: Any, other: Any, monic: Any = ...) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __lshift__(self: Any, k: Any) -> Any:
        ...
    def __rshift__(self: Any, k: Any) -> Any:
        ...
    def change_variable_name(self: Any, var: Any) -> Any:
        ...
    def is_term(self: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def coefficients(self: Any, sparse: Any = ...) -> List[Any]:
        ...
    def number_of_terms(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def right_mod(self: Any, other: Any) -> Any:
        ...
    def left_mod(self: Any, other: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def prec(self: Any) -> Any:
        ...
    def padded_list(self: Any, n: Any = ...) -> Any:
        ...
    def variable_name(self: Any) -> Any:
        ...

class OrePolynomial_generic_dense(OrePolynomial):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., construct: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def monomial_coefficients(self: Any) -> Dict[Any, Any]:
        ...
    def degree(self: Any) -> Integer:
        ...
    def valuation(self: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def coefficients(self: Any, sparse: Any = ...) -> List[Any]:
        ...
    def hilbert_shift(self: Any, s: Any, var: Any = ...) -> Any:
        ...

class ConstantOrePolynomialSection(Map):
    ...

class OrePolynomialBaseringInjection(Morphism):
    def __init__(self: Any, domain: Any, codomain: Any) -> Any:
        ...
    def an_element(self: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
