from typing import Any

def unpickle_NCPolynomial_plural(R: Any, d: Any) -> Any:
    ...

def new_CRing(rw: Any, base_ring: Any) -> Any:
    ...

def new_NRing(rw: Any, base_ring: Any) -> Any:
    ...

def new_Ring(rw: Any, base_ring: Any) -> Any:
    ...

def SCA(base_ring: Any, names: Any, alt_vars: Any, order: Any = ...) -> Any:
    ...

def ExteriorAlgebra(base_ring: Any, names: Any, order: Any = ...) -> Any:
    ...

class G_AlgFactory(UniqueFactory):
    def create_object(self: Any, version: Any, key: Any) -> Any:
        ...

class NCPolynomialRing_plural(Ring):
    def __init__(self: Any, base_ring: Any, names: Any, c: Any, d: Any, order: Any, category: Any, check: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def free_algebra(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, _: Any) -> Any:
        ...
    def term_order(self: Any) -> Any:
        ...
    def relations(self: Any, add_commutative: Any = ...) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def gen(self: Any, n: Any = ...) -> Any:
        ...
    def algebra_generators(self: Any) -> Any:
        ...
    def ideal(self: Any) -> Any:
        ...
    def monomial_quotient(self: Any, f: Any, g: Any, coeff: Any = ...) -> Any:
        ...
    def monomial_divides(self: Any, a: Any, b: Any) -> Any:
        ...
    def monomial_lcm(self: Any, f: Any, g: Any) -> Any:
        ...
    def monomial_reduce(self: Any, f: Any, G: Any) -> Any:
        ...
    def monomial_pairwise_prime(self: Any, g: Any, h: Any) -> Any:
        ...
    def monomial_all_divisors(self: Any, t: Any) -> Any:
        ...

class NCPolynomial_plural(RingElement):
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, mod: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def reduce(self: Any, I: Any) -> Any:
        ...
    def degree(self: Any, x: Any = ...) -> Any:
        ...
    def total_degree(self: Any) -> Any:
        ...
    def degrees(self: Any) -> Any:
        ...
    def coefficient(self: Any, degrees: Any) -> Any:
        ...
    def monomial_coefficient(self: Any, mon: Any) -> Any:
        ...
    def dict(self: Any) -> Dict[Any, Any]:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Dict[Any, Any]:
        ...
    def __getitem__(self: Any, x: Any) -> Any:
        ...
    def exponents(self: Any, as_ETuples: Any = ...) -> Any:
        ...
    def is_homogeneous(self: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def monomials(self: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def lm(self: Any) -> Any:
        ...
    def lc(self: Any) -> Any:
        ...
    def lt(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
