from typing import Any, Optional, Iterator, List, Union
from sage.rings.polynomial.commutative_polynomial import CommutativePolynomial

def is_Polynomial(f: Any) -> bool:
    ...

def make_generic_polynomial(parent: Any, coeffs: List[Any]) -> 'Polynomial':
    ...

def universal_discriminant(n: int) -> 'Polynomial':
    ...

def generic_power_trunc(p: 'Polynomial', n: int, prec: int) -> 'Polynomial':
    ...

class PariError(Exception):
    ...

class Polynomial(CommutativePolynomial):
    def __init__(self, parent: Any, is_gen: bool = False, construct: bool = False) -> None:
        ...
    def is_zero(self) -> bool:
        ...
    def is_one(self) -> bool:
        ...
    def plot(self, xmin: Optional[float] = None, xmax: Optional[float] = None, **kwds: Any) -> Any:
        ...
    def subs(self, in_dict: Optional[dict] = None, **kwds: Any) -> Any:
        ...
    def __call__(self, *args: Any, **kwds: Any) -> Any:
        ...
    def compose_trunc(self, other: 'Polynomial', n: int) -> 'Polynomial':
        ...
    def __bool__(self) -> bool:
        ...
    def __getitem__(self, n: int) -> Any:
        ...
    def __iter__(self) -> Iterator[Any]:
        ...
    def __hash__(self) -> int:
        ...
    def __int__(self) -> int:
        ...
    def __float__(self) -> float:
        ...
    def __complex__(self) -> complex:
        ...
    def __invert__(self) -> 'Polynomial':
        ...
    def inverse_of_unit(self) -> 'Polynomial':
        ...
    def inverse_mod(a: Any, m: Any) -> Any:
        ...
    def inverse_series_trunc(self: Any, prec: Any) -> Any:
        ...
    def revert_series(self: Any, n: Any) -> Any:
        ...
    def multiplication_trunc(self: Any, other: Any, n: Any) -> Any:
        ...
    def square(self: Any) -> Any:
        ...
    def squarefree_decomposition(self: Any) -> Any:
        ...
    def is_square(self: Any, root: Any = ...) -> Any:
        ...
    def any_irreducible_factor(self: Any, degree: Any = ..., assume_squarefree: Any = ..., assume_equal_deg: Any = ..., ext_degree: Any = ...) -> Any:
        ...
    def any_root(self: Any, ring: Any = ..., degree: Any = ..., assume_squarefree: Any = ..., assume_equal_deg: Any = ...) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __pow__(left: Any, right: Any, modulus: Any) -> Any:
        ...
    def power_trunc(self: Any, n: Any, prec: Any) -> Any:
        ...
    def __setitem__(self: Any, n: Any, value: Any) -> Any:
        ...
    def __mod__(self: Any, other: Any) -> Any:
        ...
    def mod(self: Any, other: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def base_extend(self: Any, R: Any) -> Any:
        ...
    def change_variable_name(self: Any, var: Any) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def degree(self: Any, gen: Any = ...) -> Any:
        ...
    def euclidean_degree(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def gradient(self: Any) -> Any:
        ...
    def integral(self: Any, var: Any = ...) -> Any:
        ...
    def monomial_coefficients(self: Any, copy: Any = ...) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def splitting_field(self: Any, names: Any = ..., map: Any = ...) -> Any:
        ...
    def pseudo_quo_rem(self: Any, other: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...
    def lcm(self: Any, other: Any) -> Any:
        ...
    def is_primitive(self: Any, n: Any = ..., n_prime_divs: Any = ...) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def is_monomial(self: Any) -> Any:
        ...
    def is_term(self: Any) -> bool:
        ...
    def root_field(self: Any, names: Any, check_irreducible: Any = ...) -> Any:
        ...
    def sylvester_matrix(self: Any, right: Any, variable: Any = ...) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def is_monic(self: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def is_gen(self: Any) -> Any:
        ...
    def lc(self: Any) -> Any:
        ...
    def leading_coefficient(self: Any) -> Any:
        ...
    def canonical_associate(self: Any) -> Any:
        ...
    def lm(self: Any) -> Any:
        ...
    def lt(self: Any) -> Any:
        ...
    def monic(self: Any) -> Any:
        ...
    def coefficients(self: Any, sparse: Any = ...) -> Any:
        ...
    def global_height(self: Any, prec: Any = ...) -> Any:
        ...
    def local_height(self: Any, v: Any, prec: Any = ...) -> Any:
        ...
    def local_height_arch(self: Any, i: Any, prec: Any = ...) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def prec(self: Any) -> Any:
        ...
    def padded_list(self: Any, n: Any = ...) -> Any:
        ...
    def monomial_coefficient(self: Any, m: Any) -> Any:
        ...
    def monomials(self: Any) -> Any:
        ...
    def newton_raphson(self: Any, n: Any, x0: Any) -> Any:
        ...
    def polynomial(self: Any, var: Any) -> Any:
        ...
    def newton_slopes(self: Any, p: Any, lengths: Any = ...) -> Any:
        ...
    def dispersion_set(self: Any, other: Any = ...) -> Any:
        ...
    def dispersion(self: Any, other: Any = ...) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def resultant(self: Any, other: Any) -> Any:
        ...
    def subresultants(self: Any, other: Any) -> Any:
        ...
    def composed_op(p1: Any, p2: Any, op: Any, algorithm: Any = ..., monic: Any = ...) -> Any:
        ...
    def compose_power(self: Any, k: Any, algorithm: Any = ..., monic: Any = ...) -> Any:
        ...
    def adams_operator_on_roots(self: Any, n: Any, monic: Any = ...) -> Any:
        ...
    def symmetric_power(self: Any, k: Any, monic: Any = ...) -> Any:
        ...
    def star(g: Any, h: Any) -> Any:
        ...
    def rpow(g: Any, n: Any) -> Any:
        ...
    def discriminant(self: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def roots(self: Any, ring: Any = ..., multiplicities: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def real_roots(self: Any) -> Any:
        ...
    def complex_roots(self: Any) -> Any:
        ...
    def number_of_roots_in_interval(self: Any, a: Any = ..., b: Any = ...) -> Any:
        ...
    def number_of_real_roots(self: Any) -> Any:
        ...
    def all_roots_in_interval(self: Any, a: Any = ..., b: Any = ...) -> Any:
        ...
    def is_real_rooted(self: Any) -> Any:
        ...
    def reciprocal_transform(self: Any, R: Any = ..., q: Any = ...) -> Any:
        ...
    def trace_polynomial(self: Any) -> Any:
        ...
    def is_weil_polynomial(self: Any, return_q: Any = ...) -> Any:
        ...
    def is_lorentzian(self: Any, explain: Any = ...) -> Any:
        ...
    def variable_name(self: Any) -> Any:
        ...
    def xgcd(self: Any, other: Any) -> Any:
        ...
    def rational_reconstruction(self: Any, m: Any, n_deg: Any = ..., d_deg: Any = ...) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def args(self: Any) -> Any:
        ...
    def valuation(self: Any, p: Any = ...) -> Any:
        ...
    def ord(self: Any, p: Any = ...) -> Any:
        ...
    def add_bigoh(self: Any, prec: Any) -> Any:
        ...
    def is_irreducible(self: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __lshift__(self: Any, k: Any) -> Any:
        ...
    def __rshift__(self: Any, k: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def is_squarefree(self: Any) -> Any:
        ...
    def radical(self: Any) -> Any:
        ...
    def content_ideal(self: Any) -> Any:
        ...
    def norm(self: Any, p: Any) -> Any:
        ...
    def map_coefficients(self: Any, f: Any, new_base_ring: Any = ...) -> Any:
        ...
    def is_cyclotomic(self: Any, certificate: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def is_cyclotomic_product(self: Any) -> Any:
        ...
    def cyclotomic_part(self: Any) -> Any:
        ...
    def homogenize(self: Any, var: Any = ...) -> Any:
        ...
    def is_homogeneous(self: Any) -> Any:
        ...
    def nth_root(self: Any, n: Any) -> Any:
        ...
    def divides(self: Any, p: Any) -> Any:
        ...
    def specialization(self: Any, D: Any = ..., phi: Any = ...) -> Any:
        ...

class Polynomial_generic_dense(Polynomial):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_term(self: Any) -> bool:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def constant_coefficient(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def degree(self: Any, gen: Any = ...) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def quo_rem(self: Any, other: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...

class Polynomial_generic_dense_inexact(Polynomial_generic_dense):
    def degree(self: Any, secure: Any = ...) -> Any:
        ...
    def prec_degree(self: Any) -> Any:
        ...

class ConstantPolynomialSection(Map):
    ...

class PolynomialBaseringInjection(Morphism):
    def __init__(self: Any, domain: Any, codomain: Any) -> Any:
        ...
    def section(self: Any) -> Any:
        ...
    def is_injective(self: Any) -> Any:
        ...
    def is_surjective(self: Any) -> Any:
        ...
