from typing import Any

class Polynomial_complex_arb(Polynomial):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def quo_rem(self: Any, divisor: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def __lshift__(val: Any, n: Any) -> Any:
        ...
    def __rshift__(val: Any, n: Any) -> Any:
        ...
    def inverse_series_trunc(self: Any, n: Any) -> Any:
        ...
    def compose_trunc(self: Any, other: Any, n: Any) -> Any:
        ...
    def revert_series(self: Any, n: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
