from typing import Any

def make_element(parent: Any, args: Any) -> Any:
    ...

def small_roots(self: Any, X: Any = ..., beta: Any = ..., epsilon: Any = ...) -> Any:
    ...

class Polynomial_dense_mod_n(Polynomial):
    def __reduce__(self: Any) -> Any:
        ...
    def int_list(self: Any) -> Any:
        ...
    def __pari__(self: Any, variable: Any = ...) -> Any:
        ...
    def ntl_ZZ_pX(self: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def degree(self: Any, gen: Any = ...) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def ntl_set_directly(self: Any, v: Any) -> Any:
        ...
    def minpoly_mod(self: Any, other: Any) -> Any:
        ...
    def small_roots(self: Any) -> Any:
        ...
    def compose_mod(self: Any, other: Any, modulus: Any) -> Any:
        ...

class Polynomial_dense_modn_ntl_zz(Polynomial_dense_mod_n):
    def __init__(self: Any, parent: Any, v: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def ntl_set_directly(self: Any, v: Any) -> Any:
        ...
    def int_list(self: Any) -> Any:
        ...
    def __pow__(self: Any, ee: Any, modulus: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def is_gen(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...

class Polynomial_dense_modn_ntl_ZZ(Polynomial_dense_mod_n):
    def __init__(self: Any, parent: Any, v: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def __pow__(self: Any, ee: Any, modulus: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def is_gen(self: Any) -> Any:
        ...
    def valuation(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...

class Polynomial_dense_mod_p(Polynomial_dense_mod_n):
    def __pow__(self: Any, n: Any, modulus: Any) -> Any:
        ...
    def gcd(self: Any, right: Any) -> Any:
        ...
    def xgcd(self: Any, other: Any) -> Any:
        ...
    def resultant(self: Any, other: Any) -> Any:
        ...
    def discriminant(self: Any) -> Any:
        ...
