from typing import Any

class Polynomial_integer_dense_ntl(Polynomial):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def content(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def gcd(self: Any, right: Any) -> Any:
        ...
    def lcm(self: Any, right: Any) -> Any:
        ...
    def xgcd(self: Any, right: Any) -> Any:
        ...
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def real_root_intervals(self: Any) -> Any:
        ...
    def degree(self: Any, gen: Any = ...) -> Any:
        ...
    def discriminant(self: Any, proof: Any = ...) -> Any:
        ...
    def __pari__(self: Any, variable: Any = ...) -> Any:
        ...
    def squarefree_decomposition(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def factor_mod(self: Any, p: Any) -> Any:
        ...
    def factor_padic(self: Any, p: Any, prec: Any = ...) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def resultant(self: Any, other: Any, proof: Any = ...) -> Any:
        ...
