from typing import Any

class Polynomial_integer_dense_flint(Polynomial):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def content(self: Any) -> Integer:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def is_zero(self: Any) -> bool:
        ...
    def is_one(self: Any) -> bool:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def gcd(self: Any, right: Any) -> Any:
        ...
    def lcm(self: Any, right: Any) -> Any:
        ...
    def xgcd(self: Any, right: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, mod: Any) -> Any:
        ...
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def inverse_series_trunc(self: Any, prec: Any) -> Any:
        ...
    def real_root_intervals(self: Any) -> Any:
        ...
    def degree(self: Any, gen: Any = ...) -> Any:
        ...
    def pseudo_divrem(self: Any, B: Any) -> Any:
        ...
    def discriminant(self: Any, proof: Any = ...) -> Any:
        ...
    def __pari__(self: Any, variable: Any = ...) -> Any:
        ...
    def squarefree_decomposition(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def factor_mod(self: Any, p: Any) -> Any:
        ...
    def factor_padic(self: Any, p: Any, prec: Any = ...) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def resultant(self: Any, other: Any, proof: Any = ...) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def revert_series(self: Any, n: Any) -> Any:
        ...
