from typing import Any

def monomial_exponent(p: Any) -> Any:
    ...

def make_PolyDict(data: Any) -> Any:
    ...

def make_ETuple(data: Any, length: Any) -> Any:
    ...

class PolyDict:
    def __init__(self: Any, pdict: Any, zero: Any = ..., remove_zero: Any = ..., force_int_exponents: Any = ..., force_etuples: Any = ..., check: Any = ...) -> Any:
        ...
    def remove_zeros(self: Any, zero_test: Any = ...) -> Any:
        ...
    def apply_map(self: Any, f: Any) -> Any:
        ...
    def coerce_coefficients(self: Any, A: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def rich_compare(self: Any, other: Any, op: Any, sortkey: Any = ...) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def dict(self: Any) -> Any:
        ...
    def coefficients(self: Any) -> Any:
        ...
    def exponents(self: Any) -> Any:
        ...
    def __getitem__(self: Any, e: Any) -> Any:
        ...
    def get(self: Any, e: Any, default: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def degree(self: Any, x: Any = ...) -> Any:
        ...
    def total_degree(self: Any, w: Any = ...) -> Any:
        ...
    def monomial_coefficient(self: Any, mon: Any) -> Any:
        ...
    def polynomial_coefficient(self: Any, degrees: Any) -> Any:
        ...
    def coefficient(self: Any, mon: Any) -> Any:
        ...
    def is_homogeneous(self: Any, w: Any = ...) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def homogenize(self: Any, var: Any) -> Any:
        ...
    def __iadd__(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, right: Any) -> Any:
        ...
    def scalar_rmult(self: Any, s: Any) -> Any:
        ...
    def scalar_lmult(self: Any, s: Any) -> Any:
        ...
    def term_lmult(self: Any, exponent: Any, s: Any) -> Any:
        ...
    def term_rmult(self: Any, exponent: Any, s: Any) -> Any:
        ...
    def __sub__(self: Any, other: Any) -> Any:
        ...
    def derivative_i(self: Any, i: Any) -> Any:
        ...
    def derivative(self: Any, x: Any) -> Any:
        ...
    def integral_i(self: Any, i: Any) -> Any:
        ...
    def integral(self: Any, x: Any) -> Any:
        ...
    def lcmt(self: Any, greater_etuple: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def min_exp(self: Any) -> Any:
        ...
    def max_exp(self: Any) -> Any:
        ...

class ETuple:
    def __init__(self: Any, data: Any = ..., length: Any = ...) -> Any:
        ...
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, factor: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __contains__(self: Any, elem: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def unweighted_degree(self: Any) -> int:
        ...
    def weighted_degree(self: Any, w: Any) -> int:
        ...
    def unweighted_quotient_degree(self: Any, other: Any) -> int:
        ...
    def weighted_quotient_degree(self: Any, other: Any, w: Any) -> int:
        ...
    def eadd(self: Any, other: Any) -> Any:
        ...
    def eadd_p(self: Any, other: Any, pos: Any) -> Any:
        ...
    def eadd_scaled(self: Any, other: Any, scalar: Any) -> Any:
        ...
    def esub(self: Any, other: Any) -> Any:
        ...
    def emul(self: Any, factor: Any) -> Any:
        ...
    def emax(self: Any, other: Any) -> Any:
        ...
    def emin(self: Any, other: Any) -> Any:
        ...
    def dotprod(self: Any, other: Any) -> int:
        ...
    def escalar_div(self: Any, n: Any) -> Any:
        ...
    def divide_by_gcd(self: Any, other: Any) -> Any:
        ...
    def divide_by_var(self: Any, pos: Any) -> Any:
        ...
    def divides(self: Any, other: Any) -> bool:
        ...
    def is_multiple_of(self: Any, n: Any) -> bool:
        ...
    def nonzero_positions(self: Any, sort: Any = ...) -> List[Any]:
        ...
    def common_nonzero_positions(self: Any, other: Any, sort: Any = ...) -> Any:
        ...
    def nonzero_values(self: Any, sort: Any = ...) -> List[Any]:
        ...
    def reversed(self: Any) -> Any:
        ...
    def sparse_iter(self: Any) -> Any:
        ...
    def combine_to_positives(self: Any, other: Any) -> Any:
        ...
