from typing import Any

def GF2X_BuildIrred_list(n: Any) -> Any:
    ...

def GF2X_BuildSparseIrred_list(n: Any) -> Any:
    ...

def GF2X_BuildRandomIrred_list(n: Any) -> Any:
    ...

class Polynomial_GF2X(Polynomial_template):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __pari__(self: Any, variable: Any = ...) -> Any:
        ...
    def modular_composition(self: Any, g: Any, h: Any, algorithm: Any = ...) -> Any:
        ...
    def is_irreducible(self: Any) -> Any:
        ...
