from typing import Any

def make_PolynomialRealDense(parent: Any, data: Any) -> Any:
    ...

class PolynomialRealDense(Polynomial):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def truncate_abs(self: Any, bound: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def integral(self: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def quo_rem(self: Any, other: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
