from typing import Any

class Polynomial_ZZ_pEX(Polynomial_template):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def __call__(self: Any) -> Any:
        ...
    def resultant(self: Any, other: Any) -> Any:
        ...
    def is_irreducible(self: Any, algorithm: Any = ..., iter: Any = ...) -> Any:
        ...
    def minpoly_mod(self: Any, other: Any) -> Any:
        ...
    def shift(self: Any, n: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def inverse_series_trunc(self: Any, prec: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, modulus: Any) -> Any:
        ...
    def compose_mod(self: Any, other: Any, modulus: Any) -> Any:
        ...
