from typing import Any

class Polynomial_zmod_flint(Polynomial_template):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def resultant(self: Any, other: Any) -> Any:
        ...
    def small_roots(self: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, modulus: Any) -> Any:
        ...
    def rational_reconstruction(self: Any, m: Any, n_deg: Any = ..., d_deg: Any = ...) -> Any:
        ...
    def is_irreducible(self: Any) -> Any:
        ...
    def squarefree_decomposition(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def monic(self: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def revert_series(self: Any, n: Any) -> Any:
        ...
    def minpoly_mod(self: Any, other: Any) -> Any:
        ...
    def compose_mod(self: Any, other: Any, modulus: Any) -> Any:
        ...
