from typing import Any

class Polynomial_rational_flint(Polynomial):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., is_gen: Any = ..., construct: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def list(self: Any, copy: Any = ...) -> List[Any]:
        ...
    def degree(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def truncate(self: Any, n: Any) -> Any:
        ...
    def reverse(self: Any, degree: Any = ...) -> Any:
        ...
    def revert_series(self: Any, n: Any) -> Any:
        ...
    def is_zero(self: Any) -> bool:
        ...
    def is_one(self: Any) -> bool:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __lshift__(self: Any, n: Any) -> Any:
        ...
    def __rshift__(self: Any, n: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def gcd(self: Any, right: Any) -> Any:
        ...
    def lcm(self: Any, right: Any) -> Any:
        ...
    def xgcd(self: Any, right: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, mod: Any) -> Any:
        ...
    def __floordiv__(self: Any, right: Any) -> Any:
        ...
    def inverse_series_trunc(self: Any, prec: Any) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def real_root_intervals(self: Any) -> Any:
        ...
    def resultant(self: Any, right: Any) -> Any:
        ...
    def is_irreducible(self: Any) -> Any:
        ...
    def galois_group(self: Any, pari_group: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def factor_mod(self: Any, p: Any) -> Any:
        ...
    def factor_padic(self: Any, p: Any, prec: Any = ...) -> Any:
        ...
    def hensel_lift(self: Any, p: Any, e: Any) -> Any:
        ...
    def discriminant(self: Any) -> Any:
        ...
    def galois_group_davenport_smith_test(self: Any, num_trials: Any = ..., assume_irreducible: Any = ...) -> Any:
        ...
