from typing import Any

def de_casteljau_intvec(c: Any, c_bitsize: Any, x: Any, use_ints: Any) -> Any:
    ...

def intvec_to_doublevec(b: Any, err: Any) -> Any:
    ...

def de_casteljau_doublevec(c: Any, x: Any) -> Any:
    ...

def max_abs_doublevec(c: Any) -> Any:
    ...

def wordsize_rational(a: Any, b: Any, wordsize: Any) -> Any:
    ...

def relative_bounds(a: Any, b: Any) -> Any:
    ...

def bitsize_doctest(n: Any) -> Any:
    ...

def degree_reduction_next_size(n: Any) -> Any:
    ...

def precompute_degree_reduction_cache(n: Any) -> Any:
    ...

def bernstein_down(d1: Any, d2: Any, s: Any) -> Any:
    ...

def pseudoinverse(m: Any) -> Any:
    ...

def bernstein_up(d1: Any, d2: Any, s: Any = ...) -> Any:
    ...

def subsample_vec_doctest(a: Any, slen: Any, llen: Any) -> Any:
    ...

def maximum_root_first_lambda(p: Any) -> Any:
    ...

def cl_maximum_root_first_lambda(cl: Any) -> Any:
    ...

def maximum_root_local_max(p: Any) -> Any:
    ...

def cl_maximum_root_local_max(cl: Any) -> Any:
    ...

def cl_maximum_root(cl: Any) -> Any:
    ...

def root_bounds(p: Any) -> Any:
    ...

def rational_root_bounds(p: Any) -> Any:
    ...

def split_for_targets(ctx: Any, bp: Any, target_list: Any, precise: Any = ...) -> Any:
    ...

def real_roots(p: Any, bounds: Any = ..., seed: Any = ..., skip_squarefree: Any = ..., do_logging: Any = ..., wordsize: Any = ..., retval: Any = ..., strategy: Any = ..., max_diameter: Any = ...) -> Any:
    ...

def scale_intvec_var(c: Any, k: Any) -> Any:
    ...

def taylor_shift1_intvec(c: Any) -> Any:
    ...

def reverse_intvec(c: Any) -> Any:
    ...

def get_realfield_rndu(n: Any) -> Any:
    ...

def mk_context(do_logging: Any = ..., seed: Any = ..., wordsize: Any = ...) -> Any:
    ...

def to_bernstein(p: Any, low: Any = ..., high: Any = ..., degree: Any = ...) -> Any:
    ...

def to_bernstein_warp(p: Any) -> Any:
    ...

def bernstein_expand(c: Any, d2: Any) -> Any:
    ...

def max_bitsize_intvec_doctest(b: Any) -> Any:
    ...

def dprod_imatrow_vec(m: Any, v: Any, k: Any) -> Any:
    ...

def min_max_delta_intvec(a: Any, b: Any) -> Any:
    ...

def min_max_diff_intvec(b: Any) -> Any:
    ...

def min_max_diff_doublevec(c: Any) -> Any:
    ...

class interval_bernstein_polynomial:
    def variations(self: Any) -> Any:
        ...
    def try_split(self: Any, ctx: Any, logging_note: Any) -> Any:
        ...
    def try_rand_split(self: Any, ctx: Any, logging_note: Any) -> Any:
        ...
    def region(self: Any) -> Any:
        ...
    def region_width(self: Any) -> Any:
        ...

class interval_bernstein_polynomial_integer(interval_bernstein_polynomial):
    def __init__(self: Any, coeffs: Any, lower: Any, upper: Any, lsign: Any, usign: Any, error: Any, scale_log2: Any, level: Any, slope_err: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def de_casteljau(self: Any, ctx: Any, mid: Any, msign: Any = ...) -> Any:
        ...
    def as_float(self: Any) -> Any:
        ...
    def get_msb_bit(self: Any) -> Any:
        ...
    def down_degree(self: Any, ctx: Any, max_err: Any, exp_err_shift: Any) -> Any:
        ...
    def down_degree_iter(self: Any, ctx: Any, max_scale: Any) -> Any:
        ...
    def downscale(self: Any, bits: Any) -> Any:
        ...
    def slope_range(self: Any) -> Any:
        ...

class interval_bernstein_polynomial_float(interval_bernstein_polynomial):
    def __init__(self: Any, coeffs: Any, lower: Any, upper: Any, lsign: Any, usign: Any, neg_err: Any, pos_err: Any, scale_log2: Any, level: Any, slope_err: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def de_casteljau(self: Any, ctx: Any, mid: Any, msign: Any = ...) -> Any:
        ...
    def as_float(self: Any) -> Any:
        ...
    def get_msb_bit(self: Any) -> Any:
        ...
    def slope_range(self: Any) -> Any:
        ...

class PrecisionError(ValueError):
    ...

class bernstein_polynomial_factory:
    def lsign(self: Any) -> Any:
        ...
    def usign(self: Any) -> Any:
        ...

class bernstein_polynomial_factory_intlist(bernstein_polynomial_factory):
    def __init__(self: Any, coeffs: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def coeffs_bitsize(self: Any) -> Any:
        ...
    def bernstein_polynomial(self: Any, scale_log2: Any) -> Any:
        ...

class bernstein_polynomial_factory_ratlist(bernstein_polynomial_factory):
    def __init__(self: Any, coeffs: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def coeffs_bitsize(self: Any) -> Any:
        ...
    def bernstein_polynomial(self: Any, scale_log2: Any) -> Any:
        ...

class bernstein_polynomial_factory_ar(bernstein_polynomial_factory):
    def __init__(self: Any, poly: Any, neg: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def coeffs_bitsize(self: Any) -> Any:
        ...
    def bernstein_polynomial(self: Any, scale_log2: Any) -> Any:
        ...

class ocean:
    def __init__(self: Any, ctx: Any, bpf: Any, mapping: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def approx_bp(self: Any, scale_log2: Any) -> Any:
        ...
    def find_roots(self: Any) -> Any:
        ...
    def roots(self: Any) -> Any:
        ...
    def refine_all(self: Any) -> Any:
        ...
    def all_done(self: Any) -> Any:
        ...
    def reset_root_width(self: Any, isle_num: Any, target_width: Any) -> Any:
        ...
    def increase_precision(self: Any) -> Any:
        ...

class island:
    def __init__(self: Any, bp: Any, lgap: Any, rgap: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def shrink_bp(self: Any, ctx: Any) -> Any:
        ...
    def refine(self: Any, ctx: Any) -> Any:
        ...
    def refine_recurse(self: Any, ctx: Any, bp: Any, ancestors: Any, history: Any, rightmost: Any) -> Any:
        ...
    def less_bits(self: Any, ancestors: Any, bp: Any) -> Any:
        ...
    def more_bits(self: Any, ctx: Any, ancestors: Any, bp: Any, rightmost: Any) -> Any:
        ...
    def reset_root_width(self: Any, target_width: Any) -> Any:
        ...
    def bp_done(self: Any, bp: Any) -> Any:
        ...
    def done(self: Any, ctx: Any) -> Any:
        ...

class rr_gap:
    def __init__(self: Any, lower: Any, upper: Any, sign: Any) -> Any:
        ...
    def region(self: Any) -> Any:
        ...

class linear_map:
    def __init__(self: Any, lower: Any, upper: Any) -> Any:
        ...
    def from_ocean(self: Any, region: Any) -> Any:
        ...
    def to_ocean(self: Any, region: Any) -> Any:
        ...

class warp_map:
    def __init__(self: Any, neg: Any) -> Any:
        ...
    def from_ocean(self: Any, region: Any) -> Any:
        ...
    def to_ocean(self: Any, region: Any) -> Any:
        ...

class context:
    def __init__(self: Any, do_logging: Any, seed: Any, wordsize: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def get_dc_log(self: Any) -> Any:
        ...
    def get_be_log(self: Any) -> Any:
        ...
