from typing import Any

class SkewPolynomial_generic_dense(OrePolynomial_generic_dense):
    def left_power_mod(self: Any, exp: Any, modulus: Any) -> Any:
        ...
    def right_power_mod(self: Any, exp: Any, modulus: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, modulus: Any) -> Any:
        ...
    def __call__(self: Any, eval_pt: Any) -> Any:
        ...
    def operator_eval(self: Any, eval_pt: Any) -> Any:
        ...
    def conjugate(self: Any, n: Any) -> Any:
        ...
    def multi_point_evaluation(self: Any, eval_pts: Any) -> Any:
        ...
