from typing import Any

class SkewPolynomial_finite_field_dense(SkewPolynomial_finite_order_dense):
    def is_irreducible(self: Any) -> Any:
        ...
    def type(self: Any, N: Any) -> Any:
        ...
    def right_irreducible_divisor(self: Any, uniform: Any = ...) -> Any:
        ...
    def left_irreducible_divisor(self: Any, uniform: Any = ...) -> Any:
        ...
    def right_irreducible_divisors(self: Any) -> Any:
        ...
    def left_irreducible_divisors(self: Any) -> Any:
        ...
    def count_irreducible_divisors(self: Any) -> Any:
        ...
    def factor(self: Any, uniform: Any = ...) -> Any:
        ...
    def count_factorizations(self: Any) -> Any:
        ...
    def factorizations(self: Any) -> Any:
        ...
    def factorizations_rec(P: Any) -> Any:
        ...
