from typing import Any

class SkewPolynomial_finite_order_dense(SkewPolynomial_generic_dense):
    def __init__(self: Any, parent: Any, x: Any = ..., check: Any = ..., construct: Any = ...) -> Any:
        ...
    def reduced_trace(self: Any, var: Any = ...) -> Any:
        ...
    def reduced_norm(self: Any, var: Any = ...) -> Any:
        ...
    def reduced_charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def bound(self: Any) -> Any:
        ...
    def optimal_bound(self: Any) -> Any:
        ...
