from typing import Any

class SymmetricReductionStrategy:
    def __init__(self: Any, Parent: Any, L: Any = ..., tailreduce: Any = ..., good_input: Any = ...) -> Any:
        ...
    def __getinitargs__(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, L: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def setgens(self: Any, L: Any) -> Any:
        ...
    def reset(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __call__(self: Any, p: Any) -> Any:
        ...
    def add_generator(self: Any, p: Any, good_input: Any = ...) -> Any:
        ...
    def reduce(self: Any, p: Any, notail: Any = ..., report: Any = ...) -> Any:
        ...
    def tailreduce(self: Any, p: Any, report: Any = ...) -> Any:
        ...
