from typing import Any

def random_tests(n: Any = ..., nrows_max: Any = ..., ncols_max: Any = ..., nsymbols_max: Any = ..., perms_per_matrix: Any = ..., density_range: Any = ...) -> Any:
    ...

class MatrixStruct:
    def __cinit__(self: Any, matrix: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def display(self: Any) -> Any:
        ...
    def run(self: Any, partition: Any = ...) -> Any:
        ...
    def automorphism_group(self: Any) -> Any:
        ...
    def canonical_relabeling(self: Any) -> Any:
        ...
    def is_isomorphic(self: Any, other: Any) -> Any:
        ...
