from typing import Any

def random_tests(num: Any = ..., n_max: Any = ..., k_max: Any = ..., nwords_max: Any = ..., perms_per_code: Any = ..., density_range: Any = ...) -> Any:
    ...

class LinearBinaryCodeStruct(BinaryCodeStruct):
    def __cinit__(self: Any, matrix: Any) -> Any:
        ...
    def run(self: Any, partition: Any = ...) -> Any:
        ...
    def automorphism_group(self: Any) -> Any:
        ...
    def canonical_relabeling(self: Any) -> Any:
        ...
    def is_isomorphic(self: Any, other: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class NonlinearBinaryCodeStruct(BinaryCodeStruct):
    def __cinit__(self: Any, arg: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def run(self: Any, partition: Any = ...) -> Any:
        ...
    def automorphism_group(self: Any) -> Any:
        ...
    def canonical_relabeling(self: Any) -> Any:
        ...
    def is_isomorphic(self: Any, other: Any) -> Any:
        ...
