from typing import Any

class PythonPartitionStack:
    def __init__(self: Any, n: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def display(self: Any) -> Any:
        ...
    def is_discrete(self: Any) -> Any:
        ...
    def num_cells(self: Any) -> Any:
        ...
    def move_min_to_front(self: Any, start: Any, end: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def clear(self: Any) -> Any:
        ...
    def entries(self: Any) -> Any:
        ...
    def set_entry(self: Any, i: Any, entry: Any) -> Any:
        ...
    def get_entry(self: Any, i: Any) -> Any:
        ...
    def levels(self: Any) -> Any:
        ...
    def set_level(self: Any, i: Any, level: Any) -> Any:
        ...
    def get_level(self: Any, i: Any) -> Any:
        ...
    def depth(self: Any, new: Any = ...) -> Any:
        ...
    def degree(self: Any, new: Any = ...) -> Any:
        ...
    def partition(self: Any, k: Any) -> Any:
        ...

class PythonObjectWrapper:
    def __init__(self: Any, obj: Any, acae_fn: Any, rari_fn: Any, cs_fn: Any, degree: Any) -> Any:
        ...
