from typing import Any

class ArithmeticSubgroupElement(MultiplicativeGroupElement):
    def __init__(self: Any, parent: Any, x: Any, check: Any = ...) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def det(self: Any) -> Any:
        ...
    def a(self: Any) -> Any:
        ...
    def b(self: Any) -> Any:
        ...
    def c(self: Any) -> Any:
        ...
    def d(self: Any) -> Any:
        ...
    def acton(self: Any, z: Any) -> Any:
        ...
    def __getitem__(self: Any, q: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
