from typing import Any

class Farey:
    def __cinit__(self: Any, group: Any, data: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def pairing_matrices_to_tietze_index(self: Any) -> Any:
        ...
    def word_problem(self: Any, M: Any, output: Any = ..., check: Any = ...) -> Any:
        ...
    def __contains__(self: Any, M: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def index(self: Any) -> Any:
        ...
    def genus(self: Any) -> Any:
        ...
    def level(self: Any) -> Any:
        ...
    def nu2(self: Any) -> Any:
        ...
    def nu3(self: Any) -> Any:
        ...
    def coset_reps(self: Any) -> Any:
        ...
    def generators(self: Any) -> Any:
        ...
    def fractions(self: Any) -> Any:
        ...
    def pairings(self: Any) -> Any:
        ...
    def paired_sides(self: Any) -> Any:
        ...
    def pairing_matrices(self: Any) -> Any:
        ...
    def cusps(self: Any) -> Any:
        ...
    def cusp_widths(self: Any) -> Any:
        ...
    def cusp_class(self: Any, c: Any) -> Any:
        ...
    def reduce_to_cusp(self: Any, r: Any) -> Any:
        ...
    def fundamental_domain(self: Any) -> Any:
        ...
