from typing import Any

def is_sage_wrapper_for_singular_ring(ring: Any) -> Any:
    ...

def is_singular_poly_wrapper(p: Any) -> Any:
    ...

def all_singular_poly_wrapper(s: Any) -> Any:
    ...

def all_vectors(s: Any) -> Any:
    ...

def singular_function(name: Any) -> Any:
    ...

def lib(name: Any) -> Any:
    ...

def get_printlevel() -> Any:
    ...

def set_printlevel(l: Any) -> Any:
    ...

def list_of_functions(packages: Any = ...) -> Any:
    ...

class RingWrap:
    def __repr__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def var_names(self: Any) -> Any:
        ...
    def npars(self: Any) -> Any:
        ...
    def ordering_string(self: Any) -> Any:
        ...
    def par_names(self: Any) -> Any:
        ...
    def characteristic(self: Any) -> Any:
        ...
    def is_commutative(self: Any) -> Any:
        ...

class Resolution:
    def __init__(self: Any, base_ring: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...

class Converter(SageObject):
    def __init__(self: Any, args: Any, ring: Any, attributes: Any = ...) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...

class BaseCallHandler:
    ...

class LibraryCallHandler(BaseCallHandler):
    def __init__(self: Any) -> Any:
        ...

class KernelCallHandler(BaseCallHandler):
    def __init__(self: Any, cmd_n: Any, arity: Any) -> Any:
        ...

class SingularFunction(SageObject):
    def __init__(self: Any, name: Any) -> Any:
        ...
    def __call__(self: Any, ring: Any = ..., interruptible: Any = ..., attributes: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...

class SingularLibraryFunction(SingularFunction):
    def __init__(self: Any, name: Any) -> Any:
        ...

class SingularKernelFunction(SingularFunction):
    def __init__(self: Any, name: Any) -> Any:
        ...
