from typing import Any

def unpickle_NCGroebnerStrategy0(I: Any) -> Any:
    ...

def unpickle_GroebnerStrategy0(I: Any) -> Any:
    ...

class GroebnerStrategy(SageObject):
    def __cinit__(self: Any, L: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def ideal(self: Any) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def normal_form(self: Any, p: Any) -> Any:
        ...

class NCGroebnerStrategy(SageObject):
    def __init__(self: Any, L: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def ideal(self: Any) -> Any:
        ...
    def ring(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def normal_form(self: Any, p: Any) -> Any:
        ...
