from typing import Any

class LibSingularOptions_abstract:
    def __init__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, name: Any) -> Any:
        ...
    def __setitem__(self: Any, name: Any, value: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def save(self: Any) -> Any:
        ...
    def load(self: Any, value: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class LibSingularOptions(LibSingularOptions_abstract):
    def __init__(self: Any) -> Any:
        ...
    def reset_default(self: Any) -> Any:
        ...

class LibSingularVerboseOptions(LibSingularOptions_abstract):
    def __init__(self: Any) -> Any:
        ...
    def reset_default(self: Any) -> Any:
        ...

class LibSingularOptionsContext:
    def __init__(self: Any, opt: Any) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def __exit__(self: Any, typ: Any, value: Any, tb: Any) -> Any:
        ...
