from typing import Any

def poison_currRing(frame: Any, event: Any, arg: Any) -> Any:
    ...

def print_currRing() -> Any:
    ...

def currRing_wrapper() -> Any:
    ...

class ring_wrapper_Py:
    def __cinit__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
