from typing import Any

def SAT(solver: Any = ...) -> Any:
    ...

class SatSolver:
    def __cinit__(self: Any) -> Any:
        ...
    def var(self: Any, decision: Any = ...) -> Any:
        ...
    def nvars(self: Any) -> Any:
        ...
    def add_clause(self: Any, lits: Any) -> Any:
        ...
    def read(self: Any, filename: Any) -> Any:
        ...
    def __call__(self: Any, assumptions: Any = ...) -> Any:
        ...
    def conflict_clause(self: Any) -> Any:
        ...
    def learnt_clauses(self: Any, unitary_only: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def clauses(self: Any, filename: Any = ...) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
