from typing import Any

def Lfunction_from_character(chi: Any, type: Any = ...) -> Any:
    ...

def Lfunction_from_elliptic_curve(E: Any, number_of_coeffs: Any = ...) -> Any:
    ...

class Lfunction:
    def __repr__(self: Any) -> Any:
        ...
    def value(self: Any, s: Any, derivative: Any = ...) -> Any:
        ...
    def hardy_z_function(self: Any, s: Any) -> Any:
        ...
    def compute_rank(self: Any) -> Any:
        ...
    def find_zeros(self: Any, T1: Any, T2: Any, stepsize: Any) -> Any:
        ...
    def find_zeros_via_N(self: Any, count: Any = ..., start: Any = ..., max_refine: Any = ..., rank: Any = ...) -> Any:
        ...

class Lfunction_I(Lfunction):
    def __dealloc__(self: Any) -> Any:
        ...

class Lfunction_D(Lfunction):
    def __dealloc__(self: Any) -> Any:
        ...

class Lfunction_C:
    def __dealloc__(self: Any) -> Any:
        ...

class Lfunction_Zeta(Lfunction):
    def __init__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
