from typing import Any

class WordDatatype:
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class WordDatatype_list(WordDatatype):
    def __init__(self: Any, parent: Any = ..., data: Any = ...) -> Any:
        ...
    def __contains__(self: Any, a: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def length(self: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def number_of_letter_occurrences(self: Any, a: Any) -> Any:
        ...

class WordDatatype_str(WordDatatype):
    def __init__(self: Any, parent: Any = ..., data: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __contains__(self: Any, a: Any) -> Any:
        ...
    def find(self: Any, sub: Any, start: Any = ..., end: Any = ...) -> Any:
        ...
    def rfind(self: Any, sub: Any, start: Any = ..., end: Any = ...) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def length(self: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def number_of_letter_occurrences(self: Any, letter: Any) -> Any:
        ...
    def split(self: Any, sep: Any = ..., maxsplit: Any = ...) -> Any:
        ...
    def partition(self: Any, sep: Any) -> Any:
        ...

class WordDatatype_tuple(WordDatatype):
    def __init__(self: Any, parent: Any = ..., data: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def length(self: Any) -> Any:
        ...
    def __contains__(self: Any, a: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
