from typing import Any

def reversed_word_iterator(w: Any) -> Any:
    ...

class WordDatatype_char(WordDatatype):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, data: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_empty(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def length(self: Any) -> Any:
        ...
    def letters(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __reversed__(self: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def concatenate(self: Any, other: Any) -> Any:
        ...
    def __pow__(self: Any, exp: Any, mod: Any) -> Any:
        ...
    def fcn(n: Any) -> Any:
        ...
    def longest_common_prefix(self: Any, other: Any) -> Any:
        ...
    def longest_common_suffix(self: Any, other: Any) -> Any:
        ...
