from typing import Any

class TropicalSemiringElement(Element):
    def __init__(self: Any, parent: Any, val: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __pow__(base: Any, exp: Any, dummy: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def lift(self: Any) -> ModuleElement:
        ...

class TropicalSemiring(Parent, UniqueRepresentation):
    def __init__(self: Any, base: Any, use_min: Any = ...) -> Any:
        ...
    def zero(self: Any) -> Any:
        ...
    def one(self: Any) -> Any:
        ...

class TropicalToTropical(Map):
    ...
