from typing import Any

class GSLDoubleArray:
    def __init__(self: Any, n: Any, stride: Any = ..., data: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __setitem__(self: Any, i: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
