from typing import Any

class FreeAlgebraElement_letterplace(AlgebraElement):
    def __init__(self: Any, A: Any, x: Any, check: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def degree(self: Any) -> Any:
        ...
    def letterplace_polynomial(self: Any) -> Any:
        ...
    def lm(self: Any) -> Any:
        ...
    def lt(self: Any) -> Any:
        ...
    def lc(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def lm_divides(self: Any, p: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, k: Any) -> Any:
        ...
    def reduce(self: Any, G: Any) -> Any:
        ...
    def normal_form(self: Any, I: Any) -> Any:
        ...
