from typing import Any

class FreeAlgebra_letterplace(Parent):
    def __init__(self: Any, R: Any, degrees: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any) -> Any:
        ...
    def current_ring(self: Any) -> Any:
        ...
    def commutative_ring(self: Any) -> Any:
        ...
    def term_order_of_block(self: Any) -> Any:
        ...
    def generator_degrees(self: Any) -> Any:
        ...
    def degbound(self: Any) -> Any:
        ...
    def set_degbound(self: Any, d: Any) -> Any:
        ...
    def ideal_monoid(self: Any) -> Any:
        ...

class FreeAlgebra_letterplace_libsingular:
    def __init__(self: Any, commutative_ring: Any, degbound: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
