from typing import Any

class LetterplaceIdeal(Ideal_nc):
    def __init__(self: Any, ring: Any, gens: Any, coerce: Any = ..., side: Any = ...) -> Any:
        ...
    def groebner_basis(self: Any, degbound: Any = ...) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def reduce(self: Any, G: Any) -> Any:
        ...
