from typing import Any

def get_dist_classes(p: Any, prec_cap: Any, base: Any, symk: Any, implementation: Any) -> Any:
    ...

class Dist(ModuleElement):
    def moment(self: Any, n: Any) -> Any:
        ...
    def moments(self: Any) -> Any:
        ...
    def normalize(self: Any, include_zeroth_moment: Any = ...) -> Any:
        ...
    def scale(self: Any, left: Any) -> Any:
        ...
    def find_scalar(self: Any, _other: Any, p: Any, M: Any = ..., check: Any = ...) -> Any:
        ...
    def find_scalar_from_zeroth_moment(self: Any, _other: Any, p: Any, M: Any = ..., check: Any = ...) -> Any:
        ...
    def diagonal_valuation(self: Any, p: Any = ...) -> Any:
        ...
    def valuation(self: Any, p: Any = ...) -> Any:
        ...
    def specialize(self: Any, new_base_ring: Any = ...) -> Any:
        ...
    def lift(self: Any, p: Any = ..., M: Any = ..., new_base_ring: Any = ...) -> Any:
        ...
    def act_right(self: Any, gamma: Any) -> Any:
        ...

class Dist_vector(Dist):
    def __init__(self: Any, moments: Any, parent: Any, ordp: Any = ..., check: Any = ..., normalize: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def precision_relative(self: Any) -> Any:
        ...
    def precision_absolute(self: Any) -> Any:
        ...
    def normalize(self: Any, include_zeroth_moment: Any = ...) -> Any:
        ...
    def reduce_precision(self: Any, M: Any) -> Any:
        ...
    def solve_difference_equation(self: Any) -> Any:
        ...

class WeightKAction(Action):
    def __init__(self: Any, Dk: Any, character: Any, adjuster: Any, on_left: Any, dettwist: Any, padic: Any = ...) -> Any:
        ...
    def clear_cache(self: Any) -> Any:
        ...
    def acting_matrix(self: Any, g: Any, M: Any) -> Any:
        ...

class WeightKAction_vector(WeightKAction):
    ...
