from typing import Any

def add_lightness_smoothing_to_rgb(rgb: Any, delta: Any) -> Any:
    ...

def add_contours_to_rgb(rgb: Any, delta: Any, dark_rate: Any = ...) -> Any:
    ...

def rgb_to_hls(rgb: Any) -> Any:
    ...

def hls_to_rgb(hls: Any) -> Any:
    ...

class ComplexPlot(GraphicPrimitive):
    def __init__(self: Any, rgb_data: Any, x_range: Any, y_range: Any, options: Any) -> Any:
        ...
    def get_minmax_data(self: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
    def f(z: Any) -> Any:
        ...
