from typing import Any

def test_popcount() -> Any:
    ...

class FastDigraph:
    def __cinit__(self: Any, D: Any, vertex_list: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def print_adjacency_matrix(self: Any) -> Any:
        ...
