from typing import Any

def corneil_habib_paul_tedder_algorithm(G: Any) -> Any:
    ...

def print_md_tree(root: Any) -> Any:
    ...

def recursive_print_md_tree(root: Any, level: Any) -> Any:
    ...

def gamma_classes(graph: Any) -> Any:
    ...

def habib_maurer_algorithm(graph: Any, g_classes: Any = ...) -> Any:
    ...

def modular_decomposition(G: Any, algorithm: Any = ...) -> Any:
    ...

def check_modular_decomposition(tree_root: Any, graph: Any) -> Any:
    ...

def check_maximal_modules(tree_root: Any, graph: Any) -> Any:
    ...

def get_vertices(component_root: Any) -> Any:
    ...

def recurse_component(node: Any, vertices: Any) -> Any:
    ...

def get_module_type(graph: Any) -> Any:
    ...

def form_module(index: Any, other_index: Any, tree_root: Any, graph: Any) -> Any:
    ...

def check_module(module: Any, graph: Any) -> Any:
    ...

def children_node_type(module: Any, node_type: Any) -> Any:
    ...

def either_connected_or_not_connected(v: Any, vertices_in_module: Any, graph: Any) -> Any:
    ...

def tree_to_nested_tuple(root: Any) -> Any:
    ...

def nested_tuple_to_tree(nest: Any) -> Any:
    ...

def equivalent_trees(root1: Any, root2: Any) -> Any:
    ...

def node_id(root: Any) -> Any:
    ...

def relabel_tree(root: Any, perm: Any) -> Any:
    ...

def check_gamma_modules(trials: Any, vertices: Any, prob: Any, verbose: Any = ...) -> Any:
    ...

def permute_decomposition(trials: Any, algorithm: Any, vertices: Any, prob: Any, verbose: Any = ...) -> Any:
    ...

def random_md_tree(max_depth: Any, max_fan_out: Any, leaf_probability: Any) -> Any:
    ...

def rand_md_tree(max_depth: Any, parent_type: Any) -> Any:
    ...

def md_tree_to_graph(root: Any, prime_node_generator: Any = ...) -> Any:
    ...

def tree_to_vertices_and_edges(root: Any) -> Any:
    ...

def check_algos_are_equivalent(trials: Any, graph_gen: Any, verbose: Any = ...) -> Any:
    ...

class NodeType(IntEnum):
    ...

class Node:
    def __init__(self: Any, node_type: Any) -> Any:
        ...
    def is_prime(self: Any) -> Any:
        ...
    def is_series(self: Any) -> Any:
        ...
    def is_empty(self: Any) -> Any:
        ...
    def is_leaf(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def create_leaf(cls: Any, v: Any) -> Any:
        ...
