from typing import Any

def slice_decomposition(G: Any, initial_vertex: Any = ...) -> Any:
    ...

class SliceDecomposition(SageObject):
    def __init__(self: Any, G: Any, initial_vertex: Any = ...) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, v: Any) -> Any:
        ...
    def lexBFS_order(self: Any) -> Any:
        ...
    def xslice_data(self: Any, v: Any) -> Any:
        ...
    def slice(self: Any, v: Any) -> Any:
        ...
    def xslice_sequence(self: Any, v: Any) -> Any:
        ...
    def lexicographic_label(self: Any, v: Any) -> Any:
        ...
    def active_edges(self: Any, v: Any) -> Any:
        ...
    def underlying_graph(self: Any) -> Any:
        ...
    def inner_repr(idx: Any) -> Any:
        ...
