from typing import Any

def is_valid_tree_decomposition(G: Any, T: Any) -> Any:
    ...

def reduced_tree_decomposition(T: Any) -> Any:
    ...

def get_ancestor(ancestor: Any, u: Any) -> Any:
    ...

def width_of_tree_decomposition(G: Any, T: Any, check: Any = ...) -> Any:
    ...

def treewidth(g: Any, k: Any = ..., kmin: Any = ..., certificate: Any = ..., algorithm: Any = ..., nice: Any = ...) -> Any:
    ...

def rec(cut: Any, cc: Any) -> Any:
    ...

def make_nice_tree_decomposition(graph: Any, tree_decomp: Any) -> Any:
    ...

def add_path_of_intro_nodes(u: Any, v: Any) -> Any:
    ...

def add_path_of_forget_nodes(u: Any, v: Any) -> Any:
    ...

def label_nice_tree_decomposition(nice_TD: Any, root: Any, directed: Any = ...) -> Any:
    ...

def length_of_tree_decomposition(G: Any, T: Any, check: Any = ...) -> Any:
    ...

def treelength_lowerbound(G: Any) -> Any:
    ...

def treelength(G: Any, k: Any = ..., certificate: Any = ...) -> Any:
    ...

class TreelengthConnected:
    def __init__(self: Any, G: Any, k: Any = ..., certificate: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def rec(cut: Any, cc: Any) -> Any:
        ...
    def good_label(x: Any) -> Any:
        ...
    def good_label(x: Any) -> Any:
        ...
    def get_tree_decomposition(self: Any) -> Any:
        ...
    def get_length(self: Any) -> Any:
        ...
    def is_less_than_k(self: Any) -> Any:
        ...
