from typing import Any

def dlx_solver(rows: Any) -> Any:
    ...

def make_dlxwrapper(s: Any) -> Any:
    ...

class dancing_linksWrapper:
    def __init__(self: Any, rows: Any) -> Any:
        ...
    def reinitialize(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def rows(self: Any) -> Any:
        ...
    def ncols(self: Any) -> Any:
        ...
    def nrows(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def get_solution(self: Any) -> Any:
        ...
    def search(self: Any) -> Any:
        ...
    def restrict(self: Any, indices: Any) -> Any:
        ...
    def split(self: Any, column: Any) -> Any:
        ...
    def solutions_iterator(self: Any) -> Any:
        ...
    def one_solution(self: Any, ncpus: Any = ..., column: Any = ...) -> Any:
        ...
    def first_solution(i: Any) -> Any:
        ...
    def all_solutions(self: Any, ncpus: Any = ..., column: Any = ...) -> Any:
        ...
    def all_solutions(i: Any) -> Any:
        ...
    def number_of_solutions(self: Any, ncpus: Any = ..., column: Any = ...) -> Any:
        ...
    def nb_sol(i: Any) -> Any:
        ...
    def to_sat_solver(self: Any, solver: Any = ...) -> Any:
        ...
    def one_solution_using_sat_solver(self: Any, solver: Any = ...) -> Any:
        ...
    def to_milp(self: Any, solver: Any = ...) -> Any:
        ...
    def one_solution_using_milp_solver(self: Any, solver: Any = ..., integrality_tolerance: Any = ...) -> Any:
        ...
