from typing import Any

def MatrixArgs_init(space: Any, entries: Any) -> Any:
    ...

class SparseEntry:
    def __init__(self: Any, i: Any, j: Any, entry: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class MatrixArgs:
    def __cinit__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def iter(self: Any, convert: Any = ..., sparse: Any = ...) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def matrix(self: Any, convert: Any = ...) -> Matrix:
        ...
    def element(self: Any, immutable: Any = ...) -> Any:
        ...
    def list(self: Any, convert: Any = ...) -> List[Any]:
        ...
    def dict(self: Any, convert: Any = ...) -> Dict[Any, Any]:
        ...
    def set_column_keys(self: Any, column_keys: Any) -> int:
        ...
    def set_row_keys(self: Any, row_keys: Any) -> int:
        ...
    def set_space(self: Any, space: Any) -> int:
        ...
    def finalized(self: Any) -> Any:
        ...
