from typing import Any, List, Optional, Union
from sage.matrix.matrix_dense import Matrix_dense
from sage.rings.rational import Rational
from sage.rings.integer import Integer

class Matrix_rational_dense(Matrix_dense):
    def __cinit__(self) -> None:
        ...
    def __dealloc__(self) -> None:
        ...
    def __init__(self, parent: Any, entries: Any = ..., copy: bool = ..., coerce: bool = ...) -> None:
        ...
    def matrix_from_columns(self, columns: List[int]) -> "Matrix_rational_dense":
        ...
    def add_to_entry(self, i: int, j: int, elt: Rational) -> None:
        ...
    def __neg__(self) -> "Matrix_rational_dense":
        ...
    def __copy__(self) -> "Matrix_rational_dense":
        ...
    def __invert__(self) -> "Matrix_rational_dense":
        ...
    def inverse(self, algorithm: Optional[str] = ..., check_invertible: bool = ...) -> "Matrix_rational_dense":
        ...
    def determinant(self, algorithm: Optional[str] = ..., proof: bool = ...) -> Rational:
        ...
    def denominator(self) -> Integer:
        ...
    def charpoly(self, var: str = ..., algorithm: Optional[str] = ...) -> Any:
        ...
    def minpoly(self, var: str = ..., algorithm: Optional[str] = ...) -> Any:
        ...
    def height(self) -> Rational:
        ...
    def prod_of_row_sums(self, cols: List[int]) -> Rational:
        ...
    def change_ring(self, R: Any) -> Any:
        ...
    def rank(self, algorithm: Optional[str] = ...) -> int:
        ...
    def transpose(self) -> "Matrix_rational_dense":
        ...
    def antitranspose(self) -> "Matrix_rational_dense":
        ...
    def set_row_to_multiple_of_row(self, i: int, j: int, s: Rational) -> None:
        ...
    def __pari__(self) -> Any:
        ...
    def row(self, i: int, from_list: bool = ...) -> Any:
        ...
    def column(self, i: int, from_list: bool = ...) -> Any:
        ...
    def BKZ(self) -> "Matrix_rational_dense":
        ...
    def LLL(self) -> "Matrix_rational_dense":
        ...
    def is_LLL_reduced(self, delta: float = ..., eta: float = ...) -> bool:
        ...
