from typing import Any

def Matrix_sparse_from_rows(X: Any) -> Any:
    ...

class Matrix_generic_sparse(matrix_sparse.Matrix_sparse):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
