from typing import Any

class Matrix_numpy_dense(Matrix_dense):
    def __create_matrix__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def is_symmetric(self: Any, tol: Any = ...) -> Any:
        ...
    def numpy(self: Any, dtype: Any = ...) -> Any:
        ...
