from typing import Any

class Matrix_double_dense(Matrix_numpy_dense):
    def LU_valid(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def condition(self: Any, p: Any = ...) -> Any:
        ...
    def norm(self: Any, p: Any = ...) -> Any:
        ...
    def singular_values(self: Any, eps: Any = ...) -> Any:
        ...
    def LU(self: Any) -> Any:
        ...
    def eigenvectors_left(self: Any, other: Any = ..., algorithm: Any = ..., homogeneous: Any = ...) -> Any:
        ...
    def eigenvectors_right(self: Any, other: Any = ..., homogeneous: Any = ...) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def log_determinant(self: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def SVD(self: Any) -> Any:
        ...
    def QR(self: Any) -> Any:
        ...
    def is_unitary(self: Any, tol: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def is_hermitian(self: Any, tol: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def is_skew_hermitian(self: Any, tol: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def is_normal(self: Any, tol: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def schur(self: Any, base_ring: Any = ...) -> Any:
        ...
    def cholesky(self: Any) -> Any:
        ...
    def is_positive_definite(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def zero_at(self: Any, eps: Any) -> Any:
        ...
    def round(self: Any, ndigits: Any = ...) -> Any:
        ...
