from typing import Any

class Matrix_mpolynomial_dense(Matrix_generic_dense):
    def echelon_form(self: Any, algorithm: Any = ...) -> Any:
        ...
    def pivots(self: Any) -> Any:
        ...
    def echelonize(self: Any, algorithm: Any = ...) -> Any:
        ...
    def swapped_columns(self: Any) -> Any:
        ...
    def determinant(self: Any, algorithm: Any = ...) -> Any:
        ...
