from typing import Any

def mtx_unpickle(f: Any, nr: Any, nc: Any, data: Any, m: Any) -> Any:
    ...

class FieldConverter_class:
    def __init__(self: Any, field: Any) -> Any:
        ...
    def field_to_fel(self: Any, x: Any) -> Any:
        ...

class PrimeFieldConverter_class(FieldConverter_class):
    def __init__(self: Any, field: Any) -> Any:
        ...
    def field_to_fel(self: Any, x: Any) -> Any:
        ...

class Matrix_gfpn_dense(Matrix_dense):
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ..., mutable: Any = ...) -> Any:
        ...
    def from_filename(filename: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def randomize(self: Any, density: Any = ..., nonzero: Any = ...) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __truediv__(self: Any, p: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def left_kernel_matrix(self: Any) -> Any:
        ...
