from typing import Any

def unpickle_matrix_mod2_dense_v2(r: Any, c: Any, data: Any, size: Any, immutable: Any = ...) -> Any:
    ...

def from_png(filename: Any) -> Any:
    ...

def to_png(A: Any, filename: Any) -> Any:
    ...

def pluq(A: Any, algorithm: Any = ..., param: Any = ...) -> Any:
    ...

def ple(A: Any, algorithm: Any = ..., param: Any = ...) -> Any:
    ...

class Matrix_mod2_dense(matrix_dense.Matrix_dense):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def row(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def columns(self: Any, copy: Any = ...) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def echelonize(self: Any, algorithm: Any = ..., cutoff: Any = ..., reduced: Any = ...) -> Any:
        ...
    def randomize(self: Any, density: Any = ..., nonzero: Any = ...) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def augment(self: Any, right: Any, subdivide: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def density(self: Any, approx: Any = ...) -> Any:
        ...
    def rank(self: Any, algorithm: Any = ...) -> Any:
        ...
    def doubly_lexical_ordering(self: Any, inplace: Any = ...) -> Any:
        ...
    def is_Gamma_free(self: Any, certificate: Any = ...) -> Any:
        ...
