from typing import Any

class Matrix_gap(Matrix_dense):
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def gap(self: Any) -> GapElement:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def rank(self: Any) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def elementary_divisors(self: Any) -> Any:
        ...
