from typing import Any

class Matrix(Matrix0):
    def __pari__(self: Any) -> Any:
        ...
    def numpy(self: Any, dtype: Any = ..., copy: Any = ...) -> Any:
        ...
    def matrix_over_field(self: Any) -> Any:
        ...
    def lift(self: Any) -> Any:
        ...
    def lift_centered(self: Any) -> Any:
        ...
    def row_ambient_module(self: Any, base_ring: Any = ..., sparse: Any = ...) -> Any:
        ...
    def column_ambient_module(self: Any, base_ring: Any = ..., sparse: Any = ...) -> Any:
        ...
    def columns(self: Any, copy: Any = ...) -> Any:
        ...
    def rows(self: Any, copy: Any = ...) -> Any:
        ...
    def dense_columns(self: Any, copy: Any = ...) -> Any:
        ...
    def dense_rows(self: Any, copy: Any = ...) -> Any:
        ...
    def sparse_columns(self: Any, copy: Any = ...) -> Any:
        ...
    def sparse_rows(self: Any, copy: Any = ...) -> Any:
        ...
    def column(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def row(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def stack(self: Any, bottom: Any, subdivide: Any = ...) -> Any:
        ...
    def augment(self: Any, right: Any, subdivide: Any = ...) -> Any:
        ...
    def matrix_from_columns(self: Any, columns: Any) -> Any:
        ...
    def delete_columns(self: Any, dcols: Any, check: Any = ...) -> Any:
        ...
    def matrix_from_rows(self: Any, rows: Any) -> Any:
        ...
    def delete_rows(self: Any, drows: Any, check: Any = ...) -> Any:
        ...
    def matrix_from_rows_and_columns(self: Any, rows: Any, columns: Any) -> Any:
        ...
    def set_row(self: Any, row: Any, v: Any) -> Any:
        ...
    def set_column(self: Any, col: Any, v: Any) -> Any:
        ...
    def zero_pattern_matrix(self: Any, ring: Any = ...) -> Any:
        ...
    def dense_matrix(self: Any) -> Any:
        ...
    def sparse_matrix(self: Any) -> Any:
        ...
    def matrix_space(self: Any, nrows: Any = ..., ncols: Any = ..., sparse: Any = ...) -> Any:
        ...
    def block_sum(self: Any, other: Any) -> Any:
        ...
