from typing import Any

class Matrix_symbolic_sparse(Matrix_generic_sparse):
    def echelonize(self: Any) -> Any:
        ...
    def eigenvalues(self: Any, extend: Any = ...) -> Any:
        ...
    def eigenvectors_left(self: Any, other: Any = ...) -> Any:
        ...
    def eigenvectors_right(self: Any, other: Any = ...) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def fcp(self: Any, var: Any = ...) -> Any:
        ...
    def jordan_form(self: Any, subdivide: Any = ..., transformation: Any = ...) -> Any:
        ...
    def simplify(self: Any) -> Any:
        ...
    def simplify_trig(self: Any) -> Any:
        ...
    def simplify_rational(self: Any) -> Any:
        ...
    def simplify_full(self: Any) -> Any:
        ...
    def canonicalize_radical(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def expand(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def arguments(self: Any) -> Any:
        ...
    def number_of_arguments(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def function(self: Any) -> Any:
        ...
