from typing import Any

class Matrix_integer_dense(Matrix_dense):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def __pow__(sself: Any, n: Any, dummy: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def is_primitive(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def height(self: Any) -> Any:
        ...
    def symplectic_form(self: Any) -> Any:
        ...
    def saturation(self: Any, p: Any = ..., proof: Any = ..., max_dets: Any = ...) -> Any:
        ...
    def index_in_saturation(self: Any, proof: Any = ...) -> Any:
        ...
    def pivots(self: Any) -> Any:
        ...
    def elementary_divisors(self: Any, algorithm: Any = ...) -> Any:
        ...
    def smith_form(self: Any, transformation: Any = ..., integral: Any = ...) -> Any:
        ...
    def frobenius_form(self: Any, flag: Any = ..., var: Any = ...) -> Any:
        ...
    def LLL(self: Any, delta: Any = ..., eta: Any = ..., algorithm: Any = ..., fp: Any = ..., prec: Any = ..., early_red: Any = ..., use_givens: Any = ..., use_siegel: Any = ..., transformation: Any = ...) -> Any:
        ...
    def is_LLL_reduced(self: Any, delta: Any = ..., eta: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def prod_of_row_sums(self: Any, cols: Any) -> Any:
        ...
    def rational_reconstruction(self: Any, N: Any) -> Any:
        ...
    def rank(self: Any, algorithm: Any = ...) -> Any:
        ...
    def determinant(self: Any, algorithm: Any = ..., proof: Any = ..., stabilize: Any = ...) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def inverse_of_unit(self: Any) -> Any:
        ...
    def decomposition(self: Any) -> Any:
        ...
    def row(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def column(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def augment(self: Any, right: Any, subdivide: Any = ...) -> Any:
        ...
    def insert_row(self: Any, index: Any, row: Any) -> Any:
        ...
    def gcd(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def antitranspose(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def p_minimal_polynomials(self: Any, p: Any, s_max: Any = ...) -> Any:
        ...
    def null_ideal(self: Any, b: Any = ...) -> Any:
        ...
    def integer_valued_polynomials_generators(self: Any) -> Any:
        ...
