from typing import Any

class Matrix_rational_dense(Matrix_dense):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def matrix_from_columns(self: Any, columns: Any) -> Any:
        ...
    def add_to_entry(self: Any, i: Any, j: Any, elt: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def inverse(self: Any, algorithm: Any = ..., check_invertible: Any = ...) -> Any:
        ...
    def determinant(self: Any, algorithm: Any = ..., proof: Any = ...) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def height(self: Any) -> Any:
        ...
    def prod_of_row_sums(self: Any, cols: Any) -> Any:
        ...
    def change_ring(self: Any, R: Any) -> Any:
        ...
    def rank(self: Any, algorithm: Any = ...) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def antitranspose(self: Any) -> Any:
        ...
    def set_row_to_multiple_of_row(self: Any, i: Any, j: Any, s: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
    def row(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def column(self: Any, i: Any, from_list: Any = ...) -> Any:
        ...
    def BKZ(self: Any) -> Any:
        ...
    def LLL(self: Any) -> Any:
        ...
    def is_LLL_reduced(self: Any, delta: Any = ..., eta: Any = ...) -> Any:
        ...
