from typing import Any

class Matrix_complex_ball_dense(Matrix_dense):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def identical(self: Any, other: Any) -> Any:
        ...
    def overlaps(self: Any, other: Any) -> Any:
        ...
    def contains(self: Any, other: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def eigenvalues(self: Any, other: Any = ..., extend: Any = ...) -> Any:
        ...
    def eigenvectors_right_approx(self: Any, other: Any = ..., extend: Any = ...) -> Any:
        ...
    def eigenvectors_right(self: Any, other: Any = ..., extend: Any = ...) -> Any:
        ...
    def eigenvectors_left_approx(self: Any, other: Any = ..., extend: Any = ...) -> Any:
        ...
    def eigenvectors_left(self: Any, other: Any = ..., extend: Any = ...) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
