from typing import Any, List, Dict, Tuple, Iterator, Optional
import sage.structure.element

def unpickle(cls: Any, parent: Any, immutability: bool, cache: Any, data: Any, version: Any) -> Any:
    ...

class Matrix(sage.structure.element.Matrix):
    def __cinit__(self, parent: Any) -> None:
        ...
    def list(self) -> List[Any]:
        ...
    def dict(self, copy: bool = ...) -> Dict[Tuple[int, int], Any]:
        ...
    def items(self) -> Iterator[Tuple[Tuple[int, int], Any]]:
        ...
    def set_immutable(self) -> None:
        ...
    def is_immutable(self) -> bool:
        ...
    def is_mutable(self) -> bool:
        ...
    def add_to_entry(self, i: int, j: int, elt: Any) -> None:
        ...
    def __iter__(self) -> Iterator[Any]:
        ...
    def __getitem__(self, key: Any) -> Any:
        ...
    def __setitem__(self, key: Any, value: Any) -> None:
        ...
    def __reduce__(self) -> Tuple[Any, ...]:
        ...
    def base_ring(self) -> Any:
        ...
    def change_ring(self, ring: Any) -> "Matrix":
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def ncols(self) -> int:
        ...
    def nrows(self) -> int:
        ...
    def dimensions(self) -> Tuple[int, int]:
        ...
    def act_on_polynomial(self, f: Any) -> Any:
        ...
    def __call__(self) -> Any:
        ...
    def commutator(self, other: "Matrix") -> "Matrix":
        ...
    def anticommutator(self, other: "Matrix") -> "Matrix":
        ...
    def swap_columns(self, c1: int, c2: int) -> None:
        ...
    def with_swapped_columns(self, c1: int, c2: int) -> "Matrix":
        ...
    def permute_columns(self, permutation: Any) -> None:
        ...
    def with_permuted_columns(self, permutation: Any) -> "Matrix":
        ...
    def swap_rows(self, r1: int, r2: int) -> None:
        ...
    def with_swapped_rows(self, r1: int, r2: int) -> "Matrix":
        ...
    def permute_rows(self, permutation: Any) -> None:
        ...
    def with_permuted_rows(self, permutation: Any) -> "Matrix":
        ...
    def permute_rows_and_columns(self, row_permutation: Any, column_permutation: Any) -> None:
        ...
    def with_permuted_rows_and_columns(self, row_permutation: Any, column_permutation: Any) -> "Matrix":
        ...
    def rescale_row(self, i: int, s: Any, start_col: int = ...) -> None:
        ...
    def with_rescaled_row(self, i: int, s: Any, start_col: int = ...) -> "Matrix":
        ...
    def rescale_col(self, i: int, s: Any, start_row: int = ...) -> None:
        ...
    def with_rescaled_col(self, i: int, s: Any, start_row: int = ...) -> "Matrix":
        ...
    def set_row_to_multiple_of_row(self, i: int, j: int, s: Any) -> None:
        ...
    def with_row_set_to_multiple_of_row(self, i: int, j: int, s: Any) -> "Matrix":
        ...
    def set_col_to_multiple_of_col(self, i: int, j: int, s: Any) -> None:
        ...
    def with_col_set_to_multiple_of_col(self, i: int, j: int, s: Any) -> "Matrix":
        ...
    def reverse_rows_and_columns(self) -> "Matrix":
        ...
    def mutate(self, k: int) -> None:
        ...
    def linear_combination_of_rows(self, v: Any) -> Any:
        ...
    def linear_combination_of_columns(self, v: Any) -> Any:
        ...
    def is_symmetric(self) -> bool:
        ...
    def is_hermitian(self) -> bool:
        ...
    def is_skew_hermitian(self) -> bool:
        ...
    def is_skew_symmetric(self) -> bool:
        ...
    def is_alternating(self) -> bool:
        ...
    def is_symmetrizable(self, return_diag: bool = ..., positive: bool = ...) -> bool:
        ...
    def is_skew_symmetrizable(self, return_diag: bool = ..., positive: bool = ...) -> bool:
        ...
    def is_dense(self) -> bool:
        ...
    def is_sparse(self) -> bool:
        ...
    def is_square(self) -> bool:
        ...
    def is_invertible(self) -> bool:
        ...
    def is_singular(self) -> bool:
        ...
    def pivots(self) -> Tuple[int, ...]:
        ...
    def rank(self) -> int:
        ...
    def nonpivots(self) -> List[int]:
        ...
    def nonzero_positions(self, copy: bool = ..., column_order: bool = ...) -> List[Tuple[int, int]]:
        ...
    def nonzero_positions_in_column(self, i: int) -> List[int]:
        ...
    def nonzero_positions_in_row(self, i: int) -> List[int]:
        ...
    def multiplicative_order(self) -> int:
        ...
    def iterates(self, v: Any, n: int, rows: bool = ...) -> List[Any]:
        ...
    def __mod__(self, p: Any) -> "Matrix":
        ...
    def mod(self, p: Any) -> "Matrix":
        ...
    def __neg__(self) -> "Matrix":
        ...
    def __invert__(self) -> "Matrix":
        ...
    def inverse_of_unit(self, algorithm: Optional[str] = ...) -> "Matrix":
        ...
    def __pos__(self) -> "Matrix":
        ...
    def __pow__(self, n: int, ignored: Any = None) -> "Matrix":
        ...
    def __hash__(self) -> int:
        ...
    def __bool__(self) -> bool:
        ...
