from typing import Any

class Matrix_rational_sparse(Matrix_sparse):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def add_to_entry(self: Any, i: Any, j: Any, elt: Any) -> Any:
        ...
    def height(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def echelonize(self: Any, height_guess: Any = ..., proof: Any = ...) -> Any:
        ...
    def set_row_to_multiple_of_row(self: Any, i: Any, j: Any, s: Any) -> Any:
        ...
    def dense_matrix(self: Any) -> Any:
        ...
