from typing import Any

def unpickle_matrix_gf2e_dense_v0(a: Any, base_ring: Any, nrows: Any, ncols: Any) -> Any:
    ...

class M4RIE_finite_field:
    def __dealloc__(self: Any) -> Any:
        ...

class Matrix_gf2e_dense(matrix_dense.Matrix_dense):
    def __cinit__(self: Any, alloc: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def randomize(self: Any, density: Any = ..., nonzero: Any = ...) -> Any:
        ...
    def echelonize(self: Any, algorithm: Any = ..., reduced: Any = ...) -> Any:
        ...
    def is_invertible(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def augment(self: Any, right: Any) -> Any:
        ...
    def rank(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def slice(self: Any) -> Any:
        ...
    def cling(self: Any) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
