from typing import Any, List, Optional, Union
import sage.modules.vector_space

class Matrix(Matrix0):
    def __pari__(self) -> Any:
        ...
    def numpy(self, dtype: Any = ..., copy: bool = ...) -> Any:
        ...
    def matrix_over_field(self) -> "Matrix":
        ...
    def lift(self) -> "Matrix":
        ...
    def lift_centered(self) -> "Matrix":
        ...
    def row_ambient_module(self, base_ring: Any = ..., sparse: bool = ...) -> Any:
        ...
    def column_ambient_module(self, base_ring: Any = ..., sparse: bool = ...) -> Any:
        ...
    def columns(self, copy: bool = ...) -> List[Any]:
        ...
    def rows(self, copy: bool = ...) -> List[Any]:
        ...
    def dense_columns(self, copy: bool = ...) -> List[Any]:
        ...
    def dense_rows(self, copy: bool = ...) -> List[Any]:
        ...
    def sparse_columns(self, copy: bool = ...) -> List[Any]:
        ...
    def sparse_rows(self, copy: bool = ...) -> List[Any]:
        ...
    def column(self, i: int, from_list: bool = ...) -> Any:
        ...
    def row(self, i: int, from_list: bool = ...) -> Any:
        ...
    def stack(self, bottom: "Matrix", subdivide: bool = ...) -> "Matrix":
        ...
    def augment(self, right: "Matrix", subdivide: bool = ...) -> "Matrix":
        ...
    def matrix_from_columns(self, columns: List[int]) -> "Matrix":
        ...
    def delete_columns(self, dcols: List[int], check: bool = ...) -> "Matrix":
        ...
    def matrix_from_rows(self, rows: List[int]) -> "Matrix":
        ...
    def delete_rows(self, drows: List[int], check: bool = ...) -> "Matrix":
        ...
    def matrix_from_rows_and_columns(self, rows: List[int], columns: List[int]) -> "Matrix":
        ...
    def set_row(self, row: int, v: Any) -> None:
        ...
    def set_column(self, col: int, v: Any) -> None:
        ...
    def zero_pattern_matrix(self, ring: Any = ...) -> "Matrix":
        ...
    def dense_matrix(self) -> "Matrix":
        ...
    def sparse_matrix(self) -> "Matrix":
        ...
    def matrix_space(self, nrows: Optional[int] = ..., ncols: Optional[int] = ..., sparse: Optional[bool] = ...) -> Any:
        ...
    def block_sum(self, other: "Matrix") -> "Matrix":
        ...
