from typing import Any

class MatrixWindow:
    def new_empty_window(self: Any, nrows: Any, ncols: Any) -> Any:
        ...
    def set(self: Any, src: Any) -> Any:
        ...
    def set_unsafe(self: Any, i: Any, j: Any, x: Any) -> Any:
        ...
    def get_unsafe(self: Any, i: Any, j: Any) -> Any:
        ...
    def __setitem__(self: Any, ij: Any, x: Any) -> Any:
        ...
    def __getitem__(self: Any, ij: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def to_matrix(self: Any) -> Any:
        ...
    def nrows(self: Any) -> Any:
        ...
    def ncols(self: Any) -> Any:
        ...
    def set_to(self: Any, A: Any) -> Any:
        ...
    def set_to_zero(self: Any) -> Any:
        ...
    def add(self: Any, A: Any) -> Any:
        ...
    def subtract(self: Any, A: Any) -> Any:
        ...
    def set_to_sum(self: Any, A: Any, B: Any) -> Any:
        ...
    def set_to_diff(self: Any, A: Any, B: Any) -> Any:
        ...
    def set_to_prod(self: Any, A: Any, B: Any) -> Any:
        ...
    def add_prod(self: Any, A: Any, B: Any) -> Any:
        ...
    def subtract_prod(self: Any, A: Any, B: Any) -> Any:
        ...
    def swap_rows(self: Any, a: Any, b: Any) -> Any:
        ...
    def echelon_in_place(self: Any) -> Any:
        ...
