from typing import Any

class Matrix_sparse(matrix.Matrix):
    def change_ring(self: Any, ring: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def antitranspose(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def determinant(self: Any) -> Any:
        ...
    def apply_morphism(self: Any, phi: Any) -> Any:
        ...
    def apply_map(self: Any, phi: Any, R: Any = ..., sparse: Any = ...) -> Any:
        ...
    def density(self: Any) -> Any:
        ...
    def matrix_from_rows_and_columns(self: Any, rows: Any, columns: Any) -> Any:
        ...
    def augment(self: Any, right: Any, subdivide: Any = ...) -> Any:
        ...
