from typing import Any, List, Optional, Tuple, Union
from sage.matrix.matrix_dense import Matrix_dense
from sage.rings.integer import Integer

class Matrix_integer_dense(Matrix_dense):
    def __cinit__(self) -> None:
        ...
    def __dealloc__(self) -> None:
        ...
    def __init__(self, parent: Any, entries: Any = ..., copy: bool = ..., coerce: bool = ...) -> None:
        ...
    def __copy__(self) -> "Matrix_integer_dense":
        ...
    def __bool__(self) -> bool:
        ...
    def is_one(self) -> bool:
        ...
    def __pow__(self, n: int, dummy: Any = None) -> "Matrix_integer_dense":
        ...
    def __neg__(self) -> "Matrix_integer_dense":
        ...
    def is_primitive(self) -> bool:
        ...
    def charpoly(self, var: str = ..., algorithm: Optional[str] = ...) -> Any:
        ...
    def minpoly(self, var: str = ..., algorithm: Optional[str] = ...) -> Any:
        ...
    def height(self) -> Integer:
        ...
    def symplectic_form(self) -> "Matrix_integer_dense":
        ...
    def saturation(self, p: Optional[int] = ..., proof: bool = ..., max_dets: int = ...) -> Tuple["Matrix_integer_dense", Integer]:
        ...
    def index_in_saturation(self, proof: bool = ...) -> Integer:
        ...
    def pivots(self) -> Tuple[int, ...]:
        ...
    def elementary_divisors(self, algorithm: Optional[str] = ...) -> List[Integer]:
        ...
    def smith_form(self, transformation: bool = ..., integral: Optional[bool] = ...) -> Union["Matrix_integer_dense", Tuple["Matrix_integer_dense", "Matrix_integer_dense", "Matrix_integer_dense"]]:
        ...
    def frobenius_form(self, flag: int = ..., var: str = ...) -> Union[Any, Tuple[Any, "Matrix_integer_dense"]]:
        ...
    def LLL(self, delta: float = ..., eta: float = ..., algorithm: str = ..., fp: Optional[str] = ..., prec: int = ..., early_red: bool = ..., use_givens: bool = ..., use_siegel: bool = ..., transformation: bool = ...) -> Union["Matrix_integer_dense", Tuple["Matrix_integer_dense", "Matrix_integer_dense"]]:
        ...
    def is_LLL_reduced(self, delta: float = ..., eta: float = ..., algorithm: str = ...) -> bool:
        ...
    def prod_of_row_sums(self, cols: List[int]) -> Integer:
        ...
    def rational_reconstruction(self, N: Integer) -> Any:
        ...
    def rank(self, algorithm: Optional[str] = ...) -> int:
        ...
    def determinant(self, algorithm: Optional[str] = ..., proof: bool = ..., stabilize: int = ...) -> Integer:
        ...
    def __invert__(self) -> Any:
        ...
    def inverse_of_unit(self) -> "Matrix_integer_dense":
        ...
    def decomposition(self) -> List[Tuple["Matrix_integer_dense", int, bool]]:
        ...
    def row(self, i: int, from_list: bool = ...) -> Any:
        ...
    def column(self, i: int, from_list: bool = ...) -> Any:
        ...
    def augment(self, right: "Matrix_integer_dense", subdivide: bool = ...) -> "Matrix_integer_dense":
        ...
    def insert_row(self, index: int, row: Any) -> "Matrix_integer_dense":
        ...
    def gcd(self) -> Integer:
        ...
    def transpose(self) -> "Matrix_integer_dense":
        ...
    def antitranspose(self) -> "Matrix_integer_dense":
        ...
    def __pari__(self) -> Any:
        ...
    def p_minimal_polynomials(self, p: int, s_max: int = ...) -> List[Any]:
        ...
    def null_ideal(self, b: Optional[int] = ...) -> Any:
        ...
    def integer_valued_polynomials_generators(self) -> List[Any]:
        ...
