from typing import Any

class Matrix_cyclo_dense(Matrix_dense):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def set_immutable(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def coefficient_bound(self: Any) -> Any:
        ...
    def height(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ..., proof: Any = ...) -> Any:
        ...
    def echelon_form(self: Any, algorithm: Any = ..., height_guess: Any = ...) -> Any:
        ...
    def tensor_product(self: Any, A: Any, subdivide: Any = ...) -> Any:
        ...
