from typing import Any

class Matrix_integer_sparse(Matrix_sparse):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def rational_reconstruction(self: Any, N: Any) -> Any:
        ...
    def elementary_divisors(self: Any, algorithm: Any = ...) -> Any:
        ...
    def smith_form(self: Any, transformation: Any = ..., integral: Any = ...) -> Any:
        ...
    def rank(self: Any, algorithm: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
