from typing import Any

class Matrix_modn_sparse(Matrix_sparse):
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, entries: Any = ..., copy: Any = ..., coerce: Any = ...) -> Any:
        ...
    def swap_rows(self: Any, r1: Any, r2: Any) -> Any:
        ...
    def density(self: Any) -> Any:
        ...
    def transpose(self: Any) -> Any:
        ...
    def matrix_from_rows(self: Any, rows: Any) -> Any:
        ...
    def matrix_from_columns(self: Any, cols: Any) -> Any:
        ...
    def rank(self: Any, algorithm: Any = ...) -> Any:
        ...
    def determinant(self: Any, algorithm: Any = ...) -> Any:
        ...
