from typing import Any

def ideal_or_fractional(R: Any) -> Any:
    ...

def decomp_seq(v: Any) -> Any:
    ...

class Matrix(Matrix1):
    def subs(self: Any) -> Any:
        ...
    def solve_left(self: Any, B: Any, check: Any = ..., extend: Any = ...) -> Any:
        ...
    def solve_right(self: Any, B: Any, check: Any = ..., extend: Any = ...) -> Any:
        ...
    def pivot_rows(self: Any) -> Any:
        ...
    def prod_of_row_sums(self: Any, cols: Any) -> Any:
        ...
    def elementwise_product(self: Any, right: Any) -> Any:
        ...
    def permanent(self: Any, algorithm: Any = ...) -> Any:
        ...
    def permanental_minor(self: Any, k: Any, algorithm: Any = ...) -> Any:
        ...
    def pseudoinverse(self: Any, algorithm: Any = ...) -> Any:
        ...
    def rook_vector(self: Any, algorithm: Any = ..., complement: Any = ..., use_complement: Any = ...) -> Any:
        ...
    def minors(self: Any, k: Any) -> Any:
        ...
    def det(self: Any) -> Any:
        ...
    def determinant(self: Any, algorithm: Any = ...) -> Any:
        ...
    def quantum_determinant(self: Any, q: Any = ...) -> Any:
        ...
    def pfaffian(self: Any, algorithm: Any = ..., check: Any = ...) -> Any:
        ...
    def apply_morphism(self: Any, phi: Any) -> Any:
        ...
    def apply_map(self: Any, phi: Any, R: Any = ..., sparse: Any = ...) -> Any:
        ...
    def characteristic_polynomial(self: Any) -> Any:
        ...
    def minimal_polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def fcp(self: Any, var: Any = ...) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def diagonal(self: Any, offset: Any = ...) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def trace_of_product(self: Any, other: Any) -> Any:
        ...
    def get_bandwidth(self: Any) -> Any:
        ...
    def hessenberg_form(self: Any) -> Any:
        ...
    def hessenbergize(self: Any) -> Any:
        ...
    def left_nullity(self: Any) -> Any:
        ...
    def right_nullity(self: Any) -> Any:
        ...
    def right_kernel_matrix(self: Any) -> Any:
        ...
    def left_kernel_matrix(self: Any) -> Any:
        ...
    def right_kernel(self: Any) -> Any:
        ...
    def left_kernel(self: Any) -> Any:
        ...
    def kernel_on(self: Any, V: Any, poly: Any = ..., check: Any = ...) -> Any:
        ...
    def integer_kernel(self: Any, ring: Any = ...) -> Any:
        ...
    def image(self: Any) -> Any:
        ...
    def row_module(self: Any, base_ring: Any = ...) -> Any:
        ...
    def row_space(self: Any, base_ring: Any = ...) -> Any:
        ...
    def column_module(self: Any) -> Any:
        ...
    def column_space(self: Any) -> Any:
        ...
    def decomposition_of_subspace(self: Any, M: Any, check_restrict: Any = ...) -> Any:
        ...
    def restrict(self: Any, V: Any, check: Any = ...) -> Any:
        ...
    def restrict_domain(self: Any, V: Any) -> Any:
        ...
    def restrict_codomain(self: Any, V: Any) -> Any:
        ...
    def maxspin(self: Any, v: Any) -> Any:
        ...
    def wiedemann(self: Any, i: Any, t: Any = ...) -> Any:
        ...
    def eigenspaces_left(self: Any, format: Any = ..., var: Any = ..., algebraic_multiplicity: Any = ...) -> Any:
        ...
    def eigenspaces_right(self: Any, format: Any = ..., var: Any = ..., algebraic_multiplicity: Any = ...) -> Any:
        ...
    def eigenvectors_right(self: Any, other: Any = ..., extend: Any = ...) -> Any:
        ...
    def eigenmatrix_left(self: Any, other: Any = ...) -> Any:
        ...
    def eigenmatrix_right(self: Any, other: Any = ...) -> Any:
        ...
    def eigenvalue_multiplicity(self: Any, s: Any) -> Any:
        ...
    def rref(self: Any) -> Any:
        ...
    def echelonize(self: Any, algorithm: Any = ..., cutoff: Any = ...) -> Any:
        ...
    def echelon_form(self: Any, algorithm: Any = ..., cutoff: Any = ...) -> Any:
        ...
    def extended_echelon_form(self: Any, subdivide: Any = ...) -> Any:
        ...
    def as_bipartite_graph(self: Any) -> Any:
        ...
    def automorphisms_of_rows_and_columns(self: Any) -> Any:
        ...
    def permutation_normal_form(self: Any, check: Any = ...) -> Any:
        ...
    def new_sorted_matrix(m: Any) -> Any:
        ...
    def is_permutation_of(self: Any, N: Any, check: Any = ...) -> Any:
        ...
    def set_block(self: Any, row: Any, col: Any, block: Any) -> Any:
        ...
    def subdivide(self: Any, row_lines: Any = ..., col_lines: Any = ...) -> Any:
        ...
    def subdivision(self: Any, i: Any, j: Any) -> Any:
        ...
    def subdivision_entry(self: Any, i: Any, j: Any, x: Any, y: Any) -> Any:
        ...
    def subdivisions(self: Any) -> Any:
        ...
    def tensor_product(self: Any, A: Any, subdivide: Any = ...) -> Any:
        ...
    def randomize(self: Any, density: Any = ..., nonzero: Any = ...) -> Any:
        ...
    def is_one(self: Any) -> Any:
        ...
    def is_scalar(self: Any, a: Any = ...) -> Any:
        ...
    def is_bistochastic(self: Any, normalized: Any = ...) -> Any:
        ...
    def is_normal(self: Any) -> Any:
        ...
    def as_sum_of_permutations(self: Any) -> Any:
        ...
    def visualize_structure(self: Any, maxsize: Any = ...) -> Any:
        ...
    def density(self: Any) -> Any:
        ...
    def inverse(self: Any) -> Any:
        ...
    def adjugate(self: Any) -> Any:
        ...
    def QR(self: Any, full: Any = ...) -> Any:
        ...
    def gram_schmidt(self: Any, orthonormal: Any = ...) -> Any:
        ...
    def jordan_form(self: Any, base_ring: Any = ..., sparse: Any = ..., subdivide: Any = ..., transformation: Any = ..., eigenvalues: Any = ..., check_input: Any = ...) -> Any:
        ...
    def jordan_decomposition(self: Any) -> Any:
        ...
    def diagonalization(self: Any, base_field: Any = ...) -> Any:
        ...
    def is_diagonalizable(self: Any, base_field: Any = ...) -> Any:
        ...
    def is_similar(self: Any, other: Any, transformation: Any = ...) -> Any:
        ...
    def symplectic_form(self: Any) -> Any:
        ...
    def cyclic_subspace(self: Any, v: Any, var: Any = ..., basis: Any = ...) -> Any:
        ...
    def conj_square_root(u: Any) -> Any:
        ...
    def cholesky(self: Any, extended: Any = ...) -> Any:
        ...
    def inverse_positive_definite(self: Any) -> Any:
        ...
    def LU(self: Any, pivot: Any = ..., format: Any = ...) -> Any:
        ...
    def indefinite_factorization(self: Any, algorithm: Any = ..., check: Any = ...) -> Any:
        ...
    def block_ldlt(self: Any, classical: Any = ...) -> Any:
        ...
    def is_positive_semidefinite(self: Any) -> Any:
        ...
    def is_positive_definite(self: Any) -> Any:
        ...
    def principal_square_root(self: Any, check_positivity: Any = ...) -> Any:
        ...
    def hadamard_bound(self: Any) -> Any:
        ...
    def find(self: Any, f: Any, indices: Any = ...) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def conjugate_transpose(self: Any) -> Any:
        ...
    def norm(self: Any, p: Any = ...) -> Any:
        ...
    def numerical_approx(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def plot(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def exp(self: Any) -> Any:
        ...
    def elementary_divisors(self: Any, algorithm: Any = ...) -> Any:
        ...
    def smith_form(self: Any, transformation: Any = ..., integral: Any = ..., exact: Any = ...) -> Any:
        ...
    def fitting_ideal(self: Any, i: Any) -> Any:
        ...
    def hermite_form(self: Any, include_zero_rows: Any = ..., transformation: Any = ...) -> Any:
        ...
    def zigzag_form(self: Any, subdivide: Any = ..., transformation: Any = ...) -> Any:
        ...
    def rational_form(self: Any, format: Any = ..., subdivide: Any = ...) -> Any:
        ...
    def is_positive_operator_on(self: Any, K1: Any, K2: Any = ...) -> Any:
        ...
    def is_cross_positive_on(self: Any, K: Any) -> Any:
        ...
    def is_Z_operator_on(self: Any, K: Any) -> Any:
        ...
    def is_lyapunov_like_on(self: Any, K: Any) -> Any:
        ...
    def LLL_gram(self: Any, flag: Any = ...) -> Any:
        ...
    def krylov_matrix(self: Any, M: Any, shifts: Any = ..., degrees: Any = ...) -> Any:
        ...
    def krylov_basis(self: Any, M: Any, shifts: Any = ..., degrees: Any = ..., output_rows: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def krylov_kernel_basis(self: Any, M: Any, shifts: Any = ..., degrees: Any = ..., output_rows: Any = ..., var: Any = ..., basis_algorithm: Any = ...) -> Any:
        ...
    def T(self: Any) -> Any:
        ...
    def C(self: Any) -> Any:
        ...
    def H(self: Any) -> Any:
        ...

class NotFullRankError(ValueError):
    ...
