from typing import Any

def unpickle(cls: Any, parent: Any, immutability: Any, cache: Any, data: Any, version: Any) -> Any:
    ...

class Matrix(sage.structure.element.Matrix):
    def __cinit__(self: Any, parent: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def dict(self: Any, copy: Any = ...) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def set_immutable(self: Any) -> Any:
        ...
    def is_immutable(self: Any) -> Any:
        ...
    def is_mutable(self: Any) -> Any:
        ...
    def add_to_entry(self: Any, i: Any, j: Any, elt: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def change_ring(self: Any, ring: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def ncols(self: Any) -> Any:
        ...
    def nrows(self: Any) -> Any:
        ...
    def dimensions(self: Any) -> Any:
        ...
    def act_on_polynomial(self: Any, f: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def commutator(self: Any, other: Any) -> Any:
        ...
    def anticommutator(self: Any, other: Any) -> Any:
        ...
    def swap_columns(self: Any, c1: Any, c2: Any) -> Any:
        ...
    def with_swapped_columns(self: Any, c1: Any, c2: Any) -> Any:
        ...
    def permute_columns(self: Any, permutation: Any) -> Any:
        ...
    def with_permuted_columns(self: Any, permutation: Any) -> Any:
        ...
    def swap_rows(self: Any, r1: Any, r2: Any) -> Any:
        ...
    def with_swapped_rows(self: Any, r1: Any, r2: Any) -> Any:
        ...
    def permute_rows(self: Any, permutation: Any) -> Any:
        ...
    def with_permuted_rows(self: Any, permutation: Any) -> Any:
        ...
    def permute_rows_and_columns(self: Any, row_permutation: Any, column_permutation: Any) -> Any:
        ...
    def with_permuted_rows_and_columns(self: Any, row_permutation: Any, column_permutation: Any) -> Any:
        ...
    def rescale_row(self: Any, i: Any, s: Any, start_col: Any = ...) -> Any:
        ...
    def with_rescaled_row(self: Any, i: Any, s: Any, start_col: Any = ...) -> Any:
        ...
    def rescale_col(self: Any, i: Any, s: Any, start_row: Any = ...) -> Any:
        ...
    def with_rescaled_col(self: Any, i: Any, s: Any, start_row: Any = ...) -> Any:
        ...
    def set_row_to_multiple_of_row(self: Any, i: Any, j: Any, s: Any) -> Any:
        ...
    def with_row_set_to_multiple_of_row(self: Any, i: Any, j: Any, s: Any) -> Any:
        ...
    def set_col_to_multiple_of_col(self: Any, i: Any, j: Any, s: Any) -> Any:
        ...
    def with_col_set_to_multiple_of_col(self: Any, i: Any, j: Any, s: Any) -> Any:
        ...
    def reverse_rows_and_columns(self: Any) -> Any:
        ...
    def mutate(self: Any, k: Any) -> Any:
        ...
    def linear_combination_of_rows(self: Any, v: Any) -> Any:
        ...
    def linear_combination_of_columns(self: Any, v: Any) -> Any:
        ...
    def is_symmetric(self: Any) -> Any:
        ...
    def is_hermitian(self: Any) -> Any:
        ...
    def is_skew_hermitian(self: Any) -> Any:
        ...
    def is_skew_symmetric(self: Any) -> Any:
        ...
    def is_alternating(self: Any) -> Any:
        ...
    def is_symmetrizable(self: Any, return_diag: Any = ..., positive: Any = ...) -> Any:
        ...
    def is_skew_symmetrizable(self: Any, return_diag: Any = ..., positive: Any = ...) -> Any:
        ...
    def is_dense(self: Any) -> Any:
        ...
    def is_sparse(self: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def is_invertible(self: Any) -> Any:
        ...
    def is_singular(self: Any) -> Any:
        ...
    def pivots(self: Any) -> Any:
        ...
    def rank(self: Any) -> Any:
        ...
    def nonpivots(self: Any) -> Any:
        ...
    def nonzero_positions(self: Any, copy: Any = ..., column_order: Any = ...) -> Any:
        ...
    def nonzero_positions_in_column(self: Any, i: Any) -> Any:
        ...
    def nonzero_positions_in_row(self: Any, i: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def iterates(self: Any, v: Any, n: Any, rows: Any = ...) -> Any:
        ...
    def __mod__(self: Any, p: Any) -> Any:
        ...
    def mod(self: Any, p: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def inverse_of_unit(self: Any, algorithm: Any = ...) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __pow__(self: Any, n: Any, ignored: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
