from typing import Any

class Matrix_polynomial_dense(Matrix_generic_dense):
    def degree(self: Any) -> Any:
        ...
    def degree_matrix(self: Any, shifts: Any = ..., row_wise: Any = ...) -> Any:
        ...
    def constant_matrix(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def coefficient_matrix(self: Any, d: Any, row_wise: Any = ...) -> Any:
        ...
    def truncate(self: Any, d: Any, row_wise: Any = ...) -> Any:
        ...
    def shift(self: Any, d: Any, row_wise: Any = ...) -> Any:
        ...
    def reverse(self: Any, degree: Any = ..., row_wise: Any = ..., entry_wise: Any = ...) -> Any:
        ...
    def inverse_series_trunc(self: Any, d: Any) -> Any:
        ...
    def solve_left_series_trunc(self: Any, B: Any, d: Any) -> Any:
        ...
    def solve_right_series_trunc(self: Any, B: Any, d: Any) -> Any:
        ...
    def row_degrees(self: Any, shifts: Any = ...) -> Any:
        ...
    def column_degrees(self: Any, shifts: Any = ...) -> Any:
        ...
    def leading_matrix(self: Any, shifts: Any = ..., row_wise: Any = ...) -> Any:
        ...
    def hermite_form(self: Any, include_zero_rows: Any = ..., transformation: Any = ...) -> Any:
        ...
    def left_quo_rem(self: Any, B: Any) -> Any:
        ...
    def right_quo_rem(self: Any, B: Any) -> Any:
        ...
    def reduce(self: Any, B: Any, shifts: Any = ..., row_wise: Any = ..., return_quotient: Any = ...) -> Any:
        ...
    def basis_completion(self: Any, row_wise: Any = ..., algorithm: Any = ...) -> Any:
        ...
