from typing import Any

def strassen_window_multiply(C: Any, A: Any, B: Any, cutoff: Any) -> Any:
    ...

def strassen_echelon(A: Any, cutoff: Any) -> Any:
    ...

def test(n: Any, m: Any, R: Any, c: Any = ...) -> Any:
    ...

class int_range:
    def __init__(self: Any, indices: Any = ..., range: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def intervals(self: Any) -> Any:
        ...
    def to_list(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __add__(self: Any, right: Any) -> Any:
        ...
    def __sub__(self: Any, right: Any) -> Any:
        ...
    def __mul__(self: Any, right: Any) -> Any:
        ...
