from typing import Any

def terminate(sp: Any, interval: Any = ..., signals: Any = ...) -> Any:
    ...

class ContainChildren:
    def __init__(self: Any, exitcode: Any = ..., exceptcode: Any = ..., silent: Any = ...) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any) -> Any:
        ...
