from typing import Any

class SageSpawn(spawn):
    def __init__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def expect_peek(self: Any) -> Any:
        ...
    def expect_upto(self: Any) -> Any:
        ...

class SagePtyProcess(PtyProcess):
    def close(self: Any, force: Any = ...) -> Any:
        ...
    def terminate_async(self: Any, interval: Any = ...) -> Any:
        ...
