from typing import Any

def LFunctionZeroSum(X: Any) -> Any:
    ...

class LFunctionZeroSum_abstract(SageObject):
    def ncpus(self: Any, n: Any = ...) -> Any:
        ...
    def level(self: Any) -> Any:
        ...
    def weight(self: Any) -> Any:
        ...
    def C0(self: Any, include_euler_gamma: Any = ...) -> Any:
        ...
    def cnlist(self: Any, n: Any, python_floats: Any = ...) -> Any:
        ...
    def digamma(self: Any, s: Any, include_constant_term: Any = ...) -> Any:
        ...
    def logarithmic_derivative(self: Any, s: Any, num_terms: Any = ..., as_interval: Any = ...) -> Any:
        ...
    def completed_logarithmic_derivative(self: Any, s: Any, num_terms: Any = ...) -> Any:
        ...
    def zerosum(self: Any, Delta: Any = ..., tau: Any = ..., function: Any = ..., ncpus: Any = ...) -> Any:
        ...

class LFunctionZeroSum_EllipticCurve(LFunctionZeroSum_abstract):
    def __init__(self: Any, E: Any, N: Any = ..., ncpus: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def elliptic_curve(self: Any) -> Any:
        ...
    def lseries(self: Any) -> Any:
        ...
    def cn(self: Any, n: Any) -> Any:
        ...
    def run_computation(Delta: Any) -> Any:
        ...
