from typing import Any
from sage.modules.vector_rational_dense import Vector_rational_dense

def is_ToricRationalDivisorClass(x: Any) -> bool: ...

class ToricRationalDivisorClass(Vector_rational_dense):
    def __reduce__(self) -> tuple[Any, ...]: ...
    def _act_on_(self, other: Any, self_on_left: bool) -> Any: ...
    def _dot_product_(self, right: Any) -> Any: ...
    def _latex_(self) -> str: ...
    def _repr_(self) -> str: ...
    def lift(self) -> Any: ...

def _ToricRationalDivisorClass_unpickle_v1(parent: Any, entries: Any, degree: int, is_mutable: bool) -> ToricRationalDivisorClass: ...
