from typing import Any, List, Optional, Union, Tuple
from sage.rings.number_field.number_field_element_base import NumberFieldElement_base

def is_NumberFieldElement(x: Any) -> bool:
    ...

def _inverse_mod_generic(elt: 'NumberFieldElement', I: Any) -> 'NumberFieldElement':
    ...

class NumberFieldElement(NumberFieldElement_base):
    """Base class for elements of number fields."""
    
    def __init__(self, parent: Any, f: Any) -> None:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def _latex_(self) -> str:
        ...
    
    def _pari_(self) -> Any:
        ...
    
    def _magma_init_(self, magma: Any) -> str:
        ...
    
    def _gap_init_(self) -> str:
        ...
    
    def _kash_init_(self) -> str:
        ...
    
    def _sage_input_(self, sib: Any, coerced: bool) -> Any:
        ...
    
    def polynomial(self, var: str = 'x') -> Any:
        ...
    
    def minpoly(self, var: str = 'x') -> Any:
        ...
    
    def minimal_polynomial(self, var: str = 'x') -> Any:
        ...
    
    def charpoly(self, var: str = 'x') -> Any:
        ...
    
    def characteristic_polynomial(self, var: str = 'x') -> Any:
        ...
    
    def degree(self) -> int:
        ...
    
    def absolute_degree(self) -> int:
        ...
    
    def relative_degree(self) -> int:
        ...
    
    def multiplicative_order(self) -> Any:
        ...
    
    def additive_order(self) -> Any:
        ...
    
    def conjugate(self) -> 'NumberFieldElement':
        ...
    
    def galois_conjugates(self, K: Optional[Any] = None) -> List['NumberFieldElement']:
        ...
    
    def norm(self, K: Optional[Any] = None) -> Any:
        ...
    
    def absolute_norm(self) -> Any:
        ...
    
    def relative_norm(self) -> Any:
        ...
    
    def trace(self, K: Optional[Any] = None) -> Any:
        ...
    
    def absolute_trace(self) -> Any:
        ...
    
    def relative_trace(self) -> Any:
        ...
    
    def matrix(self, base: Optional[Any] = None) -> Any:
        ...
    
    def vector(self, base: Optional[Any] = None) -> Any:
        ...
    
    def coordinates_in_terms_of_powers(self) -> List[Any]:
        ...
    
    def denominator(self) -> Any:
        ...
    
    def numerator(self) -> 'NumberFieldElement':
        ...
    
    def inverse_mod(self, I: Any) -> 'NumberFieldElement':
        ...
    
    def mod(self, I: Any) -> 'NumberFieldElement':
        ...
    
    def __mod__(self, I: Any) -> 'NumberFieldElement':
        ...
    
    def is_integral(self) -> bool:
        ...
    
    def is_one(self) -> bool:
        ...
    
    def is_rational(self) -> bool:
        ...
    
    def is_square(self, root: bool = False) -> Union[bool, Tuple[bool, 'NumberFieldElement']]:
        ...
    
    def sqrt(self, all: bool = False, extend: bool = True) -> Any:
        ...
    
    def nth_root(self, n: int, all: bool = False) -> Any:
        ...
    
    def support(self) -> List[Any]:
        ...
    
    def descents(self) -> List[Any]:
        ...
    
    def has_descent(self, prime: Any) -> bool:
        ...
    
    def local_height(self, v: Any, prec: Optional[int] = None) -> Any:
        ...
    
    def local_height_arch(self, prec: Optional[int] = None) -> Any:
        ...
    
    def global_height_non_arch(self, prec: Optional[int] = None) -> Any:
        ...
    
    def global_height_arch(self, prec: Optional[int] = None) -> Any:
        ...
    
    def global_height(self, prec: Optional[int] = None) -> Any:
        ...
    
    def is_totally_positive(self) -> bool:
        ...
    
    def is_totally_negative(self) -> bool:
        ...
    
    def sign_vector(self) -> List[int]:
        ...

class NumberFieldElement_absolute(NumberFieldElement):
    """Element of an absolute number field."""
    
    def list(self) -> List[Any]:
        ...
    
    def _coefficients(self) -> List[Any]:
        ...

class NumberFieldElement_relative(NumberFieldElement):
    """Element of a relative number field."""
    
    def list(self) -> List[Any]:
        ...
    
    def relative_polynomial(self) -> Any:
        ...
    
    def absolute_polynomial(self) -> Any:
        ...

class OrderElement_absolute(NumberFieldElement_absolute):
    """Element of an absolute number field order."""
    
    def denominator(self) -> Any:
        ...

class OrderElement_relative(NumberFieldElement_relative):
    """Element of a relative number field order."""
    
    def denominator(self) -> Any:
        ...