from typing import Any

def is_NumberFieldElement(x: Any) -> Any:
    ...

class NumberFieldElement(NumberFieldElement_base):
    def __init__(self: Any, parent: Any, f: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __pari__(self: Any, name: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def sign(self: Any) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def round(self: Any) -> Any:
        ...
    def abs(self: Any, prec: Any = ..., i: Any = ...) -> Any:
        ...
    def abs_non_arch(self: Any, P: Any, prec: Any = ...) -> Any:
        ...
    def coordinates_in_terms_of_powers(self: Any) -> Any:
        ...
    def complex_embeddings(self: Any, prec: Any = ...) -> Any:
        ...
    def complex_embedding(self: Any, prec: Any = ..., i: Any = ...) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def is_norm(self: Any, L: Any, element: Any = ..., proof: Any = ...) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def factor(self: Any) -> Any:
        ...
    def is_prime(self: Any) -> Any:
        ...
    def gcd(self: Any, other: Any) -> Any:
        ...
    def is_totally_positive(self: Any) -> Any:
        ...
    def is_square(self: Any, root: Any = ...) -> Any:
        ...
    def is_padic_square(self: Any, P: Any, check: Any = ...) -> Any:
        ...
    def sqrt(self: Any, all: Any = ..., extend: Any = ...) -> Any:
        ...
    def nth_root(self: Any, n: Any, all: Any = ...) -> Any:
        ...
    def is_nth_power(self: Any, n: Any) -> Any:
        ...
    def __pow__(base: Any, exp: Any, dummy: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def galois_conjugates(self: Any, K: Any) -> Any:
        ...
    def conjugate(self: Any) -> Any:
        ...
    def polynomial(self: Any, var: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def is_integer(self: Any) -> Any:
        ...
    def trace(self: Any, K: Any = ...) -> Any:
        ...
    def norm(self: Any, K: Any = ...) -> Any:
        ...
    def absolute_norm(self: Any) -> Any:
        ...
    def relative_norm(self: Any) -> Any:
        ...
    def vector(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def is_integral(self: Any) -> Any:
        ...
    def matrix(self: Any, base: Any = ...) -> Any:
        ...
    def valuation(self: Any, P: Any) -> Any:
        ...
    def local_height(self: Any, P: Any, prec: Any = ..., weighted: Any = ...) -> Any:
        ...
    def local_height_arch(self: Any, i: Any, prec: Any = ..., weighted: Any = ...) -> Any:
        ...
    def global_height_non_arch(self: Any, prec: Any = ...) -> Any:
        ...
    def global_height_arch(self: Any, prec: Any = ...) -> Any:
        ...
    def global_height(self: Any, prec: Any = ...) -> Any:
        ...
    def numerator_ideal(self: Any) -> Any:
        ...
    def denominator_ideal(self: Any) -> Any:
        ...
    def support(self: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def inverse_mod(self: Any, I: Any) -> Any:
        ...
    def residue_symbol(self: Any, P: Any, m: Any, check: Any = ...) -> Any:
        ...
    def descend_mod_power(self: Any, K: Any = ..., d: Any = ...) -> Any:
        ...
    def different(self: Any, K: Any = ...) -> Any:
        ...
    def absolute_different(self: Any) -> Any:
        ...

class NumberFieldElement_absolute(NumberFieldElement):
    def absolute_charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def absolute_minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def lift(self: Any, var: Any = ...) -> Any:
        ...
    def is_real_positive(self: Any, min_prec: Any = ...) -> Any:
        ...

class NumberFieldElement_relative(NumberFieldElement):
    def __init__(self: Any, parent: Any, f: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def list(self: Any) -> Any:
        ...
    def lift(self: Any, var: Any = ...) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def absolute_charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def absolute_minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def valuation(self: Any, P: Any) -> Any:
        ...

class OrderElement_absolute(NumberFieldElement_absolute):
    def __init__(self: Any, order: Any, f: Any) -> Any:
        ...
    def inverse_mod(self: Any, I: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def canonical_associate(self: Any) -> Any:
        ...

class OrderElement_relative(NumberFieldElement_relative):
    def __init__(self: Any, order: Any, f: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def inverse_mod(self: Any, I: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def absolute_charpoly(self: Any, var: Any = ...) -> Any:
        ...
    def absolute_minpoly(self: Any, var: Any = ...) -> Any:
        ...
    def canonical_associate(self: Any) -> Any:
        ...

class CoordinateFunction:
    def __init__(self: Any, alpha: Any, W: Any, to_V: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def alpha(self: Any) -> Any:
        ...
    def __call__(self: Any, x: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __ne__(self: Any, other: Any) -> Any:
        ...
