from typing import Any

def __make_NumberFieldElement_quadratic0(parent: Any, a: Any, b: Any, denom: Any) -> Any:
    ...

def __make_NumberFieldElement_quadratic1(parent: Any, cls: Any, a: Any, b: Any, denom: Any) -> Any:
    ...

class NumberFieldElement_quadratic(NumberFieldElement_absolute):
    def __init__(self: Any, parent: Any, f: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __cinit__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def parts(self: Any) -> Tuple[Any, ...]:
        ...
    def sign(self: Any) -> Any:
        ...
    def continued_fraction_list(self: Any) -> Any:
        ...
    def continued_fraction(self: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def galois_conjugate(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_integer(self: Any) -> Any:
        ...
    def real(self: Any) -> Any:
        ...
    def imag(self: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...
    def numerator(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def norm(self: Any, K: Any = ...) -> Any:
        ...
    def is_integral(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def floor(self: Any) -> Any:
        ...
    def ceil(self: Any) -> Any:
        ...
    def round(self: Any) -> Any:
        ...

class NumberFieldElement_quadratic_sqrt(NumberFieldElement_quadratic):
    def denominator(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...

class NumberFieldElement_gaussian(NumberFieldElement_quadratic_sqrt):
    def real_part(self: Any) -> Any:
        ...
    def imag_part(self: Any) -> Any:
        ...
    def log(self: Any) -> Any:
        ...

class OrderElement_quadratic(NumberFieldElement_quadratic):
    def __init__(self: Any, order: Any, f: Any) -> Any:
        ...
    def norm(self: Any) -> Any:
        ...
    def trace(self: Any) -> Any:
        ...
    def charpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def minpoly(self: Any, var: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def inverse_mod(self: Any, I: Any) -> Any:
        ...
    def denominator(self: Any) -> Any:
        ...

class Z_to_quadratic_field_element(Morphism):
    def __init__(self: Any, K: Any) -> Any:
        ...

class Q_to_quadratic_field_element(Morphism):
    def __init__(self: Any, K: Any) -> Any:
        ...
