from typing import Any

def hermite_constant(n: Any) -> Any:
    ...

def lagrange_degree_3(n: Any, an1: Any, an2: Any, an3: Any) -> Any:
    ...

def int_has_small_square_divisor(d: Any) -> Any:
    ...

def easy_is_irreducible_py(f: Any) -> Any:
    ...

class tr_data:
    def __init__(self: Any, n: Any, B: Any, a: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def increment(self: Any, verbose: Any = ..., haltk: Any = ..., phc: Any = ...) -> Any:
        ...
    def printa(self: Any) -> Any:
        ...
