from typing import Any

class dfs_manager:
    def __dealloc__(self: Any) -> Any:
        ...
    def advance_exhaust(self: Any) -> Any:
        ...

class WeilPolynomials_iter:
    def __init__(self: Any, d: Any, q: Any, sign: Any, lead: Any, node_limit: Any, parallel: Any, squarefree: Any, polring: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def node_count(self: Any) -> Any:
        ...

class WeilPolynomials:
    def __init__(self: Any, d: Any, q: Any, sign: Any = ..., lead: Any = ..., node_limit: Any = ..., parallel: Any = ..., squarefree: Any = ..., polring: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def node_count(self: Any) -> Any:
        ...
