from typing import Any

def poly_to_tup(poly: Any) -> Any:
    ...

def tup_to_univ_poly(eq_tup: Any, univ_poly_ring: Any) -> Any:
    ...

def resize(eq_tup: Any, idx_map: Any, nvars: Any) -> Any:
    ...

def get_variables_degrees(eqns: Any, nvars: Any) -> List[Any]:
    ...

def variables(eq_tup: Any) -> List[Any]:
    ...

def constant_coeff(eq_tup: Any, field: Any) -> Any:
    ...

def apply_coeff_map(eq_tup: Any, coeff_map: Any) -> Tuple[Any, ...]:
    ...

def compute_known_powers(max_degs: Any, val_dict: Any, one: Any) -> Dict[Any, Any]:
    ...

def poly_tup_sortkey(eq_tup: Any) -> Tuple[Any, ...]:
    ...
