from typing import Any

def make_KSHandler(n_slots: Any, field: Any, init_data: Any) -> Any:
    ...

def make_FvarsHandler(n: Any, field: Any, idx_map: Any, init_data: Any) -> Any:
    ...

class KSHandler:
    def __init__(self: Any, n_slots: Any, field: Any, use_mp: Any = ..., init_data: Any = ..., name: Any = ...) -> Any:
        ...
    def update(self: Any, eqns: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...

class FvarsHandler:
    def __getitem__(self: Any, sextuple: Any) -> Any:
        ...
    def __setitem__(self: Any, sextuple: Any, fvar: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
