from typing import Any

def round(self: Any) -> Any:
    ...

def function(self: Any) -> Any:
    ...

def power(self: Any, exp: Any, hold: Any = ...) -> Any:
    ...

def add(self: Any, hold: Any = ...) -> Any:
    ...

def mul(self: Any, hold: Any = ...) -> Any:
    ...

def coefficient(self: Any, s: Any, n: Any = ...) -> Any:
    ...

def coefficients(self: Any, x: Any = ..., sparse: Any = ...) -> Any:
    ...

def list(self: Any, x: Any = ...) -> Any:
    ...

def leading_coefficient(self: Any, s: Any) -> Any:
    ...

def trailing_coefficient(self: Any, s: Any) -> Any:
    ...

def low_degree(self: Any, s: Any) -> Any:
    ...

def degree(self: Any, s: Any) -> Any:
    ...

def unit(self: Any, s: Any) -> Any:
    ...

def content(self: Any, s: Any) -> Any:
    ...

def primitive_part(self: Any, s: Any) -> Any:
    ...

def unit_content_primitive(self: Any, s: Any) -> Any:
    ...

def poly(self: Any, x: Any = ...) -> Any:
    ...

def polynomial(self: Any, base_ring: Any = ..., ring: Any = ...) -> Any:
    ...

def laurent_polynomial(self: Any, base_ring: Any = ..., ring: Any = ...) -> Any:
    ...

def fraction(self: Any, base_ring: Any) -> Any:
    ...

def power_series(self: Any, base_ring: Any) -> Any:
    ...

def gcd(self: Any, b: Any) -> Any:
    ...

def gosper_sum(self: Any) -> Any:
    ...

def gosper_term(self: Any, n: Any) -> Any:
    ...

def WZ_certificate(self: Any, n: Any, k: Any) -> Any:
    ...

def lcm(self: Any, b: Any) -> Any:
    ...

def resultant(self: Any, other: Any, var: Any) -> Any:
    ...

def collect(self: Any, s: Any) -> Any:
    ...

def horner(self: Any, x: Any) -> Any:
    ...

def collect_common_factors(self: Any) -> Any:
    ...

def __abs__(self: Any) -> Any:
    ...

def abs(self: Any, hold: Any = ...) -> Any:
    ...

def step(self: Any, hold: Any = ...) -> Any:
    ...

def csgn(self: Any, hold: Any = ...) -> Any:
    ...

def conjugate(self: Any, hold: Any = ...) -> Any:
    ...

def norm(self: Any) -> Any:
    ...

def real_part(self: Any, hold: Any = ...) -> Any:
    ...

def imag_part(self: Any, hold: Any = ...) -> Any:
    ...

def sqrt(self: Any, hold: Any = ...) -> Any:
    ...

def sin(self: Any, hold: Any = ...) -> Any:
    ...

def cos(self: Any, hold: Any = ...) -> Any:
    ...

def tan(self: Any, hold: Any = ...) -> Any:
    ...

def arcsin(self: Any, hold: Any = ...) -> Any:
    ...

def arccos(self: Any, hold: Any = ...) -> Any:
    ...

def arctan(self: Any, hold: Any = ...) -> Any:
    ...

def arctan2(self: Any, x: Any, hold: Any = ...) -> Any:
    ...

def sinh(self: Any, hold: Any = ...) -> Any:
    ...

def cosh(self: Any, hold: Any = ...) -> Any:
    ...

def tanh(self: Any, hold: Any = ...) -> Any:
    ...

def arcsinh(self: Any, hold: Any = ...) -> Any:
    ...

def arccosh(self: Any, hold: Any = ...) -> Any:
    ...

def arctanh(self: Any, hold: Any = ...) -> Any:
    ...

def exp(self: Any, hold: Any = ...) -> Any:
    ...

def log(self: Any, b: Any = ..., hold: Any = ...) -> Any:
    ...

def zeta(self: Any, hold: Any = ...) -> Any:
    ...

def factorial(self: Any, hold: Any = ...) -> Any:
    ...

def binomial(self: Any, k: Any, hold: Any = ...) -> Any:
    ...

def Order(self: Any, hold: Any = ...) -> Any:
    ...

def gamma(self: Any, hold: Any = ...) -> Any:
    ...

def log_gamma(self: Any, hold: Any = ...) -> Any:
    ...

def default_variable(self: Any) -> Any:
    ...

def combine(self: Any, deep: Any = ...) -> Any:
    ...

def normalize(self: Any) -> Any:
    ...

def numerator(self: Any, normalize: Any = ...) -> Any:
    ...

def denominator(self: Any, normalize: Any = ...) -> Any:
    ...

def numerator_denominator(self: Any, normalize: Any = ...) -> Any:
    ...

def partial_fraction(self: Any, var: Any = ...) -> Any:
    ...

def partial_fraction_decomposition(self: Any, var: Any = ...) -> Any:
    ...

def maxima_methods(self: Any) -> Any:
    ...

def rectform(self: Any) -> Any:
    ...

def unhold(self: Any, exclude: Any = ...) -> Any:
    ...

def simplify(self: Any, algorithm: Any = ...) -> Any:
    ...

def simplify_full(self: Any) -> Any:
    ...

def simplify_hypergeometric(self: Any, algorithm: Any = ...) -> Any:
    ...

def simplify(o: Any) -> Any:
    ...

def simplify_rectform(self: Any, complexity_measure: Any = ...) -> Any:
    ...

def simplify_real(self: Any) -> Any:
    ...

def simplify_trig(self: Any, expand: Any = ...) -> Any:
    ...

def simplify_rational(self: Any, algorithm: Any = ..., map: Any = ...) -> Any:
    ...

def simplify_factorial(self: Any) -> Any:
    ...

def to_gamma(self: Any) -> Any:
    ...

def gamma_normalize(self: Any) -> Any:
    ...

def expand_sum(self: Any) -> Any:
    ...

def canonicalize_radical(self: Any) -> Any:
    ...

def simplify_log(self: Any, algorithm: Any = ...) -> Any:
    ...

def expand_log(self: Any, algorithm: Any = ...) -> Any:
    ...

def distribute(self: Any, recursive: Any = ...) -> Any:
    ...

def treat_term(op: Any, term: Any, args: Any) -> Any:
    ...

def factor(self: Any, dontfactor: Any = ...) -> Any:
    ...

def factor_list(self: Any, dontfactor: Any = ...) -> Any:
    ...

def convert(self: Any, target: Any = ...) -> Any:
    ...

def roots(self: Any, x: Any = ..., explicit_solutions: Any = ..., multiplicities: Any = ..., ring: Any = ...) -> Any:
    ...

def solve(self: Any, x: Any, multiplicities: Any = ..., solution_dict: Any = ..., explicit_solutions: Any = ..., to_poly_solve: Any = ..., algorithm: Any = ..., domain: Any = ...) -> Any:
    ...

def solve_diophantine(self: Any, x: Any = ..., solution_dict: Any = ...) -> Any:
    ...

def show(self: Any) -> Any:
    ...

def plot(self: Any) -> Any:
    ...

def sum(self: Any) -> Any:
    ...

def prod(self: Any) -> Any:
    ...

def integral(self: Any) -> Any:
    ...

def nintegral(self: Any) -> Any:
    ...

def minpoly(self: Any) -> Any:
    ...

def limit(self: Any) -> Any:
    ...

def laplace(self: Any, t: Any, s: Any) -> Any:
    ...

def inverse_laplace(self: Any, t: Any, s: Any) -> Any:
    ...

def add_to_both_sides(self: Any, x: Any) -> Any:
    ...

def subtract_from_both_sides(self: Any, x: Any) -> Any:
    ...

def multiply_both_sides(self: Any, x: Any, checksign: Any = ...) -> Any:
    ...

def divide_both_sides(self: Any, x: Any, checksign: Any = ...) -> Any:
    ...

def compositional_inverse(self: Any, allow_multivalued_inverse: Any = ...) -> Any:
    ...

def implicit_derivative(self: Any, Y: Any, X: Any, n: Any = ...) -> Any:
    ...

def solve_diophantine(f: Any) -> Any:
    ...

def new_f(ex: Any) -> Any:
    ...

def new_Expression(parent: Any, x: Any) -> Any:
    ...

def new_Expression_from_pyobject(parent: Any, x: Any, force: Any = ..., recursive: Any = ...) -> Any:
    ...

def new_Expression_wild(parent: Any, n: Any = ...) -> Any:
    ...

def new_Expression_symbol(parent: Any, name: Any = ..., latex_name: Any = ..., domain: Any = ...) -> Any:
    ...

class Expression(Expression_abc):
    def pyobject(self: Any) -> Any:
        ...
    def __init__(self: Any, SR: Any, x: Any = ...) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def assume(self: Any) -> Any:
        ...
    def forget(self: Any) -> Any:
        ...
    def decl_assume(self: Any, decl: Any) -> Any:
        ...
    def decl_forget(self: Any, decl: Any) -> Any:
        ...
    def is_algebraic(self: Any) -> Any:
        ...
    def is_rational_expression(self: Any) -> Any:
        ...
    def is_real(self: Any) -> Any:
        ...
    def is_positive(self: Any) -> Any:
        ...
    def is_negative(self: Any) -> Any:
        ...
    def is_integer(self: Any) -> Any:
        ...
    def is_symbol(self: Any) -> Any:
        ...
    def is_constant(self: Any) -> Any:
        ...
    def is_numeric(self: Any) -> Any:
        ...
    def is_terminating_series(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> Any:
        ...
    def numelems_gen(expr: Any) -> Any:
        ...
    def is_square(self: Any) -> Any:
        ...
    def is_callable(self: Any) -> Any:
        ...
    def left_hand_side(self: Any) -> Any:
        ...
    def right_hand_side(self: Any) -> Any:
        ...
    def is_trivially_equal(self: Any, other: Any) -> Any:
        ...
    def is_trivial_zero(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def test_relation(self: Any, ntests: Any = ..., domain: Any = ..., proof: Any = ...) -> Any:
        ...
    def negation(self: Any) -> Any:
        ...
    def contradicts(self: Any, soln: Any) -> Any:
        ...
    def is_unit(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def derivative(self: Any) -> Any:
        ...
    def gradient(self: Any, variables: Any = ...) -> Any:
        ...
    def hessian(self: Any) -> Any:
        ...
    def series(self: Any, symbol: Any, order: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def residue(self: Any, symbol: Any) -> Any:
        ...
    def taylor(self: Any) -> Any:
        ...
    def truncate(self: Any) -> Any:
        ...
    def expand(self: Any, side: Any = ...) -> Any:
        ...
    def expand_trig(self: Any, full: Any = ..., half_angles: Any = ..., plus: Any = ..., times: Any = ...) -> Any:
        ...
    def reduce_trig(self: Any, var: Any = ...) -> Any:
        ...
    def match(self: Any, pattern: Any) -> Any:
        ...
    def find(self: Any, pattern: Any) -> Any:
        ...
    def has(self: Any, pattern: Any) -> Any:
        ...
    def subs(self: Any) -> Any:
        ...
    def substitute_function(self: Any) -> Any:
        ...
    def exponentialize(self: Any) -> Any:
        ...
    def demoivre(self: Any, force: Any = ...) -> Any:
        ...
    def half_angle(self: Any) -> Any:
        ...
    def substitution_delayed(self: Any, pattern: Any, replacement: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def variables(self: Any) -> Any:
        ...
    def free_variables(self: Any) -> Any:
        ...
    def arguments(self: Any) -> Any:
        ...
    def number_of_arguments(self: Any) -> Any:
        ...
    def number_of_operands(self: Any) -> Any:
        ...
    def operands(self: Any) -> Any:
        ...
    def operator(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...
    def iterator(self: Any) -> Any:
        ...
    def op(self: Any) -> Any:
        ...
    def numerical_approx(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...

class DefiniteSumExpander(ExpressionTreeWalker):
    def composition(self: Any, ex: Any, operator: Any) -> Any:
        ...

class ExpressionIterator:
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...

class hold_class:
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any) -> Any:
        ...
    def start(self: Any) -> Any:
        ...
    def stop(self: Any) -> Any:
        ...
