from typing import Any

class EvaluationAGCodeEncoder(Encoder):
    def __init__(self: Any, code: Any, decoder: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def encode(self: Any, message: Any) -> Any:
        ...
    def unencode_nocheck(self: Any, codeword: Any) -> Any:
        ...

class DifferentialAGCodeEncoder(Encoder):
    def __init__(self: Any, code: Any, decoder: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def encode(self: Any, message: Any) -> Any:
        ...
    def unencode_nocheck(self: Any, codeword: Any) -> Any:
        ...

class EvaluationAGCodeUniqueDecoder(Decoder):
    def __init__(self: Any, code: Any, Q: Any = ..., basis: Any = ..., verbose: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def connected_encoder(self: Any) -> Any:
        ...
    def decoding_radius(self: Any) -> Any:
        ...
    def decode_to_message(self: Any, received_vector: Any) -> Any:
        ...
    def decode_to_code(self: Any, received_vector: Any) -> Any:
        ...

class DifferentialAGCodeUniqueDecoder(Decoder):
    def __init__(self: Any, code: Any, Q: Any = ..., basis: Any = ..., verbose: Any = ...) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def connected_encoder(self: Any) -> Any:
        ...
    def decoding_radius(self: Any) -> Any:
        ...
    def decode_to_message(self: Any, received_vector: Any) -> Any:
        ...
    def decode_to_code(self: Any, received_vector: Any) -> Any:
        ...

class Decoder_K:
    def encode(self: Any, message: Any) -> Any:
        ...
    def vprint_g(g: Any, s: Any) -> Any:
        ...

class EvaluationAGCodeDecoder_K(Decoder_K):
    def __init__(self: Any, pls: Any, G: Any, Q: Any, verbose: Any = ...) -> Any:
        ...
    def ev_mon(sk: Any, si: Any) -> Any:
        ...
    def nu(s: Any) -> Any:
        ...
    def vec_form(f: Any) -> Any:
        ...

class DifferentialAGCodeDecoder_K(Decoder_K):
    def __init__(self: Any, pls: Any, G: Any, Q: Any, verbose: Any = ...) -> Any:
        ...
    def res_mon(sk: Any, si: Any) -> Any:
        ...
    def nu(s: Any) -> Any:
        ...
    def vec_form(f: Any) -> Any:
        ...

class Decoder_K_extension:
    def __init__(self: Any, pls: Any, G: Any, Q: Any, decoder_cls: Any, verbose: Any = ...) -> Any:
        ...
    def conorm_prime_divisor(pl: Any) -> Any:
        ...
    def conorm(d: Any) -> Any:
        ...
    def lift_place(pl: Any) -> Any:
        ...
    def encode(self: Any, message: Any) -> Any:
        ...
    def decode(self: Any, received_vector: Any) -> Any:
        ...

class EvaluationAGCodeDecoder_K_extension(Decoder_K_extension):
    def __init__(self: Any, pls: Any, G: Any, Q: Any, verbose: Any = ...) -> Any:
        ...

class DifferentialAGCodeDecoder_K_extension(Decoder_K_extension):
    def __init__(self: Any, pls: Any, G: Any, Q: Any, verbose: Any = ...) -> Any:
        ...
