from typing import Any

def weight_dist(M: Any) -> Any:
    ...

def test_word_perms(t_limit: Any = ...) -> Any:
    ...

def test_expand_to_ortho_basis(B: Any = ...) -> Any:
    ...

class BinaryCode:
    def __cinit__(self: Any, arg1: Any, arg2: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def matrix(self: Any) -> Any:
        ...
    def print_data(self: Any) -> Any:
        ...
    def apply_permutation(self: Any, labeling: Any) -> Any:
        ...

class OrbitPartition:
    def __cinit__(self: Any, nrows: Any, ncols: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...

class PartitionStack:
    def __cinit__(self: Any, arg1: Any, arg2: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def print_data(self: Any) -> Any:
        ...
    def print_basis(self: Any) -> Any:
        ...

class BinaryCodeClassifier:
    def __cinit__(self: Any) -> Any:
        ...
    def put_in_canonical_form(self: Any, B: Any) -> Any:
        ...
    def generate_children(self: Any, B: Any, n: Any, d: Any = ...) -> Any:
        ...
