from typing import Any

class KasamiCode(AbstractLinearCode):
    def __init__(self: Any, s: Any, t: Any, extended: Any = ...) -> Any:
        ...
    def parameters(self: Any) -> Any:
        ...
    def __eq__(self: Any, other: Any) -> Any:
        ...
    def generator_matrix(self: Any) -> Any:
        ...
    def exp(row: Any) -> Any:
        ...
