from typing import Any

def py_scalar_parent(py_type: Any) -> Any:
    ...

def py_scalar_to_element(x: Any) -> Any:
    ...

def parent_is_integers(P: Any) -> bool:
    ...

def parent_is_numerical(P: Any) -> Any:
    ...

def parent_is_real_numerical(P: Any) -> Any:
    ...

class CoercionModel:
    def __init__(self: Any) -> Any:
        ...
    def reset_cache(self: Any) -> Any:
        ...
    def get_cache(self: Any) -> Any:
        ...
    def record_exceptions(self: Any, value: Any = ...) -> Any:
        ...
    def exception_stack(self: Any) -> Any:
        ...
    def explain(self: Any, xp: Any, yp: Any, op: Any = ..., verbosity: Any = ...) -> Any:
        ...
    def analyse(self: Any, xp: Any, yp: Any, op: Any = ...) -> Any:
        ...
    def common_parent(self: Any) -> Any:
        ...
    def division_parent(self: Any, P: Any) -> Any:
        ...
    def bin_op(self: Any, x: Any, y: Any, op: Any) -> Any:
        ...
    def canonical_coercion(self: Any, x: Any, y: Any) -> Any:
        ...
    def coercion_maps(self: Any, R: Any, S: Any) -> Any:
        ...
    def verify_coercion_maps(self: Any, R: Any, S: Any, homs: Any, fix: Any = ...) -> Any:
        ...
    def discover_coercion(self: Any, R: Any, S: Any) -> Any:
        ...
    def get_action(self: Any, R: Any, S: Any, op: Any = ..., r: Any = ..., s: Any = ...) -> Any:
        ...
    def verify_action(self: Any, action: Any, R: Any, S: Any, op: Any, fix: Any = ...) -> Any:
        ...
    def discover_action(self: Any, R: Any, S: Any, op: Any, r: Any = ..., s: Any = ...) -> Any:
        ...
    def richcmp(self: Any, x: Any, y: Any, op: Any) -> Any:
        ...
