from typing import Any

def make_element(_class: Any, _dict: Any, parent: Any) -> Any:
    ...

def is_Element(x: Any) -> Any:
    ...

def is_ModuleElement(x: Any) -> Any:
    ...

def is_MonoidElement(x: Any) -> Any:
    ...

def is_AdditiveGroupElement(x: Any) -> Any:
    ...

def is_MultiplicativeGroupElement(x: Any) -> Any:
    ...

def is_RingElement(x: Any) -> Any:
    ...

def is_CommutativeRingElement(x: Any) -> Any:
    ...

def is_Vector(x: Any) -> Any:
    ...

def is_Matrix(x: Any) -> Any:
    ...

def is_IntegralDomainElement(x: Any) -> Any:
    ...

def is_DedekindDomainElement(x: Any) -> Any:
    ...

def is_PrincipalIdealDomainElement(x: Any) -> Any:
    ...

def is_EuclideanDomainElement(x: Any) -> Any:
    ...

def is_FieldElement(x: Any) -> Any:
    ...

def is_AlgebraElement(x: Any) -> Any:
    ...

def is_CommutativeAlgebraElement(x: Any) -> Any:
    ...

def is_InfinityElement(x: Any) -> Any:
    ...

def canonical_coercion(x: Any, y: Any) -> Any:
    ...

def bin_op(x: Any, y: Any, op: Any) -> Any:
    ...

def get_coercion_model() -> Any:
    ...

def coercion_traceback(dump: Any = ...) -> Any:
    ...

def coerce_binop(method: Any) -> Any:
    ...

def new_method(self: Any, other: Any) -> Any:
    ...

class Element(SageObject):
    def __getmetaclass__(_: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, state: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def base_extend(self: Any, R: Any) -> Any:
        ...
    def base_ring(self: Any) -> Any:
        ...
    def category(self: Any) -> Any:
        ...
    def parent(self: Any, x: Any = ...) -> Any:
        ...
    def subs(self: Any, in_dict: Any = ...) -> Any:
        ...
    def substitute(self: Any) -> Any:
        ...
    def numerical_approx(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def n(self: Any, prec: Any = ..., digits: Any = ..., algorithm: Any = ...) -> Any:
        ...
    def __xor__(self: Any, right: Any) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def is_zero(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __matmul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __floordiv__(left: Any, right: Any) -> Any:
        ...
    def __mod__(left: Any, right: Any) -> Any:
        ...
    def __pow__(left: Any, right: Any, modulus: Any) -> Any:
        ...

class ElementWithCachedMethod(Element):
    ...

class ModuleElement(Element):
    def order(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...

class ModuleElementWithMutability(ModuleElement):
    def __init__(self: Any, parent: Any, is_immutable: Any = ...) -> Any:
        ...
    def set_immutable(self: Any) -> Any:
        ...

class MonoidElement(Element):
    def order(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def powers(self: Any, n: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...

class AdditiveGroupElement(ModuleElement):
    def order(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...

class MultiplicativeGroupElement(MonoidElement):
    def order(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...

class RingElement(ModuleElement):
    def is_one(self: Any) -> Any:
        ...
    def powers(self: Any, n: Any) -> Any:
        ...
    def __divmod__(self: Any, other: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def additive_order(self: Any) -> Any:
        ...
    def multiplicative_order(self: Any) -> Any:
        ...
    def is_nilpotent(self: Any) -> Any:
        ...
    def abs(self: Any) -> Any:
        ...
    def is_prime(self: Any) -> Any:
        ...

class CommutativeRingElement(RingElement):
    def inverse_mod(self: Any, I: Any) -> Any:
        ...
    def divides(self: Any, x: Any) -> Any:
        ...
    def mod(self: Any, I: Any) -> Any:
        ...

class Expression(CommutativeRingElement):
    ...

class Vector(ModuleElementWithMutability):
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(self: Any, right: Any) -> Any:
        ...

class Matrix(ModuleElement):
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...

class IntegralDomainElement(CommutativeRingElement):
    def is_nilpotent(self: Any) -> Any:
        ...

class DedekindDomainElement(IntegralDomainElement):
    ...

class PrincipalIdealDomainElement(DedekindDomainElement):
    def gcd(self: Any, right: Any) -> Any:
        ...
    def lcm(self: Any, right: Any) -> Any:
        ...

class EuclideanDomainElement(PrincipalIdealDomainElement):
    def degree(self: Any) -> Any:
        ...
    def leading_coefficient(self: Any) -> Any:
        ...
    def quo_rem(self: Any, other: Any) -> Any:
        ...

class FieldElement(CommutativeRingElement):
    def is_unit(self: Any) -> Any:
        ...
    def quo_rem(self: Any, right: Any) -> Any:
        ...
    def divides(self: Any, other: Any) -> Any:
        ...
    def canonical_associate(self: Any) -> Any:
        ...

class AlgebraElement(RingElement):
    ...

class CommutativeAlgebraElement(CommutativeRingElement):
    ...

class InfinityElement(RingElement):
    def __invert__(self: Any) -> Any:
        ...
