from typing import Any

def register_factory_unpickle(name: Any, callable: Any) -> Any:
    ...

def generic_factory_unpickle(factory: Any) -> Any:
    ...

def generic_factory_reduce(self: Any, proto: Any) -> Any:
    ...

def lookup_global(name: Any) -> Any:
    ...

class UniqueFactory(SageObject):
    def __init__(self: Any, name: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any) -> Any:
        ...
    def get_object(self: Any, version: Any, key: Any, extra_args: Any) -> Any:
        ...
    def get_version(self: Any, sage_version: Any) -> Any:
        ...
    def create_key_and_extra_args(self: Any) -> Any:
        ...
    def create_key(self: Any) -> Any:
        ...
    def create_object(self: Any, version: Any, key: Any) -> Any:
        ...
    def other_keys(self: Any, key: Any, obj: Any) -> Any:
        ...
    def reduce_data(self: Any, obj: Any) -> Any:
        ...
