from typing import Any

class ClonableElement(Element):
    def __cinit__(self: Any) -> Any:
        ...
    def set_immutable(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def clone(self: Any, check: Any = ...) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any, typ: Any, value: Any, tracback: Any) -> Any:
        ...

class ClonableArray(ClonableElement):
    def __init__(self: Any, parent: Any, lst: Any, check: Any = ..., immutable: Any = ...) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __contains__(self: Any, item: Any) -> Any:
        ...
    def index(self: Any, x: Any, start: Any = ..., stop: Any = ...) -> int:
        ...
    def count(self: Any, key: Any) -> int:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def check(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class ClonableList(ClonableArray):
    def append(self: Any, el: Any) -> Any:
        ...
    def extend(self: Any, it: Any) -> Any:
        ...
    def insert(self: Any, index: Any, el: Any) -> Any:
        ...
    def pop(self: Any, index: Any = ...) -> Any:
        ...
    def remove(self: Any, el: Any) -> Any:
        ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any:
        ...
    def __delitem__(self: Any, key: Any) -> Any:
        ...

class ClonableIntArray(ClonableElement):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, parent: Any, lst: Any, check: Any = ..., immutable: Any = ...) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def list(self: Any) -> List[Any]:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any:
        ...
    def __contains__(self: Any, item: Any) -> Any:
        ...
    def index(self: Any, item: Any) -> int:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def check(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class NormalizedClonableList(ClonableList):
    def __init__(self: Any, parent: Any, lst: Any, check: Any = ..., immutable: Any = ...) -> Any:
        ...
    def __exit__(self: Any, typ: Any, value: Any, tracback: Any) -> Any:
        ...
    def normalize(self: Any) -> Any:
        ...
