from typing import Any, Optional, Type, Dict
from sage.structure.category_object import CategoryObject

def is_Parent(x: Any) -> bool:
    ...

class Parent(CategoryObject):
    def __cinit__(self) -> None:
        ...
    def element_class(self) -> Type:
        ...
    def __make_element_class__(self, cls: Type, name: Optional[str] = None, module: Optional[str] = None, inherit: Optional[bool] = None) -> Type:
        ...
    def category(self) -> Any:
        ...
    def __getstate__(self) -> Dict[str, Any]:
        ...
    def __setstate__(self, d: Dict[str, Any]) -> None:
        ...
    def __call__(self, x: Any = 0) -> Any:
        ...
    def __mul__(self, x: Any) -> Any:
        ...
    def __pow__(self, x: Any, mod: Any = None) -> Any:
        ...
    def __contains__(self, x: Any) -> bool:
        ...
    def coerce(self, x: Any) -> Any:
        ...
    def __bool__(self) -> bool:
        ...
    def __getitem__(self, n: Any) -> Any:
        ...
    def Hom(self, codomain: 'Parent', category: Optional[Any] = None) -> Any:
        ...
    def hom(self, im_gens: Any, codomain: Optional['Parent'] = None, check: bool = True, base_map: Optional[Any] = None, category: Optional[Any] = None) -> Any:
        ...
    def register_coercion(self, mor: Any) -> None:
        ...
    def register_action(self, action: Any) -> None:
        ...
    def register_conversion(self, mor: Any) -> None:
        ...
    def register_embedding(self, embedding: Any) -> None:
        ...
    def coerce_embedding(self) -> Optional[Any]:
        ...
    def has_coerce_map_from(self, S: 'Parent') -> bool:
        ...
    def coerce_map_from(self, S: 'Parent') -> Optional[Any]:
        ...
    def convert_map_from(self, S: 'Parent') -> Optional[Any]:
        ...
    def get_action(self, S: 'Parent', op: str = '*', self_on_left: bool = True, self_el: Optional[Any] = None, S_el: Optional[Any] = None) -> Optional[Any]:
        ...
    def an_element(self) -> Any:
        ...
    def is_exact(self) -> bool:
        ...

class Set_generic(Parent):
    def object(self) -> Any:
        ...
    def __bool__(self) -> bool:
        ...

class EltPair:
    def __init__(self, x: Any, y: Any, tag: Any) -> None:
        ...
    def __richcmp__(self, other: 'EltPair', op: int) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def short_repr(self) -> str:
        ...
    def __repr__(self) -> str:
        ...
