from typing import Any

def is_Parent(x: Any) -> Any:
    ...

class Parent(sage.structure.category_object.CategoryObject):
    def __cinit__(self: Any) -> Any:
        ...
    def element_class(self: Any) -> Any:
        ...
    def __make_element_class__(self: Any, cls: Any, name: Any = ..., module: Any = ..., inherit: Any = ...) -> Any:
        ...
    def category(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, d: Any) -> Any:
        ...
    def __call__(self: Any, x: Any = ...) -> Any:
        ...
    def __mul__(self: Any, x: Any) -> Any:
        ...
    def __pow__(self: Any, x: Any, mod: Any) -> Any:
        ...
    def __contains__(self: Any, x: Any) -> Any:
        ...
    def coerce(self: Any, x: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, n: Any) -> Any:
        ...
    def Hom(self: Any, codomain: Any, category: Any = ...) -> Any:
        ...
    def hom(self: Any, im_gens: Any, codomain: Any = ..., check: Any = ..., base_map: Any = ..., category: Any = ...) -> Any:
        ...
    def register_coercion(self: Any, mor: Any) -> Any:
        ...
    def register_action(self: Any, action: Any) -> Any:
        ...
    def register_conversion(self: Any, mor: Any) -> Any:
        ...
    def register_embedding(self: Any, embedding: Any) -> Any:
        ...
    def coerce_embedding(self: Any) -> Any:
        ...
    def has_coerce_map_from(self: Any, S: Any) -> bool:
        ...
    def coerce_map_from(self: Any, S: Any) -> Any:
        ...
    def convert_map_from(self: Any, S: Any) -> Any:
        ...
    def get_action(self: Any, S: Any, op: Any = ..., self_on_left: Any = ..., self_el: Any = ..., S_el: Any = ...) -> Any:
        ...
    def an_element(self: Any) -> Any:
        ...
    def is_exact(self: Any) -> bool:
        ...

class Set_generic(Parent):
    def object(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...

class EltPair:
    def __init__(self: Any, x: Any, y: Any, tag: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def short_repr(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
