from typing import Any

class ParentWithGens(ParentWithBase):
    def __init__(self: Any, base: Any, names: Any = ..., normalize: Any = ..., category: Any = ...) -> Any:
        ...
    def ngens(self: Any) -> Any:
        ...
    def gen(self: Any, i: Any = ...) -> Any:
        ...
    def gens(self: Any) -> Any:
        ...
    def __getstate__(self: Any) -> Any:
        ...
    def __setstate__(self: Any, d: Any) -> Any:
        ...
    def hom(self: Any, im_gens: Any, codomain: Any = ..., base_map: Any = ..., category: Any = ..., check: Any = ...) -> Any:
        ...

class localvars:
    def __init__(self: Any, obj: Any, names: Any, latex_names: Any = ..., normalize: Any = ...) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any, type: Any, value: Any, traceback: Any) -> Any:
        ...
