from typing import Any, Optional

class SageObject:
    def rename(self, x: Optional[str] = None) -> None:
        ...
    def reset_name(self) -> None:
        ...
    def get_custom_name(self) -> Optional[str]:
        ...
    def __repr__(self) -> str:
        ...
    def __hash__(self) -> int:
        ...
    def save(self, filename: Optional[str] = None, compress: bool = True) -> None:
        ...
    def dump(self, filename: str, compress: bool = True) -> None:
        ...
    def dumps(self, compress: bool = True) -> str:
        ...
    def category(self) -> Any:
        ...
    def parent(self) -> Any:
        ...
    def __pari__(self) -> Any:
        ...
