from typing import Any

class SageObject:
    def rename(self: Any, x: Any = ...) -> Any:
        ...
    def reset_name(self: Any) -> Any:
        ...
    def get_custom_name(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def save(self: Any, filename: Any = ..., compress: Any = ...) -> Any:
        ...
    def dump(self: Any, filename: Any, compress: Any = ...) -> Any:
        ...
    def dumps(self: Any, compress: Any = ...) -> Any:
        ...
    def category(self: Any) -> Any:
        ...
    def parent(self: Any) -> Any:
        ...
    def __pari__(self: Any) -> Any:
        ...
