from typing import Any

class CmpKey:
    def __init__(self: Any) -> Any:
        ...
    def __get__(self: Any, inst: Any, cls: Any) -> Any:
        ...

class CmpKeyNamed:
    def __get__(self: Any, inst: Any, cls: Any) -> Any:
        ...
    def C3_merge(lists: Any) -> Any:
        ...
    def identity(x: Any) -> Any:
        ...
    def C3_sorted_merge(lists: Any, key: Any = ...) -> Tuple[Any, ...]:
        ...
    def __classcall__(cls: Any, value: Any, succ: Any, key: Any = ...) -> Any:
        ...
    def f(x: Any) -> Any:
        ...
    def __init__(self: Any, value: Any, bases: Any, key: Any, from_value: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def bases(self: Any) -> Any:
        ...
    def mro(self: Any) -> Any:
        ...
    def mro_standard(self: Any) -> Any:
        ...
    def mro_controlled(self: Any) -> Any:
        ...
    def cls(self: Any) -> Any:
        ...
    def all_bases(self: Any) -> Any:
        ...
    def all_bases_len(self: Any) -> Any:
        ...
    def all_bases_controlled_len(self: Any) -> Any:
        ...
