from typing import Any

class ConstantFunction(SageObject):
    def __init__(self: Any, value: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __call__(self: Any, *args: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
