from typing import Any

class WithEqualityById:
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...

class FastHashable_class:
    def __init__(self: Any, h: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...

class Singleton(WithEqualityById, metaclass=ClasscallMetaclass):
    def __classcall__(cls: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
