from typing import Any

def code_ctor() -> Any:
    ...

def reduce_code(co: Any) -> Any:
    ...

def pickle_function(func: Any) -> Any:
    ...

def unpickle_function(pickled: Any) -> Any:
    ...

def call_pickled_function(fpargs: Any) -> Any:
    ...

def pickleMethod(method: Any) -> Any:
    ...

def pickleModule(module: Any) -> Any:
    ...

def unpickleModule(name: Any) -> Any:
    ...
