from typing import Any

class ArgumentFixer:
    def __init__(self: Any, f: Any, classmethod: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def fix_to_named(self: Any) -> Any:
        ...
    def fix_to_pos(self: Any) -> Any:
        ...
