from typing import Any

def instancedoc(cls: Any) -> Any:
    ...

class InstanceDocDescriptor:
    def __init__(self: Any, classdoc: Any, instancedoc: Any, attr: Any = ...) -> Any:
        ...
    def __get__(self: Any, obj: Any, typ: Any) -> Any:
        ...
    def __set__(self: Any, obj: Any, value: Any) -> Any:
        ...
    def __delete__(self: Any, obj: Any) -> Any:
        ...
