from typing import Any, Optional, Dict, List, Iterator

def finish_startup() -> None:
    ...

def ensure_startup_finished() -> None:
    ...

def test_fake_startup() -> None:
    ...

def save_cache_file() -> None:
    ...

def get_star_imports(module_name: str) -> List[str]:
    ...

def attributes(a: object) -> List[str]:
    ...

def clean_namespace(namespace: Optional[Dict] = None) -> None:
    ...

class LazyImport:
    def __getattr__(self, attr: str) -> Any:
        ...
    def __dir__(self) -> List[str]:
        ...
    def __call__(self, *args: Any, **kwds: Any) -> Any:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __bool__(self) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __richcmp__(left: Any, right: Any, op: int) -> bool:
        ...
    def __len__(self) -> int:
        ...
    def __get__(self, instance: Any, owner: Any) -> Any:
        ...
    def __getitem__(self, key: Any) -> Any:
        ...
    def __setitem__(self, key: Any, value: Any) -> None:
        ...
    def __delitem__(self, key: Any) -> None:
        ...
    def __iter__(self) -> Iterator[Any]:
        ...
    def __contains__(self, item: Any) -> bool:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __matmul__(left: Any, right: Any) -> Any:
        ...
    def __floordiv__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __pow__(left: Any, right: Any, mod: Any = None) -> Any:
        ...
    def __mod__(left: Any, right: Any) -> Any:
        ...
    def __lshift__(left: Any, right: Any) -> Any:
        ...
    def __rshift__(left: Any, right: Any) -> Any:
        ...
    def __and__(left: Any, right: Any) -> Any:
        ...
    def __or__(left: Any, right: Any) -> Any:
        ...
    def __xor__(left: Any, right: Any) -> Any:
        ...
    def __neg__(self) -> Any:
        ...
    def __pos__(self) -> Any:
        ...
    def __abs__(self) -> Any:
        ...
    def __invert__(self) -> Any:
        ...
    def __complex__(self) -> complex:
        ...
    def __int__(self) -> int:
        ...
    def __float__(self) -> float:
        ...
    def __oct__(self) -> str:
        ...
    def __hex__(self) -> str:
        ...
    def __index__(self) -> int:
        ...
    def __copy__(self) -> Any:
        ...
    def __deepcopy__(self, memo: Dict = {}) -> Any:
        ...
    def __instancecheck__(self, x: Any) -> bool:
        ...
    def __subclasscheck__(self, x: Any) -> bool:
        ...
