from typing import Any

def finish_startup() -> Any:
    ...

def ensure_startup_finished() -> Any:
    ...

def test_fake_startup() -> Any:
    ...

def save_cache_file() -> Any:
    ...

def get_star_imports(module_name: Any) -> Any:
    ...

def attributes(a: Any) -> Any:
    ...

def clean_namespace(namespace: Any = ...) -> Any:
    ...

class LazyImport:
    def __getattr__(self: Any, attr: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __call__(self: Any, *args: Any, **kwds: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(left: Any, right: Any, op: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __get__(self: Any, instance: Any, owner: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __setitem__(self: Any, key: Any, value: Any) -> Any:
        ...
    def __delitem__(self: Any, key: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __contains__(self: Any, item: Any) -> Any:
        ...
    def __add__(left: Any, right: Any) -> Any:
        ...
    def __sub__(left: Any, right: Any) -> Any:
        ...
    def __mul__(left: Any, right: Any) -> Any:
        ...
    def __matmul__(left: Any, right: Any) -> Any:
        ...
    def __floordiv__(left: Any, right: Any) -> Any:
        ...
    def __truediv__(left: Any, right: Any) -> Any:
        ...
    def __pow__(left: Any, right: Any, mod: Any) -> Any:
        ...
    def __mod__(left: Any, right: Any) -> Any:
        ...
    def __lshift__(left: Any, right: Any) -> Any:
        ...
    def __rshift__(left: Any, right: Any) -> Any:
        ...
    def __and__(left: Any, right: Any) -> Any:
        ...
    def __or__(left: Any, right: Any) -> Any:
        ...
    def __xor__(left: Any, right: Any) -> Any:
        ...
    def __neg__(self: Any) -> Any:
        ...
    def __pos__(self: Any) -> Any:
        ...
    def __abs__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __complex__(self: Any) -> Any:
        ...
    def __int__(self: Any) -> Any:
        ...
    def __float__(self: Any) -> Any:
        ...
    def __oct__(self: Any) -> Any:
        ...
    def __hex__(self: Any) -> Any:
        ...
    def __index__(self: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any = ...) -> Any:
        ...
    def __instancecheck__(self: Any, x: Any) -> Any:
        ...
    def __subclasscheck__(self: Any, x: Any) -> Any:
        ...
