from typing import Any

def is_lazy_string(obj: Any) -> Any:
    ...

def lazy_string(f: Any) -> Any:
    ...

class _LazyString:
    def __init__(self: Any, f: Any, args: Any, kwargs: Any) -> Any:
        ...
    def value(self: Any) -> Any:
        ...
    def __contains__(self: Any, key: Any) -> Any:
        ...
    def __bool__(self: Any) -> Any:
        ...
    def __dir__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __str__(self: Any) -> Any:
        ...
    def __fspath__(self: Any) -> Any:
        ...
    def __add__(self: Any, other: Any) -> Any:
        ...
    def __mod__(self: Any, other: Any) -> Any:
        ...
    def __mul__(self: Any, other: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __getattr__(self: Any, name: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, key: Any) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def update_lazy_string(self: Any, args: Any, kwds: Any) -> Any:
        ...
