from typing import Any

def running_total(L: Any, start: Any = ...) -> Any:
    ...

def prod(x: Any, z: Any = ..., recursion_cutoff: Any = ...) -> Any:
    ...

def iterator_prod(L: Any, z: Any = ..., multiply: Any = ...) -> Any:
    ...

def __init__(self: Any, left: Any, right: Any = ...) -> Any:
    ...

def __repr__(self: Any) -> Any:
    ...

def __mul__(self: Any, other: Any) -> Any:
    ...

def balanced_sum(x: Any, z: Any = ..., recursion_cutoff: Any = ...) -> Any:
    ...

def normalize_index(key: Any, size: Any) -> List[Any]:
    ...

class sized_iter:
    def __init__(self: Any, iterable: Any, length: Any = ...) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
    def cyflush() -> Any:
        ...
