from typing import Any

def foo(*args: Any, **kwds: Any) -> Any:
    ...

def token_to_str(token: Any) -> Any:
    ...

class Tokenizer:
    def __init__(self: Any, s: Any) -> Any:
        ...
    def test(self: Any) -> Any:
        ...
    def reset(self: Any, pos: Any = ...) -> Any:
        ...
    def backtrack(self: Any) -> bool:
        ...
    def last_token_string(self: Any) -> Any:
        ...

class Parser:
    def __init__(self: Any, make_int: Any = ..., make_float: Any = ..., make_var: Any = ..., make_function: Any = ..., implicit_multiplication: Any = ...) -> Any:
        ...
    def parse(self: Any, s: Any, accept_eqn: Any = ...) -> Any:
        ...
    def parse_expression(self: Any, s: Any) -> Any:
        ...
    def parse_sequence(self: Any, s: Any) -> Any:
        ...
    def p_matrix(self: Any, tokens: Any) -> Any:
        ...
    def p_sequence(self: Any, tokens: Any) -> Any:
        ...
    def p_list(self: Any, tokens: Any) -> Any:
        ...
    def p_tuple(self: Any, tokens: Any) -> Any:
        ...
    def p_eqn(self: Any, tokens: Any) -> Any:
        ...
    def p_expr(self: Any, tokens: Any) -> Any:
        ...
    def p_term(self: Any, tokens: Any) -> Any:
        ...
    def p_factor(self: Any, tokens: Any) -> Any:
        ...
    def p_power(self: Any, tokens: Any) -> Any:
        ...
    def p_atom(self: Any, tokens: Any) -> Any:
        ...
    def p_args(self: Any, tokens: Any) -> Any:
        ...
    def p_arg(self: Any, tokens: Any) -> Any:
        ...

class LookupNameMaker:
    def __init__(self: Any, names: Any, fallback: Any = ...) -> Any:
        ...
    def set_names(self: Any, new_names: Any) -> Any:
        ...
    def __call__(self: Any, name: Any) -> Any:
        ...
