from typing import Any

def current_randstate() -> Any:
    ...

def set_random_seed(seed: Any = ...) -> Any:
    ...

def initial_seed() -> Any:
    ...

def benchmark_libc() -> Any:
    ...

def benchmark_mt() -> Any:
    ...

class randstate:
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, seed: Any = ...) -> Any:
        ...
    def seed(self: Any) -> Any:
        ...
    def python_random(self: Any, cls: Any = ..., seed: Any = ...) -> Any:
        ...
    def ZZ_seed(self: Any) -> Any:
        ...
    def long_seed(self: Any) -> Any:
        ...
    def set_seed_libc(self: Any, force: Any) -> Any:
        ...
    def set_seed_ntl(self: Any, force: Any) -> Any:
        ...
    def set_seed_gap(self: Any) -> Any:
        ...
    def set_seed_libgap(self: Any) -> Any:
        ...
    def set_seed_gp(self: Any, gp: Any = ...) -> Any:
        ...
    def set_seed_pari(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any, ty: Any, value: Any, traceback: Any) -> Any:
        ...
