from typing import Any

def restore_cwd(chdir: Any = ...) -> Any:
    ...

class redirection:
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, source: Any, dest: Any, close: Any = ...) -> Any:
        ...
    def __enter__(self: Any) -> Any:
        ...
    def __exit__(self: Any, *args: Any) -> Any:
        ...
