from typing import Any

class WeakValueDictEraser:
    def __init__(self: Any, D: Any) -> Any:
        ...
    def __call__(self: Any, r: Any) -> Any:
        ...

class WeakValueDictionary(dict):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, data: Any = ...) -> Any:
        ...
    def __copy__(self: Any) -> Any:
        ...
    def __deepcopy__(self: Any, memo: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def setdefault(self: Any, k: Any, default: Any = ...) -> Any:
        ...
    def __setitem__(self: Any, k: Any, v: Any) -> Any:
        ...
    def pop(self: Any, k: Any) -> Any:
        ...
    def popitem(self: Any) -> Any:
        ...
    def get(self: Any, k: Any, d: Any = ...) -> Any:
        ...
    def __getitem__(self: Any, k: Any) -> Any:
        ...
    def __contains__(self: Any, k: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def keys(self: Any) -> Any:
        ...
    def itervalues(self: Any) -> Any:
        ...
    def values(self: Any) -> Any:
        ...
    def values_list(self: Any) -> Any:
        ...
    def iteritems(self: Any) -> Any:
        ...
    def items(self: Any) -> Any:
        ...
    def items_list(self: Any) -> Any:
        ...

class CachedWeakValueDictionary(WeakValueDictionary):
    def __cinit__(self: Any) -> Any:
        ...
    def __init__(self: Any, data: Any = ..., cache: Any = ...) -> Any:
        ...
