from typing import Any

def get_CoxGroup(cartan_type: Any) -> Any:
    ...

class String:
    def __init__(self: Any, s: Any = ...) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class Type:
    def __init__(self: Any, s: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def name(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...

class CoxGroup(SageObject):
    def __cinit__(self: Any, cartan_type: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __dealloc__(self: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def bruhat_interval(self: Any, w: Any, v: Any) -> Any:
        ...
    def orderings(self: Any) -> Any:
        ...
    def type(self: Any) -> Any:
        ...
    def rank(self: Any) -> Any:
        ...
    def order(self: Any) -> Any:
        ...
    def is_finite(self: Any) -> Any:
        ...
    def long_element(self: Any) -> Any:
        ...
    def __call__(self: Any, w: Any) -> Any:
        ...
    def coxeter_matrix(self: Any) -> Any:
        ...
    def coxeter_graph(self: Any) -> Any:
        ...

class CoxGroupElement:
    def __init__(self: Any, group: Any, w: Any, normal_form: Any = ...) -> Any:
        ...
    def __reduce__(self: Any) -> Any:
        ...
    def __invert__(self: Any) -> Any:
        ...
    def __getitem__(self: Any, i: Any) -> Any:
        ...
    def __repr__(self: Any) -> Any:
        ...
    def __hash__(self: Any) -> Any:
        ...
    def __richcmp__(self: Any, other: Any, op: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __len__(self: Any) -> Any:
        ...
    def left_descents(self: Any) -> Any:
        ...
    def right_descents(self: Any) -> Any:
        ...
    def bruhat_le(self: Any, w: Any) -> Any:
        ...
    def is_two_sided_descent(self: Any, s: Any) -> Any:
        ...
    def coatoms(self: Any) -> Any:
        ...
    def normal_form(self: Any) -> Any:
        ...
    def reduced(self: Any) -> Any:
        ...
    def __mul__(self: Any, y: Any) -> Any:
        ...
    def poincare_polynomial(self: Any) -> Any:
        ...
    def kazhdan_lusztig_polynomial(self: Any, v: Any) -> Any:
        ...
    def mu_coefficient(self: Any, v: Any) -> Any:
        ...

class CoxGroupIterator:
    def __init__(self: Any, group: Any) -> Any:
        ...
    def __iter__(self: Any) -> Any:
        ...
    def __next__(self: Any) -> Any:
        ...
